### ISSUE TITLE
[Bug]: effet de Slowness en continue 

### ISSUE THREAD

**Issue by Inconnu200** [Paladium-Developpement/Paladium-Issue#1002]
### Pseudo InGame

Inconnu200

### Que s'est-il passé ?

Support sur TS , effet qu'il reste en continue même si le joueur meurt , l'effet ne s'enlève pas malgré la commande /effect [Pseudo] clear et n'apparaît pas dans la page inventaire.

**Comment by Zeldown** [comment]
❌ Il suffit de lui mettre l'effet durant 1s sur le serveur concerné.
