### ISSUE TITLE
[Bug]: Farmland

### ISSUE THREAD

**Issue by Taxbac** [Paladium-Developpement/Paladium-Issue#1003]
### Pseudo InGame

Taxbac

### Que s'est-il passé ?

Il n'y a pas de mobs dans la farmland nether + end en comparaison à la zone du lac
En 1min on clear le nether de mon et puis plus rien pendant 10min et ainsi de suite

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
