### ISSUE TITLE
[Bug]: Quête Palapass

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1004]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Palapass : problème de quête quotidienne [A la bonne soupe] et [Eaux piégeuses] où il faut crafter respectivement 20 soupes de champignon et 20 fake water. Ça ne fonctionne pas. Et il est possible qu'il y ait d'autres quêtes dans ce genre qui ne fonctionnent pas non plus.

### Qu'aurait-il dû arriver ?

A chaque craft, un point palapass aurait du être donné.

**Comment by KraemerJoe** [comment]
Hello corrigé merci.
