### ISSUE TITLE
[Bug]: Bug grapique, crystal chest

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1005]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lorsque qu'on met une pog de n'importe qu'elle niveau, le crystal chest va afficher une pog lvl 1 et non pas celle mise dans le chest

### Serveur

Imbali

**Comment by Zeldown** [comment]
❌ Ce bug mineur ne peut pas être corrigé.
