### ISSUE TITLE
[Bug][Launcher]: Téléchargement du jeu impossible pour certains joueurs 

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#1007]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Certains joueurs ne peuvent télécharger Paladium avec le launcher V8.
Lorsqu'ils cliquent sur le bouton "Installer", le téléchargement de Java s'effectue, puis le bouton Installer revient.

Dans les logs, nous pouvons voir ceci lorsque le joueur clique sur Installer : 
[2022-10-22 17:59:33.840] [info]  version game paladium : null, distribVersion: 1.0.0
La version du jeu est indiquée null alors qu'il ne devrait pas, la distribution ayant bien été téléchargée et chargée sur le launcher : Les actualités sont visibles. Cependant, ils ne peuvent afficher la page pour lancer Minecraft Vanilla.

La réinstallation du launcher, avec suppression de tous les fichiers, ne change rien. Sur toutes les solutions "de base" essayées (pare-feu, antivirus, changement de connexion, etc.), seule un reset Windows était effective

**Comment by aureliancnx** [comment]
Bonjour,

A-t-il été testé d'effectuer la commande curl vers le fichier de distribution (en format json) avec le -i pour voir le résultat sorti sur un PC ayant ce problème ? Il est difficile pour l'instant de diagnostiquer une quelconque possibilité de facteur causant ce problème pour le moment sans plus de manipulations techniques sur cette minorité de signalements

Cordialement,

**Comment by AlxTNF** [comment]
Bonjour,

La distribution est bien téléchargée sur les PC ayant le problème, et est identique à celle présente sur un PC n'ayant pas celui-ci.

Cordialement,

**Comment by aureliancnx** [comment]
Cela a bien été vérifié avec l’opération que j’ai mentionnée ci-dessus ?

est-ce que l’utilisateur en question a téléchargé la dernière version du launcher ?

**Comment by kngsolgan** [comment]
problème resolue: j'ai eu le meme probleme que vous pour evité cela il faut juste que vous installer java sur internet sur le site officiel ou si vous l'avez deja mettez le a jour et bonne journée
