### ISSUE TITLE
[Bug]: HOME REMOVER -  Corrections à apporter aux textes suivants :

### ISSUE THREAD

**Issue by Inconnu200** [Paladium-Developpement/Paladium-Issue#1009]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La structure a été **verrouillée** avec succès

La structure a été **déverrouillée** avec succès

Statut: **non-protégé**

X **localisation(s) trouvée(s)** à cet endroit, combattez **le(s) gardien(s)** ! [ajouter une espace entre "gardiens" et "!"]

**Aucunes** localisations trouvées **à** cet endroit !

Un home remover vous a **empêché(e)** de vous reconnecter à **l'endroit** de votre déconnexion

Autre : il n'y a aucun message après suppression d'un home par home remover pour le joueur qui souhaite se TP à son home et qui se TP au spawn à la place

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
