### ISSUE TITLE
[Bug]: Quête palapass Vivre dangereusement

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1010]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

La quête ne comptabilise pas le fait qu'on soit dans un claim ennemie.

### Qu'aurait-il dû arriver ?

Cela aurai du compter le nombre de claim traverser

### Serveur

Global

**Comment by KraemerJoe** [comment]
Corrigé merci.
