### ISSUE TITLE
[Bug]: Texture Bannières Back to the future

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#1012]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

Il faudrais fix les bannieres qui ont ete add par le back2future de terrainwax, actuellments toutes les bannieres sont blanche avec des petit cube de couleurs, il faudrais qu'il retrouve leurs couleur Id des block 604:0 a 604:15 ou alors les integrée au nouveau back to the future de zeldown pour pouvoir enlever le mod de terrain dans une prochaine version

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
