### ISSUE TITLE
[Bug]: Paris alternance couleur gagant/perdant

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1013]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/203421921-9f923074-9bc5-48dc-beff-501a6f97b126.png)

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
