### ISSUE TITLE
[Bug][Faction]: Mdf commande remove bug

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1016]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/203647151-9e3e7d05-08b6-4eb7-b3f8-c1810e55a03b.png)

### Serveur

Soleratl

### Date et heure de la production du bug

22:13

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Akysooo** [comment]
Update j'ai créé une autre mdf pour un test et j'ai test de la remove, la ca a marché. Ce qui change c'est que la Mdf1 a été créé avant le dernier bug mdf fixé et la rg de la mdf n'existe plus

**Comment by aureliancnx** [comment]
Oui. C'est pour cela que ça te met que la region n'existe pas (pas traduit).
Je la supprime en DB.
