### ISSUE TITLE
[Bug][Palapass]: Quête "au boulot"

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1019]
### Pseudo InGame

VeckPex

### Que s'est-il passé ?

Quand on pose un bloc de bois et qu'on le mine, il compte pour la palapass, il est possible de reposer le bloc, pour le miner de nouveau afin de faire monter sa quête.

### Qu'aurait-il dû arriver ?

Poser un bloc déjà miné ne devrait pas compter de nouveau pour le palapass.

### Serveur

Minage

**Comment by KraemerJoe** [comment]
Bonjour, testé et fonctionnel pour moi, je close.
