### ISSUE TITLE
[Bug][Faction]: Point egghunt doublé en reset saison

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1021]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lors de la fin d'un saison, les points du classement egg hunt sont donné dans le classement qui vient de finir et celui qui vient de commencer. (Ex : faction blackold)

### Qu'aurait-il dû arriver ?

Devrait être que pour celui qui vient de finir.

### Serveur

Global

### Date et heure de la production du bug

21/11 00h00m

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
