### ISSUE TITLE
[Bug][Faction]: Point quête non faite reset saison

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1022]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lors de la fin d'une saison, les points retirés par la quête non faite sont retiré après le reset de la saison. (ex blackmonkey)

### Qu'aurait-il dû arriver ?

Devrait être retiré à l'ancienne saison, pas la nouvelle

### Serveur

Global

### Date et heure de la production du bug

21/11 00h00m

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
