### ISSUE TITLE
[Bug][Faction]: Quête failed pas de perte d'elo

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1023]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Pour les quêtes de faction du 31/10/2022 - 06/11/2022 (4e0f76e4-5eba-456d-87a2-bd86c6ce9a0c) et 07/11/2022 - 13/11/2022 (0d34557e-c9f1-4cc0-bcf2-fc10d1feb59b), il n'y a pas de trace de failed lorsqu'elles n'ont pas été faite. Par contre, le gain d'elo est bien marqué si elles ont été faite.

Pour la quête suivante, 14/11/2022 - 20/11/2022, il y a le failed mais c'est dans la saison d'après relatif au bug #1022 

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
