### ISSUE TITLE
[Verification]: Loot Turtle Scale

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1026]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lors de la version , j'ai remarqué que le loot de la Tortue (Turtle Scale) était beaucoup plus rare que les autres. Serait-il possible de vérifier directement dans le code , afin de vérifier si le loot est belle et bien obtenable? Si elle est obtenable , est-ce que son taux de loot est différent par rapport aux autres "loot rare" des mobs du métier Hunter.

**Comment by Zeldown** [comment]
✔️ Le taux de drop sera augmenté !
