### ISSUE TITLE
[Bug]: Palapass entité ajout

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1028]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il manque ces entités dans la liste des possibilités : 
- pig 
- slime
- ghast
- Silverfish
- Blaze
- witch
- Sheep
- Skeleton
- Magma cube

**Comment by KraemerJoe** [comment]
Les entités sont enregistrées.
Merci
