### ISSUE TITLE
[Bug]: Minerais de Pala Infinis Dim mineur

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#1030]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

En utilisant une POG Big Hole sur un drawer, ça casse les minerais qu'il y a autour (dont le paladium) sans les décompter au score de la dimension.

De façon générale les points des minerais récupérés "secondairement" par les hammer et les POG ne sont pas décomptés

### Serveur

Minage

### Date et heure de la production du bug

29/11 7h49

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Le bug signalé n'est pas un bug inhérent au mod Factions

**Comment by KraemerJoe** [comment]
Hello,
Ce soucis ne sera plus d'actualité à la prochaine version.
Merci ;)
