### ISSUE TITLE
[Bug]: Black lucky block, mauvais évent

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1031]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lorsqu'on ouvre un lucky bloc, la roulette nous donne un event, dans ce rec apporté par un joueur, il obtient des évent mais pas les récompenses qui vont avec, le dauphin a la place des vaches, les sonic boots a la place du pnj trader.
https://www.youtube.com/watch?v=ELlcg1kgAYc

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
