### ISSUE TITLE
[Bug][BedWars]: Fin de game Connection Lost

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#1033]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

A la fin de chaque partie, l'on Connection Lost 
[ https://prnt.sc/1DG0EWVIxrBX ]

### Qu'aurait-il dû arriver ?

un retour au lobby ? ou sur le gui du bedwars 

### Numéro de la partie (/lag)

?

### Nom de la map (/map)

?

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
