### ISSUE TITLE
[Bug][BedWars]: Spectateur début de game

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#1035]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

J'ai rejoint la game à 1 seconde du lancement,
donc le tchat à affiché Vous etes en mode ghost, je suis donc compté comme [spectateur] Rouge mais je ne suis pas en spectateur -je suis avec l'inventaire de début de jeu, https://prnt.sc/1-dTiBnmdvMF
-j'ai etait tp a la base rouge
-je ne peut pas fly ni spec la game donc je suis coincé sur l'ile
-le gui en haut me dit que je suis rouge https://prnt.sc/e3c1U18BJEeb
-cela bloque la fin de game vu que je suis dans une equipe, personne gagne 

### Qu'aurait-il dû arriver ?

soit faire que je soit réellement dans la game, soit faire réellment le ghost

### Numéro de la partie (/lag)

?

### Nom de la map (/map)

jardin

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
