### ISSUE TITLE
[Bug]: Notif XP Métier

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#1040]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Le gain d'xp n'est pas accumulé sur les nouvelles notifications et spam donc les notifications

Vidéo : https://youtu.be/GJV4-xXyf10

### Qu'aurait-il dû arriver ?

L'xp devrait être accumulé en 1 seule notification

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
