### ISSUE TITLE
[Bug][Faction]: Impossible de Surclaim une AP. Bug prix achat AP 

### ISSUE THREAD

**Issue by Inconnu200** [Paladium-Developpement/Paladium-Issue#1042]
### Pseudo InGame

Inconnu200

### Que s'est-il passé ?

Lors de la possession d'un AP , les joueurs ne peuvent pas **surclaim** l'AP de la faction. De plus des joueurs possédant un grade ne bénéficie pas de la réduction en fonction du grade.  

### Serveur

Manashino

### Date et heure de la production du bug

11h50 environ.

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci de fournir une vidéo des problèmes mentionnés, sans cela je ne pourrais pas traiter l’issue. Les deux issues n’ayant pas de rapport, je t’invite à en créer deux pour chacun des deux bugs signalés

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
