### ISSUE TITLE
[Bug]: Calendrier bug notif 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1043]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Notif quand on clique sur une case d'un autre jour 
![image](https://user-images.githubusercontent.com/92928910/204927562-f31ada42-236f-4c03-a32d-4d7b1cb89722.png)

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
