### ISSUE TITLE
[Bug]: Calendrier fatal error ouverture box

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1044]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Fatal error pendant l'ouverture d'une case

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
