### ISSUE TITLE
[Bug]: Item non récupérable "Didier ID:3095" 

### ISSUE THREAD

**Issue by Inconnu200** [Paladium-Developpement/Paladium-Issue#1046]
### Pseudo InGame

Inconnu200

### Que s'est-il passé ?

Report d'un joueur qui à eu un clear sur l'item "Didier" après l'avoir posé. 
Réalisation d'un éssai sur le faction SM avec différentes pioches sans enchant et avec "silk touch" 

**[ Résultat ]** : Item non récupérable 

### Qu'aurait-il dû arriver ?

récupération de l'item par l'un des moyens essayé.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
