### ISSUE TITLE
[Bug]: Safe chest 

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1048]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il est possible de mettre des safe chest dans l'ec et dans le coffre de faction

### Qu'aurait-il dû arriver ?

Ne pas pouvoir les mettres, ou du moins les retirer

### Serveur

Global

**Comment by VexonTV1** [comment]
(fonctionne avec tous les types de safe chest)

**Comment by aureliancnx** [comment]
Corrigé dans le cas du coffre de Factions ✅

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
