### ISSUE TITLE
[Bug][BedWars]: Bug Nombre verre

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1050]
### Pseudo InGame

Suny_y

### Que s'est-il passé ?

En jeu il y a écrit qu'on achete 12 verre mais on en reçois que 4

### Qu'aurait-il dû arriver ?

On aurai du soit en recevoir 12 soit afficher qu'on en recois 4

### Numéro de la partie (/lag)

toute

### Nom de la map (/map)

toute

**Comment by aureliancnx** [comment]
Corrigé!
