### ISSUE TITLE
[Bug][BedWars]: vanish

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#1051]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

Enlever le vanish et le /god à chaque début de game, je suis dans le cas ou j'ai tué des joueurs mais eux ne me voit pas

### Qu'aurait-il dû arriver ?

Que je soit visible pour les joueurs 

### Numéro de la partie (/lag)

bedwars1x8-l2bk83 02/12/2022 21:42:36

### Nom de la map (/map)

Pirate

**Comment by aureliancnx** [comment]
Ne te met pas en vanish avant le début de la game ? :)

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
