### ISSUE TITLE
[Bug]: Crash lorsque 2 launcher sont ouvert

### ISSUE THREAD

**Issue by Celtix27** [Paladium-Developpement/Paladium-Issue#1053]
### Pseudo InGame

Celtix27

### Que s'est-il passé ?

Lorsque j'ai un launcher d'ouvert et que je tente d'ouvrir un deuxième, mon launcher que je tente d'ouvrir crash

### Qu'aurait-il dû arriver ?

Le deuxième laucher aurait du ouvrir comme le premier

### Serveur

None

### LOG

![image](https://user-images.githubusercontent.com/112564513/205455143-420513f4-c764-414e-af79-d1d91dd3e2b2.png)

**Comment by aureliancnx** [comment]
Bonjour,

Supprime tous les fichiers de ton dossier mods.
