### ISSUE TITLE
[Bug]: Item clear palapass lorsque l'inventaire est plein

### ISSUE THREAD

**Issue by Celtix27** [Paladium-Developpement/Paladium-Issue#1054]
### Pseudo InGame

Celtix27

### Que s'est-il passé ?

Les items sont clear lorsque nous voulons récup une récompense du palapass et que l'inventaire est plein, l'item est clear.

### Qu'aurait-il dû arriver ?

Mettre un message comme quoi l'inventaire est plein et ne pas donner l'item au joueur.

https://www.youtube.com/watch?v=SCwwQucQSqE

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello, corrigé merci.
