### ISSUE TITLE
[Bug][Faction]: Sponge [ID:606] Claim

### ISSUE THREAD

**Issue by Eclair93** [Paladium-Developpement/Paladium-Issue#1055]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Quand on pose une éponge dans un claim ou on a pas d'accès. Son effet se produit et elle enlève l'eau/fakewater. Ce qui permet de pouvoir endium dyna sans canon a sable ou enlever toute l'eau/fake d'une base sans effort.

Voici un rec qui montre la chose : https://youtu.be/FnpAL_aoPMI

### Serveur

Global

### Date et heure de la production du bug

04:25

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
