### ISSUE TITLE
[Bug]: Golem Fou 

### ISSUE THREAD

**Issue by Inconnu200** [Paladium-Developpement/Paladium-Issue#1056]
### Pseudo InGame

Inco

### Que s'est-il passé ?

Lors de l'ajout de la compétences "Golem fou" de la voie Guerrière , le Golem vous attaque vous et les autres joueurs présent mais ne casse aucun block ( essaie réalisé avec de l'hardened et de la stone ). 
Si c'est volontaire , faire un changement IG ou/et Wiki. 

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

La description sera corrigé IG. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
