### ISSUE TITLE
[Bug]: Impossible d'obtenir des éponges

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1058]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Il est impossible d'obtenir un éponge selon la méthode du Wiki : "Pour obtenir une éponge, vous devez procéder de la manière suivante : il faut trouver un mouton non-tondu et faire un clic droit dessus avec un poisson cru. Le mouton devient alors un mouton spongieux, qu’il faut ensuite placer dans l’eau. Une fois gorgé d’eau, il suffit de le tondre avec des cisailles. Il redeviendra alors un mouton normal."

Rec : https://www.youtube.com/watch?v=EmABPSpqEjg&ab_channel=Sebastien

### Qu'aurait-il dû arriver ?

Lorsqu'on fait un clique droit sur un mouton spongieux , on devrait recupérer les éponges et le mouton reviendra normal.

### Serveur

None

**Comment by Akysooo** [comment]
Les éponges sont bien récupérables (aka mes tests et le fait des quêtes de factions validées. Essaye le faire passer dans plusieurs sources d'eau

**Comment by aureliancnx** [comment]
Bonjour,

Je ferme ce ticket
