### ISSUE TITLE
[Bug][Faction]: Quête de faction, récompense non donné

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1061]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

De temps en temps, lorsque qu'une faction fini la quête, les récompense reste "en cours" et ne sont pas donné, 
Exemple de faction la "Listenbourg" http://haste.minestats.eu:47777/lenuvenogu
https://prnt.sc/WIkzwBWOBRCX
Même chose avec la Orion

### Serveur

Global

### Date et heure de la production du bug

28/11/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Akysooo** [comment]
Update la Orion a de nouveau le problème avec la quête de cette semaine

**Comment by Akysooo** [comment]
Le problème est toujours d'actualité, la par exemple "LaVictory". 
![image](https://user-images.githubusercontent.com/92928910/229362334-6150ec11-62a5-415d-96ce-43acb2236a69.png)
Quête fait le mardi 28 vers 14h. Tous les joueurs qui ajoutaient, à ce moment là, les items étaient sur untaa.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
