### ISSUE TITLE
[Bug][BedWars]: Hitbox

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1064]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Nous pouvons voir la hitbox des personnes qui sont invisible.

### Qu'aurait-il dû arriver ?

On devrait rien voir

### Numéro de la partie (/lag)

toutes

### Nom de la map (/map)

toutes

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
