### ISSUE TITLE
[Bug]: Cooldown Foreuse

### ISSUE THREAD

**Issue by ZyF0x** [Paladium-Developpement/Paladium-Issue#1065]
### Pseudo InGame

ZyF0x

### Que s'est-il passé ?

Possibilité d'utiliser la foreuse sans temps d'attente 

### Qu'aurait-il dû arriver ?

Un cooldown de 2h est indiqué sur l'item

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
