### ISSUE TITLE
[Bug][Faction]: Probleme vente ap

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1066]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

N'importe qui peut vendre une ap de sa faction même sans avoir les perm peu importe le role dans la faction

### Qu'aurait-il dû arriver ?

On ne devrait pouvoir vendre que si on as la perm

### Serveur

Global

### Date et heure de la production du bug

07/12/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

https://youtu.be/8iJPHg1yRbg
https://cdn.discordapp.com/attachments/922904088335769660/1050155339233898576/Paladium_-_Fila21.png

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
