### ISSUE TITLE
[Bug]: Pas de texture aux particules quand on casse les LB de Noel

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#107]
### Pseudo InGame

FuzeIII

### Que s'est-il passé ?

Quand on casse le Lucky Block In game y'a des particules noires et roses moches

### Qu'aurait-il dû arriver ?

Les particules doivent avoir la texture des LB.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
