### ISSUE TITLE
[Bug]: Possible de stocker un Safe Chest dans un EC

### ISSUE THREAD

**Issue by SirLink23** [Paladium-Developpement/Paladium-Issue#1070]
### Pseudo InGame

SirLink_

### Que s'est-il passé ?

Il est possible de stocker dans un enderchest un safe chest https://youtu.be/34teOxpEMgE
Testé dans le rec avec un Mega Safe Chest mais faisable avec tout les safe chest.

### Serveur

Manashino

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
