### ISSUE TITLE
[Bug]: Chaudron n'absorbe pas les paladium flower

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1071]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les paladium flower jeté dans le chaudron donne 3d'xp au lvl 10, on a beau les jetés elle ne dispawn pas et ne donne aucune xp 
https://www.youtube.com/watch?v=xBa6thbMvs8

### Serveur

Naera

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
