### ISSUE TITLE
[Bug]: Mineral flower fait crash quand on la bone meal

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1072]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on force la pouce d'une mineral flower on crash
https://www.youtube.com/watch?v=HhI7GT2IcWM

### Serveur

Imbali

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
