### ISSUE TITLE
[Bug]: Drawbridge et feuillage

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1073]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on met n'importe quelle type de feuille dans le drawbridge, ce sont des oak qui sont posé et qui sont repris
https://www.youtube.com/watch?v=bjM71hCjjRQ

### Serveur

Imbali

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
