### ISSUE TITLE
[Bug]: Potion mineur fou

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1076]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lorsqu'on active une potion du mineur fou, on ne gagne plus d'xp pour le métier de mineur avec la stone par exemple.

### Serveur

Imbali

**Comment by KraemerJoe** [comment]
Hello, je viens de tester et cela fonctionne pour moi, cela doit être un autre soucis (limite daily xp, impossibilité de gg de l'exp à ton niveau ? )
