### ISSUE TITLE
[Bug][Faction]: Possibilité de mettre les boites à golem dans le village de Fac

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#1079]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

J'ai réussi à poser une boite à golem, à claim la zone avec mon village de fac et la boite à golem est réstée intacte

### Qu'aurait-il dû arriver ?

La boite à golem aurait dû se détruire (comme pour un coffre par exemple)

### Serveur

Soleratl

### Date et heure de la production du bug

13/12

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Corrigé !
