### ISSUE TITLE
[Bug]: Déblocage étrange Lucky Stats

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#108]
### Pseudo InGame

Fuzay

### Que s'est-il passé ?

Parfois quand on ouvre des Lucky Blocks (typiquement ceux de Noel), on reçoit une notif "vous avez débloqué x% du Lucky Stats" alors que ça n'est pas le cas (genre par exemple on reçoit une notif de 50% alors qu'on vient de passer les 25).

Ensuite parfois on se fait spammer de notif comme quoi on a débloqué X% sans raisons.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
