### ISSUE TITLE
[Bug]: LB 6 Pssssssss

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1082]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: "Fais spawn 10 creeper superchargés invincibles
Les creepers ne font pas de dégâts de zone ou d’attaque"

Actuel: Les creepers ne sont pas invincibles

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
