### ISSUE TITLE
[Bug]: LB 9/10/11/12 Beacon

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1083]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Crée une structure beacon avec des blocs de diamant (3 étages)

Actuel: Il y a une chance que le joueur soit kick est que l'event ne se produise pas correctement (seuls le beacon et 3 blocs sont alors posés)

### Serveur

None

**Comment by aureliancnx** [comment]
As-tu des logs clients ?

**Comment by aureliancnx** [comment]
Je n'ai pas eu de réponse au ticket et je n'ai pas réussi à reproduire le bug
