### ISSUE TITLE
[Bug]: Snow chiante sur l'effet Grand Froid du Lucky Block Noel

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#109]
### Pseudo InGame

Fuzay

### Que s'est-il passé ?

Parfois l'effet qui fait que la neige se pose partout où on passe se retrouve à créer de la neige "Flottante". Ca peut également empêcher de descendre des blocs (en mode auto bridge sous ses pieds à cause de la neige).

### Qu'aurait-il dû arriver ?

Il faut rajouter un check pour vérifier si le joueur touche bien le sol au moment de mettre la neige.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
