### ISSUE TITLE
[Bug]: LB 51 Instant break up

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1090]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Détruit l’objet dans la main du joueur

Actuel: Seulement si c'est un outil + à corriger : "à ce que tu as en main" + mettre le message en couleur

### Serveur

None

**Comment by aureliancnx** [comment]
Corrigé pour le message.
En revanche pour uniquement l'outil, cela a été développé comme ca.
