### ISSUE TITLE
LB 90 Adieu faction

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1094]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Kick le joueur de la faction. Si il en est le chef, alors ça kick un de ses membres au pif. Affiche au dessus de la hotbar “Vous avez été kické de votre faction… Ooops”

Actuel: ne fait rien

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
