### ISSUE TITLE
[Bug]: LB 101 Wi-Fi

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1095]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Give un levier sans fil (wireless lever)

Actuel: "Fonctionnel
Le levier ne fonctionne pas en revanche"

### Serveur

None

**Comment by Zeldown** [comment]
❌ Le wireless lever fonctionned très bien.
