### ISSUE TITLE
[Bug]: LB 110 Tire aux pigeons

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1097]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Fait spawn 3 poules qui s'envolent (l'une d'elles donne du paladium à sa mort)

Actuel: "Fonctionnel
Apparemment, les trois poules donnent du paladium, mais seule une seule en donne (à cause du fait qu'elles se stackent ?)"

### Serveur

None

**Comment by Zeldown** [comment]
❌ Le mobstacker étant indispensable, cela ne sera pas corrigé.
