### ISSUE TITLE
[Bug]: Téléportation Foireuse

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#110]
### Pseudo InGame

Fuzay

### Que s'est-il passé ?

C'est un bug qui est là depuis longtemps (depuis l'anti No-Clip) mais qui dégrade bcp l'experience de jeu. Quand ton se tp dans un endroit unsafe (dans un block ou dans le "vide" on se retrouve glitché). C'est également le cas pour des blocs non pleins sans hitbox genre les hautes herbes.

Je sais pas si c'est fixable.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
