### ISSUE TITLE
[Bug]: LB 138 Steve Jobs

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1100]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Donne le skin de steve au joueur jusqu'à ce qu'il déco

Actuel: Fait crash

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
