### ISSUE TITLE
[Bug]: LB 148 Père fouras

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1101]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Le joueur reçoit une enigme dans le chat et doit répondre, il a 3 essais, s'il se trompe il meurt sinon il gagne 10 pala - ne pas afficher la réponse du joueur à tout le monde

Actuel: "Fonctionnel
Il meurt mais ne perd pas son  stuff"

### Serveur

None

**Comment by aureliancnx** [comment]
Corrigé
