### ISSUE TITLE
[Bug]: LB 158 Nether Activé

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1102]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Créer un portail du nether, quand le joueur passe dedans il est directement tué (le portail s’auto-détruit après). Attention à ce que ça ne remplace pas la bedrock.

Actuel: "Fonctionnel
Le joueur ne perd pas son stuff"

### Serveur

None

**Comment by aureliancnx** [comment]
Corrigé
