### ISSUE TITLE
[Bug]: LB 163 Terrain miné

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1103]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Fait spawn 1 bloc miné au hasard, si le joueur le récupère avec Silk Touch il peut les garder

Actuel: "Fonctionnel
Le bloc explose si on le casse"

### Serveur

None

**Comment by aureliancnx** [comment]
Je n'ai pas bien compris. Le bloc est censé exploser si le joueur ne récupère pas le bloc en question avec Silk Touch.

**Comment by aureliancnx** [comment]
OK
