### ISSUE TITLE
[Bug]: LB 181 Time Machine

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1106]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Remplace les blocs autour du Lucky Block par des blocs d’herbes de la alpha (ceux avec le vert Flashy) dans un rayon de 4 blocs

Actuel: Ne marche pas et fait lag le serveur en entier

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
