### ISSUE TITLE
[Bug]: LB 191 Sonic

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1107]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Donne un effet de vitesse 200 pendant 1min au joueur, mais il ne peut plus sauter ni monter le blocs avec le travel stuff

Actuel: Donne l'effet de speed mais fait rollback quand on avance

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ L'effet de potion a été diminué à 8 car sinon le serveur rollback automatiquement les joueurs qui vont trop vite.

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
