### ISSUE TITLE
[Bug]: LB 192 Danse maintnant

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1108]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Fait spawn une pluie d’éclairs sur le joueur qui dure 30 secondes. Le joueur peut esquiver.

Actuel: Fonctionnel, mais dur 2 minutes

### Serveur

None

**Comment by aureliancnx** [comment]
Corrigé !
