### ISSUE TITLE
[Bug]: LB 193 N’en parle à personne

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1109]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Envois le lien d’une vidéo Youtube au joueur (qui est sur la chaîne de Fuze en non repertorié)

Actuel: Ne donne pas de lien de vidéo

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

N'ayant pas eu de réponse par rapport à l'URL de la vidéo de la part de l'auteur du Luckyblock, je ferme cette issue et ce sera un WONTFIX en attendant.
