### ISSUE TITLE
[Equilibrage]: Changer le nombre de Lucky Blocks de Noel donnés à chaque palier

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#111]
### Pseudo InGame

Fuzay

### Que s'est-il passé ?

Les lucky Blocks de Noel donnent trop de LB à chaque pallier. Les diviser par deux.

**Comment by Zeldown** [comment]
🕐 Attendre le retrait des LuckyBlock de Noël de la boutique pour le faire

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
