### ISSUE TITLE
[Bug]: LB 225 Pas là

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1113]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Fait apparaître 3 x 3 x 3 Minerais de Paladium. Sauf que quand le joueur les casse, rien ne drop (c’est des faux minerais de pala). Ils peuvent être récup en utilisant Silk Touch

Actuel: Fonctionnel mais fait spawn un 2x3 si il est mis sur de la bedrock

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
