### ISSUE TITLE
[Bug]: LB 226 Prendre du recul

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1114]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Bloque le joueur en F5 arrière jusqu’à la prochaine connexion

Actuel: Fonctionnel, /lobby enlève le blocage 

### Serveur

None

**Comment by aureliancnx** [comment]
Ce n’est pas un bug
