### ISSUE TITLE
[Bug]: LB 240 Prêt à tout

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1118]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Des enclumes “dollar” tombent du ciel dans un pattern random. A chaque enclume qui tombe sur la tête d’un joueur, le joueur est crédité de 1000$ (mais il prend les même dégats que pour une vraie enclume . Entre 7 et 15 enclumes.

Actuel: Première essai 4 enclume, deuxième essai 1 seul, troisième essai 7, la money est bien donné

### Serveur

None

**Comment by aureliancnx** [comment]
Corrigé
