### ISSUE TITLE
[Bug]: LB 244 Ton heure à sonnée

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1121]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: "Le joueur meurt, à l’emplacement de sa mort se trouve une tombe. En respawnent le joueur dispose d’une clé de de tombe (la clé de tombe permet de se téléporter directement à la tombe, ne marche pas si le joueur est en combat). Si le joueur fait clique droit sur sa tombe il récupère son stuff.
La tombe doit avoir porter le nom de son ""auteur"". Permet de ne pas stacker les tombes et de pouvoir retrouver la personne s'il y a un pb"

Actuel: Ne tue pas, donne un effet de potion

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
