### ISSUE TITLE
[Bug]: LB 256 Tu n'es plus toi même

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1122]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

CDC: Change le skin du joueur par un skin random

Actuel: Ne fonctionne pas

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
