### ISSUE TITLE
[Bug]: LB 278 Grand Froid

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1126]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on à l'effet grand froid qui pose de la neige au sol, si on ce tp a notre home avec un bloc en dessous comme un coffre, il est clear.

https://www.youtube.com/watch?v=K2norfDXzaw

### Serveur

None

**Comment by aureliancnx** [comment]
Corrigé
