### ISSUE TITLE
[Bug]: Quête Palapass

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1128]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Je ne peux pas la test donc je report juste
Report du joueur : 
"La quette : Armurier Flemmard, Ne fonctionne pas j'ai beau réparer la durabilité de mon armure ceci ne fonctionne pas !"

### Serveur

None

**Comment by KraemerJoe** [comment]
![image](https://user-images.githubusercontent.com/40207750/208093420-fb261b36-0f52-46c4-bd98-b464ef93d32d.png)
Merci à l'avenir de BIEN (BIEN) tester les bugs avant de les reports.
