### ISSUE TITLE
[Bug][Faction]: Panneau ap/mdf cassé

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1129]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Des joueurs arrivent à casser les panneaux des ap.
Il faudrait les remettre à chaque redémarrage serveur comme pour les infos dedans.

Même si les panneaux des mdfs sont hors de celle ci, on peut aussi appliquer le truc à eux au cas où

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Corrigé
