### ISSUE TITLE
Le farm de fleurs via le chaudron n'apporte plus d'xp[Bug]: 

### ISSUE THREAD

**Issue by Camouchat** [Paladium-Developpement/Paladium-Issue#113]
### Pseudo InGame

Camouchaat

### Que s'est-il passé ?

Le fait de drop des fleurs dans le chaudron ne donne plus d'xp

### Qu'aurait-il dû arriver ?

J'aurais du gagner 2xp par fleur, cela semble avoir été désactivé depuis la dernière MAJ

**Comment by Camouchat** [comment]
https://www.youtube.com/watch?v=G1VfspxFhj0&feature=youtu.be
Voici un rec pour vous montrer

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
