### ISSUE TITLE
[Bug]: Crusher Endium Nugget

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1132]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Bonsoir, Il y aurait un souci avec le crusher, une fois le lancement effectué après avoir rempli la jauge avec des orangeblue, le joueur crasherait au moment où il récupère l'endium nugget.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Je vois que ton issue est écrite au conditionnel. Peux-tu me fournir les logs de crash ?

Sans cela je devrai fermer le ticket.

Cordialement

**Comment by aureliancnx** [comment]
Je ferme le ticket, n’ayant reçu aucune réponse.

@iWoZ0
