### ISSUE TITLE
[Bug]: Foreuse lag et crash serveur

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1134]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

La foreuse fait lag, voir crash les serveurs, muzdan le 19/12/2022 vers 16h crashai toute les 5min à cause de Herve qui l'utilisai

### Serveur

Muzdan

**Comment by aureliancnx** [comment]
Bonjour

as-tu une vidéo ?

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
