### ISSUE TITLE
[Bug][Faction]: Acces MDF

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1135]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lorsque d'un joueur d'une fac est kick, les perm d'acces a la MDF sont toujours mise, donc un joueurs peux venir dans la mdf temps que les perms ne sont pas enlevé, dans le cas de la bisounours ils ce sont fait volé un t4, une lg dans le coffre à don, et grief la mdf, mais je n'est pas réussi à casser le moindre item, cependant on peux tout de même rentrer
https://www.youtube.com/watch?v=5t-MOHMktHk&feature=youtu.be

### Serveur

Global

### Date et heure de la production du bug

21/12/2022 17h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bug pris en compte

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,

**Comment by Zazho** [comment]
Je ne sais pas si la patch prend en compte aussi les AP, mais on viens de me report la même chose pour les AP, je ne voulais pas recréer d'issue si jamais ca corrige les 2 en même temps

**Comment by aureliancnx** [comment]
Pour les AP il s'agit du comportement du **/f access** classique, contrairement aux AP
Tu peux tout-à-fait ajouter un joueur en /f access dans ton AP ou dans un claim classique (qu'il soit de ta faction ou non). Cela a donc un comportement normal que ça ne supprime pas le joueur du /f access s'il est kick de la faction, dans le cas des AP.
