### ISSUE TITLE
[Bug]Switch golem en paladium

### ISSUE THREAD

**Issue by Shadixxs** [Paladium-Developpement/Paladium-Issue#1137]
### Pseudo InGame

Shadixs

### Que s'est-il passé ?

Le golem en paladium peut etre switch via une switch arrow.

### Qu'aurait-il dû arriver ?

Comme les autres entités telle que les endermites, le joueur ne devrait pas pouvoir se switch avec le golem.

### Serveur

Global

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
