### ISSUE TITLE
[Bug][Faction]: Extrapolated Bucket dans les MDF

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#1139]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Les joueurs non access peuvent extraolated bucket les sources de liquide si celle-ci sont trop proche.

Rec : https://youtu.be/tg4Hk35hUjE

### Qu'aurait-il dû arriver ?

Les joueurs ne devrait pas pouvoir retirer les sources

### Serveur

Global

### Date et heure de la production du bug

22/12/2022 13H50

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bug de region et non bug du plugin Faction ❌
