### ISSUE TITLE
[Bug]: Il n'est plus possible de retirer le chaudron et le cauldron core

### ISSUE THREAD

**Issue by Camouchat** [Paladium-Developpement/Paladium-Issue#114]
### Pseudo InGame

Camouchaat

### Que s'est-il passé ?

Pour retirer le chaudron il fallait retirer le cauldron core en premier lieu, puis on pouvait récupérer les autres blocs du chaudron. 
Hors la, en enlevant le cauldron core en premier, l'espace où se trouve l'angelic water se transorme automatiquement en lave. Comme si il y avait une erreur lors du démontage alors que non cela a bien été réalisé dans l'ordre. 

### Qu'aurait-il dû arriver ?

Nous aurions du récupérer le Cauldron Core normalement et aucune lave aurait du se former. 
Ce bug est sans doute lié à la dernière mise à jour concernant l'angelic water; cf mon dernier report bug issue en rapport avec la problématique d'xp

**Comment by Camouchat** [comment]
https://www.youtube.com/watch?v=uh7U-b4kpiU&feature=youtu.be
Voici le rec, bon je viens de me rendre compte dans la panique de ma mort que je n'ai pas coupé assez tot et donc on ne voit pas précisement que j'enleve le cauldron core en first mais c'est bien le cas xD

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport

**Comment by Camouchat** [comment]
Coucou Zel, je viens de faire le test pour : 
l'xp apportée par les fleurs : cela ne fonctionne toujours pas 
le fait de récupérer le cauldron core : pareil il se casse encore et tout se transforme en lave :/

**Comment by Camouchat** [comment]
Je ne sais pas si cela t'es utile, mais au cas où, voici un rec si ça peut faciliter ton travail : 
https://www.youtube.com/watch?v=CwJ72uLGJkg
