### ISSUE TITLE
[Bug][Faction]: Probleme MDF

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1141]
### Pseudo InGame

Fila21

### Que s'est-il passé ?

La maison de faction n'est plus accéssible et impossible a racheter

### Qu'aurait-il dû arriver ?

La maison de faction aurai dû pouvoir être racheter ou alors renouvelé

### Serveur

Global

### Date et heure de la production du bug

23/12/2022 21h05

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Lorsque tu signales un bug, il est important de me donner des informations claires et précises. En effet, il n'existe pas qu'une seule maison de faction sur Paladium. Sur chaque serveur Faction, une multitude de maisons de factions sont présentes.

Par conséquent, m'informer de l'impossibilité qu'une maison de faction est inaccessible et impossible à acheter revient à me demander revient, par effet miroir, à me positionner sur une incompréhension de ton signalement de bug.

Lorsque tu signales un bug, il faut en effet préciser le nom du serveur en question plutôt que "Global" - car non, il n'y a pas de maisons de faction en Minage, ni dans les mini-jeux - pas encore à ma connaissance, au moins.

Il y a 80 maisons de faction enregistrés dans la base de données. Admettons qu'une maison de faction me prenne 2 minutes à vérifier qu'on puisse bien "y accéder" et pouvoir l'acheter, cela me prend 160 minutes sur ma journée. Rajoutons à cela 10 minutes le temps de naviguer à travers tous les serveurs Factions et 1 minute, pour le temps de lecture de ton signalement de bug. Cela revient à 171 minutes, soit 11,875% d'une journée complète (24 heures) ou **35,625%** d'une journée de travail de huit heures. Je fais évidemment l'impasse sur la durée du traitement du bug qui me prendrait moins d'une heure, soyons large.

Par conséquent, l'inefficacité d'un traitement de bug pourrait se traduire par la nécessité d'aller chercher par moi-même d'autres informations : 

- "Maison de faction n'est plus accessible" - **Qu'est-ce qu'une maison de faction "plus accessible" exactement?** Que veux-tu dire par cela ? Une capture d'écran du problème rencontré pourrait aider à mieux comprendre le problème que tu rencontres. Sinon, il m'est nécessaire de faire la différence du comportement des 80 maisons de faction dans lesquelles j'essaye "d'accéder", en admettant que je veuille rentrer dedans.
- "Maison de faction impossible à racheter" - **Que veux-tu dire par "impossible à racheter" exactement ?** Cela pourrait vouloir dire plusieurs choses : 

1. Tu as un crash quand tu essayes de cliquer sur le panneau de la maison de fation
2. Le panneau de la maison de faction n'existe plus
3. Le panneau de la maison de faction affiche une erreur spécifique qui me permettrait d'en savoir plus, mais tu ne me l'as pas donné. Je dois aller cliquer sur les 80 panneaux des maisons de faction présentes en bases de données
4. Le panneau de la maison de faction ne fait rien, dans ce cas, il est important de me le préciser

Cela peut encore vouloir dire d'autres choses, mais j'en fais une synthèse des potentiels problèmes que tu peux rencontrer, en prenant **uniquement** les idées les plus _probables_.

Au défaut de ne pas pouvoir deviner ton problème, je t'invite à te renseigner sur la façon dont tu peux **signaler un bug efficacement**. Plusieurs tutoriels existent, dont [voici un exemple](https://www.browserstack.com/guide/how-to-write-a-bug-report).

Si nous demandons des logs, des captures d'écrans, des informations précises sur le problème que tu rencontres (c'est-à-dire développer exactement le comportement du problème que tu rencontres), c'est pour pouvoir traiter efficacement le bug rencontré, et ainsi éviter de devoir entamer une procédure de recherche pour chaque bug signalé lors d'un sprint curatif. Ainsi, cela permet d'éviter également à devoir demander des informations supplémentaires à chaque individu nous signalant un bug, qui peut être une perte de temps.

Je t'invite à réouvrir une issue lorsque toutes les conditions du signalement de ton bug seront réunies.
