### ISSUE TITLE
[Bug]: Commande dans le tchat faction, ally,...

### ISSUE THREAD

**Issue by Shadixxs** [Paladium-Developpement/Paladium-Issue#1144]
### Pseudo InGame

Shadixs

### Que s'est-il passé ?

Quand un joueur ecrit une commande dans le tchat faction, allies, truces, allies/truces celle-ci est envoye dans le tchat alors qu'elle devrait s'executer comme la photo ci-dessous
![image](https://user-images.githubusercontent.com/96438167/209582773-580f2e4b-5c8f-417a-b82d-3bebcf1a3ffd.png)

### Qu'aurait-il dû arriver ?

La commande devrait s'executer et pas s'envoyer dans le tchat comme c'est le cas dans le tchat global. 

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
