### ISSUE TITLE
[Bug]: Online detector

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1145]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Le bloc online detector ne ce met pas en vert quand le joueur est connecté 

### Serveur

Global

**Comment by KraemerJoe** [comment]
![image](https://user-images.githubusercontent.com/40207750/209675064-bbd34492-bbf6-46ab-bf79-62cc5570a8bb.png)

**Comment by KraemerJoe** [comment]
Fonctionnel.......

**Comment by Zazho** [comment]
Marche pas avec les staff alors, on s'en fiche alors

**Comment by Zazho** [comment]
Il ne marche pas interserver cependant
