### ISSUE TITLE
[Bug]: Fiole d'xp farmeur / mineur

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1147]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Impossible de boire les fioles d'xp des métiers de farmeur / mineur 
![image](https://user-images.githubusercontent.com/104795165/209741892-0f8b002c-7ca4-4b55-bb0f-1a382ee1d6e2.png)

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello,
Bug plus d'actualité avec la refonte.
