### ISSUE TITLE
[Bug]: Mending Pierre de survie

### ISSUE THREAD

**Issue by SirLink23** [Paladium-Developpement/Paladium-Issue#115]
### Pseudo InGame

SirLink_

### Que s'est-il passé ?

Selon des retours de certains joueurs, Mending serait fonctionnel sur la Pierre de Survie ce qui permet de ne pas la casser et de ce fait de pouvoir l'utiliser à nouveau.

https://www.youtube.com/watch?v=BcWDaIeqTvo à 4:34 on voit le joueur utiliser la pierre et des xp berrys.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
