### ISSUE TITLE
[Bug][Faction]: Banque de fac 

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1150]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

La NoNameFac ne peux pas accéder à la banque de faction peux importe le grade 
On a le message d'erreur "veuillez patientez entre chaque requête", une seul à pourtant été envoyé
https://prnt.sc/Sjnzwnoova3W

### Serveur

Global

### Date et heure de la production du bug

30/12/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
