### ISSUE TITLE
[Bug]: Clé natura box builder

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1155]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les clé natura box builder ne marche pas
https://prnt.sc/UTbtXwk4DPSf
https://prnt.sc/N2SNoqQjh2b6

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
