### ISSUE TITLE
[Bug]: Lucky flower trop longue

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1156]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les lucky flower ne ce casse pas après 3j, j'ai eu un joueurs avec qui elle a tenu 9j, et j'ai fait un test actuellement elle est encore posé, et elle en est à 7j actuellement
https://prnt.sc/4d8ly7OkgrHc

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
