### ISSUE TITLE
[Bug][Faction]: Achat d'ap sans enlever l'argent

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1157]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Une personne a pus avoir une ap sans avoir la perm d'enlever l'argent de la banque de fac. Le panneau ne change pas mais l'ap appartient bien a sa faction. Possible de le faire sur toutes les ap. La faction qui a vendu l'ap ne recois aucun argent.

### Qu'aurait-il dû arriver ?

Il n'aurai pas du pouvoir acheter sans la permission

### Serveur

Global

### Date et heure de la production du bug

04/01/2023 22h45

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

https://www.youtube.com/watch?v=tvrgOhrKsms

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
