### ISSUE TITLE
[Bug]: JetPack

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1158]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Il est toujours possible de réparé le jetpack grâce au diamant.

### Qu'aurait-il dû arriver ?

On ne devrait pas pouvoir

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
