### ISSUE TITLE
[Bug]: Cassage de l'obsi moddé + duplication obsidienne

### ISSUE THREAD

**Issue by AlanahPaladium** [Paladium-Developpement/Paladium-Issue#116]
### Pseudo InGame

Aalanah

### Que s'est-il passé ?

La pioche avec enchantement Silk touch permet de casser l'obsidienne moddé.
Lorsque le bloc d'obsi moddé est cassé, il est automatiquement remplacé par un bloc d'obsi normal
voir rec fais par Camouchaat ; https://www.youtube.com/watch?v=GvPYMdUKOK4

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
