### ISSUE TITLE
[Bug]: Couche anormal

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1160]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Il est possible grace au wither et a la wither saddle ou encore au jetpack avec un inv full de fire work, d'aller a des couche très haute (dans les plus de 1000). A ses couches ils tp un dc qu'ils déco pour le reco dès qu'il veulent chercher des base. A des couche au dessus de la couche 256 (ou un peu plus) les seuls pourcent afficher sont les pourcents modée. Et a ses hauteur, les fleur tel que les harpago ou encore les lucky flower ne marche pas ou ne sont pas du tout pris en compte. Beaucoup de joueur en "abuse" pour pouvoir aller piller des base facillement et être sur que ce soit des bases de joueurs.

### Qu'aurait-il dû arriver ?

Soit les fleurs aurait du marcher, soit tous les pourcent aurais du être visible ou alors il aurait dû être impossible d'aller aussi haut.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
