### ISSUE TITLE
[Bug]: Farmand

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1163]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Depuis quelque jour plus aucun mob ou presque ne spawn en farmland. Beaucoup de joueurs sont venu nous le report et j'ai été vérifier personnellement et en effet nous ne croisons plus aucun mob même après le message disant que des mob vont spawn.

De ce que les joueurs m'ont dit ca serait depuis le changement des nom des minage mais je n'ai aucune certitude sur cela.

### Qu'aurait-il dû arriver ?

Des mobs devrait continuer a spawn.

### Serveur

Farmland

**Comment by aureliancnx** [comment]
Corrigé
