### ISSUE TITLE
[Bug]: Bionic snowball

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1164]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on envoie une bionic sur un joueur qui à de l'endium ou du paladium vert elle ne fait rien et nous marque dans le chat qu'on ne peux pas sur du pala vert ou de l'endium, le soucis étant actuellement que le pala vert est courant, tout le monde pvp avec au minimum les bottes, ce qui rend totalement inutile la bionic en pvp car elle ne pourras jamais tuer personne

### Qu'aurait-il dû arriver ?

Enlever la protection avec le paladium vert maintenant qu'il est devenu courant

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour

Ceci n’est pas un bug mais c’est à voir avec la création

Cordialement
