### ISSUE TITLE
[Bug]: Endium flower

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1165]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on pose une endium flower, elle deviens rouge si quelqu'un rentre dans la zone, cependant elle ne redeviens pas bleu si le joueur déco ou /spawn

### Qu'aurait-il dû arriver ?

Redevenir bleu une fois que plus personne n'es dans la zone

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour

as-tu une vidéo de cela ?

**Comment by KraemerJoe** [comment]
Hello,
A la décision on ne mettra pas que le poseur soit exclus.
