### ISSUE TITLE
[Bug]: crash à l'ouverture de box au spawn

### ISSUE THREAD

**Issue by PrincesseM23** [Paladium-Developpement/Paladium-Issue#1166]
### Pseudo InGame

_PrincesseM_

### Que s'est-il passé ?

Plusieurs joueurs ont report sur TS que le jeu plante à chaque fois qu'ils ouvrent une box au spawn. Ils sont obligés de fermer leur jeu manuellement voir de redémarrer leur PC. Mais ils récupèrent quand même le contenu de la box.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Peux-tu me fournir des logs de crash client ?

Cordialement

**Comment by aureliancnx** [comment]
N’ayant pas reçu de logs, je suis contraint de fermer cette issue.
