### ISSUE TITLE
[Bug]: Eponge dans les claims

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1169]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

Lorsqu'on utilise une éponge dans un claim enemie, le bloc ne se pose pas, mais l'éffet de l'éponge s'active, retirant l'eau et la fake.
Dans le cas de l'eau, celà permet de dyna / endium dyna des blocs normalement inaccessible.

https://www.youtube.com/watch?v=xvZuMt4lIX8

### Qu'aurait-il dû arriver ?

Le bloc ne se pose pas et l'effet ne proc pas.

### Serveur

Rakavi

**Comment by aureliancnx** [comment]
Bonjour

je t’invite à consulter les bugs déjà ouverts et fermés. En effet, j’ai déjà réglé ce bug pour la prochaine mise à jour (v8.5).
