### ISSUE TITLE
Annulation de l’effet rebondissant du slimepad sur les Withers

### ISSUE THREAD

**Issue by Syb3rtron** [Paladium-Developpement/Paladium-Issue#117]
### Pseudo InGame

Sybertron_

### Que s'est-il passé ?

Lorsqu’une Frost Arrow est lancée sur un Wither, celui-ci n’est plus affecté par le recul des slimepads pendant 20 secondes ce qui rend inutile cette défense dans les bases claim.

### Qu'aurait-il dû arriver ?

Le Wither ne devrait pas être affecté par la Frost Arrow.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
