### ISSUE TITLE
[Bug][Faction]: Attaque de village

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1170]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Lors d'une attaque de village la faction qui attaque reste bloquer sur le message suivant "Le village est en cours de sauvegarde... L'assaut commencera dès que la sauvegarde sera terminer. Une erreur est survenue lors de la sauvegarde du village. L'assaut ne peut pas commencer. Veuillez contacter le support."

Faction qui defend Elysiium

Faction qui attaque : OverLoard

### Qu'aurait-il dû arriver ?

La sauvegarde aurait du pouvoir ce faire et donc l'assaut aurai du pouvoir ce faire 

### Serveur

Imbali

### Date et heure de la production du bug

24/01/2023 21h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

https://cdn.discordapp.com/attachments/1001190418509209641/1067544185466523738/image.png

**Comment by aureliancnx** [comment]
Bonjour

Pouvez-vous me dire si le bug est spécifique sur Imbali ou est présent sur les autres serveurs ?
