### ISSUE TITLE
[Bug]: Affichage PB market

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#1171]
### Pseudo InGame

babastyz

### Que s'est-il passé ?

Lorsqu'un joueur dépasse 380 000 PB dans le market on ne voit plus le K et lorsque l'ont passe la souris dessus l'affichage est bug.

ScreenShot 1 : https://prnt.sc/qGvlki-rLp_X

ScreenShot 2 : https://prnt.sc/1zgM_jFKSO5B

### Qu'aurait-il dû arriver ?

On devrait voir un K derrière et l'affichage devrait pouvoir afficher le nombre exact de PB.

### Serveur

Global

**Comment by KraemerJoe** [comment]
![image](https://user-images.githubusercontent.com/40207750/214787697-743c6d49-be4f-47d0-9d20-3516e0cd8c60.png)
