### ISSUE TITLE
[Bug]: Mending sur épée en lucky-ium

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1173]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

On peux mettre mending sur l'épée et la réparer via ce moyen, alors que l'épée ne devrait être réparable uniquement via des lucky blocks

https://www.youtube.com/watch?v=ucdVt1V28bI

### Qu'aurait-il dû arriver ?

Impossible de mettre mending sur l'épée

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
