### ISSUE TITLE
[Bug][Faction]: Unclaim parcelle village de fac

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#1176]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Lorsque ont fait /f vunclaim on ne récupère pas le point de parcelle et celui-ci est clelete n'apparaît pas dans l'hôtel de ville.

### Qu'aurait-il dû arriver ?

On devrait récupérer le point de parcelle pour pouvoir le déplacer par exemple....

### Serveur

Global

### Date et heure de la production du bug

29/01/23 | 18h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour

Ce problème m’a déjà été signalé mais il ne m’a jamais été informé dans le cahier des charges correspondant à cette fonctionnalité d’effectuer le remboursement.
