### ISSUE TITLE
[Bug]: Restone XP mineur

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1177]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

La redstone ne donne pas d'XP dans le métier de mineur. Et je pense savoir pourquoi, quand on mine de la redstone, elle se transforme en redstone allumée, et ce bloc ne donne pas d'xp.
Vidéo du bug [ici](https://youtu.be/5xwEWtURnz0)

### Serveur

Minage

**Comment by KraemerJoe** [comment]
Corrigé merci
