### ISSUE TITLE
[Bug]: Commande /go : Naera / Rakavi

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#1178]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/43002022/216713702-f000f364-de12-4a4c-ada1-0b8c1a548573.png)
Les serveurs Naera et Rakavi n'ont pas été supprimer du /go

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
