### ISSUE TITLE
[Bug]: Show FPS

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#1180]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/43002022/216718636-6eae1ac8-3d0c-423e-ad51-1cd5a9eba5e8.png)
Le show fps a les entités ce qui avait été désactiver pour pas faire concurrence à l'unclaim finder

### Qu'aurait-il dû arriver ?

Avant seul les fps était afficher

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
