### ISSUE TITLE
[Bug]: PalaJobs récompense

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#1182]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

Les récompenses de changement de métier ne drop pas dans l'hypothèse ou l'inventaire du joueur serait full

### Qu'aurait-il dû arriver ?

Elle devrait drop au sol

### Serveur

Global

**Comment by KraemerJoe** [comment]
Corrigé merci
