### ISSUE TITLE
[Bug]: Enchantement Pickaxe Of the God 

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#1183]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

Il est possible d'enchanté la pog alors qu'il avait été convenu qu'elle ne soit plus enchantable 

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
