### ISSUE TITLE
[Bug]: Obsidienne slab incassable

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1185]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les obsi slab sont incassable, que ce soit avec un builder wand ou avec une pioche
https://www.youtube.com/watch?v=k6GZCMNgqkw&feature=youtu.be

### Serveur

Manashino

**Comment by KraemerJoe** [comment]
Corrigé merci.
