### ISSUE TITLE
[Bug]: Box trixium

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1187]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

J'ai aucun rec, mais 3 supports en 5 min, ils ont tout les 3 trouvé un blocs blanc dans les serveur minage, surement la box trixium, ce qui leur a donné cet item 
https://prnt.sc/nehqGwDRGQz8
https://prnt.sc/7GMvzIjdf-R0

J'ai aucun moyen de générer un box trixium, mais 3 report en 5 min c'est rarement normal

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
