### ISSUE TITLE
[Bug]: /ec

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1188]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Il est possible de faire la commande /ec lorsqu'on est en combat via une macro du nei (ou aussi en le tapant je pense)

### Qu'aurait-il dû arriver ?

La commande ne devrait pas être possible. 

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
