### ISSUE TITLE
[Bug]: /nether ne tp pas

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1194]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on fait /nether on a beau tout avoir de coché, elle ne nous tp pas
https://studio.youtube.com/video/TfxnFFuL_DM/edit

### Qu'aurait-il dû arriver ?

TP dans le nether

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
