### ISSUE TITLE
[Bug]: Quartz ore, tout n'xp pas

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1195]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on casse du quartz en mienrai on a pas l'xp tout le temps
https://www.youtube.com/watch?v=ge-hcVJdZw8

### Qu'aurait-il dû arriver ?

Xp a chaque bloque cassé

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
