### ISSUE TITLE
[Bug]: Pickaxe of the Gods (POG)

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1196]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Bug 1 : La texture des pog est décalée d'un niveau, voici l'ordre correct, de 1 à 100. La texture de la POG niv 6 est celle des pogs 1 à 5 alors qu'elle devrait être la même que les pogs 7 à 10 et c'est la même chose pour les intervalles suivantes. 

Bug 2 : Les enchantements de la POG niveau 100 ne se déclenchent pas après avoir casser les premiers blocs.

### Qu'aurait-il dû arriver ?

Bug 1 : voir les screens en dessous pour l'ordre et les bonnes textures à appliquer

Bug 2 : les enchantements **Efficacité 5 Fortune 3** auraient dû se mettre sur la POG niv 100

### Serveur

Global

### LOG

![image](https://user-images.githubusercontent.com/121042777/216817673-9d6b9ee5-ae79-493c-88e0-79d6c0010ff4.png)
![image](https://user-images.githubusercontent.com/121042777/216817670-7d358e2a-5247-4599-80dc-2217bb270dd5.png)

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
