### ISSUE TITLE
[Bug]: Palaquest - Mauvais gagnant

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1197]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Il a été constaté plusieurs fois que des joueurs gagnaient le palaquest sans avoir été les premiers à donner la réponse. Le joueur ayant donné la réponse ne gagnant rien du tout.
![image](https://user-images.githubusercontent.com/121130216/216818555-04c91759-df9c-4933-80ee-4ddb1d72d464.png)
![image](https://user-images.githubusercontent.com/121130216/216818568-82685a97-e8db-4296-bba2-5b8c1f46aad9.png)

### Qu'aurait-il dû arriver ?

C'est le premier joueur à donner la bonne réponse qui est censé gagner.

### Serveur

Global

**Comment by Zeldown** [comment]
❌ Ceci n'est pas un bug, le joueur en question voit son message avant mais il ne l'est pas réellement, c'est dû a sa connexion.
