### ISSUE TITLE
[Bug]: Quête métier - Pierre précieuse

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1198]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La quête, qui consiste à casser 2 minerais de diamant, ne se valide pas. 

### Qu'aurait-il dû arriver ?

La quête devrait se valider après avoir piocher les deux minerais de diamant.

### Serveur

None

### LOG

https://www.youtube.com/watch?v=94M3baOEPW8

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
