### ISSUE TITLE
[Bug]: Quête métier - Tomber en morceaux

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1199]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La quête qui consiste à casser 64 blocs de gravier ne fonctionne pas correctement : les blocs cassés ne sont pas tous comptabilisés. 

### Qu'aurait-il dû arriver ?

Chaque bloc cassé devrait être comptabilisé. 

### Serveur

Global

### LOG

https://www.youtube.com/watch?v=kgWxk43OLb8&ab_channel=TRZ_Nythrox

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
