### ISSUE TITLE
[Bug]: Enchantements livres étranges/dysfonctionnels & bug slimepad joueur

### ISSUE THREAD

**Issue by swaiino** [Paladium-Developpement/Paladium-Issue#120]
### Pseudo InGame

swaiino

### Que s'est-il passé ?

J'ai vu avec un joueur qu'avec certains livres le fait de le combiner avec une pièce d'armure en paladium ou tout autre item n'était pas réalisable en fonction des livres. 

Par exemple j'ai essayé avec ce joueur d'enchanter un pantalon en paladium P4 U3 avec un livre P4 U3 et cela à mis "too expensive", même chose avec un livre P4 U3 Mending. Et par contre ça à fonctionner avec un livre P4 U3 Sharpness 5 Infinity 1 etc (beaucoup d'enchantements).

Je ne sais pas d'où peux venir le problème sachant que tous ces livres ont la même ID (et au passage même souci pour une épée, bottes...)

------------------------------

Et pour ce qui est du bug slimepad j'envoie directement une vidéo où un joueur est "KB" dans les slimepads dans un AP et arrive à en sortir par magie.

(time code à 00:13)

Merci d'avance

**Comment by Zeldown** [comment]
Merci d'ouvrir 2 issues différentes pour 2 bugs différents.

**Comment by Zeldown** [comment]
Merci d'apporter plus d'infos pour la bug du "too expensive" avec rec et contexte svp.

**Comment by Zeldown** [comment]
Ceci n'est pas un bug.
