### ISSUE TITLE
[Bug]:  XP Mineur (Block : Diorite, Andésite, Granite)

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1201]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello,
Petit bug pour avoir de l'exp mineur à l'infini avec uniquement 3 blocs il suffit de les poser quelque part dans la nature attendre que le serveur crash où redémarre et cassaient les blocs pour gagner de l'exp.
Rec : https://www.youtube.com/watch?v=9x9E6APGDM4 

### Serveur

Global

**Comment by Zeldown** [comment]
❌ Ce n'est pas corrigeable, cela à toujours été comme cela.
