### ISSUE TITLE
[Bug]: Métier alchimiste - extraction de sève

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1206]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Lors de l'extraction de sève, la fiole se remplit et la bûche se vide. Quand on retire la fiole, elle donne 4xp (ici, elle donne 4,60 à cause de grade). 

Le problème étant : la fiole n'est en fait pas pleine du tout, juste visuellement. Si on éteint et rallume l'extracteur, on voit qu'elle n'est pas pleine. 

1. Peu importe à combien elle est remplie, elle donne 4xp.
2. Visuellement, elle est à chaque fois pleine, alors qu'elle ne l'est pas.
3. Il est possible d'xp à l'infini le métier d'alchimiste (cf. rec 2).
4. Ce bug est effectif avec les 4 sortes de bûches (le nombre d'xp gagnée pour chaque type de bûche est différent).

### Qu'aurait-il dû arriver ?

Normalement on ne devrait que : 
- récupérer l'xp complète qu'avec une fiole pleine
- remplir au plus 6 fioles à partir d'une bûche

### Serveur

None

### LOG

Preuve 1 : https://youtu.be/I27VpHHGMfQ
Preuve 2 : https://www.youtube.com/watch?v=qZ-TPwgrbew&ab_channel=RoselyneeR%C3%A9daction

**Comment by KraemerJoe** [comment]
Corrigé merci.
