### ISSUE TITLE
[Bug]: Lucky Block 26 à modifier 

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1209]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Le Lucky Block 26 "Explosif" drop une dynamite en endium au joueur. Cependant, celles-ci ont été bloquées et ne sont plus accessibles aux joueurs.

Il faudrait modifier cet événement, peut-être en droppant une autre sorte de dynamite : 
- Dynamite : ID 4568
- Ninja Dynamite : ID 4569
- Big Dynamite : ID 4570

### Serveur

None

### LOG

![image](https://user-images.githubusercontent.com/121042777/217047340-d49a5441-24b1-4e97-81b3-e71e635a547e.png)

**Comment by KraemerJoe** [comment]
Corrigé merci.
