### ISSUE TITLE
[Bug]: GUI Invisible Changer couleur aura

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1210]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le GUI pour changer la couleur d'une aura est invisible. Le GUI est belle et bien présent , mais invisible. Il faut donc appuyer sur ÉCHAP pour continuer de naviguer dans le GUI des cosmétiques.

### Qu'aurait-il dû arriver ?

Le GUI pour changer la couleur d'une aura devrait être visible.

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
