### ISSUE TITLE
[Bug]: 2 crafts pareil pour 2 items différents

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1211]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le Home remover et du "feu" ont un craft identique. De plus , je ne pense pas que du feu soit craftable.

![image](https://user-images.githubusercontent.com/104092723/217143260-66d65787-8d2d-4852-a594-2c1c9f7877c2.png)

![image](https://user-images.githubusercontent.com/104092723/217143405-d4e65453-7d79-4901-a14f-e7e95fceaf6d.png)

### Qu'aurait-il dû arriver ?

Le feu ne devrait pas être craftable.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
