### ISSUE TITLE
[Bug]: Notification de récompenses

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1216]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La notification de récompenses disponibles via le /rewards claim s'affiche pour des joueurs n'ayant pourtant pas de grade. 

Si le joueur tente tout de même de faire la commande, un message dans le chat lui indique qu'il n'a pas accès à cette permission.

### Qu'aurait-il dû arriver ?

Le joueur ne devrait pas recevoir de notification en rapport avec le /rewards claim s'il n'est pas concerné.

### Serveur

None

### LOG

https://www.youtube.com/watch?v=kPkQYrJlrD0

Joueur ayant report le bug + à l'origine du rec : lebayk - non-gradé

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
