### ISSUE TITLE
[Bug]: les tank absorbe trop de sève

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1218]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand no rempli un tank de sève, il va absorber les 16 fiole donc 16000, même si il dois en prendre que 3000, ceci clear donc la différence entre ce que le tank veux, et ce que tu a.
https://www.youtube.com/watch?v=b5IWelEHC9g

### Qu'aurait-il dû arriver ?

Prendre uniquement ce que le tank dois prendre pour être rempli

### Serveur

Global

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
