### ISSUE TITLE
[Bug]: /skin qui fait n'imp

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#122]
### Pseudo InGame

FuzeIII

### Que s'est-il passé ?

Le /skin en jeu change tout le temps et c'est jamais celui qu'on a sélectionné.
Il n'y a également pas moyen de revenir au skin par défaut.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
Je laisse @terrainwax s'en charger, cela semble venir de sa mise à jour Halloween

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
