### ISSUE TITLE
[Bug xp hammer

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1220]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on casse de la stone avec un hammer donc 9 bloc, on ne recoit l'xp que de 1 bloc
https://www.youtube.com/watch?v=zlhgJhguJDI&feature=youtu.be

### Qu'aurait-il dû arriver ?

Recevoir l'xp de 9 blocs

### Serveur

Global

**Comment by KraemerJoe** [comment]
Corrigé @Zeldown merci
