### ISSUE TITLE
[Bug]: Xp métier, buche de bois alchimiste

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1221]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Casser les 3 bois moddés ne donne pas d'xp
https://www.youtube.com/watch?v=Wl6LGnq2E6g&feature=youtu.be

### Serveur

None

**Comment by Zeldown** [comment]
❌ Cela fonctionne très bien.
