### ISSUE TITLE
[Bug]: Bloc portal dispawn

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1222]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les bloc portal des portail alchimiste dispawn quand on les poses
https://www.youtube.com/watch?v=hyfggxfuQ94&feature=youtu.be

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
