### ISSUE TITLE
[Bug]: Stack d'item

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1227]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

A gauche de l'écrant il y a un gui qui nous dit ce qu'on porte, et ce qu'on tiens, et la quantité, elle nous donne maintenant plus que la quantité tenu dans notre mains elle ne prend pas en compte l'inventaire, ce qui étais le cas avant
https://prnt.sc/9vlOAFvyFrBp

### Qu'aurait-il dû arriver ?

Prendre en compte tous l'inventaire

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
