### ISSUE TITLE
[Bug]: Casser de la stone avec silktouch

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1228]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Casser de la stone donne 0.5 d'xp, cependant la casser avec silktouch n'en donne pas, il n'es précisé nul part qu'elle dois forcément être transformer en cobble
https://www.youtube.com/watch?v=ijXHSX6vcKM&feature=youtu.be

### Qu'aurait-il dû arriver ?

Gagner aussi de l'xp

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello,
Aucun XP n'est donné si il y a l'enchant silktouch, même pour la stone.
