### ISSUE TITLE
[Bug]: Egg non présent parchemin

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#123]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Le parchemin indique la direction du spawn de l'oeuf quand l'oeuf est sur un autre serveur 

### Qu'aurait-il dû arriver ?

Le parchemin devrait dire que l'oeuf est sur un autre serveur et si possible lequel.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
