### ISSUE TITLE
[Bug]: Item à 0 au /ah

### ISSUE THREAD

**Issue by Sunlay-10** [Paladium-Developpement/Paladium-Issue#1231]
### Pseudo InGame

Sunlay10

### Que s'est-il passé ?

Un joueur est venu se plaindre d'avoir des items a vendre au /ah mais la quantité est à 0, c'est à dire que lorsque l'objet est vendu dans sa totalité, l'item reste dans le shop alors qu'il n'est plus achetable car il n'y a plus de quantité, de plus cela garde un slot occupé dans la reserve ah du joueur

### Qu'aurait-il dû arriver ?

L'item aurait du disparaitre et le slot libéré

### Serveur

None

### LOG

![Uploading 2023-02-09_13.10.31.png…]()

**Comment by KraemerJoe** [comment]
Normalement corrigé à la prochaine MAJ merci
