### ISSUE TITLE
[Bug]: Correction à apporter

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1232]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/121042777/217785629-e5582ed8-a042-4ba4-938e-c9f2da3119c5.png)

Il faut corriger "leurs arènes" en "leur arène".

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
