### ISSUE TITLE
[Bug]: Correction - GUI Métiers

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1234]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/121042777/217797598-879fb478-37bf-4b25-af18-0b65cceb0196.png)

Les phrases ne sont pas très françaises, il faudrait les remplacer par : 

Tous les jours, vous gagnez 0,1% de bonus d'xp en plus lorsque vous validez les trois quêtes.

Ne pas valider les 3 quêtes divise par 2 votre bonus actuel.

### Serveur

None

**Comment by KraemerJoe** [comment]
Corrigé merci.
