### ISSUE TITLE
[Bug]: Lvl25 farmeur : pas d'xp avec les carottes

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1236]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les joueurs lvl25 farmeur ne gagnent pas d'xp en récoltant les carottes.

(rec de ZyF0x, retesté par Inconnu200)

### Qu'aurait-il dû arriver ?

Ils devraient gagner 1,75xp par carotte.

### Serveur

None

### LOG

https://www.youtube.com/watch?v=0KtMCyKu27U

**Comment by KraemerJoe** [comment]
Corrigé merci.
