### ISSUE TITLE
[Bug]: Pas d'xp mineur avec silk touch

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1239]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

On ne gagne pas d'xp mineur lorsqu'on mine avec une pioche silk touch, ni quand on recasse les blocs ensuite avec une pioche classique.

Le rec est fait avec de la stone et du charbon, mais le cas est identique pour de la redstone, lapis, quartz, etc

### Qu'aurait-il dû arriver ?

On devrait gagner de l'xp mineur soit au moment de miner le bloc avec la silk touch, soit quand on le recasse ensuite avec une pioche classique (deuxième option plus logique selon moi)

### Serveur

None

### LOG

https://www.youtube.com/watch?v=eQGVAVu_kz0

**Comment by KraemerJoe** [comment]
Hello,
Tout comme la version précédente:
- Le silk touch empêche de gagner de l'XP
- Les minerais posés à la main de rapporte pas d'XP 

Pour gagner de l'XP avec des minerais posés, il faut utiliser smelt le minerais, exemple hammer smelt + minerais de paladium vous donnera l'xp
