### ISSUE TITLE
[Bug]: Obsidian flower pots 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1240]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello,
Le flower pots en obsidienne est incassable à l'endium dynamite !

voir rec : https://www.youtube.com/watch?v=-Xmm9PoI3bc

### Serveur

None

**Comment by KraemerJoe** [comment]
Corrigé merci.
