### ISSUE TITLE
[Bug]: achievements : Explorateur dimensionnel

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1242]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

L'achievement Explorateur dimensionnel ne fonctionne pas. Il ne débloque pas les différents serveurs au fur et à mesure qu'on se tp dedans. Test fait sur l'ensemble des serveurs avec /go et /lobby.

(rec datant d'il y a 2-3 jours mais bug toujours d'actualité)

### Qu'aurait-il dû arriver ?

L'achievement devrait se compléter au fur et à mesure que le joueur visite les serveurs.

### Serveur

Global

### LOG

https://www.youtube.com/watch?v=wCsSNLBTl5E

**Comment by KraemerJoe** [comment]
Corrigé merci.
