### ISSUE TITLE
[Bug]: grade trixium nombre de homes

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1243]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les joueurs trixium et trixium+ ne possèdent que 15 homes par serveur contre 20 annoncés.

(rec 1 de moi-même avec grades trixium et modérateur chat sur luccento
et rec 2 du joueur PlayerOfTheRoom grade trixium sur untaa)

### Qu'aurait-il dû arriver ?

Les joueurs du grade trixium au moins devraient avoir 20 homes.

### Serveur

Global

### LOG

Rec 1 : https://www.youtube.com/watch?v=DuZiNc421pM

Rec 2 : https://www.youtube.com/watch?v=N-WOhrHW8Wo

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
