### ISSUE TITLE
[Bug]: Mailbox notif

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1244]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Certains joueurs ont une notif comme quoi ils ont un mail et quand ils vont dans leur Mailbox ils n'ont rien, aucun mail.

### Serveur

None

**Comment by KraemerJoe** [comment]
Salut, il faudrait plus de détails, quels joueurs, rec etc
