### ISSUE TITLE
[Bug]: Mineur fou ne one shot pas

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1245]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

En minant avec la potion de mineur fou et une pioche en pala non enchantée, on ne casse pas instantanément la stone. (je n'ai pu essayer qu'en minage)
Tous les blocs se cassent à la même vitesse mais pas instantanément (rec 1). 
La stone se brise plus rapidement sans mineur fou avec une pioche effi 5 (rec 2)

### Qu'aurait-il dû arriver ?

Le wiki dit : "Une fois consommée, cette potion vous permet de casser de façon instantanée les blocs avec une pioche en paladium"
Il faudrait donc apporter une correction au jeu ou au wiki.

### Serveur

Minage

### LOG

Rec 1 : https://www.youtube.com/watch?v=d_NpYYC3OzQ

Rec 2 : https://www.youtube.com/watch?v=2Z58JwJJi24

**Comment by KraemerJoe** [comment]
Hello,
Il n'y a pas de soucis sur ton rec la potion prends bien effet et te permet de casser l'obsidian instant.
Le ralentissement est normal étant donné les vérifications apportées ( PS: pas rentable pour la stone)
