### ISSUE TITLE
[Bug]: Potion mineur fou permet de casser bloc au spawn

### ISSUE THREAD

**Issue by Ramoniste95** [Paladium-Developpement/Paladium-Issue#1248]
### Pseudo InGame

Ramoniste

### Que s'est-il passé ?

Un joueur à réussi à casser des blocs au spawn du minage NCFQ64 en utilisant une potion de mineur fou

### Qu'aurait-il dû arriver ?

Il n'aurai pas du réussir à casser les blocs

### Serveur

None

**Comment by KraemerJoe** [comment]
Corrigé merci @Zeldown
