### ISSUE TITLE
[Bug]: potion mineurs

### ISSUE THREAD

**Issue by Bytotox93** [Paladium-Developpement/Paladium-Issue#1250]
### Pseudo InGame

ByTotoxx93

### Que s'est-il passé ?

âpres avoir bu la potion de mineur fou 1h et 2h les bloque ne se one shot pas

Preuve : https://youtu.be/yLo5hF-XipI

### Qu'aurait-il dû arriver ?

j'aurais du pouvoir casser les block en un coup 

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello,
Cette potion n'est effective uniquement sur les blocs sensibles aux pioches.
