### ISSUE TITLE
[Bug]: Seed Crystals 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1252]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Possibilité d'avoir des ice crystal seed à l'infini 
voir la vidéo : 
https://www.youtube.com/watch?v=jTYWDzO6o8Y

### Serveur

None

**Comment by KraemerJoe** [comment]
Salut, le problème semble corrigé, j'attends confirmation
