### ISSUE TITLE
[Bug]: Pickaxe of the gods XP

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1253]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello, un joueur est venue me report un bug sur les pogs elles dépendent toujours du métier de Mineur 

Voir la vidéo ( très mauvaise qualité ) : https://www.youtube.com/watch?v=bhtFltwWHPM

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
