### ISSUE TITLE
[Bug]: Faction ptr 

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1254]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il est impossible de rejoindre le faction ptr actuellement avec la commande /go faction-ptr 

### Qu'aurait-il dû arriver ?

allez dans le serveur créatif

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
