### ISSUE TITLE
[Bug]: Blocs one shot par POG lvl1

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1255]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Certains blocs se cassent instantanément à la main et aussi avec la POG lvl1 et permettent donc de l'up très facilement. Ce sont les "bûches", les **items 628 à 628:5**. On peut les reposer et xp la POG à l'infini. Cette technique commence à être utilisée par certains joueurs, en binôme pour reposer avec un builder wand.

Je vous ai fait le rec en minage, mais cela fonctionne aussi en faction, avec les autres types de bois.

### Qu'aurait-il dû arriver ?

Soit les blocs ne devraient pas se casser instantanément, soit ils ne devraient pas permettre de gagner de l'xp sur la POG.

### Serveur

Global

### LOG

https://www.youtube.com/watch?v=WQ43D8xLIVA

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
