### ISSUE TITLE
[Bug]: Correction orthographe - munitions

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1256]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/121042777/218514602-9d912186-7c04-4c63-b45b-28d0a47872a5.png)
Pour les munitions 4734, 4734:1, 4734:2, 4734:3, 4735, 4735:1, 4735:2, 4735:3, 4736, 4736:1, 4736:2, 4736:3, il faut corriger "anti-matiériel" en "**anti-matériel**"

![image](https://user-images.githubusercontent.com/121042777/218515125-d30b3024-19f5-491e-b413-7d4f56286403.png)
Pour les munitions 4737, 4737:1, 4737:2, 4737:3, 4738, 4738:1, 4738:2, 4738:3, 4739, 4739:1, 4739:2, 4739:3, , il faut corriger "anti-personnel" en "**antipersonnel**"

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
