### ISSUE TITLE
[Bug]: achievements ( Explorateur Dimensionnel )

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1259]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello,
L'achievements Explorateur Dimensionnel ne fonctionne pas pour certains joueurs pour les faction Muzdan ou Manashino

### Serveur

None

**Comment by KraemerJoe** [comment]
![image](https://user-images.githubusercontent.com/40207750/219943031-ab1ba863-edaf-4177-a9ac-c1f35cce9d95.png)
