### ISSUE TITLE
[Bug]: XP métiers et upgrade drawer

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1261]
### Pseudo InGame

Lyxya_

### Que s'est-il passé ?

(Le bug ne vient pas de moi, je mets le pseudo de la personne qui m'a envoyé le bug)
En mettant des upgrades en émeraude (à vérif avec les autres upgrades) dans un compacting drawer (à vérif avec les autres drawers), il est possible de gagner de l'xp dans un métier aléatoire, l'événement semble survenir aléatoirement, à voir si il y a une certaine manipulation à faire
Vidéo du bug : https://youtu.be/4jwZKKeAPIM (à 1:30)
Dans la vidéo on voit que la personne gagne 1 point d'xp (+ le bonus de son grade), mais elle m'a dit avoir gagné d'autres quantités d'XP, jusqu'à 50 points en farmer.

### Serveur

Neolith

**Comment by KraemerJoe** [comment]
Salut,
Doublon + à du être corrigé
