### ISSUE TITLE
[Bug]: Helios - module Territoires

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1263]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/121042777/219125920-99beac47-0c67-416a-a2d1-b817ec958aa5.png)

Comme le montre le screen, le module territoire ne fonctionne pas correctement, en effet, on ne se trouve pas dans le claim de "Rose", mais dans le claim "domysix". Et "Rose" est affiché dans tous les territoires, même wilderness.

### Qu'aurait-il dû arriver ?

Le bon territoire devrait être précisé.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
