### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sunlay-10** [Paladium-Developpement/Paladium-Issue#1266]
### Pseudo InGame

Sunlay10

### Que s'est-il passé ?

quand on vends un objet coloré a la dyeing machine dans le /ah, il reprend sa couleur d'origine,

### Qu'aurait-il dû arriver ?

Il aurait du être vendu avec la couleur choisie

### Serveur

Global

### LOG

![2023-02-16_15 39 53](https://user-images.githubusercontent.com/122158730/219355991-d5d246e7-2cb2-47a6-a267-0cb54b88a4a8.png)

**Comment by KraemerJoe** [comment]
Doublon ici https://github.com/Paladium-Developpement/Paladium-Issue/issues/1249
