### ISSUE TITLE
[Bug]: Marteau des cavernes

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1267]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Le marteau des cavernes est déblocable au niveau 35 hunter, mais lorsqu'on veut l'utiliser, un message dans le chat nous dit qu'on ne peut l'utiliser qu'à partir du niveau 60 
![image](https://user-images.githubusercontent.com/121042777/219395426-6d9b6ade-71d0-44f9-a8e7-e6dbbd614cb1.png)

### Qu'aurait-il dû arriver ?

On devrait pouvoir l'utiliser dès le niveau 35

### Serveur

None

**Comment by Volpe0008** [comment]
Je rajoute cette vidéo qu'un joueur m'a envoyer au cas ou pour montré a quel niveau c'est normalement utilisable

https://www.youtube.com/watch?v=Tp4qIcCdXgQ

**Comment by KraemerJoe** [comment]
Hello
Corrigé merci
