### ISSUE TITLE
[Bug]: Cuisson du poisson qui ne donne pas le bon montant d'xp

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1269]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Pseudo du joueur : SasukeIsBack
Serveur : Muzdan

Comme vous pouvez le voir dans ce rec, le joueur ne récupère pas le bon montant d'xp suite à la cuisson du poisson. Pourtant, cela fonctionne correctement sur les autres serveurs. Il faudrait peut-être voir s'il y a un problème avec lui ou si quelque chose a causé cela.

### Serveur

Muzdan

### LOG

https://www.youtube.com/watch?v=mRdrgWqxt50

**Comment by KraemerJoe** [comment]
Problème identifié et résolu merci
