### ISSUE TITLE
[Bug]: Quête : Steak ? Pastèque !

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1271]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Lorsqu'un joueur a la quête métier demandant de casser 32 pastèques et qu'il le fait, elles ne sont pas comptabilisées (a la main, a la hache, avec ou sans silk touch...).

Rec du joueur Onoxi

### Serveur

Global

### LOG

https://www.youtube.com/watch?v=EgSRCUl9i9k

**Comment by KraemerJoe** [comment]
Hello corrigé merci
