### ISSUE TITLE
[Bug]: Voidstone minage / bloc de voidstone

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1273]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Lorsque l'on pose une voidstone minage pour la transformer en bloc de voidstone et qu'on casse le bloc, on récupère une voidstone.

### Qu'aurait-il dû arriver ?

On devrait récupérer une **voidstone minage**.

### Serveur

None

### LOG

https://user-images.githubusercontent.com/121042777/219649143-7660afa6-e6e6-4565-827a-fa0e2b99432c.mp4

**Comment by KraemerJoe** [comment]
Merci
Corrigé @Zeldown
