### ISSUE TITLE
[Bug]: Icones achievement Metier mineur

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#1275]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

Les icones des achievements "Mineur Novice, professionnel, spécialiste et expert" située dans la partie metier on pas les bonne icones elle ont celle du hunter voir screen https://prnt.sc/LKpoq1Y6WoV6

### Serveur

None

**Comment by KraemerJoe** [comment]
Corrigé merci.
