### ISSUE TITLE
[Bug]: Market items colorés 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1277]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Un joueur et venu me report sur Teamspeak que les items colorés n'étaient pas visibles depuis le market

### Serveur

None

**Comment by KraemerJoe** [comment]
![image](https://user-images.githubusercontent.com/40207750/219943909-8aafe7e9-ef80-48a9-bdcc-be6a81d9898a.png)
Pour moi cela fonctionne, possibilité d'avoir des screen en plus, avec différents items, différents colorants ?

**Comment by Zazho** [comment]
Tu a déja fermé mon issus, pourtant c'est bien bugué, j'ai fait un rec pour le prouver, l'hang glider est bleu, dans le AH il est blanc
https://www.youtube.com/watch?v=KHYsQfNJix8&feature=youtu.be

**Comment by KraemerJoe** [comment]
@Zeldown fix
