### ISSUE TITLE
[Bug]: Bateau en bambou

### ISSUE THREAD

**Issue by WhitzQc** [Paladium-Developpement/Paladium-Issue#1279]
### Pseudo InGame

WhitzQc

### Que s'est-il passé ?

Il est possible de usebug 5 couches avec le bateau en bambou.

### Qu'aurait-il dû arriver ?

Il devrait seulement pouvoir usebug une seule couche comme le bateau normal.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
