### ISSUE TITLE
[Bug]: Faute d'orthographe

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#128]
### Pseudo InGame

FuzeIII

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/7911589/148683215-751f7834-b470-4060-a2d8-3c1e207b1dbf.png)
ça devrait être => Le dragon a déjà **été** vaincu

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
