### ISSUE TITLE
[Bug]: Bug craft escalier obsidienne renforcee 

### ISSUE THREAD

**Issue by Kittenxs** [Paladium-Developpement/Paladium-Issue#1281]
### Pseudo InGame

Mr_Kittenxs

### Que s'est-il passé ?

Le Craft de l'escalier obsidienne renforcée donne 3 escalier obsidienne normal 

https://zupimages.net/up/23/07/k9de.jpg

### Qu'aurait-il dû arriver ?

Craft de l'escalier obsidienne renforcée

### Serveur

None

**Comment by KraemerJoe** [comment]
Corrigé merci.
