### ISSUE TITLE
[Bug]: Les bonbons d'xp métiers ne donnent pas les récompenses de palier une fois consommés

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#1282]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

En mangeant un bonbon d'xp pour les métiers, celui-ci remplit bien sa fonction première de me faire gagner de l'xp pour le bonbon correspondant au métier; cependant les paliers passés lors de ce gain d'xp ne me donnent pas les récompenses prévues (ni les items, ni la money)
J'ai testé en étant lvl 1, pour les 4 métiers avec les 4 bonbons et le bonbon multicolore. 
 
Une exception près : pour le métier de Mineur et Alchimiste (respectivement bonbon jaune et mauve) j'ai reçu pour passer 10 palier : 
5 lingot de Pala et 11 trixium

Rec vidéo si besoin : https://www.youtube.com/watch?v=ae6UDvGVn2Y

### Qu'aurait-il dû arriver ?

J'aurais du recevoir chaque récompense (item et money) des paliers passés grâce au gain d'xp des bonbons

### Serveur

Manashino

**Comment by Kittenxs** [comment]
https://www.youtube.com/watch?v=AL_r44scFlg

**Comment by KraemerJoe** [comment]
Hello résolu, merci
