### ISSUE TITLE
Possible d'enchanter un hammer avec XP Bottler.

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1285]
### Pseudo InGame

VeckPex

### Que s'est-il passé ?

Il est possible de mettre l'enchantement XP Bottler sur un hammer. Cependant, seul l'xp généré en cassant de la stone fonctionne. L'xp généré par les minerais, elle est non fonctionnel.

https://cdn.discordapp.com/attachments/1019629922416857118/1077587525763354654/image.png

### Qu'aurait-il dû arriver ?

D'après le wiki, il n'est pas possible de mettre l'enchantement XP bottler sur un hammer. L'enchantement aurait du ne pas pouvoir être mis sur le hammer.

### Serveur

Global

**Comment by Zeldown** [comment]
Hello @VeckPex, comment a t'il fait pour mettre l'enchantement sur le Hammer ?

**Comment by Zazho** [comment]
@Zeldown C'est plus possible depuis plusieurs jours, au moment du report je l'avais fait avec veckpex, on avais juste à mettre le hammer dans une table moddé (ps: c'est pas mon compte opé qui avait test)
