### ISSUE TITLE
[Bug]: Remise sur le prix d'un avant-poste non-faite

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1288]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Snaki_Gold (grade Trixium) de la Overlord a acheté un AP et il a payé 700 000 $ au lieu de 490 000 $.

[Edit : la réduction ne se fait pour aucun grade]

### Qu'aurait-il dû arriver ?

Il aurait dû bénéficier d'une remise de 30%, soit de 210 000 $. 

### Serveur

Imbali

### LOG

![image](https://user-images.githubusercontent.com/121042777/220785684-e84322a1-109c-4d88-a2ac-41ca823fd95c.png)
![image](https://user-images.githubusercontent.com/121042777/220785705-feb388bb-2517-4260-aa43-55ff18a9874b.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
