### ISSUE TITLE
[Bug]: Pousse de bouleau des rivières infaisable 

### ISSUE THREAD

**Issue by swaiino** [Paladium-Developpement/Paladium-Issue#129]
### Pseudo InGame

swaiino

### Que s'est-il passé ?

Lorsque l'on jette de l'argile avec une pousse de bouleau on n'obtient pas la pousse de bouleau des rivières (comme indiqué sur le wiki)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
