### ISSUE TITLE
[Bug]: Arc en paladium

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1290]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Un joueur ayant le niveau 58 requis pour utiliser l'arc en serveur à voulu s'en servir, se dernier fait des sortes d'accoups quand on veut tirer avec des flèches dans l'inventaire sans message d'erreur de métier dans le tchat.
Or, il m'a dit quand faction PTR, l'arc fonctionne correctement.

Rec pour preuves: https://www.youtube.com/watch?v=GZ0gpebdvNs

### Qu'aurait-il dû arriver ?

L'arc en Paladium devrait aussi bien fonctionné en serveur faction qu'en serveur PTR.

### Serveur

Global

**Comment by roselyneelavraie** [comment]
Pour précision, il est utilisable à partir du niveau 65 (et normalement, ça devrait donc être 58).

**Comment by KraemerJoe** [comment]
Hello, corrigé merci
