### ISSUE TITLE
[Bug]: Mini golem niveau de métier

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1292]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

L'utilisation des mini-golems est débloquée au niveau 10 selon le tableau des récompenses. Cependant, s'ils peuvent être "posés", ils ne peuvent pas être placés dans les boîtes à golem. 

### Qu'aurait-il dû arriver ?

Il devrait être possible de les placer dans les boîtes à golem à partir du niveau 10.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
