### ISSUE TITLE
[Bug][Faction]: Claim invisible après disband

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1294]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Après avoir disband (lagarderie) les claim ont tous sauté, cependant il est impossible de casser ou de surclaim la zone, mais aucun claim est affiché.
https://www.youtube.com/watch?v=1Lc5Jl64mpY

Imbali 
-21920 64 5234

### Qu'aurait-il dû arriver ?

Pouvoir casser et claim la zone du fait qu'elle ne soit pas claim

### Serveur

Imbali

### Date et heure de la production du bug

25/02/23 12h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Cela peut arriver en cas de lag serveur. Après un redémarrage automatique du serveur, le problème n'est plus présent.
