### ISSUE TITLE
[Bug]: Quête métier lait

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1295]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Il est impossible de faire la quête de métier hunter où nous devons poser 20 sceau de lait même lorsqu'on en as 

### Qu'aurait-il dû arriver ?

On devrait pouvoir les mettre 

### Serveur

Global

### LOG

![image](https://user-images.githubusercontent.com/104594672/221355411-d96e3dc3-d3e4-4174-8fa1-3a5c1a347a2b.png)

https://youtu.be/_JGskjb7awA?t=420

(De 7 min a 7min 24)

**Comment by KraemerJoe** [comment]
Hello, fonctionnel de mon côté,
si il y a nouveau des reports merci de donner sur plusieurs types de serveurs, factions, farmland,minage etc 
![image](https://user-images.githubusercontent.com/40207750/221399507-0272a172-6a8c-4b06-a9dc-886b17e46c34.png)
