### ISSUE TITLE
[Bug]: /f sethome non bloqué au-dessus de la couche 256

### ISSUE THREAD

**Issue by Syb3rtron** [Paladium-Developpement/Paladium-Issue#130]
### Pseudo InGame

Sybertron_

### Que s'est-il passé ?

La V7.5 de Paladium a bloqué le fait de pouvoir utiliser la commande /sethome au-dessus de la couche Y : 256. Cependant, **il est possible d'utiliser la commande /f sethome après la couche Y : 256** et permet ainsi d'avoir un home très haut en montant avec un jetpack, à la couche Y : 20 000 par exemple. De ce fait, traverser la carte est très rapide, il suffit d'utiliser la commande /f home.

### Qu'aurait-il dû arriver ?

La commande /f sethome devrait être bloquée après la couche Y : 256, tout comme la commande /sethome.

**Comment by aureliancnx** [comment]
Corrigé
