### ISSUE TITLE
[Bug]:  Plus besoin de fiole pour l'echantement experience bottler 

### ISSUE THREAD

**Issue by Kittenxs** [Paladium-Developpement/Paladium-Issue#1300]
### Pseudo InGame

Mr_kittenxs

### Que s'est-il passé ?

Lorsque qu'une fiole arrive a 1000xp Farmer et qu'on en a plus dans sont inventaire une nouvelle fiole de crée tout seul 

https://www.youtube.com/watch?v=J7NmqL-Ngxo

### Serveur

None

**Comment by Zeldown** [comment]
Duplicate of #1297
