### ISSUE TITLE
[Bug]: Excavateur casse l'obsidienne renforcée

### ISSUE THREAD

**Issue by Syb3rtron** [Paladium-Developpement/Paladium-Issue#131]
### Pseudo InGame

Sybertron_

### Que s'est-il passé ?

Ce bug avec l'excavateur est le même que celui qui permettait de casser la bedrock très rapidement en début de version.
Il est possible de casser de l'obsidienne renforcée à l'aide d'un excavateur si cette obsidienne se trouve dans le rayon d'action de l'excavateur quand il casse de la terre. Voici une vidéo explicative : https://youtu.be/Z4lZIFW7prw

### Qu'aurait-il dû arriver ?

L'excavateur ne devrait pas permettre de casser de l'obsidienne renforcée.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
