### ISSUE TITLE
[Bug]: Golem interaction impossible world border

### ISSUE THREAD

**Issue by Eclair93** [Paladium-Developpement/Paladium-Issue#1311]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

On ne peux plus faire d'intéractions avec des golems car quand on le pose et qu'on clique dessus pour ouvrir l'interface, ça nous met que nous sommes trop proche de la Worldborder ou qu'on soit dans la map et même en minage

https://www.youtube.com/watch?v=c9E4qftvZi0&ab_channel=scandpop

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
