### ISSUE TITLE
[Bug][Faction]: Ap check pas le world

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1314]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Les zones de mdfs sont aussi présente dans le world end

### Qu'aurait-il dû arriver ?

Il faudrait qu'elles soient présentes que sur le overworld

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
