### ISSUE TITLE
[Bug][Faction]: Perm de faction

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1317]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il est impossible d'ouvrir une enclume moddés dans un claim si on a pas la perm "build" on peux cependant ouvrir et utiliser une anvil vanilla
https://www.youtube.com/watch?v=5Nt5p4ejp4c&feature=youtu.be

### Qu'aurait-il dû arriver ?

Que ce soit la perm d'ouvrir les coffres qui permet d'ouvrir les anvil et pas la perm build

### Serveur

Global

### Date et heure de la production du bug

02/03 18h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
