### ISSUE TITLE
[Bug]: Impossible de réinvoquer une monture suite à un crash

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1322]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand un serveur minage crash et qu'on avais une monture invoqué dessus, le serv ferme, on ne peux pas la désinvoquer car elle est considéré comme sur un autre serveur mais le serveur est fermé (reset?)
![image](https://user-images.githubusercontent.com/93079724/223431177-dac39b41-2d72-4b03-bb3e-11c4471da64c.png)

### Qu'aurait-il dû arriver ?

Désinvoquer la monture quand un serv crash
Pouvoir la réinvoquer ensuite

### Serveur

Minage

**Comment by KraemerJoe** [comment]
Hello,
Corrigé merci.

**Comment by Zazho** [comment]
Hello, j'ai voulut retirer ma monture suite au patch, et celle de anubeni, mais on ne peux toujours pas la retirer par le GUI du raccourci et par le barn controller
