### ISSUE TITLE
[Bug]: Crash des serveurs quand on monte sur une monture

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1323]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Testé sur des serveurs minage
Quand on invoque une monture et qu'on monte dessus avec un clique droit le serveur crash 
Le rec va être apporté par Anubeni je pouvais plus invoquer de monture

### Qu'aurait-il dû arriver ?

Pouvoir monter sur la monture

### Serveur

Minage

**Comment by Anubeni** [comment]
Ci dessous le rec et mes logs lors du test :

https://www.youtube.com/watch?v=QfatkCXOg6U

https://paste.rocks/?0aea05b19039a2f2#GNphU54RUuirFBvwvsTdUF5kiWqBuywg3MtT3KtDiGyL

**Comment by KraemerJoe** [comment]
Hello,
Corrigé merci.
