### ISSUE TITLE
[Bug]: Xp métier Paladium Vert

### ISSUE THREAD

**Issue by Voltext** [Paladium-Developpement/Paladium-Issue#1331]
### Pseudo InGame

Voltext

### Que s'est-il passé ?

Le Paladium Vert ne donne plus XP dans le métier de mineur lorsqu'il est cuit (four ou hammer smelt)

### Qu'aurait-il dû arriver ?

Il devrait donner 150XP

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello, corrigé merci.
