### ISSUE TITLE
[Bug]: Pistolet à liquide non fonctionnel

### ISSUE THREAD

**Issue by Voltext** [Paladium-Developpement/Paladium-Issue#1334]
### Pseudo InGame

Voltext

### Que s'est-il passé ?

Le pistolet à liquide ne fonctionne pas du tout malgré les tank (non stack) présent dans l'inventaire du joueur

### Qu'aurait-il dû arriver ?

Le pistolet à liquide devrait permettre d'interagir avec les liquides des tanks

### Serveur

None

### LOG

Petite vidéo d'explication envoyée par le joueur : https://www.youtube.com/watch?v=7o3k5nkZelc

**Comment by KraemerJoe** [comment]
Hello,
Corrigé merci.
