### ISSUE TITLE
[Bug]: Sauge non présente dans la génération des maps

### ISSUE THREAD

**Issue by Voltext** [Paladium-Developpement/Paladium-Issue#1335]
### Pseudo InGame

Voltext

### Que s'est-il passé ?

Depuis quelques semaines déjà, aucune sauge ne semble spawn sur la map, rendant ainsi le craft de la verveine impossible

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
