### ISSUE TITLE
[Bug]: Lucky drawer, possibilité de savoir qu'est-ce qui a été vendu

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1339]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il est possible de savoir qu'est-ce qui viens d'être vendu dans un lucky drawer, me mp pour connaitre la méthode

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello
Corrigé merci
