### ISSUE TITLE
[Bug]: Lucky drawer infini ah

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1341]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Si on ne quitte pas l'interface des lucky drawer quand on les met en vente il est possible d'en mettre autant qu'on veux et donc de dépasser la limite des 5 lucky drawer

### Qu'aurait-il dû arriver ?

Cela devrai ce bloquer a 5

### Serveur

Global

### LOG

https://www.youtube.com/watch?v=B-1rqit5u2A

Commencement 54 sec et ca va jusqu'a 1min35

**Comment by KraemerJoe** [comment]
Hello corrigé merci
