### ISSUE TITLE
[Bug]: Drop des items au sol avec le /trade 

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1342]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Avec le retour du /trade, les joueurs ont trouvé une faille pour arnaquer les autres joueurs. Il se tp l'un à l'autre et il suffit de fermer le menu au moment ou l'un des deux joueurs pose un item dans l'interface pour que ce dernier tombe au sol. ce qui fait que le joueur d'en face récupère tout les items et ducoup arnaque l'autre.

### Qu'aurait-il dû arriver ?

Lorsque l'un des deux joueurs choisi d'annuler l'échange, les items des deux joueurs devraient retourner dans leurs inventaire respectif au lieux d'être drop au sol.

### Serveur

Global

### LOG

Rec de test avec Jabsyyy : https://youtu.be/Mx2hqoXwNrU

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
