### ISSUE TITLE
[Bug]: Joueur glitch bloc

### ISSUE THREAD

**Issue by Gtonstuff** [Paladium-Developpement/Paladium-Issue#1344]
### Pseudo InGame

Ram0s__

### Que s'est-il passé ?

Glitch dans un block, on ne peux pas bouger surement à cause de l'anti noclip et on est freeze et la seul façon d'être débug il faut perle sauf que quand sa arrive dans la zone pvp, boss, koth les perles sont désactiver 

### Qu'aurait-il dû arriver ?

La personne n'aurais pas du être glitch dans un block et aurais pu sortir normalement 

### Serveur

Global

### LOG

https://www.youtube.com/watch?v=3ww6rFEZ2sI

**Comment by KraemerJoe** [comment]
Hello,
La vidéo est privée

**Comment by Gtonstuff** [comment]
https://youtu.be/2dLlGhNK3rA

**Comment by Gtonstuff** [comment]
https://youtu.be/3ww6rFEZ2sI

**Comment by Akysooo** [comment]
https://youtu.be/EVKbyoOdX_Q?t=35

**Comment by Lorn87** [comment]
Merci de fournir les noms des blocs en question svp

**Comment by Gtonstuff** [comment]
Il y a les trapdoor, les portes, les barreaux en fer, les chorus fruit quand il pousse, les trap door au dessus des barrieres

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
