### ISSUE TITLE
[Bug]: Probleme DPI souris 

### ISSUE THREAD

**Issue by Kittenxs** [Paladium-Developpement/Paladium-Issue#1346]
### Pseudo InGame

Mr_Kittenxs

### Que s'est-il passé ?

A certain moment la souris ce met a faire n'importe quoi meme apres une sensibilité a 1%

Voici les rec d'un joueur.

Cela le fait a plusieurs joueur.

https://www.youtube.com/watch?v=HnDk0HicSfw

### Serveur

None

**Comment by Zeldown** [comment]
Ce problème n'est pas lié à Paladium, le problème est présent dans tous les launcher Minecraft en version < 1.9 (lunar, Minecraft, Badlion, ...)
