### ISSUE TITLE
[Bug]: Affichage ToggleSprint sur Helios

### ISSUE THREAD

**Issue by Voltext** [Paladium-Developpement/Paladium-Issue#1352]
### Pseudo InGame

Voltext

### Que s'est-il passé ?

L'affichage du module Helios "Toggle Sprint" ne change jamais. Il reste fixé sur "Non" même lorsque les joueurs l'active

### Qu'aurait-il dû arriver ?

Il devrait évoluer en fonction de l'activation de celui-ci

### Serveur

Global

**Comment by Zeldown** [comment]
❌ Le bug n'est pas présent chez moi, puisque cette issue ne contient pas de rec je la close.
