### ISSUE TITLE
[Bug]: Corne dancarok craftabble

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1355]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il est possible de craft toute les cornes de dankarok peux importe notre niveau hunter

### Qu'aurait-il dû arriver ?

Etre bloqué par le niveau hunter

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello,
Corrigé merci.
