### ISSUE TITLE
[Bug]: Monture dispawn quand on la tape

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1356]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on tape une monture, peux importe avec quoi, elle disparais, on dois la désinvoquer par l'enclos pour pouvoir la réinvoquer
https://www.youtube.com/watch?v=egmjLSMZ90A

### Qu'aurait-il dû arriver ?

Qu'elle reste sur place mais prenne les dégats

### Serveur

Luccento

**Comment by KraemerJoe** [comment]
Hello,
L'issue a été traitée et le problème devrait être corrigé
