### ISSUE TITLE
[Bug]: Sort Batum dans les spawn

### ISSUE THREAD

**Issue by Voltext** [Paladium-Developpement/Paladium-Issue#1363]
### Pseudo InGame

Voltext

### Que s'est-il passé ?

Il est possible de lancer des sorts dans le spawn. En l'occurence, le sort Batum qui génère des bateaux dans le spawn

### Qu'aurait-il dû arriver ?

Cela ne devrait pas arriver car cela peut créer un abus de la part des joueurs et des bateaux partout dans le spawn

### Serveur

Global

**Comment by Zeldown** [comment]
❌ N'ayant pas d'info sur le serveur en question, ni de rec je close l'issue
![image](https://user-images.githubusercontent.com/42982613/226665704-69145862-f742-4db5-ab56-439ccfe6daad.png)

**Comment by Voltext** [comment]
https://user-images.githubusercontent.com/50301044/227010350-096009ee-af22-412b-a9c7-c9ded1232ea9.mp4

Voilà la preuve : Dans le spawn du Neolith
