### ISSUE TITLE
[Bug]: Portail en endium Alchi

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1364]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Le portail en endium d'alchimiste absorbe la sève d'ostrya mais ne rempli pas la clé, donc l'endium est pas obtenable 
https://www.youtube.com/watch?v=Y1xCjOE8QvA

### Serveur

Imbali

**Comment by KraemerJoe** [comment]
Hello, corrigé merci
