### ISSUE TITLE
[Bug]: Monture, impossible de déséquiper après une mort

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1366]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand une monture meurt sur un serveur minage, elle disparais, on ne dispo pas d'enclos sur notre serveur minage, ou on a pas forcément le niveau requis pour le poser.
On dois donc allez sur un faction déposer la monture pour la soigner, c'est impossible car un message d'erreur dit qu'elle est invoquer sur un autre serveur
On peux cependant poser un enclos sur le minage et récupérer la gemme, uniquement si il est encore ouvert, si le serveur minage c'est fermé entre temps, on est bloqué sans jamais pouvoir désinvoquer la monture et donc jamais pouvoir en équiper d'autre
https://www.youtube.com/watch?v=SpUxAMo6-eQ

### Qu'aurait-il dû arriver ?

Désinvoquer automatiquement la monture quand elle meurt pour pouvoir la soigner plus tard

### Serveur

Minage

**Comment by KraemerJoe** [comment]
Corrigé merci.
