### ISSUE TITLE
[Bug]:Monture, clear corne

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1369]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on équipe une corne sur une monture, si on /lobby sans désinvoquer la monture elle est clear quand on la repose.
https://www.youtube.com/watch?v=QpRYVSVoogw

### Qu'aurait-il dû arriver ?

garder la corne dans l'inventaire

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
