### ISSUE TITLE
[Bug][Faction]: but visuels classement faction

### ISSUE THREAD

**Issue by Celtix27** [Paladium-Developpement/Paladium-Issue#1374]
### Pseudo InGame

VloKee_

### Que s'est-il passé ?

Bug visuel au niveau du classement faction. 

### Qu'aurait-il dû arriver ?

Nous devrions voir la faction epsylon dans le classement.

Serveur GLOBAL

### Serveur

Global

### Date et heure de la production du bug

Depuis 1 semaine selon le joueur 

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

https://youtu.be/ZJEm1-YJhQ4

**Comment by aureliancnx** [comment]
Bonjour,

Cette faction ne semble plus exister. Je viens de constater que le joueur qui a effectué le signalement est dans une autre faction qui est présente dans le classement. Des problèmes peuvent avoir surgi lors du reset du classement et cela pourrait en être la cause, les factions peuvent prendre un peu de temps avant de s'afficher dans le prochain classement.

Si un staff constate le même problème pour une autre faction, n'hésitez pas à réouvrir ce ticket.

Cordialement,
