### ISSUE TITLE
[Bug]: Correction - /trade

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1378]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/121042777/227887985-4454c1d6-d3b2-41ef-a093-ae9412555925.png)

> "a bien été **envoyée**"

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
