### ISSUE TITLE
[Bug]: Gain d'expérience miner avec Dancarok

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#1379]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

Lorsqu'un hammer ou une pioche est tenu par le joueur et qu'il se trouve sur un Dancarok avec des cornes, la pierre cassée rapporte de l'expérience de métier sans faire perdre de durabilités à l'outil en main

### Qu'aurait-il dû arriver ?

Nous ne devrions pas pouvoir gagner de l'expérience

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
