### ISSUE TITLE
[Bug]: Pas de feedback quand la periode de l'oeuf est passée

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#138]
### Pseudo InGame

FuzeIII

### Que s'est-il passé ?

Il faudrait rajouter un feedback à la place d'écrire "Egg XP dans 10minutes" du style "L'oeuf doit être ramené au village"

Ou encore mieux: ramener automatiquement l'oeuf au village et afficher une notification "Le temps de l'oeuf est écoulé, il a été ramené au village".

**Comment by Zeldown** [comment]
:x La feature à été revue et ne nécessite plus cet ajout
