### ISSUE TITLE
[Bug][Faction]: Chest explorer ne marche pas dans un claim

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#1386]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

On ne peux pas voir ce qui est dans un coffre avec un chest explorer si le coffre est claim par un autre faction
https://www.youtube.com/watch?v=olVZJlmlPHQ

### Qu'aurait-il dû arriver ?

Voir le contenu du coffre

### Serveur

Global

### Date et heure de la production du bug

31/03/2023 14h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
