### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gtonstuff** [Paladium-Developpement/Paladium-Issue#1391]
### Pseudo InGame

Gtonstuff_

### Que s'est-il passé ?

Le serveur n'est pas fluide en warzone c'est impossible de pvp c'est comme si on avais 20 fps alors que sa nous affiche 70fps il faudrait que vous tester par vous mêmes car sur un rec on ne peux pas trop le voir mais c'est arrivé depuis la dernière mise à jours

### Qu'aurait-il dû arriver ?

On devrais pas avoir une aussi grosse baisse de fps

### Serveur

None

**Comment by Zeldown** [comment]
❌
