### ISSUE TITLE
[Bug]: Perte énorme de FPS suite à la dernière maj 

### ISSUE THREAD

**Issue by Gtonstuff** [Paladium-Developpement/Paladium-Issue#1395]
### Pseudo InGame

Gtonstuff_

### Que s'est-il passé ?

Le serveur n'est pas fluide en warzone c'est impossible de pvp c'est comme si on avais 20 fps alors que sa nous affiche 70fps il faudrait que vous tester par vous mêmes car sur un rec on ne peux pas trop le voir mais c'est arrivé depuis la dernière mise à jours même en KOTH avec 10 joueurs on est à -10 fps c'est injouable pour tous les joueurs
https://youtu.be/uIL4-7Kc81U

### Serveur

None

### LOG

https://youtu.be/uIL4-7Kc81U

**Comment by Gtonstuff** [comment]
Rec des anciens FPS avant la maj : https://youtu.be/_3D2PEIsl34
FPS actuel après la maj : https://youtu.be/7Fx57QdR71Y

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
