### ISSUE TITLE
[Bug]: Cornes montures qui dépop une fois équipées

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#1396]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Lorsqu'un joueur équipe des cornes sur la monture Dancarok et l'utilise, par exemple pour creuser, si le joueur vient à se faire déco lors d'un crash du serveur, la monture perdra sa corne équipée. Testé et avéré sur corne en paladium et améthyste, pas eu de cas du titane encore

Exemple avec ce rec ci contre : https://www.youtube.com/watch?v=dZ47KJpXyqs
_monture équipée de corne : < 0:30sec
crash serveur : 0:33
monture sans corne : 1:03_

Autre exemple : https://www.youtube.com/watch?v=cIXnGdR-v8U
_0:00 monture équipée d'une corne paladium
0:52 crash serveur
2:08 réinvocation monture suite au crash, sans corne_

Dernier exemple intéressant, pareil lors d'un crash de serveur, les cornes depop. 
Ce qui est intéressant à noter et que lorsque la monture se déséquipe quand elle n'a plus d'énergie, le joueur la nourrit, et la réinvoque et elle retrouve bien ses cornes. 
_26:15 : creuse et perte d'energie
27:15 réinvoque la monture, bien équipée de cornes_

Par contre, quelques minutes après : 
_27:51 : retour lobby (cornée)
35:00 : réinvoque sa monture (sans cornes)_

### Qu'aurait-il dû arriver ?

La monture aurait du garder ses cornes, lorsqu'elle est réinvoquée suite à un retour au lobby

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello,
Est-ce que l'inventaire de la monture est également perdu ?
merci du report

**Comment by Camoouchat** [comment]
Oui, on vient d'avoir un cas : https://www.youtube.com/watch?v=W0R5U_A8huE

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
