### ISSUE TITLE
[Bug]: Farm xp bottle avec dancarok

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1403]
### Pseudo InGame

Mr_Kittenxs

### Que s'est-il passé ?

Malgré la mise à jour et la tentative de patch, il est toujours possible de farmer à l'aide d'un dancarok les xp bottle.
https://www.youtube.com/watch?v=-Ho_S2kjkYQ

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
