### ISSUE TITLE
[Bug]: Mute IG mais peux continuer à parler dans l'onglet faction

### ISSUE THREAD

**Issue by SunyYtb** [Paladium-Developpement/Paladium-Issue#1414]
### Pseudo InGame

Suny_y

### Que s'est-il passé ?

Un joueur mute IG peux continuer de parler dans l'onglet faction (cela peux être considéré comme un contournement de mute)

### Qu'aurait-il dû arriver ?

Quand un joueur est mute IG, il devrais ne pas parler.

### Serveur

Global

**Comment by aureliancnx** [comment]
Ne peut pas à l'heure actuelle vérifier l'état du mute.
