### ISSUE TITLE
[Bug]: Banque de faction inacessible / affichage vide 

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1420]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

La banque de la faction OverLord est inacessible.
L'affichage du GUI est completement vide. Il n'existe plus de case. 

https://image.noelshack.com/fichiers/2023/16/2/1681772366-image.png

J'ai manuellement réussi à bouger de l'argent (/f money), mais l'affichage est resté tel quel.

C'est le cas uniquement pour la overlord,  les autres factions ont leur banque qui fonctionne. 

Ce problème était déjà apparu il y a 6 mois, corrigé par un dev. 

### Qu'aurait-il dû arriver ?

Affichage présent, banque fonctionnelle 

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
