### ISSUE TITLE
[Bug][PaintWars]: Impossible de rejoindre le Paint Wars

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#1425]
### Pseudo InGame

ZelukLoveMorgane

### Que s'est-il passé ?

Il n'est plus possible de rejoindre le Paint Wars en raison d'une erreur : "Attention, vos mods ne sont pas à jour...", même après avoir relancé le jeu.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
