### ISSUE TITLE
[Bug]: Ouverture de l'interface des golems 

### ISSUE THREAD

**Issue by PierreLeLonie01** [Paladium-Developpement/Paladium-Issue#1428]
### Pseudo InGame

PierreLeLonie

### Que s'est-il passé ?

Lorsque l'on veut ouvrir l'interface des golems en faisant clique droit, celui-ci ne s'ouvre plus, pas d'interaction avec ce dernier. 

### Qu'aurait-il dû arriver ?

Ouverture de l'interface golem.

### Serveur

Soleratl

### Date et heure de la production du bug

report via ts par un joueur

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Je retire le tag Factions car cela ne concerne pas le mod factions en lui même

**Comment by aureliancnx** [comment]
Duplicate de https://github.com/Paladium-Developpement/Paladium-Issue/issues/1427
