### ISSUE TITLE
[Bug]: Trade affichage non modifié pour le validant

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1431]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Si un joueur valide le truc mais que moi je modifie ce que je lui propose, lui visuellement ca va lui cancel la validation mais pour moi je verrais comme toujours validé
https://youtu.be/SXFn3AwXGCg

### Serveur

None

**Comment by Akysooo** [comment]
En profiter pour ajouter un temps de 2 secondes avant de pouvoir cliquer sur valider lorsque la validation a été cancel par la modification de l'autre joueur

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
