### ISSUE TITLE
[Bug][Faction]: BCC unclaim puis re-claim -> Exp de faction infinie

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1440]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

Le 21/04/23 vers 21h30/ 22h00, la faction "LaProjection" a posé un BCC sur imbali (2500/1/20341)
Quelques temps plus tard, la faction à unclaim la zone en laissant le BCC et ils ont claim avec une autre faction (greenskyz).
Ils ont unclaim pour récupérer leur bcc et ça leur a fourni 50 points d'élo + 9.734E8 XP, les faisant passer du lv 20 à 100.

Je n'ai pas plus d'informations sur ces faits.

Joueur concerné : LoloZealot
Faction : LaProjection

https://image.noelshack.com/fichiers/2023/16/7/1682265439-2023-04-21-22-copie.jpg
https://image.noelshack.com/fichiers/2023/16/7/1682265439-2023-04-21-22.jpg

Je n'arrive pas à leur retirer leur exp de faction et les set lv 20. Impossible de leur prendre l'exp.
Le BCC est affiché comme présent au /f f mais n'est plus physiquement là

### Qu'aurait-il dû arriver ?

Ca n'aurait pas du arriver

### Serveur

Imbali

### Date et heure de la production du bug

21/04/23 vers 21h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
