### ISSUE TITLE
[Bug]: Consommation bouteilles xp métiers pré-MAJ impossible

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1447]
### Pseudo InGame

Telco_ (report par LaMissPinguin)

### Que s'est-il passé ?

Il est impossible d'utiliser les bouteilles d'expérience métier qui ont été obtenues avec xp bottler avant la mise à jour du 27/04/2023 (du moins celles du métier de farmer).

### Qu'aurait-il dû arriver ?

Il devrait être possible de les utiliser.

### Serveur

Global

### LOG

https://www.youtube.com/watch?v=a0ukNkLqQnA

**Comment by E-Lone** [comment]
Hello,

Je rajoute également que celles du métier Mineur ne fonctionne pas également.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
