### ISSUE TITLE
[Bug]: Affichage nom métier helios et notifications 

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1449]
### Pseudo InGame

ZelukLoveMorgane

### Que s'est-il passé ?

Depuis la maj les noms des métiers sur le module Helios jobs et les notifications n'affiche plus les noms des jobs mais Jobs.Hunter.Name

ScreenShot : https://prnt.sc/GMu1md6rLZ5J

### Qu'aurait-il dû arriver ?

Les noms des jobs devraient être affichés normalement.

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
