### ISSUE TITLE
[Bug][Faction]: Problème Texture relations

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1452]
### Pseudo InGame

ZelukLoveMorgane

### Que s'est-il passé ?

Dans l'onglet Diplomatie et demande en cours le curseur à droite est décalé et il est impossible de remonter voir le demande au-dessus (voir screen)

ScreenShot : https://prnt.sc/tI5BpVK1nEh9

### Qu'aurait-il dû arriver ?

Les textures devraient être bien affichées et pouvoir se déplacer dans le menu.

### Serveur

Global

### Date et heure de la production du bug

27/04/2023 17H50

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
