### ISSUE TITLE
[Bug][Faction]: 

### ISSUE THREAD

**Issue by Gtonstuff** [Paladium-Developpement/Paladium-Issue#1457]
### Pseudo InGame

gtonstxff

### Que s'est-il passé ?

La permission pour le gestion event est bug on ne peut pas ajouter de joueur soit cela écrit que le joueur doit être la depuis au moins 7 jours ou sinon sa écris joueur inconnu 

### Qu'aurait-il dû arriver ?

On aurais pu ajouter n'importe quel membre de la faction 

### Serveur

Global

### Date et heure de la production du bug

Depuis la mise à jours

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

https://prnt.sc/Qp7B7jIt2pKD

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
