### ISSUE TITLE
[Bug]:  Portail Alchimiste pour creuser la Bedrock

### ISSUE THREAD

**Issue by Kittenxs** [Paladium-Developpement/Paladium-Issue#1460]
### Pseudo InGame

Mr_Kittenxs

### Que s'est-il passé ?

Lorsque l'on pose le portail comme dans la vidéo , ça casse la bedrock

### Qu'aurait-il dû arriver ?

Ne pas casser la Bedrock 

https://www.youtube.com/watch?v=Ab47oNeVVQc

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
