### ISSUE TITLE
[Bug]: Classement bug texture list

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1461]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/235448774-9c07b8ec-45a9-4819-b202-89e3fa2d8781.png)

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
