### ISSUE TITLE
[Bug]: Dimension mineur 

### ISSUE THREAD

**Issue by Kittenxs** [Paladium-Developpement/Paladium-Issue#1462]
### Pseudo InGame

sini0_

### Que s'est-il passé ?

Le joueur est rentré dans le portal du serveur event pendant la génération de sa dimension .

Il ne peux plus ouvrir de dimension maintenant.

https://youtu.be/Sw0bptrmAWQ

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
