### ISSUE TITLE
[Bug]: /furnace Cactus

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#1463]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

En faisant un /furnace avec des cactus pour le faire cuir, on obtient non pas du colorant vert mais de l'ink sac

### Qu'aurait-il dû arriver ?

Recevoir du cactus green et non pas de l'ink sac

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
