### ISSUE TITLE
[Bug]: Minage voidstone

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1464]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Lorsqu'on essaye de placer la voidstone par terre pour récupérer un voidstone block, il ne se passe rien

https://www.youtube.com/watch?v=uROVzV3YgQk

### Qu'aurait-il dû arriver ?

Il devrait y avoir un voidstone bloc poser par terre

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
