### ISSUE TITLE
[Bug]: Online detector vert alors que joueur non connecté

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1467]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Un online detector détectant un joueur (dans mon cas, Kowaii_) l'affichait connecté sur le serveur ou j'étais alors qu'il ne l'était pas.

### Qu'aurait-il dû arriver ?

L'online detector devrait être rouge étant donné que le joueur en question n'était pas connecté)

### Serveur

Luccento

### LOG

https://youtu.be/QiYzOnyKdbA

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
