### ISSUE TITLE
[Bug]: Duplication lié au Drawbridge 

### ISSUE THREAD

**Issue by Helwine** [Paladium-Developpement/Paladium-Issue#147]
### Pseudo InGame

Helwine

### Que s'est-il passé ?

L'utilisation d'item type extractor, statue permet une duplication par l'utilisation des drawbridge. 

Ci-après le rec : 

https://youtu.be/vsYuzJ-QpYg

**Comment by fritzhaxx** [comment]
oh non dommage

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
