### ISSUE TITLE
[Bug][Faction]: Le retrait de la whitelist KOTH ne fonctionne pas

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1470]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

Lorsqu'un chef de faction veut faire participer un joueur au KOTH, il est désormais necessaire de le whitelist.

Sauf qu'il est impossible de retirer un joueur deja présent en whitelist. 

https://image.noelshack.com/fichiers/2023/19/2/1683630705-sans-titre.png

Le message apparait comme "supprimer Riku95 de l'event" alors que je tente de retirer Sufod_, et c'est pareil pour tout les joueurs.

### Qu'aurait-il dû arriver ?

"Supprimer Sufod_ de l'event" et retrait du joueur de la WL

### Serveur

Global

### Date et heure de la production du bug

07/05/23 à 21h35

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
