### ISSUE TITLE
[Bug]: Aucune notification de Gain d'expérience métier

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1471]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on gagne de l'expérience nous recevons aucune notification du gain d'expérience qu'on a gagné.

https://www.youtube.com/watch?v=61YsQMeq8ME

### Qu'aurait-il dû arriver ?

On devrait recevoir une notification du gain d'expérience que nous avons reçu.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
