### ISSUE TITLE
[Bug]: PVP prendre moins de dégat

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1473]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on bloque avec son épée et en utilisant une macro nei pour faire /craft , nous resterons en permanance en bloquer , le problème est que nous pouvons tapé et nous déplacés, tout en prenant moins de dégat.

De notre POV , nous ne voyons pas notre épée bloqué , mais les autres joueurs si.

https://www.youtube.com/watch?v=xo1Mo3kdKIE

### Qu'aurait-il dû arriver ?

L'épée ne devrait pas être bloqué dans son état, il aurait du revenir a son état normal sans qu'aucune réduction de dégat soit ajouté.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
