### ISSUE TITLE
[Bug]: Verveine non fonctionnelle

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1475]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

La verveine ne fonctionne pas, on a fait nos tests sur le ptr, Untaa et aucun des deux n'a fonctionner. 

Test Untaa:
https://www.youtube.com/watch?v=csdlhPwhDtU

### Qu'aurait-il dû arriver ?

La verveine aurait du empêcher le wither de détruire des blocks et de faire des dégats exponentielle toutes les 10 secondes.

### Serveur

Untaa

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
