### ISSUE TITLE
[Bug]: Plusieurs lignes du Patch note non appliqué

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1476]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

J'ai remarqué que plusieurs ligne du patch note était éronnée , en voici ceux que j'ai trouvé :

Correction de l'affichage des coordonnées du menu F3.
Correction de l'affichage des minerais dans le menu F3.

![2023-05-11_11 32 26](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/4735b701-5b51-4491-bd22-294067e497eb)

Correction du triage des joueurs lors de l'affichage par pourcentage de quête hebdomadaires.
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/d3b8afbd-0ffa-4141-b928-351b4c7ebaa4)
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/3349a642-3d7d-46d3-bb8c-60ad5ddb4f70)

Correction de l'impossibilité d'utiliser les bouteilles d'expériences créées avant la mise à jour 8.5.13.0.

- Après un test de ma part ça ne fonctionne toujours pas

Ajout du niveau de la pickaxe of the gods dans sa description.
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/fd8d9925-3f71-4177-9362-91137df6d0e1)

### Serveur

None

**Comment by Zeldown** [comment]
❌ Après test cette issue n'est pas juste.
