### ISSUE TITLE
[Bug]: Fiole xp farmer

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1479]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

L'utilisation des fiole d'xp farmer ne fonctionne pas même après le patch

### Qu'aurait-il dû arriver ?

Elle devrait marcher

### Serveur

Global

### LOG

https://youtu.be/fCkRie3CDzc quand la fiole est dans les main la personne spam le click droit

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
