### ISSUE TITLE
[Bug]: /ah en combat

### ISSUE THREAD

**Issue by Gtonstuff** [Paladium-Developpement/Paladium-Issue#1482]
### Pseudo InGame

gtonstxff

### Que s'est-il passé ?

On peut ouvrir le ah avec la commande dans le chat @p: 
et Quand on clique sur le message on peut me mettre des items en ventes en plein combat ou en acheter 

### Qu'aurait-il dû arriver ?

La personne n'aurais pas pu ouvrir le ah grâce au chat avec le @p: et n'aurais pas du pouvoir vendre ou acheter des items en étant en combat

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
