### ISSUE TITLE
[Bug]: poser des blocks dans les maison de factions de luccento / Manashino

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1487]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Il est possible de poser des blocks dans les maisons de factions du serveur Luccento/Manashino mais par contre on ne peut pas y rentré.

Manashino: 2/96/35 ---- 44/85/11
Luccento: Global

### Qu'aurait-il dû arriver ?

Nous ne sommes pas sensé pouvoir interagir de quelconque manière dans les maison de factions qui ne nous appartiennent pas ou ne sont pas claim de notre propre faction.

### Serveur

Global

### LOG

https://youtu.be/JhCexJ_npc4

**Comment by aureliancnx** [comment]
Il s'agit d'un problème de rg qui a été remonté à la création.
