### ISSUE TITLE
[Bug][Faction]: 

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1490]
### Pseudo InGame

mamath716

### Que s'est-il passé ?

Crash lors du /ah sell ou /ah puis appuyé sur le bouton sell

### Serveur

Global

### Date et heure de la production du bug

Depuis le 19/05/23

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
