### ISSUE TITLE
[Bug]: Crash Changement de serveur

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1492]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Il arrive quand nous utilisons la commande /lobby ou /go que notre jeu crash.

### Qu'aurait-il dû arriver ?

Le jeu ne devrait pas crash et nous renvoyer au lobby ou sur le serveur qu'on veut s'y connecter.

### Serveur

None

### LOG

https://paste.rocks/?c72d223c47015a84#GrjLSeQ2sz1wjNQn3K32L3icuppQKNvHvyyyqTMoA71q

**Comment by SK0R3N** [comment]
https://paste.rocks/?eaed5d5561f02ac0#2oB1sYMBHETdHuiwWcgwhrmZ72GqggEe68giPXchXAFi

Voici un autre cas de crash lors d'un /lobby

**Comment by aureliancnx** [comment]
Bonjour,

C'est un bug connu qui ne pourra malheureusement pas être corrigé.
