### ISSUE TITLE
[Bug][Faction]: pistons keltis

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1495]
### Pseudo InGame

akamariii

### Que s'est-il passé ?

Les pistons fonctionnes plus sur keltis, mais les autres serv oui 

### Qu'aurait-il dû arriver ?

les pistons s'active pas mais la redstonne oui

### Serveur

Keltis

### Date et heure de la production du bug

21h00

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
