### ISSUE TITLE
[Bug][Faction]: Pnj faction renommable 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1496]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Les pnj factions comme l'office du tourisme ou le marché sont renommable avec les nametag
(screen soleralt)
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/92928910/1bfa4d37-d6f7-40a8-9927-c4d642f64bf0)

### Qu'aurait-il dû arriver ?

Empêcher le renommage avec le nametag et nametag en endium

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
