### ISSUE TITLE
[Bug]: Affichage grade joueur tab

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1498]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Sur la plupart des serveurs (voir lesquels dans la section serveur), les pseudos des joueurs non gradés ont le préfixe **Joueur**. Cela provoque un décalage, le nom du grade sort du rectangle qui affiche le pseudo.
Exemple ici sur Keltis :
![2023-05-30_12 59 22](https://github.com/Paladium-Developpement/Paladium-Issue/assets/62394506/bce2cd81-b091-43f3-9cc0-04eb819a3329)

### Qu'aurait-il dû arriver ?

Comme pour tous les grades, cela devrait afficher la première lettre du grade (donc un J).
Exemple ici sur Luccento :
![2023-05-30_12 52 10](https://github.com/Paladium-Developpement/Paladium-Issue/assets/62394506/c26a06d0-ecce-4988-867d-563b714fbb8e)

### Serveur

Keltis ; Untaa ; Neolith ; Manashino ; Imbali ; Muzdan ; farmland-1 ; minage-1

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors du redémarrage du serveur en question

Cordialement,
