### ISSUE TITLE
[Bug]: Texture paladium crusher

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#150]
### Pseudo InGame

Akyky

### Que s'est-il passé ?

Le paladium crusher n'a pas la nouvelle texture de la refonte (ressource pack et non)

### Qu'aurait-il dû arriver ?

La texture commandée devrait remplacer l'ancienne sur le vanilla et le ressource pack

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
