### ISSUE TITLE
fin du palapass

### ISSUE THREAD

**Issue by Micromum1** [Paladium-Developpement/Paladium-Issue#1504]
### Pseudo InGame

MicroMum

### Que s'est-il passé ?

Le Palapass affiche actuellement un reset dans 55 jours et 4h.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
