### ISSUE TITLE
[Bug][Faction]: Pvp dans la fac

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1505]
### Pseudo InGame

Lukiloke

### Que s'est-il passé ?

Il peut se pvp avec les bras droits et le chef de sa faction.

### Qu'aurait-il dû arriver ?

Normalement on peut pas taper ses allié ou les membres de faction.

### Serveur

Global

### Date et heure de la production du bug

19h50

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
wontfix, c'est une fonctionnalité. On peut désormais se PvP entre membres de la faction avec la permission du Friendly Fire. Pour désactiver cette fonctionnalité, cela est possible. Il suffit d'enlever la permission pour le grade Bras Droit.
