### ISSUE TITLE
[Bug]: Certains /home ne sont plus fonctionnels (refus de tp)

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1507]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

Lorsqu'un joueur essaie de se tp dans un home, certains fonctionnent et tp le joueurs, d'autres n'entrainent pas de tp.

Exemple : joueur tickui  , home fle

Ce bug touche un grand nombre de joueur

### Qu'aurait-il dû arriver ?

Le joueur devrait être tp

### Serveur

Untaa

### Date et heure de la production du bug

04/06/23 à 22h10

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by WashiPaladium** [comment]
Bonjour, le soucis est toujours d'actualité suite à un report d'un groupe de joueurs ce jour sur TeamSpeak. Merci !

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
