### ISSUE TITLE
[Bug]: Luckypass, alt F4 permet de relancer une nouvelle fois la roue

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1508]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

Lorsqu'on lance le luckypass, la roue tourne.
Un peu avant la fin, on visualise le nombre de LB qu'on va obtenir.
Si on fait ALT F4 avant d'obtenir les récompenses, il est possible de relancer la roue pour espérer en avoir plus.

### Qu'aurait-il dû arriver ?

Le nombre de LB obtenu devrait être fixé lors du click sur lancer, et pas uniquement à la fin de l'animation

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
