### ISSUE TITLE
[Bug][Faction]: Permission Friendly Fire

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1511]
### Pseudo InGame

Zeluck_ | SithamLaPagaille

### Que s'est-il passé ?

Même lorsque la permission Friendly Fire est désactivé les joueurs peuvent se frapper.

Video : https://youtu.be/3AkBN9XXSaI

### Qu'aurait-il dû arriver ?

Lorsque la permission est désactivé les joueurs ne devraient pas pouvoir se frapper

### Serveur

Global

### Date et heure de la production du bug

09/06/2023 14h20 

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Ce n'est pas un bug. En fait le grade Bras Droit a la permission ALL
