### ISSUE TITLE
[Bug]: Grade Youtubeur/Streamer dans le tabs

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1512]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Le grade Youtubeur/Streameur n'est pas visible dans le tabs on voit seulement le grade endium

ScreenShot : https://prnt.sc/MZk3yaRFU993

### Qu'aurait-il dû arriver ?

On devrait pouvoir voir le grade

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
