### ISSUE TITLE
[Bug][Faction]: Extrapolated Bucket ne fonctionne pas

### ISSUE THREAD

**Issue by Waazix** [Paladium-Developpement/Paladium-Issue#1514]
### Pseudo InGame

Waazix19

### Que s'est-il passé ?

L'extrapolated bucket ne fonctionne pas dans les claim des autres factions.
On obtient le message "xxx ne vous a pas autorisé à construire sur ce claim." même si il y a un bloc derrière

### Qu'aurait-il dû arriver ?

La source d'eau/lave/fake water aurait dû être retirée

### Serveur

Global

### Date et heure de la production du bug

14/06/2023 10h55

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
