### ISSUE TITLE
[Bug]: Golem Régime industrielle description hard codé

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1518]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/92928910/8e47850e-4c36-4fff-8286-7aa91c2baafa)
Il y a marqué toutes les 6 minutes alors que c'est 8 minutes

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
