### ISSUE TITLE
[Bug]: Auto crafter- Visuel bug

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#152]
### Pseudo InGame

Akyky

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/151406694-19f618f1-83ce-41fd-86c3-08a38e24eaed.png)
Quand on passe sa souris sur les boutons des crafts, ceux qui sont après s'assombrisse 

### Qu'aurait-il dû arriver ?

Tous les boutons devraient rester clair

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
