### ISSUE TITLE
[Bug]: Quête metier

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1520]
### Pseudo InGame

mael_arrlt

### Que s'est-il passé ?

Sa mission quotidienne pour l'exp des métier ne fonctionne pas, il doit casser des minerais de diamant cela ne fonctionne pas .
Un autre joueur me dit ça pour la pierre. Ou encore les bois moddés.
Résultat, ils perdent leur pourcentage d'xp

### Qu'aurait-il dû arriver ?

La cota devrait augmenté, mais il reste à 0

### Serveur

Global

### Date et heure de la production du bug

ce matin et là, 14h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Duplicate de https://github.com/Paladium-Developpement/Paladium-Issue/issues/1472
