### ISSUE TITLE
[Bug][Faction]: VDF : Chunk unclaim non dispo dans l'hôtel de ville

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1521]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

La faction souhaitait réorganisé le village de faction. Ils ont unclaim un chunk pour reclaim plus loin. Le chunk ne s'est pas mis disponible dans l'hôtel de ville et la faction a du racheter un chunk avec un prix plus élevé.

Faction : WCDI
Serveur : Manashino
Chunk unclaim : -12247 / -26873
Joueur qui a unclaim et leader de la fac : Furvo

### Qu'aurait-il dû arriver ?

Le chunk unclaim aurait du apparaitre disponible dans l'hôtel de ville pour être claim sans surcoût.

### Serveur

Manashino

### Date et heure de la production du bug

15/06/2023 heure approximative : 19-20h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
