### ISSUE TITLE
[Bug]: crash serveur event

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1524]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Quand le joueur tombe dans l'eau en bas du spawn, le serveur crash (on comprends mieux en regardant la vidéo)

### Qu'aurait-il dû arriver ?

le serveur devrait pas crash

### Serveur

Lobby

### LOG

https://www.youtube.com/watch?v=4pdI2SO87Is

**Comment by aureliancnx** [comment]
Bonjour,

Le problème est-il toujours d'actualité ? Je n'arrive pas à le reproduire

**Comment by blockgu07** [comment]
Je ne pense pas je n'ai reçu aucun autre report
