### ISSUE TITLE
[Bug]: Le wither ne prend plus l'aggro après avoir déchargé la zone / reboot le serveur

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1525]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

Sur demande de Zeldown : 

Les withers (normal), gentils, passifs, perdent leur focus lorsqu'ils sont laissés dans une zone déchargée trop longtemps / que le serveur à reboot.

Le wither normal lance des têtes sur les joueurs aux alentours, mais lorsqu'il est hit, il ne suit plus le joueur. 

Le quickrestart du serveur permet de réinitialiser le wither et qu'il fonctionne de nouveau.

https://youtu.be/TFqSLC7oZUk

Constaté sur Soleratl, Neolith, Imbali et Manashino

### Qu'aurait-il dû arriver ?

Le wither ne devrait pas perdre son aggro

### Serveur

Neolith

**Comment by Anubeni** [comment]
Sur Neolith après avoir refait spawn un wither gentil, celui ci ne prend pas l'aggro, sans l'avoir laissé dans une zone déchargée
