### ISSUE TITLE
[Bug][Faction]: Les joueurs arrivent à avoir plus de 20 joueurs en KOTH + bypass de l'ancienneté d'une semaine

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1526]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

Constaté sur le KOTH de ce jour : 

Lors du KOTH, les joueurs de la faction X, ayant préalablement été enregistrés sur la whitelist koth de leur faction, quittent leur faction et rejoignent la faction Y. 

Ils ont alors accès au KOTH sans limite de temps dans la faction, et ça permet de passer la limite de 20 joueurs par faction sur le koth.
En l'espèce, la faction Y avaient 25 joueurs sur la zone.

### Qu'aurait-il dû arriver ?

Le timer de ces joueurs aurait dû être reset et ils n'auraient pas pu accéder à la zone du koth

### Serveur

Global

### Date et heure de la production du bug

21/06/23 à 21h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Gtonstuff** [comment]
Oui

**Comment by aureliancnx** [comment]
Bonsoir,

As-tu une vidéo du problème ? Les joueurs sont-ils dans la zone au moment de quitter la faction ?

**Comment by Riku955** [comment]
Ils ont rejoint avant que le KOTH débute. 
Je n'ai pas de vidéo, j'ai demandé à GTONSTUFF qui était dans la zone

**Comment by aureliancnx** [comment]
J'aimerais bien avoir une vidéo qui explique l'opération en DM si possible 🤔
