### ISSUE TITLE
[Bug][Faction]: Erreur lors de l'assaut d'un village.

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1528]
### Pseudo InGame

Anubeni 

### Que s'est-il passé ?

Lors de l'assaut du village de fac de la Fuz3Fac par la WithHold, deux messages d'erreur se sont succédés quand les membres de la WithHold ont voulu rentrer dans le village.

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/51adf11a-e1da-49a2-b030-551fcad6604a)

### Qu'aurait-il dû arriver ?

La faction aurait du pouvoir entrer dans le village et faire l'assaut

### Serveur

Global

### Date et heure de la production du bug

22/06/2023 entre 22h30 et 23h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
