### ISSUE TITLE
[Bug][Faction]: Aucune récompense défense assaut VDF

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1529]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

La faction Insomnium s'est faite assaut son village de fac sur Keltis mardi par la Winter. L'assaut devait durer de 11h30 à 17h30. Ils sont restés toute la journée sur le village et aucun ennemi n'est venu. Ils n'ont eu aucun message dans le chat ni rien et n'ont pas gagné d'hélo ni d'argent. à la fin de l'assaut. 

### Qu'aurait-il dû arriver ?

La faction aurait dû gagner de l'élo et l'argent de la faction qui a payé pour les attaquer. 

### Serveur

Keltis

### Date et heure de la production du bug

20/06/2023 entre 11h30 et 17h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
