### ISSUE TITLE
[Bug]: Office de tourisme

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1532]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Quand j'ouvre l'office du tourisme, je ne peux pas voir tous les villages, voir screen.
![2023-06-26_11 08 37](https://github.com/Paladium-Developpement/Paladium-Issue/assets/133444239/fff6e4b5-cef1-4875-975b-f086f62c3d7c)

### Qu'aurait-il dû arriver ?

Normalement, le bouton à droite est en haut sauf que là il est en bas

### Serveur

Global

**Comment by aureliancnx** [comment]
Et même en remontant la scroll bar ?

**Comment by Zeluck-github** [comment]
> Et même en remontant la scroll bar ?

Hello, j'envoie un petit rec de ce que ca fait lorsqu'on l'ouvre.

https://youtu.be/lIUjD85UkNI

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
