### ISSUE TITLE
[Bug]: Connexion sur deux serveur à la fois

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1534]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Un joueur est venu sur TS en me disant qu'il était connecté à la fois sur Untaa et en minage suite à un crash le ramenant au lobby, en reconnectant son DC sur Untaa pour afk dans une farm, il voyait toujours son compte principale connecté alors que ce dernier était en minage 4. Nous avons tenté de le kick et de le ban, rien n'y fait. Nous avons dû demandé à un op de restart le serveur et cela à fonctionner.  Voir vidéo dans log. 

### Qu'aurait-il dû arriver ?

Le compte principale aurait du être déconnecté au même titre que le DC, surement une erreur de synchronisation.

### Serveur

Untaa

### LOG

https://www.youtube.com/watch?v=nOLZMUYfSh4

**Comment by aureliancnx** [comment]
Bonjour,

Il s'agit d'un problème interne dans le socket dont nous n'avons pas vraiment la main dessus. Ce bug ne sera pas fixé.
