### ISSUE TITLE
[Bug][Faction]: Pillage BCC avec surclaim (Withhold / W1NT3R) - BCC non réinitialisé

### ISSUE THREAD

**Issue by Riku955** [Paladium-Developpement/Paladium-Issue#1536]
### Pseudo InGame

Riku95

### Que s'est-il passé ?

La Withhold a pillé la base claim de la W1NT3R. Ils ont surclaim le centre puis cassé le BCC.
C'est la withhold qui a perdu de l'élo suite au pillage du BCC (Ils n'avaient pas lu le wiki).

A la suite de ça, le jeu ayant cru qu'ils avaient cassé leur propre BCC, le leur est devenu inactif. Ils l'ont donc cassé et re-perdu de l'élo. 

Cependant : 

- Le BCC de la Withhold n'est plus apparent sur le GUI mais ils continuent de gagner des points (Need reset)
- Le BCC de la W1NT3R est toujours présent sur le GUI et ils continuent de gagner des points (need reset).

J'ai effectué les remboursements etc mais impossible d'interagir pour réinitialiser les factions niveau bcc

BC W1NT3R : Muzdan
BC Withhold Manashino

### Qu'aurait-il dû arriver ?

Réinitialisation du BCC, perte de points, pas de gain d'élo automatique

### Serveur

Muzdan

### Date et heure de la production du bug

25/06/23 à 7h15

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
@KraemerJoe
