### ISSUE TITLE
[Bug]: PalaHolo marche pas

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#1537]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/92928910/a6919b60-8da6-4f46-bbff-d4b166dc6bd3)
@Zeldown 

### Serveur

Global

**Comment by aureliancnx** [comment]
La commande semble fonctionner lobby, faction, minage.
