### ISSUE TITLE
[Bug]: EC non accessibles spawn Luccento

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1540]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les EC ne sont pas accessibles aux sorties Nord, Est et Sud du spawn de Luccento. Ceux à l'Ouest le sont.

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/eaf4f4b7-81ee-4e62-9756-9b1fa6b20dc4)

### Serveur

Luccento

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
