### ISSUE TITLE
[Bug]: PNJ Office du tourisme dans warzone Luccento

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1541]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Le PNJ de l'office du tourisme au spawn de Luccento se trouve dans la warzone, à la sortie Nord.

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/e3617277-e7ab-499b-a694-09490b5e1170)

### Serveur

Luccento

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
