### ISSUE TITLE
[Bug]: Machines non fonctionnelles

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1543]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Depuis la mise à jour de ce midi, diverses machines ne fonctionnent plus : grinder, palamachine, machine à croquettes, boites à golem, drawbridges (et potentiellement d'autres). 

Pour les machines sensées crafter : lorsque le joueur met les divers ingrédients, le craft se fait dans la machine et lorsque le joueur veut retirer l'item crafté, l'item se decraft.

Pour les drawbridges, fermes à golem : les machines ne fonctionnent pas.

### Serveur

Global

### LOG

Report de plusieurs joueurs différents :
Palamachine : https://www.youtube.com/watch?v=m2p5AIVBzJM 
Food, grinder, boite à golem : https://www.youtube.com/watch?v=tgBQvIzb7Vo
Drawbridge : https://www.youtube.com/watch?v=VPLc5i1znzI

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
