### ISSUE TITLE
[Bug]: Drawbridge

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1544]
### Pseudo InGame

billy_walla

### Que s'est-il passé ?

Il met des oak_sappling dedans, sauf que c'est des acacia_sappling qui sont posé au lieu des oak_sappling.

### Serveur

Manashino

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
