### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WashiPaladium** [Paladium-Developpement/Paladium-Issue#1545]
### Pseudo InGame

Bug Vente AH

### Que s'est-il passé ?

Lorsqu'un joueur appuie sur le bouton "Sell" dans le menu du Market, le joueur est redirigé vers le lobby avec comme message d'erreur "A fatal error has occured, this connexion is terminated". 

Le joueur a essayé de faire un /ah sell, il a bien réussi à mettre son item en vente, mais en revenant en arrière sur l'interface de vente avec les cases, son jeu s'est fermé directement sans message d'erreur ni retour lobby.

Note aux Devs: Il s'agit d'un bug sur un joueur "isolé", je ne rencontre pas ce bug actuellement.

### Qu'aurait-il dû arriver ?

Le joueur devrait pouvoir accéder à l'interface de vente du market, sans crash, sans retour lobby.

### Serveur

Global

### LOG

Voici les logs du crash-report du joueur en question: https://pastebin.com/Pe7jdjee

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
