### ISSUE TITLE
[Bug]: Crash lors de l'agrandissement ou rétrécissement de la fenêtre

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1549]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Lorsque le joueur agrandit ou réduit sa fenêtre via la bouton dédié ou via F11, son jeu crash.
Report de plusieurs joueurs (semble quasi général)

### Serveur

Global

### LOG

Crash report de Blockgu :
https://paste.rocks/?0875819bbb09ca56#5KFN4GAen35EqEx5gbRKXj2wX4syCMbJ1bGgEA63knMU

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
