### ISSUE TITLE
[Bug]: Tous les events du LB s'affichent en "New"

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#155]
### Pseudo InGame

Fuzay

### Que s'est-il passé ?

A chaque fois que j'ouvre un Lucky Block, le "new" s'affiche peut importe de si j'ai eu l'event avant ou pas.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
