### ISSUE TITLE
[Bug]: Crash lors de l'ouverture d'Hélios

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1550]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Lorsque le joueur va dans Hélios depuis un serveur faction, il crash.

Report de plusieurs joueurs (semble quasi général)

### Serveur

None

### LOG

Crash report de SK0R3N : 
https://paste.rocks/?31d0f0d72878ba46#hNwMA7HJD6MizVPP2dZV4SK7cg1bAitaqTuQrx9vDNC

(presque identique à celui généré par le crash lors de l'agrandissement de la fenêtre)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
