### ISSUE TITLE
[Bug]: Crash dancarock

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1551]
### Pseudo InGame

Exardosh

### Que s'est-il passé ?

Lorsqu'il ouvre son interface de dancarock, il crash.

Crash report : https://paste.rocks/?dbe83d1a9023296a#7nDBVNXR5X8N4v2kHsk13SQEtf4EmMzarjtDJPfX3gpM

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
