### ISSUE TITLE
[Bug]: Crash lors d'un succes

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1552]
### Pseudo InGame

salim0825

### Que s'est-il passé ?

Lors d'un succes, il crash en boucle.

Crash report  :  https://paste.rocks/?cd69f642f5ebc4dc#GRpALMvepLsQRLjsvc22DWuc4KLMq9aPnaKdRcHdEgv5

### Serveur

Global

**Comment by aureliancnx** [comment]
Est-ce possible de réouvrir une issue avec le lien vers le crash report? Ton lien est expiré
