### ISSUE TITLE
[Bug]: Gain xp avec pastèques

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1554]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Selon le chunk dans lequel le joueur se trouve ou la hauteur où il est, certaines pastèques cassées ne donnent pas l'xp. 
Le rec joint est réalisé sur Muzdan mais le bug semble être présent sur plusieurs serveurs. 
Ce n'est pas un cas isolé, plusieurs joueurs ont déjà eu se problème.

https://www.youtube.com/watch?v=7rRV_nYwN40

### Qu'aurait-il dû arriver ?

LE joueur devrait recevoir l'xp farmeur peu importe le chunk où il se trouve.

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
