### ISSUE TITLE
[BUG] : Possible de faire le KOTH, après avoir rejoins moins d'une semaine une faction.

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1556]
### Pseudo InGame

VeckPex

### Que s'est-il passé ?

Hier lors du Koth, j'ai retrouvé un joueur qui était présent dans le KOTH, gentilgarcon de la Az0x, alors que celui-ci à rejoins la faction il y a seulement 3j et 19h.

### Qu'aurait-il dû arriver ?

Le joueur n'aurait pas du se retrouver dans l'arêne du KOTH.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci d'apporter des précisions sur la manière de reproduire ce bug, car après plusieurs tests, je n'ai pas réussir à reproduire ce bug.

**Comment by aureliancnx** [comment]
Sans réponse à ce jour, je suis contraint de fermer ce ticket.
