### ISSUE TITLE
[Bug]:  La quete de faction de ne donne pas toujours les bonnes récompenses.

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1557]
### Pseudo InGame

VeckPex

### Que s'est-il passé ?

Après avoir était dans plusieurs factions, j'ai constaté des bugs aléatoire dans les récompenses. Parfois de la duplication de récompense, parfois pas de récompense. C'est ainsi que :

    W1NT3R : on recu 300k en plus, il est fort possible que cela soit de meme pour xp
    Exutoire : on recu 100k en moins, possible aussi pour l'xp.
    ayga : on recu 200k en plus,
    ...

J'ai cherché une cause lié à un serveur, pas trouvé, cherché une cause lié à des horaires, pas trouvé, cherché une cause sur un palier précis, mais pareil pas trouvé. Honnêtement, c'est totalement random et je rapport 3 factions sur 6 que j'ai pu visité, il est fort possible qu'il y en ai d'autre qui ont le soucis, mais il ne se manifeste pas, ou peut être qu'ils ont pas vu, ou qu'ils n'ont pas le soucis. Je n'en sais pas plus

### Qu'aurait-il dû arriver ?

Les factions auraient du obtenir 100k pour chaque palier, soit un totale de 400k. Ni plus, ni moins.
De même pour l'xp, mais je n'ai pas les perms pour le vérifier.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
