### ISSUE TITLE
[Bug]: Quand on jette un tank rempli de sève on récupère les Minerais mais pas l'XP

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#156]
### Pseudo InGame

Fuzay

### Que s'est-il passé ?

Quand on jette un tank avec de la sève dans un portail, on ne récupère pas l'XP

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
