### ISSUE TITLE
[Bug]: Erreur /trade

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1561]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Lorsqu'un joueur envoie une demande de trade le joueur en face ne peut pas accepter le trade.

Screen : https://prnt.sc/MRHPYdgss_Jm

### Qu'aurait-il dû arriver ?

Le joueur devrait pouvoir accepter le trade

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
