### ISSUE TITLE
[Bug][Faction]: GUI Permission Truce

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1562]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Il n'est plus possible de dérouler le menu et donc de modifier les permissions des truces en bas.

Screen : https://prnt.sc/G-VbDbCpue4r

### Qu'aurait-il dû arriver ?

On devrait pouvoir dérouler le menu pour pouvoir voir les autres truces et édit les permissions

### Serveur

Global

### Date et heure de la production du bug

12/07/2023 14h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
