### ISSUE TITLE
[Bug]:  Natura box

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1564]
### Pseudo InGame

Tout le monde

### Que s'est-il passé ?

Lorsqu'on ouvre une natura box, on ne reçoit aucune récompenses

Rec : https://www.youtube.com/watch?v=Ot8q1Hdi4Vw

### Serveur

Global

**Comment by Anubeni** [comment]
Semble identique pour les trixium boxs

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
