### ISSUE TITLE
[Bug]: Couche minimale egghunt

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1566]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les joueurs peuvent avoir l'egghunt en dessous de la couche 40. Le joueur l'a couche 6 sur le rec joint.

https://www.youtube.com/watch?v=D4RzsnZWXrw

### Qu'aurait-il dû arriver ?

Le joueur n'aurait pas du pouvoir descendre sous la couche 40 avec l'egghunt.

### Serveur

Untaa

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
