### ISSUE TITLE
[Bug]: Skull of the cursed king infini

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1567]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Il est possible de mettre Mending sur l'item , en utilisant /hat avec l'item dans la main , on pourra après consommer des xp berrys pour redonner ses durabilités et donc l'utiliser a l'infini

### Qu'aurait-il dû arriver ?

L'enchantement mending ne devrait pas fonctionner sur l'item ou ne peut pas être appliquer dessus.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
