### ISSUE TITLE
[Bug]: Trade avec Drawers

### ISSUE THREAD

**Issue by E-Lone** [Paladium-Developpement/Paladium-Issue#1569]
### Pseudo InGame

POTR

### Que s'est-il passé ?

Hello !

x1 Drawer Normal
x64 Cobblestone (par exemple)

Étape 1 :
- Renommer les 64 Cobblestone en "Paladium Block"
- Introduire les 64 Cobblestone dans un drawer
- Casser le drawer, le récupérer et le mettre dans un /trade

Résultat : 
- On ne parvient pas à voir que l'item à été renommé et ce n'est pas des blocs de Cobblestone, au contraire on voit qu'il y a écrit x64 Paladium Block ce qui peut vite prêter à des arnaques.

### Qu'aurait-il dû arriver ?

Si possible, faire en sorte que l'on voit l'item renommé en italique pour éviter toute confusion, ou alors indiquer le réel nom de l'item, ou faites comme vous le sentez ! :D 

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
