### ISSUE TITLE
[Bug]: Pas de nom pour les builders wands dans le menu du mineur

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#157]
### Pseudo InGame

Akyky

### Que s'est-il passé ?

Dans le menu craft du métier de mineur, les builders wands n'ont pas de nom
![image](https://user-images.githubusercontent.com/92928910/154732828-18abf677-636f-48e9-97a0-1eae07299506.png)

### Qu'aurait-il dû arriver ?

Un nom pour chaque builder wand

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
