### ISSUE TITLE
[Bug]: crash autoclick

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1571]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Un joueur m'a report que lorsqu'il casse ses eggplants avec l'autoclick, il crash après 3 graines cassées

### Qu'aurait-il dû arriver ?

ne pas crash

### Serveur

Global

### LOG

https://paste.rocks/?9cbc8077658cc0d7#AGA92CwhEKQaASZys7DNTUP8kp85k67VY3GDUbqii86g

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
