### ISSUE TITLE
[BUG] : Home remover qui fonctionne sur les OP

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1573]
### Pseudo InGame

VeckPex

### Que s'est-il passé ?

Le home remover empeche les op de poser un home, le home peut etre remove et il empeche de revenir quand on change de server. En bref, le home remover est fonctionnel sur les op et peut être sur les responsables, à tester.

### Qu'aurait-il dû arriver ?

Le home remover ne devrait pas montrer les op qui se sont deco dans une base, ou qui ont posé un home. Cela pourrait donner des indications au éventuelles dupliqueur que des op sont présent à les surveiller.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
