### ISSUE TITLE
[Bug]: Impossible de récupérer la progression communautaire

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1574]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Même en ayant fait 25% de la progression personnelle , le joueur ne peut pas récupérer le 50% de la progression communautaire.

Si c'est parce que l'event est terminé rajouté un message d'erreur.

https://www.youtube.com/watch?v=c_cU4CgkIMA&ab_channel=exenosIII

### Qu'aurait-il dû arriver ?

Soit donner la récompense ou afficher le bon message d'erreur.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
