### ISSUE TITLE
[Bug]: Correction des noms de glueball 

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1576]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

ID 4712 - Glueball verte claire > vert clair
ID 4713 - Glueball verte foncée > vert foncé

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
