### ISSUE TITLE
[Bug][Faction]: Problème Horaires assaut

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1577]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

La faction WCDI subit un assaut de la Ancacia. L'asaut est prévu le 27/07 à 00:15, alors que les horaires de vulnérabilité de la WCDI sont de 15:00 à 20:00.
Les deux seuls membres qui y ont la perm de modifier les horaires ne l'ont pas fait et ne peuvent pas accéder à l'hôtel de ville bien qu'ils soient en dehors des horaires de vulnérabilité.

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/6b9a2e26-eecd-4b21-b5ef-cd463680d1dc)

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/b3072e00-81d3-4a96-9bde-23015ccd8e8d)

### Qu'aurait-il dû arriver ?

L'assaut ne devrait pas pouvoir se déclencher en dehors des horaires de vulnérabilité.

### Serveur

Manashino

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
