### ISSUE TITLE
[Bug]: Vente bottle xp Farmer au ah 

### ISSUE THREAD

**Issue by Totoy33270** [Paladium-Developpement/Paladium-Issue#1578]
### Pseudo InGame

Totoy33270

### Que s'est-il passé ?

Il m'est impossible de mettre en vente des bottles d'xp farmer d'environ 1000xp .
Cependant je reçois une notification en haut à droite de l'écran me disant " Ce nom d'item est interdit empêchant la vente de l'item

Suite au report d'un joueur , ci dessous un rec de mon test 

https://youtu.be/-rqhBnA1Fcg

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
