### ISSUE TITLE
[Bug]: Possibilité de faire pousser les champignon dans les claim enemy

### ISSUE THREAD

**Issue by MrKittenxs** [Paladium-Developpement/Paladium-Issue#1579]
### Pseudo InGame

Mr_kittenxs

### Que s'est-il passé ?

Possibilité de faire pousser les champignon dans les claim ennemie

### Qu'aurait-il dû arriver ?

Ne pas faire pousser le champignon 

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
