### ISSUE TITLE
[Bug]: Problème sur la description des seedplanters

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#158]
### Pseudo InGame

Akyky

### Que s'est-il passé ?

Dans la descriptions des seedplanters, il y a marqué "press shift for more info". Cependant cela n'affiche aucune description quand on appuie sur shift (gauche et droite)  

### Qu'aurait-il dû arriver ?

Changer la description dès qu'on appuie sur shift pour celle voulu (si pas de description prévu dans le code, juste enlève la description des seedplanters)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
