### ISSUE TITLE
[Bug]: Totem jeudi

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1580]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Des joueurs m'ont signalé  qu'il y a eu un totem aujourdh'ui vers 19h45. Cependant c'est sensé être que le mercredi. 
Report fais par le leader de la sooneternal Soliinox.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
