### ISSUE TITLE
[Bug]: Use bug tp zone pvp

### ISSUE THREAD

**Issue by Totoy33270** [Paladium-Developpement/Paladium-Issue#1581]
### Pseudo InGame

Totoy33270

### Que s'est-il passé ?

Pour réaliser l'use bug, il suffit seulement deux personnes, une personne qui /Tapa a la personne qui est au spawn 
Utilisé le png pour etre Tp a la zone Pvp et fait des trades avec le png black market ou juste Pvp .
Dès que le joueur a fini son trade ou est en difficulté , il suffit au deuxième joueur d'accepter le demande de Tp dans la limite des 60 seconde 

Je joint deux rec fait avec rossinante avec les deux points de vue

https://youtu.be/SEXMmDO8Cos
https://youtu.be/LxUYms3UVp4

### Qu'aurait-il dû arriver ?

La personne n'aurait pas du être téléporter 

### Serveur

Global

### Date et heure de la production du bug

28/07/2023 22h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Le Paladium issue est réservé au staff
