### ISSUE TITLE
[Bug]: Déco-combat sans drop

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1582]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Un (ou plusieurs) joueurs a sa roue de temps restant en combat qui disparait bien avant les 30 secondes. Lorsque sa roue disparait, il peut /lobby et son stuff n'est pas drop.

Les commandes /spawn et autre ne fonctionnent pas et le joueur a bien un message dans son chat mais il peut partir au lobby avant ça et conserver son stuff.

roulette qui se s'arrête toute seule : https://www.youtube.com/watch?v=GVoNjtzorY8

utilisé lors d'un combat réel : https://www.youtube.com/watch?v=rFQLNC56u6I

### Qu'aurait-il dû arriver ?

le joueur n'aurait pas pu quitter le serveur avant les 30 secondes et dans le cas où il l'aurait fait, son stuff aurait du se drop au sol.

### Serveur

Global

**Comment by Anubeni** [comment]
Pour la personne qui a donné le coup lors du test, la roue a disparu alors qu'il restait 12 secondes.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by WashiPaladium** [comment]
Bonsoir chers devs, ce bug est actuellement toujours d'actualité et des joueurs continuent d'en abuser. Preuve avec ce rec, où le stuff ne drop pas (on le voit pas sur le rec mais j'étais présent sur place pour l'attester): https://www.youtube.com/watch?v=rs6POSak12I

**Comment by WashiPaladium** [comment]
D'après un joueur, il s'agirait d'un bug lié avec le tag combat d'Helios

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,

**Comment by F0rtimel** [comment]
@aureliancnx Salut désolé de te déranger mais après la mise à jour de ce matin, le bug est toujours d'actualité 
https://www.youtube.com/watch?v=dg2K6kDlTTI

**Comment by aureliancnx** [comment]
Il n'a pas fait /lobby sur ta vidéo.

> @aureliancnx Salut désolé de te déranger mais après la mise à jour de ce matin, le bug est toujours d'actualité https://www.youtube.com/watch?v=dg2K6kDlTTI

**Comment by F0rtimel** [comment]
@aureliancnx il fait ce que @Soulivan71 a dit il a macro /lobby
