### ISSUE TITLE
[Bug][Faction]: Changement direction slime-obsi dans claim

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1583]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Il est possible pour les joueurs de changer le sens des slime obsi dans un claim ennemi, grâce à une simple interaction avec la pioche.

https://www.youtube.com/watch?v=orU_p6pR1c0

### Qu'aurait-il dû arriver ?

Les joueurs ne devraient pas pouvoir interagir avec les slime obsi dans un claim ennemi.

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
