### ISSUE TITLE
[Bug]: Weighted boots

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1584]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Lorsqu'elle se casse je les récupères avec toute la dura
Weighted boots pas enchant.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
