### ISSUE TITLE
[Bug]: Event Lucky Block d'Aout 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1585]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello, on a un petit bug sur l'event de lucky block d'aout -> de l'orage dans l'air 
On garde les effets à vie....
![2023-08-01_16 09 54](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104795165/06fc29f7-4a90-4202-bce5-cd5671ee235d)

### Serveur

None

**Comment by iWoZ0** [comment]
J'ai déco reco. bu un seau lait je me suis /slay rien fonctionne :(

**Comment by aureliancnx** [comment]
C'est censé être comme ça et disparaître au bout de 20min, est-ce le cas?

**Comment by aureliancnx** [comment]
Bonjour,

N'ayant pas reçu de réponse à ce jour pour apporter des informations supplémentaires à cette issue, je ferme cette issue.

Dans le cas où le bug est reproduit, je vous invite à créer une nouvelle issue en apportant les détails manquants.
