### ISSUE TITLE
[Bug]: Possibilité de mettre un Pnj dans le spawn

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1586]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Avec " l'ice cream seller egg" il est possible de faire spawn le pnj dans le spawn.

### Qu'aurait-il dû arriver ?

Il ne devrait pas être possible de le faire spawn dans des zones protégés.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
