### ISSUE TITLE
[Bug]: Correction - Vendeur de glace (+ oeuf du vendeur de glace - ID 5074)

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1587]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

**Nom de l'item :** Oeuf du Vendeur de glace > Oeuf du Marchand de glace (parce que le PNJ s'appelle "Marchand de glace")

**Ajouter une description à l'item :** Il te suffit d'effectuer un clic droit pour faire apparaître le marchand de glace. Attention, il ne reste que 5 minutes !

**Dialogue à corriger :** 
Bonjour, quest-ce que je vous sert ? > Bonjour, qu'est-ce que je vous sers ?
Veuillez choisir une boule ou deux boules ? > Vous souhaitez prendre une boule de glace ou deux ?

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
