### ISSUE TITLE
[Bug]: Valise (pas sûre que ce soit modifiable)

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1588]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Quand on ouvre la valise, l'inventaire de celle-ci est nommé "sac à dos", est-il possible de le nommer "valise" ? Pas forcément nécessaire, mais plus cohérent.

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121042777/629af2c0-71ae-4c85-8745-f2867d490829)

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
