### ISSUE TITLE
[Bug]: Ticket d'août

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1589]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Corriger le message d'information dans le chat qui annonce qu'on a été téléporté au forgeron
>> Vous avez été téléporté à la Palanimalerie

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121042777/3a1f712d-a8ec-40b3-824a-85b67d06e1ab)

Et la Palanimalerie est vide actuellement, il n'y a pas de PNJ (et on ne peut pas faire un retour lobby pour vérifier si le PNJ est juste invisible étant donné qu'un aller-retour nous ramène au spawn du serveur event et que le ticket a un CD d'une heure.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
