### ISSUE TITLE
[Bug]: Les nouveaux items déco ne peuvent pas être utilisé dans les VF

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1593]
### Pseudo InGame

VeckPex

### Que s'est-il passé ?

Il n'est pas possible de posé les blocs de décoration que l'on obtient dans les coffres de cosmetic au spam. Un message de type : "vous ne pouvez pas placer de bloc sur ce territoire" et l'objet reviens en main. De plus certain bloc de deco on disparu suite à une mise à jour (le requin)

### Qu'aurait-il dû arriver ?

Il faudrait pouvoir poser ces blocs de deco pour decorer les villages de faction.

### Serveur

None

**Comment by aureliancnx** [comment]
Quels blocs déco?

**Comment by VeckPex** [comment]
Les blocs qui sont obtenu dans les box blocs cosmétique, les peluches notamments, mais c'est surement l'ensemble qui pose soucis.
