### ISSUE TITLE
[Bug]: Magma Cube Palapass

### ISSUE THREAD

**Issue by E-Lone** [Paladium-Developpement/Paladium-Issue#1594]
### Pseudo InGame

POTR

### Que s'est-il passé ?

Salut les collègues !

Petit soucis avec la quête du Palapass demandant de tuer les Magma Cubes, elles ne fonctionne pas dans les Farmlands. Sachant que dans le nether des minages il n'y a pas de Magma Cubes, on ne peut pas finaliser la quête malheureusement.

Je vous transmets ça, regardez par vous même et merci à vous.

Bon courage :)
https://www.youtube.com/watch?v=TMTvfE_pxVE&feature=youtu.be

### Qu'aurait-il dû arriver ?

Effectuer l'action : Tuer un Magma Cube
Aurait du faire : Augmenter la quête du Palapass

### Serveur

Farmland

**Comment by aureliancnx** [comment]
Duplicate de https://github.com/Paladium-Developpement/Paladium-Issue/issues/1538
