### ISSUE TITLE
[Bug]: Statistiques Lucky Block Août

### ISSUE THREAD

**Issue by E-Lone** [Paladium-Developpement/Paladium-Issue#1595]
### Pseudo InGame

POTR

### Que s'est-il passé ?

Coucou les collègues du pôle développement !

Petit soucis lié avec les statistiques du Lucky Block d'Août.
D'après plusieurs témoignages, il est impossible de regarder les évènements disponibles et manquants à nos statistiques pour les Lucky block d'Août.

Du coup ils ne savent pas leur niveau d'avancement, et combien il leur reste de LB à obtenir.

### Qu'aurait-il dû arriver ?

Ouverture des statistiques du Palapass > Option pour choisir les Lucky Block d'Août > Affichage des LB déjà ouverts, Affichage des statistiques (% restants)

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
