### ISSUE TITLE
[Bug]: Redstone désactivé sur Untaa

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1596]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

La redstone est désactivé sur Untaa 
Voir vidéo : 

https://youtu.be/8wIsx0Zkk1Q

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Le bug est-il toujours d'actualité ?

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
