### ISSUE TITLE
[Bug]: Type de fleur uniquement sur Untaa

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1597]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on utilise de la bone meal (via le joueur ou un dispenser) sur Untaa, on obtient des fleurs différentes, principalement ceux qui valent 2 xp au lieu de simple pissenlit et des roses qu'on retrouve sur tous les autres serveurs.

Cette "avantage" font que les joueurs font tous leur ferme a fleur sur Untaa ce qui provoque beaucoup de forte baisse de tps sur le serveur. 

### Qu'aurait-il dû arriver ?

Soit enlever cette "avantage" a Untaa , soit ajouter cette "avantage" aux autres serveurs.

### Serveur

Untaa

**Comment by aureliancnx** [comment]
Bonjour,

Ce bug est-il toujours d'actualité ?

**Comment by SK0R3N** [comment]
Hello oui, le problème est toujours d'actualité (Je viens de le tester). Sur Manashino j'obtiens des pissenlits et des petites roses, alors que sur Untaa, je peux obtenir tous types de fleurs. Je n'ai pas testé tous les serveurs, mais lors de mes premiers tests, le bug s'effectuait bien uniquement sur Untaa.

Mais bon , le bug est bien toujours présent.
