### ISSUE TITLE
[Bug]: quêtes quotidiennes 

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1598]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Les quêtes quotidiennes ne se reset pas tous les jours

### Serveur

None

### LOG

https://www.youtube.com/watch?v=LSE1nHI8rFc
https://www.youtube.com/watch?v=m5HTn3JZi3E
(les recs sont 2 jours différents)

**Comment by aureliancnx** [comment]
Bonjour,

Le problème est-il toujours d'actualité ?

**Comment by aureliancnx** [comment]
Bonjour,

N'ayant pas reçu de réponse à ce jour pour apporter des informations supplémentaires à cette issue, je ferme cette issue.

Dans le cas où le bug est reproduit, je vous invite à créer une nouvelle issue en apportant les détails manquants.
