### ISSUE TITLE
[Bug]: Totem

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1599]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Un totem le jeudi soir

### Qu'aurait-il dû arriver ?

L'évent totem n'est sensé être que le mercredi soir

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
