### ISSUE TITLE
[Bug]: Reach mauvaise 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#160]
### Pseudo InGame

Akyky

### Que s'est-il passé ?

https://bugs.mojang.com/browse/MC-52881

### Qu'aurait-il dû arriver ?

https://bugs.mojang.com/browse/MC-52881

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
