### ISSUE TITLE
[Bug]: Monocle

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1603]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Lorsqu'un joueur avec le Monocle effectue un clic droit sur le joueur en face, ce dernier ne peut pas accepter.

ScreenShot : https://prnt.sc/nryXbczEbE2T

### Qu'aurait-il dû arriver ?

Voir les informations sur le joueur qui l'accepte.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
