### ISSUE TITLE
[Bug]: Agro Stone

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1604]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

L'Agro Stone ne fonctionne pas, elle ne parvient pas à attirer l'agro du joueur qui effectue un clic droit.

### Qu'aurait-il dû arriver ?

Le wither devrait prendre l'agro lors du clique droit avec la stone.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Je te remercie pour le signalement de ce bug. Cependant, ce bug a déjà été signalé dans une autre Issue présente sur cette plateforme de signalement de bug.

Le signalement similaire est le suivant : https://github.com/Paladium-Developpement/Paladium-Issue/issues/1604

Afin d'éviter que cela se reproduise, je t'invite à utiliser l'outil de recherche dans les Issues avec les mots clés qui correspondent au problème rencontré sur cette page pour vérifier si ce bug est déjà signalé : https://github.com/Paladium-Developpement/Paladium-Issue/issues

Cordialement.
