### ISSUE TITLE
[Bug]: Joueurs affiché en skin de Steve

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1606]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Mon skin, ainsi que celui d'autres joueurs et PNJ sont remplacés par le skin de Steve dès la première fois qu'on se met en F5
Voir screen pour moi-même : 
![2023-08-31_23 13 57](https://github.com/Paladium-Developpement/Paladium-Issue/assets/62394506/4bbda7b0-4df6-4d93-b836-7a462fd532a5)
Edit : Le problème n'arrive pas tout le temps. Je me suis connecté aujourd'hui (01/09) et j'avais mon skin.

### Qu'aurait-il dû arriver ?

Je devrais avoir le skin que j'ai mis moi-même :
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/62394506/95ec3ca9-6076-4fd7-a419-ec0e3fb2aabc)

### Serveur

Global

**Comment by aureliancnx** [comment]
Nous n'avons pas ou peu de contrôle sur l'occurrence des chargements des skins Minecraft.
