### ISSUE TITLE
[Bug]: Pèche xp all métier infini

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1608]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Quand le joueur pêche et qu'il spam sa touche clique droit sur n'importe quel bloc, celui-ci reçoit de l'xp dans tout les métiers jusqu'à l'apparition de la page de pêche. De plus pour pouvoir effectué cette technique, le joueur doit envoyer assez loin l'hameçon, le laisser remonter en surface jusqu'à ce qu'il soit stable pour ensuite clique droit sur n'importe quel bloc et ainsi gagner de l'xp. De plus, quand tu t'accroupis, tu reçois plus d'xp dans les métiers. 

Lien: 
la vidéo du joueur : https://www.youtube.com/watch?v=_H7mIHdI7PQ
Ma vidéo avec les explications : https://youtu.be/SH3OcPV6dAw

### Qu'aurait-il dû arriver ?

Il devrait simplement patienter que la page de pêche apparaisse sur son écran pour pouvoir pêcher, de plus il devrait obtenir de l'xp uniquement dans le métier hunter.

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
