### ISSUE TITLE
[Bug]: Teleport stick nn pris par le flag

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#161]
### Pseudo InGame

Akyky

### Que s'est-il passé ?

Le teleport stick est pas pris en compte par le flag enderpearl 

### Qu'aurait-il dû arriver ?

Il devrait être pris en compte

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
