### ISSUE TITLE
[Bug]: Affichage interface pêche

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1610]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Certains joueurs n'ont pas la nouvelle interface de pêche systématiquement. Parfois celle-ci s'affiche, mais parfois ils n'ont pas la nouvelle interface et pêchent comme avec l'ancien système.

Rec du joueur Fortcraft99YT en minage : https://www.youtube.com/watch?v=ld7maD4aQUk

### Qu'aurait-il dû arriver ?

Le joueur aurait du avoir systématiquement le nouvel interface de pêche.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
