### ISSUE TITLE
[Bug]: Rollback inventaire, ec, lucky pass

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1611]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Un joueur retrouve son inventaire, ec et lucky pass à l'identique à chaque fois qu'il se reco. Peu importe ce qu'il fait, il récupère le même stuff, le meme contenu de son ec et son lucky pass se reset dès qu'il revient sur le serveur.

Rec du joueur altlas37 : https://www.youtube.com/watch?v=rRX6zcTCu2g

### Serveur

Global

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
