### ISSUE TITLE
[Bug][Faction]: Affichage progression QDF

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1612]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

La progression de la QDF de la faction Eximore ne prend en compte que ce qui a été déposé par le joueur qui a donné le plus. 

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/493f8670-e3fe-4876-829a-7ea7f3d933b8)

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/fa89d7b4-b8c1-4478-9728-5f8d7d7b7bbe)

### Qu'aurait-il dû arriver ?

La progression de la qdf devrait prendre en compte la somme de tout ce que' les membres ont mis.

### Serveur

Global

### Date et heure de la production du bug

09/09 13h25

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Non, il s’agit d’un reset de la progression dans la nuit du à un Bug.

**Comment by Anubeni** [comment]
Visiblement ce n'est pas la progression mais l'affichage de l'historique qui aurait un problème. NyoSan explique ça mieux que moi dans son rec..
https://www.youtube.com/watch?v=Br8R2550kt0
