### ISSUE TITLE
[Bug][Faction]: Problème de synchro de faction entre les serveurs

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1613]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Beaucoup de faction n'arrivent pas à inviter de nouveaux membres, ou ceux-ci rejoignent mais n'apparaissent pas, ou encore se font kick très peu de temps après.

Rec de NyoSan montrant son dc se faire kick de la faction en changeant de serveur : https://www.youtube.com/watch?v=EaCsqkwFZM4

### Serveur

Global

### Date et heure de la production du bug

09/09 14h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
