### ISSUE TITLE
[Bug]:  Palapass quêtes 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1614]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Il y a un bug pour finir la quête "le bouleau c'est par là !"il faut juste avoir une buche la poser et la casser 
https://www.youtube.com/watch?v=1eEslgfXBxU

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
