### ISSUE TITLE
[Bug]: Crash du jeu lorsque l'on veut afficher la recette (U) du poisson

### ISSUE THREAD

**Issue by Laurinou** [Paladium-Developpement/Paladium-Issue#1616]
### Pseudo InGame

Laurinouu

### Que s'est-il passé ?

**Certains joueurs ont remonté le problème.**
Lorsque l'on appuie sur la touche U afin d'afficher la recette du poisson "Carpe" le jeu se ferme avec un rapport de crash.log
J'ai moi-même tester le bug et j'ai n'ai rien remarqué d'anormal, tout fonctionne bien pour moi

Voici le lien de la vidéo ou l'on observe le crash du jeu
https://youtu.be/Kb0-CFAwTEI

### Qu'aurait-il dû arriver ?

Le jeu n'aurait pas dû crash, et l'utilisation de la touche U ne doit pas afficher de recette il me semble.

### Serveur

Minage

### LOG

https://pastebin.com/HypcpXbr

Le mot de passe du pastebin est :  Paladium

**Comment by aureliancnx** [comment]
Ce problème semble être une race condition provenant de NEI. Nous n'avons pas pu reproduire le bug.
