### ISSUE TITLE
[Bug]: Quete Palapass pêche

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1618]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

La quête où le joueur doit pêcher 5 poissons crus (Pêcheur amateur) ne comptabilise pas les poissons pêchés.
Tests effectués à la canne à pêche classique, enchant et non enchant.
Report équivalent concernant la quête demandant de pêcher des puffer fish.

https://www.youtube.com/watch?v=zvy4vYdF1NI

### Serveur

Global

**Comment by Anubeni** [comment]
https://www.youtube.com/watch?v=15ljSOXCC7Q

rec sur les puffer fish

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
