### ISSUE TITLE
[Bug][Faction]: Bug affichage QDF

### ISSUE THREAD

**Issue by VallouDev** [Paladium-Developpement/Paladium-Issue#1620]
### Pseudo InGame

Vallou_

### Que s'est-il passé ?

L'historique de la QDF est totalement différent de la progression actuelle en général. Pourtant la quête est actualisée normalement.

Bug d'affichage

Screen : https://prnt.sc/ZtgymrTOyoul

### Serveur

Global

### Date et heure de la production du bug

09/09/2023 

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Anubeni** [comment]
https://www.youtube.com/watch?v=Br8R2550kt0
Rec de NyoSan mis en commentaire du #1612

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué pour tous les prochains ajouts de ressources dans la quête de faction

Cordialement,
