### ISSUE TITLE
[Bug]: Rollback inventaire/métier

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1621]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Des joueurs nos report des rollback de leurs inventaire, xp de métier et ec lors de crash ou de kick.
Selon leurs reports, cela peut se produire en minage comme en faction parfois.

Ci-dessous un rec où on voit un rollback inventaire et xp de métier en minage.
(kick à 5:55)

https://www.youtube.com/watch?v=Wr8vL0ApDe4

### Serveur

Global

**Comment by Zeldown** [comment]
Duplicate of #1611
