### ISSUE TITLE
[Bug]: Problème de prix du LuckyPass IG

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#1622]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Lorsqu'on appuie sur le ? du LuckyPass IG, une fenêtre s'ouvre avec le détail de cet abonnement mais le prix affiché est erroné : 14.51e

### Qu'aurait-il dû arriver ?

Il faudrait afficher le bon prix, celui de la boutique à 14.99e
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104101226/0c081e1c-a58e-40fd-a9d3-810f39d03b29)

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
