### ISSUE TITLE
[Bug]: /trade minimum 10Pb

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1623]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Il n'est pas possible de valider le /trade pour la raison qu'on ne peut pas "échanger moins de 10Pb", même si aucun PB n'est dans l'échange.
Tests en minage et faction.

https://www.youtube.com/watch?v=8Pp0Gv97YVM

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
