### ISSUE TITLE
[Bug]: Aucun event dans le /Agenda

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1624]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le /agenda est vide , pourtant des events bien lieux sur le serveur (Ex: A vos marques). Il est donc impossible pour les joueurs de savoir quand sont ces évènements.

https://www.youtube.com/watch?v=_IiFOBgwGKI&ab_channel=S%C3%A9bastien

### Qu'aurait-il dû arriver ?

Les evènements de l'agenda devrait être montré.

### Serveur

None

**Comment by aureliancnx** [comment]
Les events sont pas censés être en début de version. Je désactive les OYM.
