### ISSUE TITLE
[Bug]: Problème distributeur / ferme à fleur

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1625]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les distributeurs ne font plus pousser les herbes et fleurs sur la grass.

https://www.youtube.com/watch?v=K-hnpjAvwxs

### Serveur

Global

**Comment by WhitzQc** [comment]
Ils fonctionnent en monde minage, mais pas en faction.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
