### ISSUE TITLE
[Bug]: Serpents qui spawn dans les déserts en faction

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1627]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Des serpents apparaissent dans les déserts en monde faction

### Qu'aurait-il dû arriver ?

Les serpents ne devraient pas spawn

### Serveur

Imbali/Neolith

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
