### ISSUE TITLE
[Bug]: Broad sword feu infinie

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1628]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Lorsqu'on tape avec une broadsword en paladium, l'éffet fire aspect reste infiniment.

https://www.youtube.com/watch?v=utzsGj0OcUw

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
