### ISSUE TITLE
[Bug][Faction]: Reset d'xp de fac

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1630]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les factions se sont faites reset leur xp de fac. (exemples de factions top 3 à la dernières qdf)

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/f75e3f3e-d393-44b6-82c9-42edfeda0075)

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/f6edb7d3-6415-49a5-8335-a9c7d14e38f4)

### Serveur

Global

### Date et heure de la production du bug

11/09/2023 00:30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
