### ISSUE TITLE
[Bug]: Débloquer utiliter pioche en endium farmer 100

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1631]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/0149aa3b-2831-43cb-b213-a0016403c631)

Dans le level 100 Farmeur , on peut remarquer que la c'est pioche et non la hache que nous débloquions l'utilité.

### Qu'aurait-il dû arriver ?

Échanger la pioche par la Hache.

### Serveur

None

**Comment by SK0R3N** [comment]
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/6ac922f2-f3eb-45bf-87e4-1edc9e398a05)
Même soucis avec la houe en paladium vert , elle est débloquable dans deux niveaux différent , un palier 85 farmeur et l'autre Palier 75. Alors qu'on l'a débloquer niveau 75

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
