### ISSUE TITLE
[Bug][Faction]: Impossibilité de mettre des ressources dans la QDF

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1632]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les joueurs arrivent difficilement à accéder à l'interface pour mettre les ressources dans la quête de fac. Un écran de chargement s'affiche.
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/1d957bb2-8ec6-4d55-91e4-935966fcd056)

Lorsqu'ils peuvent y accéder, les ressources sont supprimées et ne sont pas prises en compte dans la progression.
https://www.youtube.com/watch?v=iW_iBc1BPvc

### Serveur

Global

### Date et heure de la production du bug

00:30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Anubeni** [comment]
autre rec d'une autre fac : https://www.youtube.com/watch?v=rIlU94uyWyM

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
