### ISSUE TITLE
[Bug]: Sealed xp bottle

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1633]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il n'a pas réussi a mettre de l'xp dans sa sealed xp bottle.

Lien de la vidéo : https://www.youtube.com/watch?v=XM9amJR9HOo

### Qu'aurait-il dû arriver ?

Il aurait du faire shift + clique droit pour pouvoir mettre de l'xp dans sa sealed xp bottle

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
