### ISSUE TITLE
[Bug]: Enchantement XP bottler 

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1634]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Normalement il est prévu dans le patchnote du début de version que les joueurs puissent débloquer l'enchantement XP bottler au niveau 50 de son métier mineur alors qu'en réalité, ig, ils ne le débloquent qu'au lvl 70. 
Screen du patchnote : 
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/c7f90198-54a2-40d4-bfa0-0b8240792e43)
Screen IG : 
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/f325b14a-48b9-43a7-8812-9dabf4fc4dde)

### Qu'aurait-il dû arriver ?

Il aurait du débloquer l'enchantement au lvl 50 de son métier de mineur

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
