### ISSUE TITLE
[Bug]: Drop du stuff au sol lors de l'équipement de l'armure symbiotique.

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1638]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Lorsqu'un joueur équipe l'armure symbiotique au spawn, son stuff se drop au sol même si le joueur a de la place dans son inventaire.

https://www.youtube.com/watch?v=0nYAGoeZTOs

### Qu'aurait-il dû arriver ?

Le stuuff du joueur devrait aller dans son inventaire ou il ne devrait pas etre possible d'équiper l'amure symbiotique au spawn.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
