### ISSUE TITLE
[Bug]: /nether, condition pour effectuer la commande

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1639]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on execute la commande /nether en ayant pas le niveau , des conditions sont montrés dans le chat.
Cependant , elles n'ont pas été modifier suite a la modification du niveau requis pour le /nether
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/df7ff1b2-b71e-49bb-9eb3-4dd21a808559)

### Qu'aurait-il dû arriver ?

"Être au moins au niveau 36 Mineur" -----> "Être au moins au niveau 12 Mineur"

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
