### ISSUE TITLE
[Bug]: Niveau module Autoclick

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1640]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Le module autoclick, accessible normalement à partir du niveau 25 farmeur ou hunter, ne se débloque pas au niveau 25 et indique un niveau 30 minimum pour être débloqué.

https://www.youtube.com/watch?v=z7rxmGldI0I

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
