### ISSUE TITLE
[Bug]: Mob invisible (Luccento)

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1641]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Un joueur à un souci dans sa farm à mob. Les mobs sont invisible 
Voir la vidéo : 
https://www.youtube.com/watch?v=Mu92Fl5yrYI

### Serveur

Luccento

**Comment by F0rtimel** [comment]
Sur imbali également

**Comment by aureliancnx** [comment]
Est-ce qu'une reconnexion règle le souci?

**Comment by aureliancnx** [comment]
N'ayant pas eu de réponse et les farms à mobs étant désactivées, je ferme cette issue.
