### ISSUE TITLE
[Bug][Faction]: membre "fantôme" dans une faction

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1642]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Lors de changement de serveur, Les joueurs se font kick de leur fac, sans vraiment l'être. Il n'arrivent dans ce cas plus ni à la join ni à la quitter.
Ceci peut parfois être réglé lorsque le leader et le joueur sont sur le même serveur (celui où à été créé la fac) et que le leader kick le joueur pour ensuite le réinviter. Le joueur se fait cependant à nouveau "ghost kick" lorsqu'il change de serveur.
Des leader peuvent également être victimes du bug et ne peuvent donc plus réintégrer leur fac sans intervention.
N'ayant pas de rec de joueurs, je vous ai mis quelques tests.

https://www.youtube.com/watch?v=u9yet8IED9o

https://www.youtube.com/watch?v=3NhA4XKJQfY

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
