### ISSUE TITLE
[Bug]: quêtes Palapass pas reset

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1643]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

les quêtes Palapass quotidiennes reset pas et ça fait apparemment 3 jours que c'est comme ça

### Qu'aurait-il dû arriver ?

les quêtes devraient reset

### Serveur

None

### LOG

je mettrais les screens (car rec pas possible) en commentaire quand j'aurai toutes les preuves

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
