### ISSUE TITLE
[Bug][Faction]: Quête palapass avec la corruption

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1645]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Quête pour manger mais l'avancement de la corruption ne fait plus descendre la nourriture

### Qu'aurait-il dû arriver ?

Pouvoir manger ou faire la quête d'une manière ou d'une autre

### Serveur

Global

### Date et heure de la production du bug

13/09/2023 a 19h58

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

https://www.youtube.com/watch?v=X4ylfcI648U

**Comment by aureliancnx** [comment]
Pas un bug
