### ISSUE TITLE
[Bug]: zone corrompue sans effet

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1646]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Dans la zone corrompue 16 (j'ai pas testé les autres zones corrompues) de Luccento, on n'a aucun effet et on prend aucun dégât.
Je suis pas le seul à avoir le problème (Steboom l'a aussi)

### Qu'aurait-il dû arriver ?

avoir les effets de la zone corrompue + recevoir des dégâts

### Serveur

None

### LOG

https://youtu.be/kuO2DsBKtY4
Si jamais mon armure sur le rec est que lvl 4 du coup je suis sensé prendre des dégâts

**Comment by SK0R3N** [comment]
Voici une autre vidéo sur le bug : https://youtu.be/jMxsCmih18Q

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
