### ISSUE TITLE
[Bug]: Xp bottler sword

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1647]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

L'enchantement Xp bottler sur une sword n'est pas possible via la table d'enchantement modée (même au palier 70 car le patchnote sur le changement de palier pour lequel j'avais précédemment fait une issue qui a été faite mais pas encore déployé) 

Lien de la vidéo montrant le problème :
https://youtu.be/sSCADMFaWTU
Screen de l'enchantement en question :
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/803530ba-ffd3-4369-9707-c082c47cc4ca)

### Qu'aurait-il dû arriver ?

Il aurait du avoir l'enchantement de disponible via la table d'enchantement en mettant son épée dans la table d'enchantement modée.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
