### ISSUE TITLE
[Bug]: Permission au sein de la faction

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1648]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Quand un joueur essaie de régler les permissions des membres de sa faction, après sauvegarde, tout les paramètres ne sont pas enregistré.
Lien de la vidéo montrant les problèmes : 
https://www.youtube.com/watch?v=99jGet_vITE

### Qu'aurait-il dû arriver ?

Il aurait du sauvegarder tout les paramètres que le joueur à mis pour le grade en question de sa faction.

### Serveur

None

**Comment by aureliancnx** [comment]
Fonctionne de mon côté. Il faut essayer à nouveau.
