### ISSUE TITLE
[Bug]: Boss métier

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1649]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Un joueur a déposé des patates dans le boss métier pour le faire invoqué et celui-ci n'a reçu aucun xp dans son métier après que celui-ci soit abattu. ( Désolé je n'ai pas de record )

### Qu'aurait-il dû arriver ?

Il aurait du recevoir l'xp que doit fournir le boss métier après que celui-ci soit mort

### Serveur

None

**Comment by F0rtimel** [comment]
Il a reçu son xp 5h après que le boss soit abattu

**Comment by Zeldown** [comment]
❌ Donc pas de bug.
