### ISSUE TITLE
[Bug]: Quête palapass possible avec blocs posés par joueurs

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1651]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Malgré le dernier patch, il est possible de compléter les quêtes palapass nécessitant de miner des blocs en minant des blocs posés par un joueur.
Exemple ici avec le bois de chêne : https://youtu.be/224hjX8rtVQ

### Qu'aurait-il dû arriver ?

Les blocs posés par le joueur ne devraient pas être comptabilisés.

### Serveur

Minage

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
