### ISSUE TITLE
[Bug][Faction]: XP bottle | Non récupération d'XP de la bouteille par minage

### ISSUE THREAD

**Issue by Rossinante05** [Paladium-Developpement/Paladium-Issue#1653]
### Pseudo InGame

Rossinante05

### Que s'est-il passé ?

Lorsqu'un joueur essaye de remplir une XP bottle métier d'XP en minant. La fiole ne se rempli pas d'XP.

Video bug report par un joueur : https://youtu.be/aSVrACNNa9c

### Qu'aurait-il dû arriver ?

La fiole devrait se remplir d'XP métier petit à petit en minant.

### Serveur

Global

### Date et heure de la production du bug

15/09/2023 à 17h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Mauvaise catégorie du report de bug.
