### ISSUE TITLE
[Bug]: Fiole Alchimiste

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1654]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Quand un joueur utilise un extractor et que le bois est devenu mort, la fiole devient "null" elle ne peut plus être utilisée. 
Temps que personne ne réutilise l'extractor avec une nouvelle fiole !
voir le rec : 
https://youtu.be/lhkQLeJrn0s

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
