### ISSUE TITLE
[Bug]: Backpack

### ISSUE THREAD

**Issue by WhitzQc** [Paladium-Developpement/Paladium-Issue#1657]
### Pseudo InGame

WhitzQc

### Que s'est-il passé ?

Le backpack en améthyste est inutilisable même après avoir atteint le niveau requis dans le métier de farmer. Il indique toujours que nous le débloquons dans le métier de hunter alors que ce n'est plus le cas ( à voir si c'est le cas avec les autres backpacks ) 

### Qu'aurait-il dû arriver ?

Normalement, au niveau 35 farmer le backpack en améthyste devient utilisable 

### Serveur

Global

### LOG

Rec : https://www.youtube.com/watch?v=m2uOcIgfzOI&feature=youtu.be

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
