### ISSUE TITLE
[Bug]: Internal server error, fiole alchimiste extractor

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#166]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

J'ai été kick du serveur pour internal error quand j'ai voulu récupérer une fiole (à 100%) d'un extracteur alors que j'avais un stack non plein de fiole à 83%. J'ai pu la récupérer que lorsque j'ai jeté le stack par terre. Ensuite quand je les ai repris, ils sont stackées avec la fiole à 100%, faisant un stack de 83%.
![image](https://user-images.githubusercontent.com/92928910/162215065-4d01eea4-ad8a-41f8-ad1a-ba757b719db2.png)
(image du stack à 83%)

### Qu'aurait-il dû arriver ?

Ne pas me kick et stack la fiole à 100% dans un autre slot. Et de ne pas pouvoir stacker des fioles avec des pourcentages différents. 

### Serveur

Mineria

**Comment by Akysooo** [comment]
Suite à ce bug, j'ai enlevé toutes mes stacks de fiole et continuer à mort le même extractor sans le déplacer et j'ai réussi à dupli les fioles du coup :/
https://youtu.be/tXjbFbALhsY

**Comment by Zeldown** [comment]
:x: N'ayant plus les logs nécessaire et étant dans l'incapacité de reproduire le bug, je marque ce ticket comme traité.
