### ISSUE TITLE
[Bug]: RollBack de Chunk 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1665]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello un joueur et venu me report un rollback infini de son chunk 
Voir le rec : https://www.youtube.com/watch?v=7Umk3HWOggw
Time code 2:30 et 14:30

### Serveur

None

**Comment by aureliancnx** [comment]
Il s'agit d'un chunk qui nécessite d'être réinitialisé
