### ISSUE TITLE
[Bug]: Symbiotic Armor Pvp

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1666]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Quand un joueur tue un autre joueur avec une armure en symbiotic le joueur ayant un full p4 en Paladium est automatiquement déséquipé et se fait équiper par l'armure en symbiotic
rec : https://www.youtube.com/watch?v=Spr8UGPbjUY

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
