### ISSUE TITLE
[Bug]:  Skeleton Zone Corrompu 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1667]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Les Skeletons corrompu inflige 7 coeurs de dégats avec l'armure symbiotic niveau 40
https://www.youtube.com/watch?v=4je_1WtLMnk

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
