### ISSUE TITLE
[Bug]: Possibilité d'avoir des enchantements moddées dans la table d'enchante vanilla.

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1672]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Il est possible d'avoir des enchantements moddés dans la table d'enchant vanilla , sans avoir le niveau requis. (Test sur le ptr)

https://www.youtube.com/watch?v=KbE65Z8JlcY

### Qu'aurait-il dû arriver ?

Il devrait être impossible d'avoir des enchantements moddés sur cette table.

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
