### ISSUE TITLE
[Bug]: Possible d'acheter un BCC n'ayant pas le niveau 10 / Sont débité de la somme mais le reçoivent pas 

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1673]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Il est possible d'acheter un Base Claim Controller alors que la faction n'a pas le niveau requis qui est 10. Ceux-ci sont débités de la somme mais ne reçoivent pas le BCC.

### Qu'aurait-il dû arriver ?

Les factions n'ayant pas le niveau requis, ne devraient pas pouvoir l'acheter.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Fonctionnel de mon côté. On peut acheter un BCC quand on a pas le niveau nécessaire : c'est l'usage prévu. En revanche, il est impossible de le poser quand sa faction n'est pas niveau 10. 

Pour ce qui est du BCC qui n'est pas give dans l'inventaire, cela fonctionne très bien de mon côté.
Dans le cas contraire, merci d'ouvrir une nouvelle issue avec une vidéo.

Cordialement,
