### ISSUE TITLE
[Bug]: Même quantité d'xp quand on drop 1 ou 16 fioles alchimiste

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1675]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Dans ce rec, le joueur drop ses fioles alchimistes pour obtenir de l'xp, pour les tanks, il reçoit correctement l'xp mais en ce qui concerne les fioles, lorsqu'il drop les stacks de 16 sortant du drawer, il obtient l'xp comme si il en jetait qu'une.
A 2:10 on voit la difference entre sneak (ou il en drop 16) et desneak (ou il en drop 1).

https://www.youtube.com/watch?v=pYZWUwQpA6o&ab_channel=GaylordCollin-kaczmareck 

### Qu'aurait-il dû arriver ?

Lorsqu'il sneak pour jeter le contenu du drawer, il devrait obtenir l'xp d'un stack (96 pour 16 fioles (6*16)) et non pas l'xp d'une fiole.

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
