### ISSUE TITLE
[Bug]: Egghunt sur Untaa fait crash le server

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#1682]
### Pseudo InGame

VeckPex

### Que s'est-il passé ?

Hier soir le Egghunt sur Untaa faisait crash le server en boucle. Le dragon apparaissait correctement, parfois se dédoublé, parfois non. Une fois tuer, l'oeuf attendrais dans la zone pvp de untaa dans une zone totalement fermé aux joueurs. Ceux-ci essayé de casser le mur pour prendre l'oeuf. La plus part du temps il le prenait, l'avait 1s et l'oeuf revenait à son point d'origine. Cela se produisait plusieurs fois jusqu'à ce que le serveur lui même crash.

Aucune ouverture pour accéder à l'oeuf n'a été constaté. Seul en cassant le mur et rapidement cliquer sur l'oeuf permettait de l'avoir durant seulement 1s. La phase de combat se déroulant sans crash, seul la phase ramassage de l'oeuf entrainé le dit crash.

### Qu'aurait-il dû arriver ?

L'egghunt aurait du se dérouler normalement avec une phase de combat normal et une fois le dragon tuer, une porte aurait du s'ouvrir pour permettre au joueur de prendre l'oeuf et ainsi continuer l'event tranquillement, sans que cela n'entraine de crash server.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
