### ISSUE TITLE
[Bug]:  Utilisation des rollers en warzone

### ISSUE THREAD

**Issue by Laurinou** [Paladium-Developpement/Paladium-Issue#1683]
### Pseudo InGame

Laurinouu

### Que s'est-il passé ?

Lorsque l'on utilise les rollers en warzone ils ne sont pas censés fonctionnés, cependant ils fonctionnent, on reçois bien l'effet.
Voici le lien de la vidéo qui montre le soucis :  https://youtu.be/PBNyqIOfiMw

### Qu'aurait-il dû arriver ?

Les rollers ne devraient pas fonctionnés

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
