### ISSUE TITLE
[Bug]: Trade d'xp

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1684]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Le joueur a voulu transférer de l'xp avec le /trade mais celle-ci a été clear dans l'échange.

https://www.youtube.com/watch?v=8bQdY-GirLk

### Serveur

Luccento

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
