### ISSUE TITLE
[Bug]: Extracteur Bug d'exp abusif Alchmiste

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1685]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello on ma report un bug sur le métier d'alchimiste assez cheat pour up
https://youtu.be/Q91uDD2pnxA?si=xWtyvjre-xCOHlXi

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
