### ISSUE TITLE
[Bug]: Extrapolated bucket

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1686]
### Pseudo InGame

iWoZ_ 

### Que s'est-il passé ?

Hello, Extrapolated Bucket est complètement abusé on peut retirer toute l'eau d'une base claim sans regarder un block
https://youtu.be/xRHm9oBDO60

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors d'une future mise à jour de Paladium.

Cordialement,
