### ISSUE TITLE
[Bug]: niveau d'utilisation du drawbridge non signalé

### ISSUE THREAD

**Issue by cecile710000** [Paladium-Developpement/Paladium-Issue#1687]
### Pseudo InGame

cecile71000

### Que s'est-il passé ?

Lorsque l'on regarde le niveau pour pouvoir utiliser un drawbridge dans le métier alchimiste on ne vois vois pas a quel niveau on peux l'utiliser , en effet on vois le niveau auquel on peux le craft mais ce n'est pas indiqué a quel niveau on peux l'utiliser et on ne peux pas l'utiliser avant le niveau 43 
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/146089285/a9a43b10-762b-4032-91bf-b4540e8d559b)

### Qu'aurait-il dû arriver ?

on devrais pouvoir voir le niveau auquel on peux l'utiliser 

### Serveur

Global

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
