### ISSUE TITLE
[Bug]: crash angelic water dans zone corrompu 

### ISSUE THREAD

**Issue by cecile710000** [Paladium-Developpement/Paladium-Issue#1688]
### Pseudo InGame

cecile71000

### Que s'est-il passé ?

quand une personne rentre dans une source d'angelic water son jeu se ferme/crash , quand on la pose nous même ça ne crash pas mais quand on fait /lobby et qu'on reviens ça le fait des que l'effet graphique de la corruption arrivent ,
ça le fait depuis la maj de ce 26/09 
rec : https://youtu.be/TjygGjQ9cDc

### Qu'aurait-il dû arriver ?

ça ne devrais pas crash 

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
