### ISSUE TITLE
[Bug]: LB De septembre non fonctionnel et bugée 

### ISSUE THREAD

**Issue by Inconnu200** [Paladium-Developpement/Paladium-Issue#1689]
### Pseudo InGame

Inconnu200 & K0rtz

### Que s'est-il passé ?

_Record 1 :_ https://youtu.be/nvnV81dlQKc 

- 0:50 > Event "**La Bonne fortune**" -> Fait crash l'utilisateur à chaque fois

- 2:30 > Event "**Le métier de rêve d'une génération**" -> ne génère pas la structure et creuse plusieurs bloc en dessous même si c'est la bedrock qui ce trouve en dessous des pied d'un joueur.

_Record 2 :_ https://youtu.be/JGPJh39837Y

- 1:03 > Event "**Enfin une prime**" -> Prime de 3000$ non reçus. 

- 1:20 > Event " **Test d'anglais**" -> Ne génère pas la Structure et nous bloque dans une zone autour du LB et cela indéfiniment , (inconnu200) je suis bloqué sur Imbali , le /slay , /ban , /spawn , /tp ne fonctionne pas et nous ramène à la zone d'ouverture du lb ( ceci n'est pas visible dans la vidéo ) , seule ma mort est visible à 11:38 mais je suis respawn à l'endroit du test anglais. 

- 3:08 > Event "**Le marchand de sable**" -> écran noir lors de l'achat du chateau de sable ( je ne sais pas si c'est pour tout le monde ) et quand nous voulons faire la commande /sandcastle , cela met une interdiction dans le tchat -> 3:59.

- 5:20 > Event "**La Bonne fortune**" -> Fait crash l'utilisateur à chaque fois

- 6:23 > la bedrock disparaît sans aucune action. 

### Serveur

None

**Comment by iWoZ0** [comment]
+ Crash serveur à cause de l'event "Pécule de Vacances"
https://www.youtube.com/watch?v=n6SDe0osxNM

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
