### ISSUE TITLE
[Bug]: Suitcase Lb septembre

### ISSUE THREAD

**Issue by WhitzQc** [Paladium-Developpement/Paladium-Issue#1690]
### Pseudo InGame

WhitzQc

### Que s'est-il passé ?

Il est possible de mettre la suitcase du boss final reçu dans les lucky blocks de septembre dans l'ec

### Qu'aurait-il dû arriver ?

Puisque c'est un moyen de stockage, nous ne devrions pas être en mesure de pouvoir le mettre dans l'ec

### Serveur

None

### LOG

 REC : https://www.youtube.com/watch?v=y-9ntCAKnAc

**Comment by Zeldown** [comment]
❌ Cet item ne sauvegarde aucun stuff, au même titre que les backpack sur Paladium.
