### ISSUE TITLE
[Bug][Faction]: Récompenses dernier palier QDF

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1691]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Je refais une issue car le problème est toujours d'actualité.
Les factions ne reçoivent pas les récompenses du dernier palier de la quête de faction. 

Exemple d'une faction qui ne l'a pas reçu : 
Banania 
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/14228f61-2e3e-452c-99f6-081ff952df24)
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/121130216/9882eeee-351d-4910-b553-d66be7191ac3)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
