### ISSUE TITLE
[Bug]: POG 100 Smelt Upgrade 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1692]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello, bug avec le smelt upgrade (ne donne pas d'xp dans le métier de mineur)
https://youtu.be/DI4JmIeJr7w

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
