### ISSUE TITLE
[Bug]: bug /corruption fatal error

### ISSUE THREAD

**Issue by cecile710000** [Paladium-Developpement/Paladium-Issue#1693]
### Pseudo InGame

cecile71000

### Que s'est-il passé ?

Lorsque on fait la commande /corruption sur certains serveurs ( keltis , soleralt , neolith et manashino ) cela nous déconnecte et nous met une erreur (a fatal error has occured, this connection is terminated)  
le lien du moment où on fait la commande : https://youtu.be/rWX9KGH3zBI

### Qu'aurait-il dû arriver ?

Le jeu n'aurais pas dû crash et aurais dû ouvrir le menu de corruption : 
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/146089285/6857c26b-7087-42ba-928c-5465f8a88dbb)

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
