### ISSUE TITLE
[Bug][Faction]: Permissions Take Money Désactivé

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1696]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Le joueur peut prendre de la money depuis la banque de faction sans avoir la permission 

Voir rec : https://youtu.be/hJZX8Uj12OA?si=6cdtskWrBAMy4VNU

### Serveur

Global

### Date et heure de la production du bug

vers 21h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Il ne s'agit pas d'un problème spécifiquement lié à la permission de pouvoir récupérer la monnaie dans la banque de Faction.
Le problème est que ce grade a été créé avec comme parent "Bras-Droit" puis a été modifié en tant qu'"Officier" plus tard. Sauf que les permissions n'ont pas été recalculées et le grade a gardé toujours toutes les permissions de faction (=> les permissions du Bras-Droit)

Un correctif a été effectué et sera effectif lors d'une prochaine mise à jour. Le chef de faction n'aura besoin que de changer à nouveau le parent du grade personnalisé "recruteur" (comme affiché dans la vidéo) afin que les permissions soient recalculées.
