### ISSUE TITLE
[Bug]: Xp bottler Épées toujours pas disponible

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1697]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

L'enchantement XP Bottle sur les épées a supposément été rajouter lors de la V9 , cependant l'enchantement n'est toujours pas disponible. Une issue avait été fait il y a 3 semaines et le bug a été considérer comme corrigé , mais n'est actuellement toujours pas disponible.
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104092723/9aac8e2b-2303-4e84-9dfd-2a51b614d506)

Aussi l'enchantement ne fonctionne pas , j'ai trouvé 2 livres différents d'experience bottler dans l'inventaire créatif et les deux ne fonctionnent pas pour récupérer l'expérience des mobs.

https://www.youtube.com/watch?v=7R2AnUz4bXQ

### Qu'aurait-il dû arriver ?

L'enchantement devrait être disponible dans la table d'enchantement moddée et lorsqu'on tue un mobs avec l'enchantement et une bouteille vide , l'expérience devrait se retrouver dans la bouteille.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
