### ISSUE TITLE
[Bug]: Mobs invisibles Corruption

### ISSUE THREAD

**Issue by Hadrynn** [Paladium-Developpement/Paladium-Issue#1698]
### Pseudo InGame

Hadrynn

### Que s'est-il passé ?

https://youtu.be/ZeTVA13RPBY Le joueur subit une attaque invisible à proximité de la zone de corruption.

### Serveur

None

**Comment by aureliancnx** [comment]
Bug vanilla de refresh des entités, nous ne pouvons pas y faire grand chose.
