### ISSUE TITLE
[Bug]: Moyen Anti-AFK

### ISSUE THREAD

**Issue by Hadrynn** [Paladium-Developpement/Paladium-Issue#1699]
### Pseudo InGame

Hadrynn

### Que s'est-il passé ?

Un joueur est venu me faire part, avec une vidéo à l'appui, d'un moyen de contourner le système Anti-AFK

- https://youtu.be/Qyfb7dVqzu4

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Ceci n'est pas un bug.
