### ISSUE TITLE
[Bug]: Bug à vos marques en farmland

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1700]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il a eu fini le à vos marques en farmland et il n'a pas reçu les 8 d'élo pour sa faction.

Lien de la vidéo du joueur (il a fini son à vos marques à 4min23):

https://www.youtube.com/watch?v=BPQ4u4w7t7U

Lien de mes vidéos de la v8.5:

https://youtu.be/qSbkwdDWe7o
https://youtu.be/5Zyo8a6-0yU

### Qu'aurait-il dû arriver ?

Il aurait du avoir finir le à vos marques et gagner les 8 d'élo pour sa faction

### Serveur

Farmland

**Comment by aureliancnx** [comment]
L'élo est bien reçu. Il n'a juste pas eu la notification.
