### ISSUE TITLE
[Bug]: Perte de l'Egghunt 

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1702]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Lors du Egghut, lorsque le joueur prend l'oeuf, il est rtp normalement, mais perd l'oeuf au bout de quelques secondes sans entrer en combat, ni descendre en dessous de la couche 40, etc. L'oeuf retourne alors en zone PVP.

https://youtu.be/noN2y00_1aA

### Serveur

Untaa

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
