### ISSUE TITLE
[Bug][Faction]: Problème AP

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1703]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

![2023-10-07_20 51 51](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104795165/c4c6a18f-d9ad-4c52-a719-c03c1bf4c2c0)
Ap Insomnium impossible de casser ni de poser de block (On a déjà check et test avec Camouchat + pour faire une issue)
-10 70 -450 

### Serveur

Imbali

### Date et heure de la production du bug

21h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by iWoZ0** [comment]
Hello, oui il y a un message d'erreur pour les joueurs. le voici :
![Capture_decran_2023-10-12_a_12 52 16](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104795165/fb56bd22-d67c-4c78-b607-cf180e58467c)

On a verif aussi les flags avec Camouchat rien de spécial à première vue.

**Comment by aureliancnx** [comment]
Ce message = problème de rg merci de vérifier.
