### ISSUE TITLE
[Bug][Faction]: Joueur dans la même faction alors que non

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1704]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Les joueurs ne sont pas dans la même faction comme on peut le voir sur le rec. Mais pourtant, les deux personnes ne peuvent pas se frapper entre eux !
Voir rec : 
https://www.youtube.com/watch?v=sbgYE35pA78

### Serveur

Global

### Date et heure de la production du bug

13h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Merci de me fournir un rec avec les commandes /f f sur les deux joueurs ainsi que de me dire comment ce bug a été reproduit, si le joueur a toujours ce problème ou si une déconnexion / reconnexion des deux membres suffit.

**Comment by aureliancnx** [comment]
Bonjour

Sans rec je close cette issue. Si ce problème se reproduit, merci de réouvrir une issue avec un rec et toutes les informations nécessaires.
