### ISSUE TITLE
[Bug][Cosmetiques]: l'affichage cosmétique avec l'armure symbiotique

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1706]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Lorsqu'on a des cosmétiques d'équipés, l'affichage de l'armure symbiotique ne se retire pas donc les 2 s'additionne alors qu'avec une armure normale l'affichage de celle-ci se désactive

### Qu'aurait-il dû arriver ?

ne faire apparaitre que les cosmétiques et pas les 2

### LOG

https://www.youtube.com/watch?v=oZseG1NTmDo

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
