### ISSUE TITLE
[Bug]: Drawbridges

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1707]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Les drawbridges ne reprennent plus les blocs qu'ils posent lorsque la redstone est désactivée.

Rec : https://youtu.be/f7rqZDuAldg

Problème présent sur tout les serveurs **hormis** Muzdan & Soleratl

### Qu'aurait-il dû arriver ?

Ils devraient reprendre les blocs.

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
