### ISSUE TITLE
[Bug]: Message arrivée sur le serveur incorrect

### ISSUE THREAD

**Issue by WashiPaladium** [Paladium-Developpement/Paladium-Issue#1710]
### Pseudo InGame

WashiGame_

### Que s'est-il passé ?

C'est mineur et un peu useless je sais, mais lorsque nous arrivons sur le serveur, il est écrit sur l'écran "Bienvenue sur Paladium V8".

### Qu'aurait-il dû arriver ?

Il devrait s'afficher "Bienvenue sur Paladium V9" à la place

### Serveur

None

### LOG

Une preuve envoyé par un joueur: https://cdn.discordapp.com/attachments/1157628477084794887/1163731157184159874/IMG_0740.png?ex=6540a418&is=652e2f18&hm=6aecb7b8e480e7af9eb6cb99a9822afd8cf945be7cb98dda342f342dd53edb31&

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
