### ISSUE TITLE
[Bug]: Freeze coffre de faction

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1717]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Lorsqu'un joueur dépose ou prend un item dans le coffre de faction le jeu freeze pendant quelques secondes. 

Rec : https://youtu.be/UtAIGsZnZuQ

### Qu'aurait-il dû arriver ?

Le jeu ne devrait pas freeze à chaque fois 

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Le bug est-il toujours d'actualité? Je n'ai pas ce comportement de mon côté lorsque je dépose et que je reprends un item dans la banque de faction.

Cordialement,

**Comment by Zeluck-github** [comment]
Hello @aureliancnx 

Je viens de vérifier lorsque le launcher est ouvert il y a un mini freeze au moment de déposer ou prendre, mais lorsqu'il est fermé il n'y a pas de problème

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug et ta réponse rapide. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
