### ISSUE TITLE
[Bug]: Bug du serveur untaa

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1728]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il n'arrive pas à se connecté au serveur untaa sans avoir de grade.
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/bc49954b-9a28-40e9-950a-022b18db56bb)

### Rec

https://www.youtube.com/watch?v=pU-K-niNREE

### Qu'aurait-il dû arriver ?

Il aurait du pouvoir se connecté au serveur sans avoir de grade 

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
