### ISSUE TITLE
[Bug]: A vos marques en farmland

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1729]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il a pêché des poissons et son nombre de poisson pour le à vos marques en farmland n'a pas augmenté.

### Rec

https://www.youtube.com/watch?v=Myq03hu1fZ8

### Qu'aurait-il dû arriver ?

Il aurait du augmenter son nombre de poisson pêché

### Serveur

Farmland

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
