### ISSUE TITLE
[Bug]: Fatal Error XP Métier

### ISSUE THREAD

**Issue by ZyF0x** [Paladium-Developpement/Paladium-Issue#173]
### Pseudo InGame

ZyF0x

### Que s'est-il passé ?

Report de plusieurs joueurs et tests effectués, tout les métiers et tout les serveurs (minages et factions) : 
Dès l'obtention d'xp dans n'importe quel métier le joueur Fatal Error.

Empêche les nouveaux joueurs de jouer puisque la Stone fait gagner de l'xp et par conséquent crash.

Ps: le joueur gagne l'xp

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
