### ISSUE TITLE
[Bug]: UTF8 luckydrawers

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1730]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Il est possible de mettre de la couleur dans les items dans un luckydrawer 

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/85510521/813a59f3-da5e-49e7-ab1d-32fdc2612305)

### Rec

Voir Screen

### Qu'aurait-il dû arriver ?

Il ne devrait plus être possible de mettre des items en couleurs en vente dans le market en les renommant

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
