### ISSUE TITLE
[Bug]: possibilité d'empoisoner quelqun en farmland

### ISSUE THREAD

**Issue by ShyvaYaku** [Paladium-Developpement/Paladium-Issue#1732]
### Pseudo InGame

Shyva_Yaku

### Que s'est-il passé ?

Un joueur a utilisé un arc en paladium avec des flèches poison sur un autre joueur dans la farmland. Cela a provoquer des dégâts au joueur qui a reçu les flèches, il aurait pu mourir.

### Rec

https://youtu.be/SGSme34aBB4

### Qu'aurait-il dû arriver ?

Les flèches n'auraient pas du faire de dégâts.

### Serveur

Farmland

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
