### ISSUE TITLE
[Bug]: Mob spawn sans T4

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1733]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Bonjour, un joueur ma report un souci avec ses t4.
Quand il a voulu récupérer ses spawners il s'est rendu compte que les mobs spawn toujours.

J'ai effectué des //replace pour voir. Mais cela n'a rien changé.

### Rec

https://www.youtube.com/watch?v=hd4oVYnomls

### Serveur

Manashino

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
