### ISSUE TITLE
[Bug]: Crash au moment de poser la fleur des 50% du lucky stats de septembre

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1734]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Au palier des 50% du lucky stats de septembre, nous obtenons une fleur corrompus (id:3187), cette dernière fait crash quiconque reste à proximité de celle ci, ce qui fait que les joueurs se rendant dans le base et les ayant posé crash instantanément, même les opérateurs ne peut rien faire.

### Rec

https://www.youtube.com/watch?v=29pDQIp18i4

### Qu'aurait-il dû arriver ?

Elle ne devrait pas faire crash quiconque mais avoir le même fonctionnement que la hunter plant mais en faisant spawn des mobs corrompus.

### Serveur

Global

### LOG

https://pastebin.com/dj8NWgqA

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
