### ISSUE TITLE
[Bug]: Probleme sethome 

### ISSUE THREAD

**Issue by MIMI49s** [Paladium-Developpement/Paladium-Issue#1739]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Un joueur ne peut pas sethome, moi je peux whitz aussi... Il a le grade joueur peut être à cause de cela.
Voir rec pour le message d'érreur.

### Rec

https://www.youtube.com/watch?v=JYmEtGZVPXw

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
