### ISSUE TITLE
[Bug V8]: Text field suppression texte rester appuyer

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#174]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

On ne peut pas supprimer les textes dans les texts fields en restant appuyer sur la touche supprimer

### Qu'aurait-il dû arriver ?

Pouvoir supprimer en restant appuyer

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
