### ISSUE TITLE
[Bug]: Luckypass Relance Infini

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1740]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello, depuis la mise à jour d'hier il est possible de relancer le luckypass à l'infini jusqu'à avoir 3 luckyblocks

### Rec

https://youtu.be/gbN_AIVxeBA

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
