### ISSUE TITLE
[Bug][Faction]: Possibilité de mettre un drawer dans le coffre de fac

### ISSUE THREAD

**Issue by ShyvaYaku** [Paladium-Developpement/Paladium-Issue#1745]
### Pseudo InGame

Shyva_Yaku

### Que s'est-il passé ?

J'ai mis un drawer avec des choses a l'intérieur et quand j'ai mis le drawer dans le coffre de fac dans un claim, il a été garder. Ensuite après avoir quitté l'interface puis fais /craft il n'est pas revenu ce qui veux dire que ce n'est pas un bug inventaire et qu'il a bel et bien été gardé dans le coffre de fac.

### Rec

https://www.youtube.com/watch?v=uP8pznSxmrk

### Qu'aurait-il dû arriver ?

Ne pas rester dans le coffre de faction et revenir dans l'inventaire du joueur.

### Serveur

Global

### Date et heure de la production du bug

29/11/2023 à 16h20

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
