### ISSUE TITLE
[Bug]: visibilité du craft de la slime obsidian in game

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1751]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

lorsque l'on appuie sur notre touche pour accéder au craft de la slime obsidian rien n'apparait.

### Rec

https://youtu.be/YLyzpQTuCsA

### Qu'aurait-il dû arriver ?

On devrait pouvoir accéder au comme pour les autres objets
Image du craft:
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/afa7b8fb-5971-42fb-91d0-b577d45b91fc)

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour

Il est possible d'accéder au craft depuis le wiki: https://wiki.paladium-pvp.fr/les-metiers/mineur/objets-debloques
