### ISSUE TITLE
[Bug][Faction]: Problème pose BCC

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1754]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

La faction BacktoPrime avait un bcc dans une base qui a été cut.
Lorsque la faction a essayé ensuite de poser un nouveau bcc, elle ne pouvait pas. (d'après eux, pas de messages particuliers dans le chat, pas de rec de ce moment là).
Un moment, le bloc de bcc s'est posé, possiblement lors d'un lag. Ce BCC n'a pas rapporté d'xp ou d'élo à la faction depuis, ils ne pouvaient pas interagir avec lui et n'avaient pas de bcc dans le /f f.
Le bcc a été pillé par une autre faction (disband depuis) et la BacktoPrime a bien perdu 284 élo lors du pillage.
Depuis, lorsqu'ils essayent de reposer un bcc aux même endroit ils ne peuvent pas et un message dans le chat leur dit qu'ils ne peuvent pas le poser aussi proche d'un autre bcc. Après vérification, il ne semble pas y avoir d'autre bcc dans un rayon de 1500 blocs.

### Rec

https://youtu.be/zNzcA-0bINw 

### Serveur

Muzdan

### Date et heure de la production du bug

Pillage du bcc le 02/12/2023 entre 0h00 et 1h00 environ

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Il existe une commande d'administration permettant à un responsable de supprimer le BCC d'une faction et de régler ce bug. Malheureusement les BCC invisibles n'est pas "bug" réglable en tant que tel car c'est dû aux lags serveurs.
