### ISSUE TITLE
[Bug]: Builder wand Vérification Joueur

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1758]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Même si il y a aucun joueur dans la zone , le builder wand continue d'afficher qu'il y a des joueurs dans la zone , le rendant inutilisable.

### Rec

https://www.youtube.com/watch?v=jGNygsofac4

### Qu'aurait-il dû arriver ?

Les blocs auraient dûes se poser du au fait qu'aucun joueur se trouvait dans la zone.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
