### ISSUE TITLE
[Bug V8] [Faction]: Diplomatie bouton bug

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#176]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Dans le gui diplomatie, on ne peut pas changer d'onglet directement, il faut passer par demande en cours pour le faire
![bouton](https://user-images.githubusercontent.com/92928910/164030074-059bf604-9fb7-4051-a767-24667a78293e.gif)
.

### Qu'aurait-il dû arriver ?

Pouvoir changer d'onglet directement.

**Comment by aureliancnx** [comment]
Corrigé
