### ISSUE TITLE
[Bug][Faction]: Problème BCC

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1762]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello, 
Suite à l'ancienne issue d'Anubeni  https://github.com/Paladium-Developpement/Paladium-Issue/issues/1754 la faction BackToPrime a remis un BCC dans leur base claim. Mais à leur grande surprise le chef de faction peu piller son propre BCC ainsi que faire perdre les points de gloire de sa propre faction. 
Le BCC n'apporte aucun point supplémentaire à la Faction BackToPrime.

### Rec

https://youtu.be/FVU9V0qAIbU

### Serveur

Muzdan

### Date et heure de la production du bug

15 Décembre au alentour de 21h - 22h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Il s'agit d'un BCC buggé pour X ou y raison qui peut être supprimée par un opérateur
