### ISSUE TITLE
[Bug][Faction]: Village De Faction Assault

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#1764]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello,
Suite à une attaque du village de faction de la Banania. 
Le village de faction reste complètement détruit. le bug s'est produit le Mercredi 20/12 à 18h suite à une attaque de la faction Arkane. Le bug a commencé après une victoire de la Banania mais suite à cette victoire l'attaque du village de faction s'est relancé  3 fois, sans que la faction Arkane relance quoi que ce soit.  De plus, aucun gloire n'a été perdue ou gagnée de la part des deux factions.

Aujourd'hui le 22/12 à 12h30 le village de faction est toujours "En attaque" mais personne ne peut finir cette attaque.
Screen montrant le message d'erreur du Town Hall Block :
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104795165/151d0742-61e9-4994-a59c-36d62c2da29c)

### Rec

https://www.youtube.com/watch?v=-cb81c7JSxw

### Serveur

Luccento

### Date et heure de la production du bug

Mercredi 20/12 à 18h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Apsig69** [comment]
Bonsoir, réitération du bug le 28/12/2023 à 21h40 sur Manashino (VDF de la faction Catorya)

**Comment by aureliancnx** [comment]
Bonjour,

J'aurais besoin de savoir :

- Est-ce que le serveur a redémarré une ou plusieurs fois pendant la première attaque ?
- Que s'est-il passé dans le tchat lors de la fin de la première attaque ? Est-ce qu'il y a eu un message d'erreur indiquant que le village n'a pas pu être remis en état, ou au contraire un message indiquant que le village a bien été remis en état ? Merci de me fournir à minima une capture d'écran, voire idéalement une vidéo.

Je n'arrive pas à reproduire le bug en l'état.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
