### ISSUE TITLE
[Bug][Faction]: Bug point assault village de faction

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#1765]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Durant une attaque de village de faction a la fin la faction a gagner un total de 1800 points avec une seule attaques de fac, les factions sont WhiteInk (le gagnant des 1800 points) et la Trenzalor qui sont respectivement niveau 27 et 55. Sachant qu'un assault de village de fac si on gagne on gagne 250 points en enlevant ses dernier on ce retrouve avec un bonus de presque 1550 points

Preuve en screen 

### Rec

Pas de rec mais des screen en bas dans log

### Serveur

Global

### Date et heure de la production du bug

23/12/2023 a 8h00

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

![image (2)](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104594672/3268f9e0-5e77-436f-b663-97f2023d6b4b)

![Screenshot_2023-12-23-10-24-02-940_com android chrome](https://github.com/Paladium-Developpement/Paladium-Issue/assets/104594672/aea6f560-9513-4e8a-9caf-b0bb15ec80bd)

**Comment by aureliancnx** [comment]
Bonjour,

En quoi cela est un bug ? Le bonus est calculé en fonction de la différence d'elo entre la faction attaquante et la faction attaquée. Cela correspond à peu près au bon montant.
