### ISSUE TITLE
[Bug][Faction]: Double assaut VDF

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#1766]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

La faction Arkane a attaqué 2 fois de suite la faction Caterya ce jour (28/12/2023), à 21h20 et a 22h20
Le village ne s'est pas réparé suite à la première attaque.

### Rec

N/A

### Qu'aurait-il dû arriver ?

Normalement une faction ne peux pas se faire attaquer dans les 7 jours suivant une première attaque.
Le village aurait du se reset après le première attaque.

### Serveur

Manashino

### Date et heure de la production du bug

22h20

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

J'aurais besoin de savoir :

- Est-ce que le serveur a redémarré une ou plusieurs fois pendant la première attaque ?
- Que s'est-il passé dans le tchat lors de la fin de la première attaque ? Est-ce qu'il y a eu un message d'erreur indiquant que le village n'a pas pu être remis en état, ou au contraire un message indiquant que le village a bien été remis en état ? Merci de me fournir à minima une capture d'écran, voire idéalement une vidéo.

Je n'arrive pas à reproduire le bug en l'état.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
