### ISSUE TITLE
[Bug]: Drop des rollers au spawn

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1768]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Lorsqu'un joueur a l'inventaire plein et qu'il va au spawn d'un serveur faction avec ses rollers aux pieds, ceux-ci se droppent au sol et le joueur ne peu pas les récupérer.

### Rec

https://www.youtube.com/watch?v=x_QgSN3vPJ4

### Qu'aurait-il dû arriver ?

Les rollers ne devraient pas drop dans le spawn mais uniquement dans la warzone

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
