### ISSUE TITLE
[Bug][Faction]: MDF - louer par dessus une autre faction

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#1769]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Les factions arrivent à louer des MDF par dessus d'autres faction

### Rec

https://imgur.com/a/7Y8iVmZ

### Qu'aurait-il dû arriver ?

Les factions ne doivent pas pouvoir louer par dessus une autre faction

### Serveur

Manashino

### Date et heure de la production du bug

Multiples bugs visible sur le screen

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Apsig69** [comment]
Un cas similaire a déjà été remonté par la blackold sur Imbali

**Comment by aureliancnx** [comment]
Bonjour le bug est-il toujours d'actualité en V9.5 ?

**Comment by aureliancnx** [comment]
Réouvrir en cas de cas similaire en v9.5 avec logs et infos de la MDF (position / serveur) à l'appui
