### ISSUE TITLE
[Bug][Faction]: Liste des joueurs KOTH / délai pour y jouer

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#1770]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

la liste des joueurs prévus pour le KOTH ne fonctionne pas, les joueurs peuvent y jouer sans être dans la liste.

Des joueurs ayant moins de 7 jours peuvent donc venir sur les KOTH

### Rec

Impossible de fournir un rec du problème, ce n'est pas un problème qui se produit a un moment T

### Qu'aurait-il dû arriver ?

Normalement seuls les joueurs présent sur la liste peuvent jouer au KOTH

Seul les joueurs ayant + de 7 jours de factions doivent pouvoir etre ajouté sur cette liste

### Serveur

Global

### Date et heure de la production du bug

06/01/2024

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
