### ISSUE TITLE
[Bug]: Achat clés boutique IG

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1772]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Dans la boutique en jeu, le bouton "Acheter des clés" en bas à gauche de la page des boxs ne fonctionne pas, il ne mène à aucun interface.

Et accessoirement il y a toujours les LB de novembre.

### Rec

https://www.youtube.com/watch?v=3iapSMI1FpU

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
