### ISSUE TITLE
[Bug]: bug sur les cd dans des claims adverses

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1776]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

J'ai mis un cd dans un jukebox dans un claim "enemy" sauf que celui-ci s'est gardé dans mon inventaire. Ensuite, quand la personne a cassé le jukebox, celle-ci a pu récupérer le cd. Ce qui n'est pas normal car il y en a 2 à la fin.

### Rec

https://youtu.be/7OdI2LuSqwo

### Qu'aurait-il dû arriver ?

Soit j'aurais du ne pas avoir le cd car celui-ci aurait été dans le jukebox soit il n'aurait pas pu rentré dans le jukebox et la personne en face n'aurait pas du le récupérer

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
