### ISSUE TITLE
[Bug]: Problème sur le slider de choix de mémoire  RAM 

### ISSUE THREAD

**Issue by Douglas1the** [Paladium-Developpement/Paladium-Issue#1777]
### Pseudo InGame

Douglas_Thedog5

### Que s'est-il passé ?

Le slider de mémoire RAM a disparu de mon écran.
Je ne peux plus changer ma mémoire RAM ce qui m'empêche totalement de jouer car il est inscrit: '' votre configuration de mémoire vive (RAM) est incorrect, la valeur minimale ne peut pas être supérieure à la valeur maximale''.

![Capture d’écran 2024-01-21 082032](https://github.com/Paladium-Developpement/Paladium-Issue/assets/157290097/ed0de65c-c733-4872-8adc-875f1b734ed6)

![Capture d’écran 2024-01-21 081730](https://github.com/Paladium-Developpement/Paladium-Issue/assets/157290097/c9a16cd2-adee-44c4-a114-25ac02971ee9)

J'ai redémarré mon ordinateur, réinstallé le launcher et toujours le même problème

 

### Rec

none

### Serveur

None

**Comment by piflom** [comment]
salut je me demandais si tu avais réussi a résoudre ce bug ?

**Comment by Douglas1the** [comment]
> salut je me demandais si tu avais réussi a résoudre ce bug ?

Non pas encore
