### ISSUE TITLE
[Bug][Faction]: A vos marques

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1779]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il a fini le à vos marques et il n'a pas reçu de points de gloires. (j'ai mis de mes anciens rec car je n'ai pas pu rec celui de cette semaine et qu'il y a toujours le même soucis que la dernière fois) (3min50s)

### Rec

https://www.youtube.com/watch?v=x0N75gJWxw4

### Qu'aurait-il dû arriver ?

Il aurait du à la fin du à vos marques recevoir +8 points de gloires dans le chat et dans les gloires dans la faction.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
