### ISSUE TITLE
[Bug]: Clear du grinder block et de son contenu

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1784]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Parfois, semble-t-il aléatoirement, le bloc du grinder se clear lors de son utilisation, et clear ainsi son contenu.
S'est produit sur différents serveurs et à différents joueurs.

(autre rec : https://www.youtube.com/watch?v=hXpygniB_IQ )

### Rec

https://www.youtube.com/watch?v=wuYtwSW4CjM

### Serveur

Global

**Comment by Anubeni** [comment]
Le block du grinder disparait lors de l'ajout des améliorations, pas lors des autres interactions (craft du hammer, ajout de pala, etc)

**Comment by aureliancnx** [comment]
duplicate https://github.com/Paladium-Developpement/Paladium-Issue/issues/1800
