### ISSUE TITLE
[Bug]: Clicker "Condition de temps de jeux" non fonctionnel pour l'achat d'upgrade

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#1791]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

La condition "Temps de jeux" du clicker n'est pas fonctionnelle à l'achat d'une upgrade, je peux déjà acheter des upgrades avec cette condition alors que je ne remplis pas la condition du "temps de jeux X" nécessaire

### Rec

Pas de rec necessaire.

### Qu'aurait-il dû arriver ?

Bloquer l'achat de l'upgrade tant que je ne remplis pas la condition "temps de jeux X" necessaire.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Le temps de jeu nécessaire est indiqué dans le code par le temps depuis le début de version et non le temps de jeu du joueur. Il s'agit d'un problème de nommage qui sera corrigé.
