### ISSUE TITLE
[Bug][Faction]: Dernier palier QDF

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1796]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les récompenses du dernier palier de la QDF sont parfois obtenues en plusieurs fois (bonus de top 1, 2, 3 également). Cela concerne les $, l'xp et l'élo.

Bug toujours d'actualité par rapport au ticket
#1691 

### Rec

Pas de rec, me mp pour les preuves

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
