### ISSUE TITLE
[Bug][Faction]: Faction crée sans élo

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1797]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Plusieurs factions ont été crées et n'ont pas reçu les 505 points d'élo initiaux.
Exemples : Trenzalore, BlackPrime (élo mise manuellement)

### Rec

Pas de rec, me mp pour les preuves

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [x] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Est-ce que les factions ont attendu au moins un jour avant de se manifester pour ce bug ? Car la mise en place des points ne se fait pas instantanément.
