### ISSUE TITLE
[Bug]: Bug d'affichage compacting drawer 

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1806]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Lorsque nous mettons de la sandstone ou du sable dans un compacting drawer, celui ci n'apparait pas dans le drawer qu'il est tout à fait possible d'en prendre ou d'en mettre.

### Rec

https://youtu.be/zM9tBwj3pec

### Qu'aurait-il dû arriver ?

Nous devrions pouvoir voir le contenu du compacting drawer.

### Serveur

Global

**Comment by aureliancnx** [comment]
duplicate of https://github.com/Paladium-Developpement/Paladium-Issue/issues/1795
