### ISSUE TITLE
[Bug]:  Clicker ne marche pas sur Keltis et Neolith

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#1817]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

Les cliques automatiques du clicker ne marche pas sur Keltis et Neolith et donc il ne gagne pas de coins quand il sont sur ces serveurs

### Rec

https://www.youtube.com/watch?v=6anc6YhPjQA

### Qu'aurait-il dû arriver ?

Les cliques automatiques devrait s'actualisé tous seul ce qui n'est pas le cas

### Serveur

Neolith

**Comment by F0rtimel** [comment]
Il ne fonctionne pas également sur solératl

**Comment by Xavierleg01** [comment]
Il ne fonctionne pas également sur luccento
Les cliques automatiques devrait s'actualisé tous seul ce qui n'est pas le cas

**Comment by HiNett** [comment]
Duplication de l'issue #1815 ✅

**Comment by L0wBly** [comment]
Toujours un problème sur Neolith
