### ISSUE TITLE
[Bug]: Damage stick au spawn actif

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1819]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Il est possible de pousser des joueurs dans le spawn à l'aide d'un damage stick.

### Rec

https://www.youtube.com/watch?v=haF7ECD0uPY

### Qu'aurait-il dû arriver ?

Le damage stick devrait être désactivé dans le spawn des serveurs factions.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
