### ISSUE TITLE
[Bug]: Familier - Compétence Nuage Électrique

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1821]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

D'après la description, la compétence Nuage Électrique est censée générer 10 éclairs. Cependant, cela ne génère rien du tout, ou bien, faut-il se trouver à une certaine hauteur ?

En bonus : petit bug graphique au niveau des ailes (présent sur plusieurs modèles).

### Rec

https://youtu.be/oMarPVRwxzA

### Qu'aurait-il dû arriver ?

J'imagine qu'il y aurait dû avoir des éclairs.

### Serveur

Global

**Comment by Liskoh** [comment]
Bug corrigé.
Merci pour le report!
