### ISSUE TITLE
[Bug]: Poser des elevator dans des claims

### ISSUE THREAD

**Issue by MIMI49ss** [Paladium-Developpement/Paladium-Issue#1822]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Avec les drawbridge, on peut poser des elevator dans des claims qui nous appartiennent pas, voir rec.

### Rec

https://www.youtube.com/watch?v=qM1Ca5cSFkc

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
