### ISSUE TITLE
[Bug]: Achat Trixium et trixium +

### ISSUE THREAD

**Issue by Lixiie** [Paladium-Developpement/Paladium-Issue#1824]
### Pseudo InGame

Lixie_

### Que s'est-il passé ?

Sur le site en cliquant sur le grade trixium ou trixium + puis sur acheter cela nous ramène à la page d'accueil de Paladium.

### Rec

https://www.youtube.com/watch?v=CL51W4o0Vlc

### Qu'aurait-il dû arriver ?

Nous aurions du arriver sur la page pour effectuer l'achat.

### Serveur

None

**Comment by E-Lone** [comment]
Hello,

Si l'utilisateur a payé son grade en Points Boutiques, alors il doit payer son Trixium en Points Boutiques directement en jeu.

Ce n'est pas un "bug", c'est quelque chose de voulu. Tu peux toujours acheter tes PB depuis la boutique en ligne, et par la suite payer ton grade Trixium en jeu.

**Comment by aureliancnx** [comment]
répondu au dessus, je close.
