### ISSUE TITLE
[Bug]: Mp non fonctonnel

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#1825]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

Ne reçois pas de mp alors qu'il est en /msg on mais seulement sur les serveurs facton 

### Rec

https://cdn.discordapp.com/attachments/1210935499594793032/1211306654709325984/image.png?ex=65edb83b&is=65db433b&hm=cafb997830aec4ec2f3756c9bd66e4ba61a5f3013178405620c048bcb1a98778&  https://cdn.discordapp.com/attachments/825489085757784095/1211306713399959602/image.png?ex=65edb849&is=65db4349&hm=fa422bec85687f49d23abaa156e9b1eace56b249016088658be70ad592af0049&

### Qu'aurait-il dû arriver ?

il devrait recevoir les mp qu'on lui adresse sur les serveurs faction

### Serveur

Untaa

**Comment by SK0R3N** [comment]
Rec supplémentaire :
Il reçoit la moitié des mps qu'on lui envoie : https://www.youtube.com/watch?v=ecYjAA8eaMc
