### ISSUE TITLE
[Bug]: Soucis offre métier dans le clicker

### ISSUE THREAD

**Issue by xLmtshadow30** [Paladium-Developpement/Paladium-Issue#1828]
### Pseudo InGame

xLmtshadow30

### Que s'est-il passé ?

1. Un joueur a remarqué qu'il y avait deux potions pour l'expérience de Miner, cependant la première donne de l'xp pour le métier de Chasseur.

### Rec

https://www.youtube.com/shorts/mEY6Ve_Zj2g

### Qu'aurait-il dû arriver ?

Le nom de cette potion devrait être "Expérience de Hunter" car la confusion peut-être vite faite avec deux potions avec le même nom.

### Serveur

Global

**Comment by aureliancnx** [comment]
pas un bug
