### ISSUE TITLE
[Bug]: Clicker dans le nether

### ISSUE THREAD

**Issue by MIMI49ss** [Paladium-Developpement/Paladium-Issue#1829]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Bonjour, l'interface du clicker dans le nether es bug.
Cependant, on les coins augmente bien, et le bon nombre. C'est à dire, que je suis à 26/s ils augmentent bien de 26/s, simplement l'interface qui est bug. 

### Rec

https://youtu.be/lUQ5lf1ITek

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
