### ISSUE TITLE
[Bug V.8]: Nom de lobby incorrect

### ISSUE THREAD

**Issue by WashiPaladium** [Paladium-Developpement/Paladium-Issue#183]
### Pseudo InGame

WashiGame_

### Que s'est-il passé ?

En voulant revenir d'un serveur faction au lobby, j'ai rentré une erreur

### Qu'aurait-il dû arriver ?

Il y aurait dû avoir un message du type: connected to lobby-0?, tandis que là, il s'affiche "connected to fallback" (voir screen)

### Serveur

Lobby

### LOG

Je vous envoie la preuve directement, c'est plus simple ainsi !

https://prnt.sc/C8fh2h9a9qcU

**Comment by aureliancnx** [comment]
Not a bug
