### ISSUE TITLE
[Bug]: Module Helios Vanish visible sur compte non-OP + module Autoclick disparu

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1833]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Il est possible de voir le module Helios Vanish sur des comptes qui n'ont pas les permissions d'opérateurs.
C'est arrivé à moi, ainsi qu'à des joueurs non-staff.
On ne voit également plus le module Autoclick.

### Rec

https://youtu.be/aCximUrIoR4

### Qu'aurait-il dû arriver ?

On ne devrait pas voir le module Vanish et voir le module Autoclick

### Serveur

Global

**Comment by roselyneelavraie** [comment]
J'ajoute la remarque que moi, je n'ai plus le module vanish et je ne sais pas ce qu'il en est pour les opé

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
