### ISSUE TITLE
[Bug]: Interfaces avec inventaire ne s'ouvrent pas quand on a une canne à pêche dans la main

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1837]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Quand on a une canne à pêche (du moins vanilla, pas le niveau pour tester avec celle en paladium) dans la main, on ne peut pas ouvrir d'interface d'inventaire avec un bouton (dépôt d'items dans la quête de fac, dépôt de trixium, quête de nourriture pour le pet). Quand on appuie sur le bouton, la canne à pêche se lance et l'interface ne s'ouvre pas.

### Rec

https://youtu.be/bI5fa-wGZCg

### Qu'aurait-il dû arriver ?

La canne à pêche ne devrait pas être lancée et l'interface avec inventaire devrait s'ouvrir

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
