### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Taxbac** [Paladium-Developpement/Paladium-Issue#1839]
### Pseudo InGame

Taxbac

### Que s'est-il passé ?

Le damage stick est utilisable au spawn 

https://github.com/Paladium-Developpement/Paladium-Issue/assets/110608313/a4db5167-25c6-40a6-b418-c29ba4295979

### Rec

t

### Qu'aurait-il dû arriver ?

Il ne devrait pas l'être, sur aucun serveur

### Serveur

Imbali

**Comment by Telco43** [comment]
Je l'avais déjà signalé ça #1819

**Comment by aureliancnx** [comment]
https://github.com/Paladium-Developpement/Paladium-Issue/issues/1819
