### ISSUE TITLE
[Bug V.8]: 

### ISSUE THREAD

**Issue by WashiPaladium** [Paladium-Developpement/Paladium-Issue#184]
### Pseudo InGame

WashiGame_

### Que s'est-il passé ?

En soi, c'est pas vraiment un bug, mais ça n'était pas présent en V7, donc je le mets ici, à voir ce que vous souhaitez en faire.

Les succès s'affichent dans les chats des lobbys.

### Qu'aurait-il dû arriver ?

Normalement, dans les lobbys, les succès ne s'affichent pas dans le chat.

### Serveur

Lobby

### LOG

Voici la preuve: https://prnt.sc/Ygg4fb3FMLCI

**Comment by aureliancnx** [comment]
Corrigé
