### ISSUE TITLE
[Bug]: (Correction texte) - Lucky Blocks mai & juin

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1846]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Petites coquilles à corriger dans les noms des LB :

**édition mai**
LB 327 "Ne soit pas minable" > "Ne **sois** pas minable"

**édition juin**
LB 334 "Fait du bruit !" > "**Fais** du bruit !"
LB 348 "Réveille toi" > "Réveille-toi" (le tiret)

### Rec

gpo

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
