### ISSUE TITLE
[Bug]:  PalaAnimation qui donne trop d'argent

### ISSUE THREAD

**Issue by LaurineW** [Paladium-Developpement/Paladium-Issue#1850]
### Pseudo InGame

Laurinouu

### Que s'est-il passé ?

J'ai gagné un PalaAnimation le 03 mars 2024 (entre 19h15 et 19h22 environ) mais j'ai reçu trop d'argent.
La somme à été vérifier et j'ai bien gagner 7.500$
![2024-03-03_19 17 28](https://github.com/Paladium-Developpement/Paladium-Issue/assets/144477975/cecc9e24-7df7-4bed-a0b0-6bd6b94e770a)

### Rec

Aucun 

### Qu'aurait-il dû arriver ?

J'aurais du gagner 2000$ et non 7.500$

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
