### ISSUE TITLE
[Bug]: Big ring

### ISSUE THREAD

**Issue by MIMI49ss** [Paladium-Developpement/Paladium-Issue#1855]
### Pseudo InGame

MIMI49s

### Que s'est-il passé ?

Bonjour, le big ring ne fonctionne pas que ce soit dans l'inventaire ou dans un coffre en améthyste, titane, paladium.
Il ne repair pas l'item.

### Rec

https://www.youtube.com/watch?v=PMIxa-TqLm8

### Serveur

None

**Comment by Zeldown** [comment]
❌ Impossible de reproduire le soucis, je pense que l'item a déjà été réparé avec un ring et donc ne peux plus être réparé a nouveau
