### ISSUE TITLE
[Bug]: [Clicker] Possibilité d'acheter 1 item de plus que la limite avec les ClicCoins

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1856]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Il est possible, en spammant, d'acheter 1 item de plus que la limite en spammant l'achat de l'item.

### Rec

https://youtu.be/i1Ty79ukF78

### Qu'aurait-il dû arriver ?

On devrait pouvoir acheter seulement la quantité définie par la limite et pas 1 de plus

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
