### ISSUE TITLE
[Bug]: [Clicker] Mauvais item affiché

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1858]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

L'item affiché dans le clicker n'est pas le bon. Le pain s'affiche au lieu du dernier item débloqué (dans mon cas, le bonbon).
![2024-03-07_18 31 38](https://github.com/Paladium-Developpement/Paladium-Issue/assets/62394506/28e1d611-ad24-428f-bd56-d547f667fa8e)
Le problème est purement visuel, quand je clique sur l'item cela me donne bien le nombre de ClicCoins correspondant.

### Rec

Voir screen ci-dessus

### Qu'aurait-il dû arriver ?

C'est le dernier item débloqué qui devrait s'afficher

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
