### ISSUE TITLE
[Bug]: Les enclumes sont incassable

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#186]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Quand on pose une enclume en Titane/améthyste/paladium on ne peut pas les récuperer 

### Qu'aurait-il dû arriver ?

On devrait pouvoir les casser avec une pioche

**Comment by VallouDev** [comment]
Je ne sais pas si tu as vu le patch note, mais on est censés les récupérer au magical tool ^^
