### ISSUE TITLE
[Bug][Faction]: Dernière récompense de QDF non reçue

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1861]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Beaucoup de factions ne reçoivent pas les récompenses du dernier palier de la QDF (bonus de Top 1, 2, 3 y compris).

Exemple de factions concernées :
QDF du 08 au 15 mars : WCDI, Astral, ShadowsRaven, Trenzalore 
QDF du 01 au 08 mars : ShadowsRaven, Gravitea, Legends

### Rec

Pas de recs, plus de données en mp

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
