### ISSUE TITLE
[Bug][Faction]: Malus QDF Failed multiples

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1862]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Certaines factions ont été sanctionnées plusieurs fois pour ne pas avoir fini la QDF du 01 au 08 mars.

Exemple de factions (remboursées manuellement) :
Kuazar : 2 malus de -50 élo
Leviatia : 3 malus de -50 élo

### Rec

Pas de rec, plus de données par mp

### Qu'aurait-il dû arriver ?

Les factions qui ne finissent pas la quête de fac ne devrait perdre qu'une seule fois 50 élo

### Serveur

Global

### Date et heure de la production du bug

Kuazar : 09/03 à 2:23 et 2:52 / Leviatia : 08/03 à 22:18 et 22:20

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
