### ISSUE TITLE
[Bug]: UTF 8 Luckydrawers

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1863]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Il est toujours possible de mettre des items en couleurs dans des luckydrawers malgré le patch : #1730 

En mettant **ç** suivi d'une couleur minecraft __EX :__ `çcZeluck_ `

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/85510521/0cc6ec43-a949-4d46-a0e1-ac93649ea83d)

### Rec

Voir Screen

### Qu'aurait-il dû arriver ?

Les items ne devraient pas pouvoir être en couleur dans un luckydrawer, permettant de faire des fausses bottles de métier

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
