### ISSUE TITLE
[Bug]: Pet visible avec LG invisibilité 

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1866]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Lorsqu'un joueur utilise une LG d'invisibilité, le pet du joueur reste visible.

### Rec

https://www.youtube.com/watch?v=sv5bCKjOdm4&ab_channel=TomyLaquerriere

### Qu'aurait-il dû arriver ?

Le pet devrait être également invisible au même titre que le joueur.

### Serveur

None

**Comment by Liskoh** [comment]
Bug corrigé, merci pour le report!
