### ISSUE TITLE
[Bug]: A vos marques minage

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1868]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Le à vos marques bug parfois pour certaines personnes. Ca met qu'ils ont déjà fait le à vos marques alors qu'il vient tout juste de commencer. Ils ne peuvent donc pas le faire. 

### Rec

https://www.youtube.com/watch?v=jW4pyXmcCao

### Qu'aurait-il dû arriver ?

Il devrait pouvoir faire le à vos marques et le compteur ne devrait pas avoir commencé ou il ne devrait pas être fini lorsque le à vos marques se lance.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
