### ISSUE TITLE
[Bug]:  Gain de graine moddé avec le pet skill 

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#1871]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

Quand on farm les kiwano ou autre graines moddé on gagne des graines supplémentaire grasse au skill du pet qui ne marche qu'avec les graines vanilla. On gagne jusqu'à 1 stack de graine en plus pas champ de 15*15

### Rec

https://youtu.be/Wg6YgUHFurA

### Qu'aurait-il dû arriver ?

on devrait avoir une graine moddé pour une graine moddé cassé

### Serveur

All

**Comment by Liskoh** [comment]
Bonjour ! Concernant le gain de graines "moddé" celles ci ont un pourcentage de chance de drop ou non.
Merci pour le report
