### ISSUE TITLE
[Bug]: Passer au dessus des blocs invisibles grâce à une enderpearl en farmland

### ISSUE THREAD

**Issue by julien417** [Paladium-Developpement/Paladium-Issue#1872]
### Pseudo InGame

Julien417

### Que s'est-il passé ?

Un joueur m'a remonter qu'en lançant une ender pearl en hauteur, on peut se retrouver au dessus des blocs invisibles, il m'a fait un rec que je vais mettre en dessous

### Rec

https://www.youtube.com/watch?v=5c_In5owqvc&feature=youtu.be

### Serveur

Farmland

**Comment by aureliancnx** [comment]
Bonjour,

La vidéo montre le résultat mais pas la tentative.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
