### ISSUE TITLE
[Bug][Faction]: dump xp fation

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#1873]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Le XP dump de faction ne fonctionn pas, ça provoque un lag en jeu et ne ressort aucun résultat

### Rec

https://prnt.sc/lG5tAGBLjZYc

### Serveur

Global

### Date et heure de la production du bug

20/03/24 20h52

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
