### ISSUE TITLE
[Bug]: Traduction À vos marques

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#1875]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Lorsqu'un "À vos marques" est lancé avec l'objectif "Péchez XX poissons", lorsqu'un joueur a le jeu en anglais, il est marqué "Fish XX fish".

![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/85510521/5a825bdd-4399-4ee1-a787-38d755e8bc09)

### Rec

Voir Screen

### Qu'aurait-il dû arriver ?

Il faudrait plutôt dire "Catch XX fish" pour que cela corresponde à la version française.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
