### ISSUE TITLE
[Bug]: xp X10

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1876]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il a pu consommer un bouteille d'xp avec le multiplicateur de la xp X10 alors que dans un patchnote il était noté que ça ne fonctionnerait pas.
image du patchnote :
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/bad5e811-1aec-4ba5-b20e-9cebe03da7e7)
(à 16min45 dans la vidéo de fuze et j'ai testé en faction ptr et ça fonctionne bien)

### Rec

https://www.youtube.com/watch?v=6hv1GxwXuhE

### Qu'aurait-il dû arriver ?

Il n'aurait pas du pourvoir faire x10 sur l'xp consommé de la bouteille.

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
