### ISSUE TITLE
[Bug]: Pickaxe of the gods + extendo grip

### ISSUE THREAD

**Issue by Lerouleurpro** [Paladium-Developpement/Paladium-Issue#1877]
### Pseudo InGame

lerouleurpro

### Que s'est-il passé ?

Suite à la fusion d'une pickaxe of the gods et d'un extendo grip, le level de la POG se retrouve figé dans le nom alors qu'il continue d'augmenter dans la description, de plus le visuel de la POG ne change pas lors des level up.

### Rec

 https://youtu.be/4SGkg33ibVk

### Qu'aurait-il dû arriver ?

Le level de la POG ainsi que le skin devraient se mettre à jour au fur et à mesure de l'évolution de celle-ci

### Serveur

Global

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
