### ISSUE TITLE
[Bug]: Seedplanter et graines moddées

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1878]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Le seedplanter (de tout type) transforme les graines moddées (eggplants, chervil, kiwano, orangeblues, iced crystal) en graine de blé lorsqu'il les plante. Le rec ne montre que les types de seedplanter mais j'ai aussi testé avec toutes les graines moddées.

### Rec

https://www.youtube.com/watch?v=Avub21utKcM

### Qu'aurait-il dû arriver ?

Le seedplanter ne devrait pas changer la graine.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
