### ISSUE TITLE
[Bug]: Crash avec les trônes

### ISSUE THREAD

**Issue by JOK0X** [Paladium-Developpement/Paladium-Issue#1879]
### Pseudo InGame

JOK0X

### Que s'est-il passé ?

Quand je m'assoie sur un trône tout en appuyant sur ctrl, le jeu me déco au lobby

### Rec

https://youtu.be/DqqgxljfNg8

### Qu'aurait-il dû arriver ?

Lors de la deuxième tentative je n'appuyais pas sur ctrl c'est pour ça que je ne me suis pas fait déconnecter au lobby, tandis que le premier et troisième oui.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci de me fournir les logs du jeu

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
