### ISSUE TITLE
[Bug]: Déco-combat

### ISSUE THREAD

**Issue by JOK0X** [Paladium-Developpement/Paladium-Issue#1881]
### Pseudo InGame

JOK0X

### Que s'est-il passé ?

Quand les joueurs utilise le /lobby ou un /go ils peuvent déconnecter sans que leurs stuff drop 

### Rec

https://www.youtube.com/watch?v=72DmayVMl5Q

### Qu'aurait-il dû arriver ?

Le stuff drop au sol 

### Serveur

Global

**Comment by aureliancnx** [comment]
duplicate de https://github.com/Paladium-Developpement/Paladium-Issue/issues/1582
