### ISSUE TITLE
[Bug]: Affichage enchantement unclaim helmet 

### ISSUE THREAD

**Issue by JOK0X** [Paladium-Developpement/Paladium-Issue#1882]
### Pseudo InGame

JOK0X

### Que s'est-il passé ?

L'enchantement unclaim helmet est marqué comme nécessitant un niveau 10 en alchimiste.  

### Rec

https://www.youtube.com/watch?v=WAdWZtpznAA

### Qu'aurait-il dû arriver ?

L'affichage de l'enchantement devrait être : Niveau 60 alchimiste requis 

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
