### ISSUE TITLE
[Bug]: lobby en combat

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#1883]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Lorsqu'on est en combat on peux /lobby

### Rec

/

### Qu'aurait-il dû arriver ?

On ne devrait pas pouvoir le faire

### Serveur

None

**Comment by aureliancnx** [comment]
hello, duplicate de https://github.com/Paladium-Developpement/Paladium-Issue/issues/1582, en cours de correction
