### ISSUE TITLE
[Bug]: Fatal error au spawn du PTR

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1887]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Le joueur estcava (et peut être d'autres) a une fatal error lorsqu'il se connecte au spawn du serveur PTR. Il a le problème sur ses deux ordinateurs, et il a déjà reset ses dossiers .paladium sans succès.

### Rec

https://youtu.be/bQUSZWxsAPM 

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour merci d'envoyer les logs client
