### ISSUE TITLE
[Bug]: skill du pet qui met un coffre à la mort ne fonctionne pas avec les backpacks

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#1888]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Lors de la mort, notre stuff se met dans des coffres mais pas le contenu du backpack

### Rec

https://www.youtube.com/watch?v=9mE-6Hv53jg

### Qu'aurait-il dû arriver ?

mettre le contenu du backpack dans un coffre lorsqu'on meurt quand on a le passive skill qui permet de mettre notre stuff dans un coffre lors de notre mort

### Serveur

None

**Comment by Liskoh** [comment]
Bonjour ! Après confirmation du pole game design, ce comportement est normal.
Merci pour le report !
