### ISSUE TITLE
[Bug v8]: Dégat à l'arc sur un membre de sa faction

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#189]
### Pseudo InGame

Physali

### Que s'est-il passé ?

On peut mettre des dégats à l'arc à un membre de sa faction

### Qu'aurait-il dû arriver ?

On ne devrait pas pouvoir mettre de dégat a un membre de sa faction

**Comment by Camoouchat** [comment]
Je précise que cela est le cas aussi sur ces alliés

**Comment by aureliancnx** [comment]
Corrigé
