### ISSUE TITLE
[Bug]: Accès aux commandes PTR pour les youtubeurs 

### ISSUE THREAD

**Issue by JOK0X** [Paladium-Developpement/Paladium-Issue#1891]
### Pseudo InGame

SNoxX_

### Que s'est-il passé ?

Le joueur SNoxX_ a le grade youtubeur donc accès au /go Faction-PTR mais il n'a accès à aucune commande.

### Rec

https://www.youtube.com/watch?v=lzX2uqL_nas

### Qu'aurait-il dû arriver ?

Possibilité de faire /gmc et toutes les autres commandes accessible en Faction-PTR

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
