### ISSUE TITLE
[Bug]: Manashino ( non gradé)

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1893]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Le joueur non gradé a essayé de se connecter sur le serveur manashino mais il est dit qu'il doit acheter un grade
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/6de409c8-0025-4973-9ac7-8c8b3a123dd3)

### Rec

il n'y en a pas 

### Qu'aurait-il dû arriver ?

Il n'a pas réussi à se co dessus alors qu'il aurait dû y arriver.

### Serveur

Manashino

**Comment by F0rtimel** [comment]
Même cas sur néolith maintenant

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
