### ISSUE TITLE
[Bug]: Bug faction ptr permission

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1894]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Bug de permission pour join le faction-ptr avec le grade trixium/trixium+
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/c4c36e4e-39b7-4fc3-9b1c-baebe1f38c44)

### Rec

il n'y en a pas 

### Qu'aurait-il dû arriver ?

Ils devraient pouvoir join le faction-ptr avec ce grade la

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
