### ISSUE TITLE
[Bug]: Fatal error au spawn du PTR

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1896]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Bug du ticket #1887 toujours d'actualité pour ce joueur.

logs du joueur : https://pastebin.com/fjhBHf0m 

### Rec

https://youtu.be/bQUSZWxsAPM

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
