### ISSUE TITLE
[Bug]: changement des textes sur le jeu

### ISSUE THREAD

**Issue by ShyvaYaku** [Paladium-Developpement/Paladium-Issue#1898]
### Pseudo InGame

Shyva_Yaku

### Que s'est-il passé ?

tout les textes important pour le jeux c'est-a-dire inventaire, métiers, pet, cliqueur ont changés 

### Rec

non

### Qu'aurait-il dû arriver ?

les textes devraient être comme de base

### Serveur

Global

### LOG

![Capture d'écran 2024-04-14 024124](https://github.com/Paladium-Developpement/Paladium-Issue/assets/147213024/777d23c4-625e-4df4-9087-7192e71b4de0)
![Capture d'écran 2024-04-14 024118](https://github.com/Paladium-Developpement/Paladium-Issue/assets/147213024/f6ea60a4-a084-4b7f-ac01-2f259ec824b0)
![Capture d'écran 2024-04-14 024109](https://github.com/Paladium-Developpement/Paladium-Issue/assets/147213024/53b4e76b-2217-42ce-a8f8-77c592270698)
![Capture d'écran 2024-04-14 024101](https://github.com/Paladium-Developpement/Paladium-Issue/assets/147213024/78bfe095-6eda-41dc-8dba-c9acec06c2d1)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
