### ISSUE TITLE
[Bug]: Coffre de faction (ultra safe chest)

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1899]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Le joueur a pu mettre un ultra safe chest dans le coffre de faction.

### Rec

https://youtu.be/ksnzn1zSPkU

### Qu'aurait-il dû arriver ?

Le joueur ne peut pas mettre d'ultra safe chest dans le coffre de faction (l'item ne peut pas rentrer dans le coffre)

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
