### ISSUE TITLE
[Bug]: Invitations de Faction

### ISSUE THREAD

**Issue by Caitline86** [Paladium-Developpement/Paladium-Issue#190]
### Pseudo InGame

Caitline1986

### Que s'est-il passé ?

On m'invite à rejoindre une faction mais le jeu ne me considère pas dedans.

En fait par le système d'enveloppe d'invitation, je peux rejoindre mais ça ne met pas à jour les membres et dès un retour au lobby fait, je ne suis plus en faction. Pour certains de ma faction, il a fallu refaire le truc plusieurs fois hier pour qu'ils puissent y entrer et ils n'ont pas bugués.

Il y a aussi le souci de ne rien pouvoir ouvrir dans les claims alors que le jeu me compte dedans selon le /f f Caitline1986 après la commande manuelle de: /f join pseudo.

### Qu'aurait-il dû arriver ?

Me mettre en faction, me laisser ouvrir les coffres pour poser du stuff etc et pas m'exclure. 

### Serveur

Fantasia

**Comment by aureliancnx** [comment]
Le bug est-il toujours d'actualité ?

**Comment by Caitline86** [comment]
Salut, à priori il fallait que la faction soit ouverte pour rejoindre avec une invitation, je ne sais pas si c'est encore nécessaire ni pourquoi il faut que ce soit ouvert si on a une invitation?
