### ISSUE TITLE
[Bug]: Error occurred while contacting login serveurs, are they down ?

### ISSUE THREAD

**Issue by Snaft64YT** [Paladium-Developpement/Paladium-Issue#1900]
### Pseudo InGame

Snaft64

### Que s'est-il passé ?

Il nous est impossible de se connecter. Ca arrive depuis quelques jours avec le même message d'erreur: "Error occurred while contacting login serveurs, are they down ?". En forçant plus ou moins on y arrive mais parfois ça peut prendre plus de 30 minutes.

### Rec

https://youtu.be/5YeMRp4tH4Y

### Qu'aurait-il dû arriver ?

On devrait pouvoir se connecter directement.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
