### ISSUE TITLE
[Bug]: Problème Boutique (Grade à abonnement)

### ISSUE THREAD

**Issue by Snaft64YT** [Paladium-Developpement/Paladium-Issue#1901]
### Pseudo InGame

Snaft64

### Que s'est-il passé ?

On est renvoyé à la page des grades dès que l'on sélectionne une période pour un grade à abonnement (Trixium / Trixium+).

### Rec

https://youtu.be/TVwlIm7N_Lc

### Qu'aurait-il dû arriver ?

On devrait pouvoir mettre l'abonnement dans notre panier.

### Serveur

None

**Comment by Apsig69** [comment]
Bonjour, ce n'est pas un bug, c'est parce que le grade endium n'a pas été acheté via la boutique web.
