### ISSUE TITLE
[Bug]: Bug Builder Wand / XP Bush

### ISSUE THREAD

**Issue by Snaft64YT** [Paladium-Developpement/Paladium-Issue#1902]
### Pseudo InGame

Snaft64

### Que s'est-il passé ?

On peut superposer des XP Bush les uns sur les autres

### Rec

https://youtu.be/MFMNT7Yed_8

### Qu'aurait-il dû arriver ?

Nous ne sommes pas sensé pouvoir le faire

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
