### ISSUE TITLE
[Bug]: Ranger des drawers dans l'enderchest

### ISSUE THREAD

**Issue by Lerouleurpro** [Paladium-Developpement/Paladium-Issue#1903]
### Pseudo InGame

lerouleurpro

### Que s'est-il passé ?

Lorsqu'on est en serveur minage, il est possible de placer des drawers dans l'enderchest en utilisant la commande /ec.

### Rec

https://youtu.be/ibq9dTpFLEQ?si=Zj6VLYQCNR_L9eYw

### Qu'aurait-il dû arriver ?

Le drawer ne devrait pas pouvoir rentrer dans l'enderchest ou être automatiquement remis dans l'inventaire du joueur

### Serveur

Minage

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
