### ISSUE TITLE
[Bug]: Permission faction-ptr

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1904]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il n'a pas pu accéder au faction-ptr alors qu'il avait le grade requis.
message écris dans le chat:
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/6799d468-7fe6-4e99-9efa-8290caedccca)

### Rec

/

### Qu'aurait-il dû arriver ?

Il aurait du pouvoir accéder au faction-ptr

### Serveur

None

**Comment by aureliancnx** [comment]
"Il" qui ?

**Comment by Snaft64YT** [comment]
> "Il" qui ?

Ca le fait pour tout le monde j'ai l'impression. Chez moi, il y a "Snaft64" ou "AxouIi" par exemple.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
