### ISSUE TITLE
[Bug]: PalaAnimation Lootbox non reçue

### ISSUE THREAD

**Issue by Anubeni** [Paladium-Developpement/Paladium-Issue#1913]
### Pseudo InGame

Anubeni

### Que s'est-il passé ?

Les joueurs gagnants du PalaAnimation ne reçoivent pas les lootbox en récompense.

### Rec

https://www.youtube.com/watch?v=Av6G48fhEYc 

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
