### ISSUE TITLE
[Bug]: Drawers dans l'EnderChest

### ISSUE THREAD

**Issue by Shad0owDark** [Paladium-Developpement/Paladium-Issue#1915]
### Pseudo InGame

Shad0wDark

### Que s'est-il passé ?

Un joueur m'a fait remonté une faille permettant de mettre un Drawer dans son EnderChest et pouvoir le récupéré plus tard.

D'après le joueur, lorsque l'ont fait "/ec" dans un serveur Minage il serait alors possible de déposer un drawer dans celui-ci, le drawer resterai alors dans l'enderchest et pourrait être récupéré n'importe quand, a part si un enderchest est ouvert dans un serveur faction ce qui aura pour conséquence de renvoyer le drawer dans l'inventaire du joueur.

### Rec

https://www.youtube.com/watch?v=ftJLPlMKJrw&ab_channel=xurych

### Qu'aurait-il dû arriver ?

Lorsque le joueur aurait essayé de mettre le drawer dans son enderchest ce dernier aurais dû s'envoyer directement dans son inventaire et le serveur aurais dû lui envoyer un message comme quoi il est impossible de déposé un drawer dans un enderchest.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
