### ISSUE TITLE
[Bug]: Bypass Cooldown des compétences des compagnons

### ISSUE THREAD

**Issue by Shad0owDark** [Paladium-Developpement/Paladium-Issue#1916]
### Pseudo InGame

Shad0wDark

### Que s'est-il passé ?

Un joueur m'a fait remonté la possibilité d'annuler le cooldown d'une compétence d'un pet en intervertissant tout simplement les deux slots ou se situe les compétences. 

### Rec

https://wiki.paladium-pvp.fr/mecaniques-et-events/mecaniques/familiers/competences

### Qu'aurait-il dû arriver ?

Même lors de l'intervertissement des slots de compétences les cooldown aurais dû persister et donc empêcher le joueur de réutilisé la compétence de son compagnon.

### Serveur

None

**Comment by hjordn** [comment]
bug corrigé, merci pour le report !
