### ISSUE TITLE
[Bug]: Drawer dans l'ec

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#1917]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

En allant en minage on peut mettre un drawer dans son ec puis on peut ensuite stack c'est drawer même en allant en faction sauf que dès que l'on ouvre notre ec en faction le drawer revient directement dans notre inventaire

### Rec

https://youtu.be/FQteQzdCVSM

### Qu'aurait-il dû arriver ?

le drawer ne devrait pas aller dans l'inventaire

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Je te remercie pour le signalement de ce bug. Cependant, ce bug a déjà été signalé dans une autre Issue présente sur cette plateforme de signalement de bug.

Le signalement similaire est le suivant : https://github.com/Paladium-Developpement/Paladium-Issue/issues/1915

Afin d'éviter que cela se reproduise, je t'invite à utiliser l'outil de recherche dans les Issues avec les mots clés qui correspondent au problème rencontré sur cette page pour vérifier si ce bug est déjà signalé : https://github.com/Paladium-Developpement/Paladium-Issue/issues

Cordialement.
