### ISSUE TITLE
[Bug]: quête white stained clay

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1918]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Problème dans la phrase car la quête dit de casser de la White stained clay alors qu'en réalité, il faut la déposer.
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/798dcf8f-c373-4aa7-98c9-b8f9e4b0823c)

### Rec

/

### Qu'aurait-il dû arriver ?

/

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
