### ISSUE TITLE
[Bug]: Quête palapass brown mushroom

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1919]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Le joueur a cassé le block demandé (brown mushroom) et la quête n'a jamais augmenté

### Rec

https://youtu.be/hlh5VUpX0Qw

### Qu'aurait-il dû arriver ?

Quand le joueur casse le block demandé (brown mushroom) dans la quête celle-ci doit augmenter.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
