### ISSUE TITLE
[Bug]: Bug golem

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1920]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

A chaque gros crash des serveurs, les golems bug et ne produisent plus de lingot. Pour que celui-ci puisse faire en sorte que ses golems reproduisent, il doit les retirer de la box recraft le golem et le reposer dedans ce qui n'est absolument pas pratique et très couteux/perd de sa rentabilité.

### Rec

https://www.youtube.com/watch?v=X0j_nA-RXH0

### Qu'aurait-il dû arriver ?

Il faudrait que les golems puissent continuer à produire même après qu'un serveur crash.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
