### ISSUE TITLE
[Bug]: personne invisible

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1921]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Lorsqu'un joueur sneak et se met dans un coin celui-ci devient invisible ce qui rend impossible de taper le joueur tant que le joueur ne se met pas correctement. Exemple à 1min 18 sur le record

### Rec

https://youtu.be/N3eSQuSND0U?si=o_szYvSZ2R7Qw9zI

### Qu'aurait-il dû arriver ?

Il faudrait que le joueur ne disparaisse pas dans toute les situations possible si celui-ci n'utilise pas de stone d'invisibilité.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

La vidéo indiquée dans l'issue est supprimée.

**Comment by F0rtimel** [comment]
@aureliancnx C'est good j'ai mis à jour le github avec la nouvelle vidéo qu'il m'a envoyé

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
