### ISSUE TITLE
[Bug]: bug home disparu

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1926]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Suite à un redémarrage de tout les serveurs, plusieurs personnes se sont vu clear leurs home sur tout les serveurs. Après plusieurs redémarrage de leurs jeux rien n'y fait ils ne récupèrent pas leurs home.

### Rec

/

### Qu'aurait-il dû arriver ?

Il faudrait faire en sorte qu'ils récupèrent leurs home.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
