### ISSUE TITLE
[Bug]: Event Totem , Elo non donnée lors de la déconnexion

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1927]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lors du totem , la withold et la blackold ont récupérer un block , le problème étant que les 2 personnes ayant récupérer le block étaient pas connecté lors de la distribution des points , la faction n'ont donc pas récupérer leur gain.

Le rec est seulement un rec de preuve comme quoi la withhold on bien déposer un block , l'elo dump dira le reste sur la situation.

### Rec

https://youtu.be/rz9LVPcOLQw

### Qu'aurait-il dû arriver ?

Donnée les points même si le joueur est deconnecter.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
