### ISSUE TITLE
[Bug]: maison de faction

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1928]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Il est possible de casser le block qui est tout en haut et qui fait la limite de la maison de faction même si la personne n'est pas sensé avoir les access.

### Rec

https://youtu.be/wqSZBDOxkcQ

### Qu'aurait-il dû arriver ?

Il faudrait faire en sorte que ça ne puisse pas se casser.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
