### ISSUE TITLE
[Bug]: bug personne 

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1929]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Certains joueurs son buggé dans le chat ig ( ils ont les mêmes apparences que s'ils étaient au lobby) et lorsqu'ils veulent interagir avec un coffre ou autre ou bien même casser quelque chose ils ne peuvent pas. 
image du pseudo dans le chat : 
![image](https://github.com/Paladium-Developpement/Paladium-Issue/assets/143201230/4ce96851-fcfc-4ffe-8bc5-4b18856025a7)

### Rec

https://www.youtube.com/watch?v=bh-OJrscZPw

### Qu'aurait-il dû arriver ?

Ils auraient dû avoir les mêmes caractéristiques au niveau du chat et ils auraient du pouvoir interagir avec des coffres et pouvoir casser des blocs,...

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
