### ISSUE TITLE
[Bug]: Le palapass bug pour certaines personnes

### ISSUE THREAD

**Issue by F0rtimel** [Paladium-Developpement/Paladium-Issue#1933]
### Pseudo InGame

F0rtimel

### Que s'est-il passé ?

Les quêtes du palapass ne veulent pas s'ouvrir pour certaines personnes

### Rec

https://youtu.be/i53lJLvySFs

### Qu'aurait-il dû arriver ?

Il faut que les personnes puissent voir les quêtes

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
