### ISSUE TITLE
[Bug]: Compétence du pet "Cercueil portable" fonctionnant toujours dans les AP

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1937]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La compétence "Cercueil portable" fonctionne dans les Avant-Postes, ceci permet aux joueurs de récupérer leur stuff après leur mort, alors qu'il devrait bien sûr revenir à l'autre. Beaucoup de joueurs profitent de ce bug actuellement.

### Rec

https://youtu.be/8LaBcrPB6Uk

### Qu'aurait-il dû arriver ?

Le stuff devrait dropper et la compétence devrait être désactivée dans ces zones (il est pourtant bien précisé dans la description "hors warzone")

### Serveur

None

**Comment by hjordn** [comment]
Bug corrigé pour cette v10, merci pour le report !
