### ISSUE TITLE
[Bug]: Utilisation lingot pala création fac, même si erreur

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#194]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Lorsque l'on créé une faction, si une erreur parvient lors de sa création, comme un nom déjà pris, des symboles, caractères spéciaux ou nom max atteint, les 100 lingots sont quand même consommés même si la création n'aboutit pas

### Qu'aurait-il dû arriver ?

Les 100 lingots ne devraient pas être consommés

**Comment by aureliancnx** [comment]
Corrigé
