### ISSUE TITLE
[Bug]: Lucky Blocks - divers

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1945]
### Pseudo InGame

Roselynee

### Nom à corriger

![image](https://github.com/user-attachments/assets/fd824e4b-ce03-4ff6-a59a-019b48d020d5)
Ton heure a **sonné**

![image](https://github.com/user-attachments/assets/ae6d5bb7-5dcb-4ec1-9c4a-9511f9293fb1)
Tous les **mêmes**

### Rec

gpo

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
