### ISSUE TITLE
[Bug]: Divers petits bugs (noms / textures)

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1946]
### Pseudo InGame

Roselynee

### Noms

Block sonore lumineux (ID 3172) > **Bloc**

### Texture

> Bois de racinier
La texture du bois de racinier (ID 3006) en jeu est celle du feuillage de racinier (ID 3005)
![image](https://github.com/user-attachments/assets/b5833544-5335-4965-9977-187e0dccea30)
Le bloc devrait avoir cette texture : 
![image](https://github.com/user-attachments/assets/7fbd2f72-a99f-414c-a660-03e54577bdf4)

> Coffres-forts
Les trois coffres-forts sont posés face au Nord alors qu'il faudrait qu'ils soient placés face au joueur. De plus, dans l'inventaire, leur texture n'est pas de face.
![image](https://github.com/user-attachments/assets/f8c7481c-9045-484d-8f27-4a5ee90cbe39)
![image](https://github.com/user-attachments/assets/7de6d9ec-7a25-4046-8159-62515d079a1d)

### Rec

gpo

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
