### ISSUE TITLE
[Bug]: Nom à corriger - agro stone / Pierre d'agro

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1947]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Pierre d'agro > Pierre d'aggro
Agro stone > Aggro stone

### Rec

gpo

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
