### ISSUE TITLE
[Bug]: List ID EnderChest pas setup

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1949]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Les id ne sont plus a jour pour l'ender chest , il est possible de mettre des drawers dans les ec.
![image](https://github.com/user-attachments/assets/87d4300e-7f79-4b85-9865-11825ebf103f)

### Rec

jé po

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
