### ISSUE TITLE
[Use bug]: Triangulation base grâce au nouveau cadran

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#195]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Une sorte de triangulation de la position du joueur est possible grâce à l'affichage du cadran en haut de l'écran,
C'est le cas des streamers notamment qui ne peuvent pas désactiver cette feature

### Qu'aurait-il dû arriver ?

Avoir la possibilité d'activer / désactiver ce cadran pour les joueurs qui le souhaitent

**Comment by Zeldown** [comment]
:x: C'est possible dans Helios
