### ISSUE TITLE
[Bug]: Armure Alignement prend le dessus du /skin

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1951]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le skin d'armure de l'alignement prend le dessus du /skin , il vient impossible de changer le skin de son armure

### Rec

https://youtu.be/xyWB7kvHDGE

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello c'est corrigé merci.
