### ISSUE TITLE
[Bug]: Le /go n'a pas les nouveaux serveurs

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1952]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le /go n'a pas suivi la mise a jour , il contient uniquement le faction-ptr
![image](https://github.com/user-attachments/assets/11bd1053-e710-4cbf-915b-c7bf7b9dcd16)

### Rec

inutile

### Qu'aurait-il dû arriver ?

Devrait avoir les 5 serveurs factions

proposition : et le serveur event, si possible.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
