### ISSUE TITLE
[Bug]: Crash lorsqu'on écrit dans le chat faction

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1953]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

On se fait déconnecter de notre serveur lorsqu'on envoie un message dans le chat faction

### Rec

https://youtu.be/dI0wS6ZFk7I

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
