### ISSUE TITLE
[Bug]: NaturaBox Palapass

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1955]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Dans le palapass (dans la partie payante) , on retrouve des natura boxs , cependant , elles ont été supprimés
![image](https://github.com/user-attachments/assets/b084ba6d-c36f-4294-a8c3-ae220cdcdefa)

### Rec

t

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
