### ISSUE TITLE
[Bug]: LP permission minage

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1956]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

La grande majorité des minages sont innacessible dûes a ce message d'erreur
![image](https://github.com/user-attachments/assets/68dd7c0e-7bcd-4227-8a7f-c00fbb011f04)

### Rec

t

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
