### ISSUE TITLE
[Bug]: Génération Minage

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1957]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

La génération des minages n'est pas la même que la dernière version , on ne retrouve plus de structure moddée (tour a mob , village witch, "dungon sousterrain", etc...).

Les océans sont très présent , contrairement a avant qui n'existait pas. 

### Rec

t

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
