### ISSUE TITLE
[Bug]: Classement affiche op

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1959]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le classement affiche les comptes opé, ce qui n'était pas le cas dernière version
![image](https://github.com/user-attachments/assets/c22a6d63-d0d0-48bc-85e7-9e07e471eb5f)

### Rec

t

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
