### ISSUE TITLE
[Bug]: /farmlands non accessible

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1961]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Les gradés n'ont pas accès au /farnland , le serveur leur mentionne qu'ils doivent avoir un grade , mais même en possèdant un , l'erreur continue

### Rec

t

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
