### ISSUE TITLE
[Bug]: Jour saison Clicker non reset

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1968]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Certaines améliorations du clicker sont disponibles alors que nous avons pas atteint les jours de saison. Par exemple sur mon screen , des upgrades de 3 jours sont déja disponibles et sur mon compte op j'ai des upgrades nécéssitant 22 jours disponible.
![image](https://github.com/user-attachments/assets/85df3c6c-d6d5-4c64-a2e7-11978ea6e9ed)

### Rec

t

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
