### ISSUE TITLE
[Bug]: Pet - Compétence "Faux tournoyante"

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1972]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Lors de l'utilisation de la compétence du pet, bien qu'ayant les graines dans l'inventaire, celles-ci ne sont pas replantées. 

### Rec

https://www.youtube.com/watch?v=X93TSO1NGNM

### Qu'aurait-il dû arriver ?

Une fois le champ cueilli, il faut que les graines soient replanter immédiatement

### Serveur

None

**Comment by hjordn** [comment]
Il s'agissait d'une description incorrect, merci pour le report, cela est corrigé !
