### ISSUE TITLE
[Bug]: Bouleau des rivières lors du craft de la glue

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1973]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Pour crafter de la glue, il faut planter une pousse de bouleau des rivières sur de la clay et recouvrir le tout d'angelic water. Le problème, c'est que le plant saute, comme les autres plants (blé, patates, etc.) lorsqu'ils sont recouverts d'eau. ça bloque donc le craft de la glue

### Rec

https://youtu.be/sSzE2R9AGwA

### Qu'aurait-il dû arriver ?

Normalement, la pousse de bouleau des rivières ne doit pas sauter, elle doit juste être là, dans l'eau, pour qu'on puisse la faire pousser avec de la poudre d'os. 

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
