### ISSUE TITLE
[Bug]: La Wither Obsidienne est inefficace avec les withers gentils et withers passifs

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1975]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La Wither Obsidienne est inefficace avec les withers gentils et withers passifs

à vérifier : normalement, la wither obsidienne bloque la capacité du wither (n'importe quelle sorte) à casser l'obsidienne, ce qui n'est pas le cas. Si ce n'est pas prévu, merci de me faire un retour pour que je modifie le wiki, si c'est prévu, c'est à corriger

### Rec

https://youtu.be/W_NEgqZ3kpE

### Qu'aurait-il dû arriver ?

Elle devrait créer une prison d'obsidienne autour du wither

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
