### ISSUE TITLE
[Bug]: dégât de la broadsword en paladium

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1977]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Bonjour ! Les dégâts de la broadsword en paladium devraient être plus importants que ceux de l'épée en paladium, comme les autres broadwords : 

**améthyste**
épée : 7
broadsword : 7.7

**titane**
épée : 7.5
broadsword : 8.2

**paladium**
épée : 10
broadsword : 9

### Rec

gpo

### Qu'aurait-il dû arriver ?

Dans la logique, la broadsword en paladium devrait faire 10.7 et non 9.

### Serveur

None

**Comment by Zeldown** [comment]
❌ Après discussion avec plusieurs joueurs pvp ils pensent que c'est pas une bonne idée
