### ISSUE TITLE
[Bug]: Totem Fleuri NV40

### ISSUE THREAD

**Issue by ekaliclua** [Paladium-Developpement/Paladium-Issue#1978]
### Pseudo InGame

Ekali

### Que s'est-il passé ?

Au niveau 42, il est impossible d'utiliser le totem fleuri.

### Rec

X

### Qu'aurait-il dû arriver ?

Le totem fleuri devrait être utilisable avant le niveau 42.

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello, as tu vérifié que c'est bien le métier alchimiste ?
Je peux l'ouvrir au niveau 42
![image](https://github.com/user-attachments/assets/6d713237-4abe-4c9a-8691-1d7d9acba612)
![image](https://github.com/user-attachments/assets/70c89e81-4c6b-42ab-bb8b-5e961f802f7c)

**Comment by roselyneelavraie** [comment]
Il voulait dire qu'avant le niveau 42, tu ne peux pas ouvrir le totem alors que tu devrais.

**Comment by KraemerJoe** [comment]
Hello je pense que le niveau requis 42 pour l'ouvrir est fait exprès non ?

**Comment by roselyneelavraie** [comment]
Bah on avait demandé justement pendant les tests si on pouvait l'utiliser avant et on nous avait dit que oui, mais si c'est bloqué, pas de problème, on le dira aux joueurs ^^

**Comment by KraemerJoe** [comment]
Hello modification effectuée
