### ISSUE TITLE
[Bug]: Chat Faction Crash

### ISSUE THREAD

**Issue by Xeliphix** [Paladium-Developpement/Paladium-Issue#1979]
### Pseudo InGame

Xeliphix

### Que s'est-il passé ?

Quand on essaie d'envoyer un message dans le chat faction cela nous kick au lobby

### Rec

.

### Qu'aurait-il dû arriver ?

Un message aurait dû être envoyé dans le chat faction sans être kick

### Serveur

Egopolis

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
