### ISSUE TITLE
[Bug]: XP faction à l'infini 

### ISSUE THREAD

**Issue by PierreLeLonie01** [Paladium-Developpement/Paladium-Issue#198]
### Pseudo InGame

PierreLeLonie

### Que s'est-il passé ?

Bug remonté par Biotaz:

"/f claim = +5 xp de faction mais /f unclaim = 0 xp donc claim puis unclaim à l'infinie rapporte de l'xp ? grande échelle cela peut être abusé !"
![Capture](https://user-images.githubusercontent.com/92879573/164322338-f5eb1d9f-29b4-4d21-804a-ddf1fa0d7003.PNG)

### Carte Graphique

1060 gtx

**Comment by aureliancnx** [comment]
Corrigé
