### ISSUE TITLE
[Bug]: Boss gost

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#1981]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

lors du boss les joueur gost dedans et ne peuvent plus rien faire ce qui est embêtent 

### Rec

https://youtu.be/btG3srA1faE

### Qu'aurait-il dû arriver ?

les joueurs devraient ne pas avoir de gost lors des boss

### Serveur

Event01

**Comment by aureliancnx** [comment]
Duplicate https://github.com/Paladium-Developpement/Paladium-Issue/issues/1711
