### ISSUE TITLE
[Bug]: PALAPASS - Quête Marcheur Fou

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1982]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La quête du Marcheur Fou ne s'actualise pas correctement, empêchant les joueurs de valider la quête.

### Rec

https://www.twitch.tv/beberttv_/clip/CovertLightNeanderthalPanicVis-7oEGaBz2VXFZoBFh

### Qu'aurait-il dû arriver ?

Il faudrait que la quete s'actualise correctement

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello, la quête fonctionne parfaitement c'est simplement que pour des soucis de performance l'actualisation n'est pas instantanée, il faut marcher et patienter :)

**Comment by roselyneelavraie** [comment]
Coucou, je veux bien croire que l'actualisation prenne du temps, mais comme tu vois, le joueur a parcouru près de 130k de blocs et pourtant, seulement 14k ont été enregistrés.

**Comment by KraemerJoe** [comment]
La donnée dans le profil n'est pas la même il faudrait voir je retesterai pas précaution mais le système n'a subît aucune modification depuis et a toujours fonctionner
