### ISSUE TITLE
[Bug]: EC - Possible d'y ranger les framed drawer et les compacting drawers

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1983]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Il est possible de ranger dans les EC les framed drawers et les compacting drawers

### Rec

https://www.youtube.com/watch?v=8tTsbPdxa_M

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
