### ISSUE TITLE
[Bug]: A vos marques

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#1984]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Sur les serveurs factions, il est possible de faire le "a vos marques" sur chacun des serveur.

### Rec

pas de rec 

### Qu'aurait-il dû arriver ?

Le "a vos marque" est censé être global pour tout les serveurs. 

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Après vérification interne, il ne semble pas possible que l'événement à vos marques puisse être effectué sur plusieurs serveurs factions, car la progression est sauvegardée indépendamment du serveur Faction. Cela semble être un comportement étrange qui nécessite des vérifications et des tests approfondis. 

Afin de mieux enquêter, est-il possible de m'indiquer si le problème est systématique et s'il est toujours présent?

**Comment by aureliancnx** [comment]
Bonjour,

N'ayant pas reçu de réponse à ce jour pour apporter des informations supplémentaires à cette issue, je ferme cette issue.

Dans le cas où le bug est reproduit, je vous invite à créer une nouvelle issue en apportant les détails manquants.
