### ISSUE TITLE
[Bug]: La commande /minage

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1986]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Normalement, la commande /minage est accessible à tous, pourtant, seuls les gradés peuvent l'utiliser.

### Rec

gpo

### Qu'aurait-il dû arriver ?

La commande devrait être accessible aussi aux non-gradés.

### Serveur

None

**Comment by aureliancnx** [comment]
La commands minage était bien prévue à la base pour les gradés
