### ISSUE TITLE
[Bug]: Switch Arrow impossible a faire

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1988]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Il est actuellement impossible de faire les switchs arrows

### Rec

https://youtu.be/KnSVWCR25fI

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
