### ISSUE TITLE
[Bug]: Mauvaise réponse à la question PalaAnimation "Quel est le nom de ce serveur Faction ?"

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#1991]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

La question "Quel est le nom de ce serveur faction ?" a été posée sur Xanoth, et le prix a été attribué à un joueur ayant répondu "Egopolis"

### Rec

https://youtu.be/hdBnIU0J1yI

### Qu'aurait-il dû arriver ?

La bonne réponse aurait du être "Xanoth"

### Serveur

Xanoth

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
