### ISSUE TITLE
[Bug]: Deco combat /lobby et /go

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1993]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on se déconnecte via le /go ou /lobby en combat , notre stuff ne drop pas a terre.

### Rec

https://youtu.be/Sezzn0OOuqM

### Qu'aurait-il dû arriver ?

Notre stuff doit se drop au sol , ou nous empêcher d'exécuter notre commande.

### Serveur

None

**Comment by aureliancnx** [comment]
Duplicate https://github.com/Paladium-Developpement/Paladium-Issue/issues/1932
