### ISSUE TITLE
[Bug]: Palapass - Quête Armure Puissante

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#1994]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La quête demande de mettre une armure en paladium, mais elle ne prend en compte que les armures en paladium neuves.

### Rec

https://www.youtube.com/watch?v=347fy7h8mcU

### Qu'aurait-il dû arriver ?

Elle devrait prendre en compte la pièce d'armure, peu importe son état d'usure.

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello, modification effectuée
