### ISSUE TITLE
[Bug]: Achat drawer clicker mais récupère stone block

### ISSUE THREAD

**Issue by Heiwaan** [Paladium-Developpement/Paladium-Issue#1995]
### Pseudo InGame

Heiwan

### Que s'est-il passé ?

Un joueur a acheté un drawer 2x2 dans le clicker, mais lors de l'achat de celui-ci, le joueur a récupéré un bloc de stone

### Rec

https://youtu.be/VOR4uEnoBbA

### Qu'aurait-il dû arriver ?

Lors de l'achat du drawer 2x2, le joueur aurait du avoir un drawer 2x2 et non un bloc de stone

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
