### ISSUE TITLE
[Bug]: Bug Showcase PTR

### ISSUE THREAD

**Issue by Heiwaan** [Paladium-Developpement/Paladium-Issue#1996]
### Pseudo InGame

Heiwan

### Que s'est-il passé ?

J'ai mis un item via le serveur PTR dans ma showcase du /profil, mais cela s'est synchronisé avec les serveurs faction. Par conséquent j'ai des items actuellement in obtenables dans ma showcase 

### Rec

https://www.youtube.com/watch?v=8g92TZuBAss

### Qu'aurait-il dû arriver ?

Quand un item est inséré dans la showcase via le /profil du PTR, celui-ci ne devrait pas être synchronisé avec les serveurs faction

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
