### ISSUE TITLE
[Bug]: Profil clicker

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#1997]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

Quand le joueur ouvre la page du clicker dans son profil cell ci se ferme instantanément 

### Rec

https://www.youtube.com/watch?v=d-xUvZXvRUM

### Qu'aurait-il dû arriver ?

le joueur devrait voir son profil du clicker

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
