### ISSUE TITLE
[Bug]: Crash Tile Entities, changement de serveur

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1998]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on fait /lobby avec un spawner controller dans la zone, notre jeu peut crash
Edit : Cela peut se produire avec toutes les tile entities, il faudrait trouver un fix à la source

### Rec

.

### Serveur

None

### LOG

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 24-09-30 22:45
Description: Unexpected error

java.lang.ClassCastException: fr.paladium.palaspawner.common.tile.TileEntitySpawnerController cannot be cast to noppes.npcs.blocks.tiles.TileCampfire
	at noppes.npcs.blocks.BlockCampfire.func_149734_b(BlockCampfire.java:78)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:354)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2127)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:974)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:900)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at noppes.npcs.blocks.BlockCampfire.func_149734_b(BlockCampfire.java:78)
	at net.minecraft.client.multiplayer.WorldClient.func_73029_E(WorldClient.java:354)

-- Affected level --
Details:
	Level name: MpServer
	Chunk stats: MultiplayerChunkCache: 81, 82
	Level seed: 0
	Level generator: ID 04 - TerrainControl, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1,101,0), Chunk: (at 15,6,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 20579745 game time, 17425708 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: Travertine (git:Heimdall-Bootstrap:1.15-SNAPSHOT:0b988ab:unknown) <- uranium,kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2523)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:929)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1836887360 bytes (1751 MB) / 3657433088 bytes (3488 MB) up to 13958643712 bytes (13312 MB)
	JVM Flags: 10 total; -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmx13312M -Xms2048M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge Paladium Optifine OptiFine_1.7.10_HD_U_E7 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	Forge{10.13.4.2512} [Minecraft Forge] (palaforge-1.7.10-10.13.4.2512.jar) 
	UCHIJA	apollon{5.3.4} [Apollon] (Apollon-9.0.0.pala) 
	UCHIJA	palaforge-utils{1.0.0} [PalaForge-Utils] (PalaForgeUtils-3.0.3.pala) 
	UCHIJA	profile{1.0.0} [Profile] (ProfileMod-2.0.4.pala) 
	UCHIJA	achievement{0.1} [AchievementMod] (Achievements-2.0.0.pala) 
	UCHIJA	alliancelobby{1.0.0} [AllianceLobby] (AllianceLobby-1.0.4.pala) 
	UCHIJA	helios{2.4.0} [Helios Mod] (Helios-6.0.2.pala) 
	UCHIJA	palakeybind{1.0.0} [PalaKeybind] (PalaKeybind-1.0.1.pala) 
	UCHIJA	common{1.0} [Paladium Common] (Paladium-Common-3.0.0.pala) 
	UCHIJA	alliancemod{1.0.0} [AllianceMod] (AllianceMod-1.2.4.pala) 
	UCHIJA	ariane{1.0.0} [Ariane] (Ariane-3.1.4.pala) 
	UCHIJA	backtothefuture{1.0} [Back to the future] (BackToTheFuture-1.0.1.pala) 
	UCHIJA	betternei{1.0.0} [BetterNEI] (BetterNEI-1.4.10.pala) 
	UCHIJA	bet{0.1} [BettingMod] (bettingmod-1.0.pala) 
	UCHIJA	blueprintmod{1.0.0} [BluePrintMod] (BluePrintMod-1.3.3.pala) 
	UCHIJA	chronos{1.0.5} [Chronos] (Chronos-Mod-2.1.2.pala) 
	UCHIJA	customnpcs{1.5.4} [CustomNpcs] (customnpcs-prod.pala) 
	UCHIJA	factions{0.1} [Factions] (Factions-2.5.3.pala) 
	UCHIJA	guardiangolem{0.1-INDEV} [Guardian Golem] (GuardianGolem-4.0.0.pala) 
	UCHIJA	lindworm{2.0.0} [Lindworm] (Lindworm-3.0.1.pala) 
	UCHIJA	mount{0.1} [Mount] (Mount-4.0.0.pala) 
	UCHIJA	palajobs{0.1} [PalaJobs] (PalaJobs-4.0.3.pala) 
	UCHIJA	palapass{1.0.0} [Palapass] (Palapass-Mod-3.0.2.pala) 
	UCHIJA	palapet{1.0.0} [PalaPet] (PalaPet-2.0.1.pala) 
	UCHIJA	shop{1.0.0} [shop] (PalaShop-3.0.3.pala) 
	UCHIJA	palaspawner{1.0.0} [PalaSpawner] (PalaSpawner-1.0.10.pala) 
	UCHIJA	zephyr-ui{1.0.0} [Zephyr UI] (Zephyr-UI-4.12.1.pala) 
	UCHIJA	palavanillagui{1.0.0} [PalaVanillaGui] (PalaVanillaGui-2.0.3.pala) 
	UCHIJA	palamod{8.0.1.6} [PalaMod] (PalaMod-5.2.0.pala) 
	UCHIJA	corruption{1.0.0} [Corruption] (Corruption-2.0.0.pala) 
	UCHIJA	cresus{0.1} [Cresus] (Cresus-3.0.0.pala) 
	UCHIJA	IronChest{6.0.43.730} [Iron Chest] (ironchest-prod.pala) 
	UCHIJA	palamarket{1.0.0} [Market] (Market-1.0.7.pala) 
	UCHIJA	palaconfiguration{1.0.0} [PalaConfiguration] (PalaConfiguration-1.0.2.pala) 
	UCHIJA	palaclicker{1.0.0} [PalaClicker] (PalaClicker-2.0.2.pala) 
	UCHIJA	palacommunityevent{1.0.0} [PalaCommunityEvent] (PalaCommunityEvent-1.4.0.pala) 
	UCHIJA	paladium-ui{1.0.0} [Paladium-UI] (Paladium-UI-2.9.1.pala) 
	UCHIJA	palaoracle{0.1} [palaoracle] (PalaOracle-1.2.0.pala) 
	UCHIJA	palatrade{1.0.1} [palatrade] (PalaTrade-3.0.2.pala) 
	UCHIJA	propsy{1.0.0} [Propsy] (Propsy-2.0.7.pala) 
	UCHIJA	ranking{1.0} [Ranking] (Ranking-Mod-3.0.2.pala) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-prod.pala) 
	UCHIJA	serverselector{1.0.0} [ServerSelector] (ServerSelector-1.0.9.pala) 
	UCHIJA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (storagedrawers-prod.pala) 
	UCHIJA	TerrainControl{2.7.2 for Forge 1.7.10 v7} [Terrain Control] (terraincontrol-prod.pala) 
	UCHIJA	translate{1.0.0} [Translate] (Translate-Mod-2.0.1.pala) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 536.23' Renderer: 'NVIDIA GeForce GTX 1070/PCIe/SSE2'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithfull_paladium_officiel.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 536.23
	OpenGlRenderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by KraemerJoe** [comment]
Cela peut se produire avec toutes les tile entities, il faudrait trouver un fix à la source

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
