### ISSUE TITLE
[Bug]: Togglesprint non fonctionnel

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#1999]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le toggle sprint n'est pas fonctionnel, peu importe si je change ma touche , il ne s'activera pas.

### Rec

.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
