### ISSUE TITLE
[Bug]: Commandes disponibles en Combat

### ISSUE THREAD

**Issue by Mist4ke123** [Paladium-Developpement/Paladium-Issue#200]
### Pseudo InGame

_Mist4ke_

### Que s'est-il passé ?

Les commandes /spawn, /lobby, /home <nomduhome> marchent en combat.
(Je n'ai pas testé d'autres commandes)

### Qu'aurait-il dû arriver ?

Ces commandes ne devraient pas marcher en combat.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
