### ISSUE TITLE
[Bug]: Le /condense ne fonctionne pas sur les minerais moddée

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#2000]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le /condense ne fonctionne pas sur les minérais moddées.

### Rec

https://youtu.be/NjfwxmMeZnY

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
