### ISSUE TITLE
[Bug]: Boutique paladium le site

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#2002]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

On ne peux pas acheter de grade sur la boutique en ligne sur le site

### Rec

https://youtu.be/GNmN-919DW8

### Qu'aurait-il dû arriver ?

on devrait pouvoir acheter un grade 

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

C'est un comportement "normal" si tu essaies d'acheter le trixium alors que tu n'as pas le grade endium
