### ISSUE TITLE
[Bug]: Minage - le nom du minage n'apparaît pas

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2003]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Comme nom de serveur, ceci apparaît

![image](https://github.com/user-attachments/assets/4300830d-3ddf-473d-a0fd-0e3c61543288)

De plus, il n'y a plus d'informations dans le chat pour indiquer le minage sur lequel on se connecte quand on choisit le minage avec la commande /minage

Quand on clique sur Minage depuis la carte
![image](https://github.com/user-attachments/assets/d72baf22-4be3-4948-91b2-886fb7e04eb5)

Quand on passe par la commande /minage
![image](https://github.com/user-attachments/assets/adb812d3-5850-47b9-a49c-477f70b53e73)

### Rec

gpo

### Qu'aurait-il dû arriver ?

Il devrait s'agir du nom du minage sur lequel on est.

On devrait avoir dans le chat le nom du minage.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
