### ISSUE TITLE
[Bug]: /tpconfirm

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2004]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

![image](https://github.com/user-attachments/assets/7ad5869e-2950-4ba5-abb9-b02e3275b8ff)
On doit remplacer ici "dans votre /profil" par "dans vos /options"

### Rec

gpo

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
