### ISSUE TITLE
[Bug]: Totem fleuri

### ISSUE THREAD

**Issue by ShyvaYaku** [Paladium-Developpement/Paladium-Issue#2005]
### Pseudo InGame

Shyva_Yaku

### Que s'est-il passé ?

Les totems se déconnectent tout le temps a cause d'un lag ou quand on quitte un chunk quelques instants  

### Rec

https://www.youtube.com/watch?v=PiPxcJt_RMQ

### Qu'aurait-il dû arriver ?

Ils doivent rester actif et ne pas restart le pourcentage a chaque fois

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello c'est corrigé
