### ISSUE TITLE
[Bug]: Traduction erronnée 

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#2006]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

![image](https://github.com/user-attachments/assets/12995bb9-79e4-4803-88fa-73c52b11a1a0)
Les noms "Rank" et "Daily Quests" sont inversés par rapport au bonus qu'ils donnent. (Dans mon cas, 15% par "les quêtes journalières" et 2.6% par "mon grade"

### Rec

Screen

### Qu'aurait-il dû arriver ?

Ceci devrait être affiché :
[2.6%] Daily Quests
[15%] Rank

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
