### ISSUE TITLE
[Bug]: Craft mini golem ptr

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#2008]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

On ne peut pas craft les mini golem en ptr

### Rec

https://youtu.be/TtDZsR6f_Jk

### Qu'aurait-il dû arriver ?

on devrait pouvoir crafter les mini golem en ptr

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello, ne fonctionne actuellement sur aucun environnement, un patch sort prochainement @AugmaTV
