### ISSUE TITLE
[Bug]: /profil non fonctionnel

### ISSUE THREAD

**Issue by blockgu07** [Paladium-Developpement/Paladium-Issue#2009]
### Pseudo InGame

Blockgu

### Que s'est-il passé ?

Lorsqu'on fait /profil, la fenêtre s'ouvre et se ferme directement après avec comme notification : "Impossible de récupérer les données"

### Rec

https://youtu.be/BeENVLFUgfY

### Qu'aurait-il dû arriver ?

Afficher la fenêtre avec toutes les informations du profil

### Serveur

Global

**Comment by KraemerJoe** [comment]
Fixed @aureliancnx
