### ISSUE TITLE
[Bug]: RG spawn minage non fonctionnelle

### ISSUE THREAD

**Issue by WashiPaladium** [Paladium-Developpement/Paladium-Issue#201]
### Pseudo InGame

WashiGame_

### Que s'est-il passé ?

En allant sur les serveurs minages, beaucoup n'ont pas de RG dans les spawns

### Qu'aurait-il dû arriver ?

Il aurait dû y avoir une RG.

### Serveur

Minage

### LOG

Il n'y a qu'à voir l'était du spawn de ce serveur: https://prnt.sc/srCwmrLMAsZ-

**Comment by aureliancnx** [comment]
Corrigé ! 🚀
