### ISSUE TITLE
[Bug]: Grade non affiché /profile

### ISSUE THREAD

**Issue by Zeluck-github** [Paladium-Developpement/Paladium-Issue#2010]
### Pseudo InGame

Zeluck_

### Que s'est-il passé ?

Les grades sur le profil ne s'affichent pas correctement ; par exemple, sur l'écran 'Joueur', à la place de 'Responsable'. Cela se produit également pour les joueurs Endium et Trixium, tous grades confondus.

Exemple :
![image](https://github.com/user-attachments/assets/e0564261-f0bd-477c-b663-215511271c05)

### Rec

Voir Screen

### Qu'aurait-il dû arriver ?

Les grades devraient être affichés correctement selon le grade réel du joueur.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Le problème est-il toujours d'actualité ?

**Comment by Zeluck-github** [comment]
@aureliancnx Problème réglé, merci
