### ISSUE TITLE
[Bug]: Enchantements via l'enclume impossibles

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2011]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Il est parfois impossible d'enchanter un item alors même qu'on a les niveaux pour. Ici, c'est un livre Tranchant 5 Butin 3 Solidité 3. On a aussi essayé avec plus de niveaux et une épée neuve. 
![image](https://github.com/user-attachments/assets/a26f8220-0898-475d-b119-b098c4143c69)

### Rec

gpo

### Qu'aurait-il dû arriver ?

On devrait pouvoir enchanter l'item

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
