### ISSUE TITLE
[Palapass] - Quête "Tuer des joueurs en zone PvP" à supprimer du palapass

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2014]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Tout est dans le titre :)

### Rec

gpo

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
