### ISSUE TITLE
[Bug]: Spawner à sorcières - aucun drop de poudre de wither

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2015]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Passé le niveau 100 du métier Chasseur, il y a une certaine chance de récupérer de la poudre de wither en tuant des sorcières. Le problème, c'est qu'actuellement aucune poudre de wither n'est drop lorsqu'un joueur tue des sorcières via le contrôleur de spawners.
![image](https://github.com/user-attachments/assets/ebf19cd6-599e-47fa-a2e9-80c93965a516)
Exemple du loot récupéré en tuant des sorcières sur plusieurs T4 avec deux améliorations butin. 

### Rec

gpo

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
