### ISSUE TITLE
[Correction] - Correction à apporter dans les messages liés à la pierre légendaire random 

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2017]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

![image](https://github.com/user-attachments/assets/dde65aec-2c81-4c07-aac8-437dae26efc4)
à quoi cela sert ??? --> à quoi cela sert-il ?

+ pour la pierre de puissance 
reu --> reçu

d'ailleurs en paladium langage EN c'est aussi en français

**Phrases à modifier :** 

![image](https://github.com/user-attachments/assets/e3b0ef92-bd44-47d0-b192-0d1e4184c7c3)
Tu as été touché(e) par une mystérieuse potion... Tu es maintenant invisible pendant 2 minutes !

![image](https://github.com/user-attachments/assets/3ee8f68c-c371-45df-a292-69287d575508)
[...] grand pouvoir. Tu es immunisé(e) à la sulfuric water pendant 5 minutes !

![image](https://github.com/user-attachments/assets/91f9d5d4-26dd-4b43-9ffc-2e57c28f9271)
La fortune est tombée sur toi !

![image](https://github.com/user-attachments/assets/f5867989-4369-4fc4-ac92-1fd065f8bc2c)
Tu as bien travaillé et tu as gagné beaucoup d'expérience. Bravo !
(ou) Moins de travail, plus d'expérience. Bravo !

### Rec

gpo

### Serveur

None

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
