### ISSUE TITLE
[Bug]: Impossible de faire rentré des âmes dans les spawners 

### ISSUE THREAD

**Issue by JOK0X** [Paladium-Developpement/Paladium-Issue#2019]
### Pseudo InGame

JOK0X

### Que s'est-il passé ?

Impossible de faire rentré l'âme du spawner dans le spawner

### Rec

https://www.youtube.com/watch?v=t403mqY6kDI

### Qu'aurait-il dû arriver ?

L'âme aurait du rentré dans le spawner 

### Serveur

Minage

**Comment by KraemerJoe** [comment]
Hello @JOK0X je vois que le titre de la vidéo mentionne le caverne hammer.
Est ce que tu sais me confirmer la bonne vidéo stp

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
