### ISSUE TITLE
[Bug]: Non validation de la quête journalière "Tuez 100 zombies"

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#2022]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Lorsque le joueur tue le zombie pour faire avancer sa quête de tuer 100 zombies, le fait d'en tuer n'est pas comptabiliser.

### Rec

https://www.youtube.com/watch?v=LXpIcQYYX3Q  (timecode: 20s)

### Qu'aurait-il dû arriver ?

La quête devrait avancer au fur et à mesure que des zombies sont tuer par le joueur.

### Serveur

Global

**Comment by KraemerJoe** [comment]
Hello, c'est corrigé merci !
