### ISSUE TITLE
[Bug]: Palapass - Quête de tuer des vaches 

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2023]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Parfois les quêtes mensuelles du Palapass ne fonctionnent pas pour tous les joueurs (et ce n'est pas une question d'actualisation qui met du temps, promis). Par exemple ici, la quête où il faut tuer des vaches ne fonctionne pas pour ce joueur (celui du rec), pourtant son ami a pu finir la quête. 

### Rec

https://www.youtube.com/watch?v=xXtPcu272gE

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello, c'est corrigé merci !
