### ISSUE TITLE
[Bug]: Récompenses trixium - palier 15 000

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2024]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Au palier des 15 000 trixiums, la récompense est toujours le cosmétiques drapeau qui n'existe plus.
![image](https://github.com/user-attachments/assets/46939266-a7f6-4d14-8e80-b6c662a5430f)

### Rec

gpo

### Qu'aurait-il dû arriver ?

Il faudrait créer un cosmétique spécial pour le trixium ou bien définir une autre récompense.

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
