### ISSUE TITLE
[Bug]: Aimant - notification

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#2026]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Les notifications "Magnet activé" et "Magnet désactivé" sont inversées. D'ailleurs, il faudrait qu'en français, ce soit écrit "Aimant".
![image](https://github.com/user-attachments/assets/b2e2882f-30b6-41f2-9d40-e6b6a40486bc)

### Rec

gpo

### Serveur

None

**Comment by KraemerJoe** [comment]
Hello,
est ce que tu arrives à reproduire le bug ?
je viens d'essayer et c'est good chez moi

**Comment by roselyneelavraie** [comment]
https://github.com/user-attachments/assets/a4e695e4-66db-41cc-9606-45aed990d40e
