### ISSUE TITLE
[Bug]: Farm des fleurs avec les totems mais pas avec des os

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#2027]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

On peut farm des fleurs avec n'importe quelle item

### Rec

https://www.youtube.com/watch?v=KDFieq6-IcI

### Qu'aurait-il dû arriver ?

On devrait pouvoir farm les fleurs qu'avec les os

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
