### ISSUE TITLE
[Bug]: Nouveau tab affichage des joueurs

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#203]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Faire en sorte que l'affichage du tab avec les joueurs connectés soit au dessus (en transparence) des infos sur les équipements possédés par le joueur comme les armures par exemple. 
Etre équipé d'un full armure ne permet pas de lire correctement les pseudos sur le côté gauche du tab

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
