### ISSUE TITLE
[Bug]: Recherche dans l'hotel des ventes

### ISSUE THREAD

**Issue by Mist4ke123** [Paladium-Developpement/Paladium-Issue#204]
### Pseudo InGame

_Mist4ke_

### Que s'est-il passé ?

Les recherches dans l'hôtel des ventes fonctionnent mal. Exemple :  Quand je cherche "amethyste" je ne trouve aucun item (alors qu'il y en a énormément sans recherche) mais ça ne se produit pas quand on cherche "ore" où pour le coup la recherche fonctionne bien.

**Comment by KraemerJoe** [comment]
✅ resolved
