### ISSUE TITLE
[Bug]: Duplication /ah

### ISSUE THREAD

**Issue by ZyF0x** [Paladium-Developpement/Paladium-Issue#205]
### Pseudo InGame

ZyF0x

### Que s'est-il passé ?

Duplication Drawers
https://youtu.be/TJ9E7bZxZfk

Principe : 
Mettre le drawer vide
Empiler le drawer plein
Echap

### Qu'aurait-il dû arriver ?

Pas de duplication

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
