### ISSUE TITLE
[Bug]: Le shift click ne marche pas sur l'autocrafter et le grinder

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#215]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on est dans l'interface du grinder et de l'autocrafter le shift clic ne marche pas (c'étais déja le cas avant)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
