### ISSUE TITLE
[Bug]: Limite xp claim chunk / mois

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#220]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

La limite de 2000 (xp ou chunk par mois, je ne suis pas sûre) imposée pour gagner de l'xp peut être dépassée
J'ai testé que ce soit pour 2000xp ou 2000 chunk mais on peut la dépasser 

### Qu'aurait-il dû arriver ?

L'xp gagnée par le claim de chunk devrait être limitée

**Comment by aureliancnx** [comment]
Ce bug a déjà été report dans l'issue https://github.com/Paladium-Developpement/Paladium-Issue/issues/198
