### ISSUE TITLE
[Bug]: Problème d'affichage caractères spéciaux TAB

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#223]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Certains caractères spéciaux ne s'affichent pas correctement dans le tab
Screen ci joint
![2022-04-25_18 37 59](https://user-images.githubusercontent.com/104101226/165134399-6655fa9f-197e-46b4-9a3c-b2161c9fdbfb.png)

**Comment by aureliancnx** [comment]
Corrigé !
