### ISSUE TITLE
[Bug]: Portail en endium 

### ISSUE THREAD

**Issue by PierreLeLonie01** [Paladium-Developpement/Paladium-Issue#225]
### Pseudo InGame

PierreLeLonie

### Que s'est-il passé ?

Lorsqu'on jette des fioles d'Ostrya dans le portail, la clé se charge mais l'on ne récupère pas l'endium.

### Qu'aurait-il dû arriver ?

Lors que la clé est chargé au maximum aurait dû donner l'enduim en question.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
