### ISSUE TITLE
[Bug]: Certaines commandes en combat sont désactivées et d'autres sont activées

### ISSUE THREAD

**Issue by Mist4ke123** [Paladium-Developpement/Paladium-Issue#226]
### Pseudo InGame

_Mist4ke_

### Que s'est-il passé ?

La commande /feed en combat est désactivée.
La commande /lobby en combat est activée.

### Qu'aurait-il dû arriver ?

La commande /feed devrait être activée et nous remplir notre barre de nourriture.
La commande /lobby devrait être désactivée et nous empêcher de rejoindre le lobby.

### Serveur

Mineria

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
