### ISSUE TITLE
[Bug]: Fiole alchi mal rempli

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#228]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on utilise les extracteurs pour le métier d'alchimiste, normalement une fois éteint la fiole dois être à 100%, et la elle ne le sont jamais, avec plein de chiffre aléatoire
https://www.youtube.com/watch?v=1YCFwTKH0Vs

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
