### ISSUE TITLE
[Bug]: Classement de faction

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#230]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Le classement général est mis par ordre alphabétique et non pas par niveau

**Comment by aureliancnx** [comment]
Le classement n'est pas par niveau mais est en fonction de l'elo, la façon de gagner de l'élo n'est pas encore implémentée donc toutes les factions sont à zéro, ce qui fait qu'elles sont classées par ordre alphabétique.
