### ISSUE TITLE
[Bug]: Faux paladium lors de la création de faction

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#231]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on créer une faction, cela nous coute 100 paladium, a chaque stack que le jeux finira pour prendre les 100 pala il laissera 1 lingot, mais ce lingot ne peux être utiliser, il peux bouger, il disparais si on ouvre le shop... un bug visuel en gros

**Comment by aureliancnx** [comment]
corrigé
