### ISSUE TITLE
[Bug]: le f home ne fonctionne pas

### ISSUE THREAD

**Issue by Waazix** [Paladium-Developpement/Paladium-Issue#233]
### Pseudo InGame

Waazix19

### Que s'est-il passé ?

Lorsqu'on met un home de faction et que l'on veut s'y téléporter, on reste à l'endroit ou on est déjà.

### Qu'aurait-il dû arriver ?

J'aurai dû être téléporté à l'endroit ou le home a été défini

**Comment by aureliancnx** [comment]
Bonjour,

Après plusieurs tests, je n'ai pas réussi à reproduire le bug que tu me décris. Je suis bien téléporté. Peux-tu me joindre une vidéo afin de mieux comprendre ?

Cordialement,

**Comment by Waazix** [comment]
J'ai regardé et je pense que le /f home ne fonctionne pas quand le chunk n'est pas chargé.

Voilà une vidéo qui démontre le soucis: https://www.youtube.com/watch?v=fBpbl5sTT88

**Comment by aureliancnx** [comment]
corrigé à la prochaine mep
