### ISSUE TITLE
[FeedBack][Faction]: permission alliés/neutres

### ISSUE THREAD

**Issue by Waazix** [Paladium-Developpement/Paladium-Issue#237]
### Pseudo InGame

Waazix19

### Que s'est-il passé ?

Il est impossible de modifier les permissions des factions alliées et neutres (pour le moment le bouton de modification de leurs permission ouvre la page de la faction: https://prnt.sc/mAmIckuvvZ8f / https://prnt.sc/U6jXHrky1ajc)

### Qu'aurait-il dû arriver ?

Un menu de modification de leurs permission aurait dû s'ouvrir

**Comment by Akysooo** [comment]
Update : Cliquer sur faction allié ou neutre fait un fatal error
![image](https://user-images.githubusercontent.com/92928910/182832267-3dc7300b-3a32-43b8-9c4f-96ff7b2aa02e.png)
[latest.log](https://github.com/Paladium-Developpement/Paladium-Issue/files/9259139/latest.log)
