### ISSUE TITLE
[Bug]: Item non drop avec la POG

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#238]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Avec la POG quand on casse un item ou plus couramment les minerai, il ne sont pas toujours drop.

**Comment by aureliancnx** [comment]
Bonjour

Cette issue est un duplicate de celle-ci : https://github.com/Paladium-Developpement/Paladium-Issue/issues/202
