### ISSUE TITLE
[Bug]: File d'attente (non prouvé)

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#239]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

J'ai eu beaucoup de report sur la file d'attente, ils choisissent forestia, pendant la file vont sur mineria, mais sont tp sur forestia plus tard

Pas du tout prouvé car je ne peux pas tester

**Comment by KraemerJoe** [comment]
Je suis sur le coup
