### ISSUE TITLE
[Bug]: Bug graphique à partir de 100 pour les faction

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#242]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on atteint 100 joueurs on a un pti soucis graphique
https://prnt.sc/2GhBhfmOlMMT

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
