### ISSUE TITLE
[Bug]: Bug de synchro à la date du 28/04/22

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#244]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Ambrogg42 est venu me report un bug de synchro avec un rec, dans le rec on le vois vers 2min avec un message dans le chat "Attention vous n'êtes plus synchronisé", ensuite il a des item qui disparaisse de sont inventaire en essayant de les réparer et quand il lobby et reviens sur mineria il perds tout sont stuff.

Rec: 
https://www.youtube.com/watch?v=OBEH6J_RrYA

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
