### ISSUE TITLE
[Bug]: Bug de porte (téléportation)

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#245]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on est en sneak sur une porte et qu'on l'ouvre/ferme, on est tp a notre home ou dernier point de "sauvegarde" précédent, déja présent en v7, il y a ca avec d'autre item que les portes
https://www.youtube.com/watch?v=I6-hzBF3gPQ

**Comment by Lorn87** [comment]
ANC
