### ISSUE TITLE
[Bug]: Shift clique cobble breaker

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#248]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Le shift clique pour mettre des item dans le cobble breaker comme la cobble ou les upgrade ne fonctionne pas, pour retirer les particule ceci marque que pour 3 cases, les 3 dernière de notre hotbarre, donc obliger de glisser ou de jeter au sol pour ensuite récupérer

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
