### ISSUE TITLE
[Bug]: Palaforge

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#249]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on met des item a fondre dans la palaforge, qu'on la casse ensuite on ne récupère pas les item, je sais que ca fait la même chose avec les upgrade des cobblebreaker
https://www.youtube.com/watch?v=GkgSnXzu448

**Comment by Zeldown** [comment]
Il n'y a aucun bug, ceci est le fonctionnement vanilla de mc
