### ISSUE TITLE
[Bug]: Travel boots

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#250]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Normalement quand on a des travel boots on a le saut automatique pour avancer vite, à l'heure actuel ce n'est pas le cas, on est obligé de sauter

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
