### ISSUE TITLE
[Bug]: Bateau 

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#251]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on veux naviguer sur l'eau avec un bateau on est kick du bateau au bout de quelque seconde, il est très difficile de naviguer aussi, ce bug existe depuis longtemps.
https://www.youtube.com/watch?v=OlLEUoLt4dU

**Comment by aureliancnx** [comment]
Ce bug a été signalé sur cette issue : https://github.com/Paladium-Developpement/Paladium-Issue/issues/83

Merci du rapport !
