### ISSUE TITLE
[Bug][Faction]: Bonus d'exp métier avec le lvl de faction

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#253]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les 3% d'exp donner avec les niveau de faction ne marche pas (je ne sais le reproduire je sais pas où ca ce trouve, lorn ma dit de report il est pas sur que ce sois encore activé)

**Comment by aureliancnx** [comment]
Corrigé
