### ISSUE TITLE
[Bug]: /nether

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#254]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on fait /nether on est tp au nether, on a un cooldown de 10min avant de pouvoir le refaire, une fois passer les 10 minutes le temps passe en négatif et donc le / nether ne marche pas 
Screen:
https://prnt.sc/W0FhVgvMLy4X

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
