### ISSUE TITLE
[Bug]: Changement de pseudo

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#255]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Lorsqu'un joueur change de pseudo, il garde son ancien pseudo lorsqu'il parle dans le tchat mais pour le lookup ou le ping dans le tchat, c'est son nouveau pseudo qu'il faut utiliser.

### Qu'aurait-il dû arriver ?

Son nouveau pseudo aurait du apparaître dans le tchat lorsqu'il parle au lieu de son ancien

### Serveur

Mineria

**Comment by Akysooo** [comment]
C'est lié au nouveau tchat

**Comment by Akysooo** [comment]
@aureliancnx
