### ISSUE TITLE
[Bug]: Combat (Arc)

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#256]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

L'arc vanilla et celui en paladium ne mettent pas en combat les joueurs.

### Qu'aurait-il dû arriver ?

Une fois touché à l'arc, le joueur aurait dû être mis en combat. Ce n'est pas le cas

### Serveur

Mineria

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
