### ISSUE TITLE
[Bug]: Crash avec les Slimy Helmet

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#262]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Lorsqu'un joueur ayant un Slimy Helmet se connecte ou met un Slimy Helmet, il crashe.

### LOG

https://pastebin.com/N3mayp4L

**Comment by Syb3rtron** [comment]
Rec d'un joueur ayant ce problème : https://youtu.be/bki4pWeJLVU

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
