### ISSUE TITLE
[Bug]: Dupli avec le grinder

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#264]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Lorsque l'on met un plastron dans un grinder presque rempli de paladium (ici la jauge est à  97/100) et qu'on met un item a fondre il n'est pas consommé et rajoute quand même du paladium dans le grinder.

https://www.youtube.com/watch?v=uXl37b6wwFc

### Qu'aurait-il dû arriver ?

l'item aurait du disparaitre ou le grinder n'aurait pas du le prendre car il dépasse la quantité maximum de la jauge et ne pas rajouter de paladium

**Comment by ZyF0x** [comment]
Au passage cela se produit uniquement lorsque l'item est full durabilité.

**Comment by KraemerJoe** [comment]
#211
