### ISSUE TITLE
[Bug]: Bug de synchro, connexion impossible sur les factions. 

### ISSUE THREAD

**Issue by PierreLeLonie01** [Paladium-Developpement/Paladium-Issue#265]
### Pseudo InGame

Bug reporté par les joueurs : Zappatwithoutbk / Ubdu03 - PierreLeLonie

### Que s'est-il passé ?

Première étape le joueur est au lobby, 
Se connecte à Mineria et est dans la file d'attente. 
Se connecte instantanément à Fantasia ==> Meurt 
Un message d'erreur apparait dans le chat et se fait kick du lobby.
https://www.youtube.com/watch?v=-rnugKX5mdc
https://pastebin.com/fMYjxfDm Logs si besoin du joueur.

De nombreux joueurs sont venus sur Teamspeak me report le problème : Clear de métiers, clear d'inventaires OU dupli de l'inventaire. 
Je n'ai moi-même le souci, donc pas pu tester. 

### Qu'aurait-il dû arriver ?

La synchronisation aurait dû se faire normalement

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
