### ISSUE TITLE
[Bug]: Dollars Stone

### ISSUE THREAD

**Issue by MrKittenxs** [Paladium-Developpement/Paladium-Issue#268]
### Pseudo InGame

Mr_Kittenxs

### Que s'est-il passé ?

Lorsque qu'on utilise l'objet "Dollars Stone" et que l'on casse de la pierre , on ne récupère pas d'argent. la terre disparer  aussi de l'inventaire a cause du Dollars Stone .

### Qu'aurait-il dû arriver ?

L'argent devrait augmenter . et la terre récupérée devrait rester dans l'inventaire.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
