### ISSUE TITLE
[Bug]: Bug production infini de paladium dans un grinder 

### ISSUE THREAD

**Issue by Mist4ke123** [Paladium-Developpement/Paladium-Issue#269]
### Pseudo InGame

_Mist4ke_

### Que s'est-il passé ?

Bug report par le joueur SunaSayf

-> Quand un grinder est à 100/100 de paladium et que l'on met un casque en paladium (ou n'importe quel item) dans le slot pour le faire fondre et qu'en même temps on produit des lingots grâce au pala fondu le casque n'est jamais fondu mais la jauge reste à 100/100 et le paladium continue d'être produit => production infini de paladium.
Vidéo youtube explicative : [https://youtu.be/llJxQIlR-TM](url)

### Qu'aurait-il dû arriver ?

Le casque devrait être fondu seulement quand il y a la place nécessaire dans la jauge de paladium fondu.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
