### ISSUE TITLE
[Bug]:Xb berries et compressed ne fonctionnent plus (ou le clic droit pour utiliser un truc)

### ISSUE THREAD

**Issue by Caitline86** [Paladium-Developpement/Paladium-Issue#272]
### Pseudo InGame

Caitline1986

### Que s'est-il passé ?

Bonsoir, impossible d'en consommer. Elles disparaissent quand on veut les manger et reviennent au clic suivant en main sans monter les niveaux d'expérience.

### Qu'aurait-il dû arriver ?

Les utiliser normalement.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
