### ISSUE TITLE
[Bug]: Problèmes de performances avec la Dollars Stone

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#273]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Lorsque la Dollars Stone est utilisée avec beaucoup d'items à vendre dans l'inventaire, le serveur se met à perdre rapidement en performances.

Vidéo illustratrice : https://youtu.be/oOZoNtmRCAc
Tests fait sur Océania le 1/5/22, 12h20

### Serveur

Océania

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
