### ISSUE TITLE
[Bug]: Pickaxe invisible

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#275]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on prend n'importe quel pickaxe vanilla dans la main, on a la main invisible et la pickaxe aussi
https://prnt.sc/AWgjsj6dXALu

[The_Shadow_57](https://minos.paladium.dev/player/734a7445-2966-4de4-81fe-105699a11623)
Bug avec la stone pickaxe
Hello, je viens report un bug avec la stone pickaxe Elle est invisible dans la main
Server
cb268296-7cd8-441b-9d94-4674547aa262
Location
x: 64, y: 102, z: 6
Date
01/05/2022 - 09:00:33

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
