### ISSUE TITLE
[Bug]: Création de faction mais pas affiché dans le chat

### ISSUE THREAD

**Issue by WashiPaladium** [Paladium-Developpement/Paladium-Issue#276]
### Pseudo InGame

WashiGame_

### Que s'est-il passé ?

Un joueur a créé sa faction (dépensé ses 100 paladium), la faction est créée, bien disponible grâce à la commande /f f (faction) avec le joueur dedans, mais Wilderness s'affiche à côté du pseudo du joueur, malgré le fait qu'il est relancé le jeu.

Voir screen: https://prnt.sc/BmxLzLFfWLgR

### Qu'aurait-il dû arriver ?

Wilderness aurait dû être modifié pour être "oblinight" (nom de faction du joueur)

### Serveur

Mineria

**Comment by aureliancnx** [comment]
Bonjour,

Quelles sont les actions à faire pour que ce bug soit reproduisible ?

**Comment by aureliancnx** [comment]
N'ayant pas eu de réponse, je me dois de fermer ce ticket. Si le problème est toujours d'actualité, merci d'indiquer toutes les actions permettant de reproduire le bug
