### ISSUE TITLE
[Bug]: Les objets tenus par les mobs "volent"

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#277]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Lorsqu'un mob spawn avec une arme en main (pelle/épée), celle-ci se retrouve à tourner autour du mob.
Captures d'écran avec un Zombie Pigman : https://imgur.com/a/wJehY1K
Vidéo avec un Zombie tenant la Sainte Pelle : https://www.youtube.com/watch?v=-d-gzyEV7mI

Note : Donner un item à un mob ne le fait pas tourner autour

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
