### ISSUE TITLE
[Bug]: Bow en paladium

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#282]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

L'arc en paladium est normalement utilisable qu'à partir d'un certain niveau du hunter, cependant si la dura est déja baissé n'importe qui peux l'utiliser.

https://www.youtube.com/watch?v=jb6oFYmlGvM

[Patate2France](https://minos.paladium.dev/player/07e06400-dd8e-4b68-8e55-2ff4ab165fd9)
titre
L'arc en Paladium est utilisable par les gens qui n'ont pas le niveau m?tier lorsque de la durabilit? lui est enlev?
Server
1116cbc0-68a9-4efb-9074-755a438e3fae
Location
x: 9683, y: 9, z: -3901
Date
01/05/2022 - 13:05:19

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
