### ISSUE TITLE
[Bug]: Sealed xp bottle, xp infini

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#283]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Au lvl 8 du métier de mineur on débloque l'utilisation des sealed xp bottle, cependant si on a pas le lvl on gagne l'exp mais ca ne consomme pas, du cout xp infini

https://www.youtube.com/watch?v=ZsA5qBvQNmk

[RommHackk](https://minos.paladium.dev/player/aa1dc87b-8c25-4d21-8b25-083acfa53839)
sealed xp bottle
Lorsque l'on n'a pas encore le niveau pour utiliser les cp bottle et qu nous essayons quand m?me de les utiliser, on peut les utiliser a l'infini et donc etre tr?s rapidement a de gros niveaux d'xp
Server
fe5e8283-c3c4-4848-95de-e3d11224c078
Location
x: -338, y: 2, z: -73
Date
02/05/2022 - 17:48:51

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
