### ISSUE TITLE
[Bug]: /glist

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#286]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le /glist ne donne pas le nombre de joueurs réellement présents sur le serveur.
https://prnt.sc/cMuml3wBztD2
https://prnt.sc/x_CTxiCQLejy

**Comment by aureliancnx** [comment]
La commande /glist ne donne que la liste des joueurs présents sur le proxy actuel.

Pour avoir le nombre total, il faut faire /proxy
