### ISSUE TITLE
[Bug]: Drawers Paladium Ender Chest

### ISSUE THREAD

**Issue by ZyF0x** [Paladium-Developpement/Paladium-Issue#287]
### Pseudo InGame

ZyF0x

### Que s'est-il passé ?

J'ai testé de mettre des drawers dans un Paladium Ender Chest et cela à fonctionner.

Pas tester avec les autres items bloqués en temps normal car pas sous la main (BagPack ou autres ?)

### Qu'aurait-il dû arriver ?

Que les drawers ne puissent pas être mis dedans.

**Comment by aureliancnx** [comment]
https://github.com/Paladium-Developpement/Paladium-Issue/issues/309
