### ISSUE TITLE
[Bug]: Craft spike autocrafter

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#291]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Le craft des spikes en paladium et titane ne consomme les ressources que d'une épée au lieu de trois, pas de problème avec les autres spikes

https://www.youtube.com/watch?v=guW5eweKuI0

date: 03/05/2022 - 18:26:44
serveur id : cb268296-7cd8-441b-9d94-4674547aa262
joueur: Petitmaltais

### Qu'aurait-il dû arriver ?

L'autocrafter ne devrait pas prendre moin de ressource pour le craft

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
