### ISSUE TITLE
[Bug]: Claim faction

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#295]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Les claims de la faction Heaven empêchent les joueurs d'une autre faction de taper les membres de la Heaven (même après /f enemy). Cela fonctionne néanmoins dans l'autre sens. Deux joueurs de deux factions différentes ne peuvent pas se taper dans le claim non plus.

### Serveur

Mineria

**Comment by KraemerJoe** [comment]
Non reproductible actuellement
