### ISSUE TITLE
[Bug]: [Faction] Problème /f admin 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#297]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Quand nous sommes dans la wilderness, le /f admin ne bypass pas la vérif de savoir si on a une faction pour faire l'action demandé.

### Qu'aurait-il dû arriver ?

Ca devrait le faire

**Comment by aureliancnx** [comment]
Quelle action ?

**Comment by Akysooo** [comment]
Pardon, il y a le unclaim (donc claim vers la wilderness), claim (par la wilderness) et une dernière mais je me souviens plus, je te dis si je la retrouve

**Comment by aureliancnx** [comment]
Duplication de cette issue ? https://github.com/Paladium-Developpement/Paladium-Issue/issues/296
