### ISSUE TITLE
[Bug]: Ap aucune indication sur les panneaux

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#299]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il n'y a aucune indication sur le panneau

**Comment by Akysooo** [comment]
Si jamais lorsque j'ai créé l'ap, j'ai cassé le panneau pour créer la zone (j'étais en gm1) et du coup je l'ai reposé (le non cassage est bon après) mais c'est peut être cela qui  a fait buggé les indications.

**Comment by KraemerJoe** [comment]
Avait été corrigé lors de la refonte.
