### ISSUE TITLE
[Bug]: Staffco

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#30]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

le /staffco ne fonctionne plus, plus aucun affichage en jeu.

### Qu'aurait-il dû arriver ?

afficher la liste des staffs inter-serveur

### Serveur

Forestia

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
