### ISSUE TITLE
[Bug]: Ap gui gestion

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#300]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

J'ai acheté un ap et cliquer sur le panneau n'ouvre pas le gui de gestion ap (ouvre rien)

**Comment by Akysooo** [comment]
C'est lié au même problème que lui #299 . 
Quand le panneau est créé avec un clic droit, on peut bien cliquer dessus cependant cela ne nous ouvre pas le gui de gestion mais d'achat, ce qui fait qu'on peut l'acheter à l'infini. https://youtu.be/zcwznHrKqQ4

**Comment by KraemerJoe** [comment]
Close après les modifications/ajouts/fixs fait sur la partie AP.
