### ISSUE TITLE
[Bug]: Ap disparition disband faction

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#301]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

J'ai acheté un ap et quelques jours plus part j'ai disband ma faction. La zone de l'ap a disparu
![image](https://user-images.githubusercontent.com/92928910/167158435-b4d6fdef-70e0-47b5-a45b-ccdcbea730ad.png)

**Comment by aureliancnx** [comment]
J'ai supprimé manuellement l'AP dû à un souci de serialization.
