### ISSUE TITLE
[Bug]: Ap création nom problème 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#302]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

J'essaie de créer une autre zone ap à coté d'un autre. Il me dit qu'il est déjà créer alors que j'ai changé le nom et que je suis dans un chunk différent
![image](https://user-images.githubusercontent.com/92928910/167159057-b44c78ff-ba5b-490d-8e24-4df42cc35f79.png)

**Comment by aureliancnx** [comment]
Est-ce que le claim est un wilderness ? (/f access v)

**Comment by KraemerJoe** [comment]
Close après les modifications/ajouts/fixs fait sur la partie AP.
