### ISSUE TITLE
[Bug]: Ap problème de traduction cassage panneau

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#303]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il manque une traduction lorsqu'uon essaie de casser le panneau d'un ap
![image](https://user-images.githubusercontent.com/92928910/167159211-b576337a-1816-492e-b526-b36893bb92be.png)

**Comment by Akysooo** [comment]
(Je n'ai pas de faction si jamais)

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour
