### ISSUE TITLE
[Bug]: Ap aucun historique

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#304]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Après [cela](https://github.com/Paladium-Developpement/Paladium-Issue/issues/300#issuecomment-1119724819), j'ai fait un history ap23 (nom de l'ap) et il n'y a aucun historique trouvé pour l'ap

**Comment by KraemerJoe** [comment]
Avait été corrigé lors de la refonte.
