### ISSUE TITLE
[Bug]: Ap id de l'ap au lieu d'ap1,2,3,...

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#306]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Quand on ne créait pas de nom cela met son id, cependant il est très difficile d'utiliser ce dernier ou de le repérer parmi une liste d'ap.
![image](https://user-images.githubusercontent.com/92928910/167164274-dfadc278-9ba9-4669-97e0-7d2a5e30f101.png)

### Qu'aurait-il dû arriver ?

Il faudrait les nommer automatique ap1,2,3,... (même si ap1 n'existe plus, juste incrémenter 1 à chaque fois) ou un truc du genre

**Comment by aureliancnx** [comment]
Ajout fait, disponible dans la prochaine mise à jour du faction
