### ISSUE TITLE
[Bug]: Position ap create et remove

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#307]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/167168099-009f5162-cc4c-421d-a359-dc550db61cc7.png)
Ce sont les positions en claim et non en coordonné

**Comment by Grandpou** [comment]
test

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour
