### ISSUE TITLE
[Bug]: Possibilité de mettre Drawer, bagpack dans les nouveaux ec

### ISSUE THREAD

**Issue by Mist4ke123** [Paladium-Developpement/Paladium-Issue#309]
### Pseudo InGame

_Mist4ke_

### Que s'est-il passé ?

Les items pouvant contenir du stuff (ex: drawer, bagpack etc...) peuvent être mis dans le nouveau enderchest

### Qu'aurait-il dû arriver ?

Impossibilité de mettre ces items => retour dans l'inventaire

**Comment by Lorn87** [comment]
fix
