### ISSUE TITLE
[Bug]: Duplication de paladium dans le grinder

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#318]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on met des item en paladium dans le grinder , on ce met entre 92 et 99 sur 100, ensuite on met un block en paladium à fondre pour arriver à 100/100, si on étais à 92 on a donc normalement pris 8 lingots du bloc, ensuite on créer un paladium bloc, ce qui enlève 9 lingots et nous remet à 91, ensuite le bloc qui étais déja fondu à 8/9 refond, et fait passé de 91 à 100, donc +9 et +8 le bloc à donc donné 17 lingots de paladium, en boucle on peux créer du pala à l'infini 

https://www.youtube.com/watch?v=0kz6lXD-GFE

Report par Patate2france

**Comment by KraemerJoe** [comment]
Corrigé, merci
