### ISSUE TITLE
[Bug]: 3D Anaglyph Bug texture

### ISSUE THREAD

**Issue by Mist4ke123** [Paladium-Developpement/Paladium-Issue#323]
### Pseudo InGame

_Mist4ke_

### Que s'est-il passé ?

Activer 3D Anaglyph puis /lobby et revenir sur le serveur => bug de texture en tt genre que ce soit avec un pack ou sans pack de texture.
Pour l'enlever il faut soit relancer le jeu soit changer son pack 

vidéo : [https://youtu.be/Wgzim89vC9w](url)

**Comment by Zeldown** [comment]
:x: Ceci est un bug venant d'optifine, il ne sera donc pas réglé de notre part.
