### ISSUE TITLE
[Bug]: Moula Stone 

### ISSUE THREAD

**Issue by ZyF0x** [Paladium-Developpement/Paladium-Issue#327]
### Pseudo InGame

ZyF0X

### Que s'est-il passé ?

Les moula stone sont censées donner 0.01 $ par stone consommé.

Pour le granite : celui-ci est consommé mais l'argent n'est pas donné.

Pour l'andésite : celle-ci n'est pas consommée 

### Qu'aurait-il dû arriver ?

Si le granite  a été ajouté volontairement : 

Pour le granite : faire en sorte qu'il donne l'argent

Pour l'andésite : la faire fonctionner (consomme + argent)

Remarque : L'un des évents de Lucky Bloc donne un commande bloc, celui-ci give un bloc de granite, par conséquent si le crédit d'argent est mis en place pour le granite, remplacer le bloc give. 
Sinon par le biais d'une clock activant le commande bloc il serait possible de gagner de l'argent sans rien faire.

**Comment by Akysooo** [comment]
Le granite, la stone et l'andésite ne sont pas en vente dans le shop, c'est donc normal qu'il ne donne pas d'argent. 

Pour l'andésite, je viens de tester elle est bien consommé. Si pour toi c'est toujours pas le cas, merci de me donner l'id de ton andésite

**Comment by KraemerJoe** [comment]
Je pense qu'il y a eut incompréhension et que la raison d'Akyso est bonne.
On close en attendant, si c'est vraiment un problème, on réopen
