### ISSUE TITLE
[Bug]: Autocrafter

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#329]
### Pseudo InGame

Physali

### Que s'est-il passé ?

L'autocrafter ne prend que 2 lingots sur les 6 nécessaire pour les épées lors du craft de spike en paladium et titane

https://www.youtube.com/watch?v=guW5eweKuI0

### Qu'aurait-il dû arriver ?

L'autocrafter devrait prendre 6 lingots et 3 sticks nécessaire au craft des épée

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
