### ISSUE TITLE
[Bug]: Lucky flower

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#330]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

La lucky flower ne despawn pas après 3 jours comme prévu normalement. Il faudrait aussi faire en sorte que la récupérer avec silk touch pour ensuite la reposer, ne réinitialise pas le temps.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
