### ISSUE TITLE
[Bug]: Perm de s'autokick de sa faction [Bug pluging Faction]

### ISSUE THREAD

**Issue by PierreLeLonie01** [Paladium-Developpement/Paladium-Issue#336]
### Pseudo InGame

PierreLeLonie

### Que s'est-il passé ?

Lorsque nous somme dans une faction il est possible de se kick d'une faction que l'on a rejoint. Sans même avoir la perm.
https://www.youtube.com/watch?v=j-NL5YIvhrM
voir vidéo.

### Qu'aurait-il dû arriver ?

Il aurait fallu que ce soit un autre joueur qui kick le joueur en question.

**Comment by aureliancnx** [comment]
Corrigé
