### ISSUE TITLE
[Bug]:  Paladium Bow Switch Arrow

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#338]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Impossible d'utiliser son arc en paladium avec les switchs arrow

https://www.youtube.com/watch?v=3GbVe-k6rd4

**Comment by KraemerJoe** [comment]
dupplicat: 
https://github.com/Paladium-Developpement/Paladium-Issue/issues/482
