### ISSUE TITLE
[Bug]: Bateau Hanté

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#341]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Impossible de contrôler un bateau. Voir explications ci-dessous

https://www.youtube.com/watch?v=EV4NcO7QXUc

date : 19/05/2022 - 222:36 
serveur :  1116cbc0-68a9-4efb-9074-755a438e3fae 
joueur : NightPaladin527

**Comment by aureliancnx** [comment]
Ce bug a été signalé sur cette issue : https://github.com/Paladium-Developpement/Paladium-Issue/issues/83

Merci du rapport !
