### ISSUE TITLE
[Bug]: Affichage arc dans la main

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#346]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Les arcs en paladium sont mal tenu

![image](https://user-images.githubusercontent.com/92928910/169822163-916be967-8098-45ed-bfa7-38e78bdbeb60.png)

### Qu'aurait-il dû arriver ?

![image](https://user-images.githubusercontent.com/92928910/169822269-2b740663-bec3-489d-b755-0acddc855662.png)

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
