### ISSUE TITLE
[Bug]: Crash lors du clic sur le Color Picker dans les Auras

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#349]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Lorsque j'ai cliqué sur l'icône color picker dans les auras, mon jeu a crashé.

### LOG

https://pastebin.com/rSBxdNwe

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
