### ISSUE TITLE
[Bug]: Hitbox avec le bambou

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#351]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Lorsque l'on marche à coter de bambou on est bloqué
https://www.youtube.com/watch?v=Yv3fyZ3DeVo

**Comment by matproulx** [comment]
Le bug arrive encore, lorsqu'on tombe sur le sommet d'un bambou. Mon personnage tommsam9 est pris de la sorte dans le monde Neolith, coordonnées -10023, 104, 14163
