### ISSUE TITLE
[Bug][GuardianGolem]: Golem Drop

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#353]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Le Golem ne drop pas les items de son inventaire avec l'amélioration Stockeur 
![image](https://user-images.githubusercontent.com/104795165/170131488-27205063-eed0-4d48-aa51-d86ec9355951.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
