### ISSUE TITLE
[Bug]: market impossible de scroll avec certaines recherches

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#355]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Avec certaines recherches dans l'hdv si l'on veut scroll pour voir les items plus bas il est impossible de le faire ni avec la molette ni avec la barre sur le coter
https://www.youtube.com/watch?v=2iTHU2GdrZA

**Comment by KraemerJoe** [comment]
Je pense que c'est qu'il y avait 4 épées et 4 ingots à voir car à priori je vois pas, on verra si ca s'avère être un vrai problème
