### ISSUE TITLE
[Bug]: pas de blason lors de la création de faction par commande

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#356]
### Pseudo InGame

Greenwich

### Que s'est-il passé ?

Lorsque j'ai crée une faction avec la commande /create ma faction a un blason blanc sans aucun motif :

### Qu'aurait-il dû arriver ?

La faction aurait du avoir un blason aléatoire.

**Comment by Greenwich31** [comment]
https://cdn.discordapp.com/attachments/699339703798857728/979316741790375976/unknown.png

**Comment by KraemerJoe** [comment]
https://github.com/Paladium-Developpement/Factions/tree/feat/f-create-randomemblem
