### ISSUE TITLE
[Bug]: Annuaire ne fonctionne pas 

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#357]
### Pseudo InGame

Greenwich

### Que s'est-il passé ?

Lorsque l'on entre du texte dans la barre de recherche de l'annuaire faction rien ne se passe. 

### Qu'aurait-il dû arriver ?

l'annuaire devrais nous proposer des factions selon notre recherche

**Comment by KraemerJoe** [comment]
https://github.com/Paladium-Developpement/Factions/commit/b86b0c5f8c8bdff49fb9c0b340fd89560ac96dcb
