### ISSUE TITLE
[Bug]: unclaim affichage

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#359]
### Pseudo InGame

Greenwich

### Que s'est-il passé ?

Lorsqu'on unclaim avec un rayon, on reçoit des messages dans le tchat pour valider le unclaim en plusieurs fois : https://cdn.discordapp.com/attachments/699339703798857728/979318713553653840/unknown.png 

### Qu'aurait-il dû arriver ?

Il faudrait qu'on ne reçoive qu'un seul message nous indiquant combien de claim on a supprimé

**Comment by aureliancnx** [comment]
Corrigé
