### ISSUE TITLE
[Bug][Factions]: Pas d'affichage des claims dans le f map graphique

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#360]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/170463723-ce328b7a-aba4-4758-9ef2-ad61c50022c2.png)
Il y a normalement un claim dans la zone chargé mais il n'est pas affiché

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
