### ISSUE TITLE
[Bug]: Permission ally pas dev

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#361]
### Pseudo InGame

Greenwich

### Que s'est-il passé ?

cette partie du cahier des charges n'est pas dev (urgent) : https://cdn.discordapp.com/attachments/699339703798857728/979320925570863155/unknown.png

**Comment by aureliancnx** [comment]
Bonjour,

Ce rapport semble déjà être existant : https://github.com/Paladium-Developpement/Paladium-Issue/issues/361
