### ISSUE TITLE
[Bug]: Shop

### ISSUE THREAD

**Issue by VallouDev** [Paladium-Developpement/Paladium-Issue#364]
### Pseudo InGame

Vallou_

### Que s'est-il passé ?

Lorsqu'on vend un item, on ne gagne pas d'argent.
On ne peut pas acheter un item également.

### Qu'aurait-il dû arriver ?

J'aurais du gagner de l'argent. Et aurais pu acheter un item

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
