### ISSUE TITLE
[Bug]:  Couleur Launcher Urgent 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#365]
### Pseudo InGame

ChitailYtb78580  ( iWoZ_ )

### Que s'est-il passé ?

Voir Vidéo : https://youtu.be/TOXq17DCCNs

**Comment by iWoZ0** [comment]
+ Possible de voir toutes les caves avec des torches

https://www.youtube.com/watch?v=3VilWKEOLNU

**Comment by aureliancnx** [comment]
Bonjour,

Ce bug a été signalé dans une autre issue. Je clos
