### ISSUE TITLE
[Bug]: Lobby Map Flat

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#366]
### Pseudo InGame

Evx06 ( iWoZ_ ) 

### Que s'est-il passé ?

Lobby en monde superflat, Pvp Activé, grief.

Vidéo : 
https://youtu.be/woGKEnOT9nU

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
