### ISSUE TITLE
[Bug]: Vente au /shop

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#368]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

En vendant la stone au /shop, celle-ci est bien partie mais je n'ai pas reçu la money.

### Qu'aurait-il dû arriver ?

J'aurais du recevoir la money

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
