### ISSUE TITLE
[Bug]: Achat au /shop

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#369]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

En essayant d'acheter des items au /shop, celui-ci pense que j'ai 0 $, alors que j'ai 500$

### Qu'aurait-il dû arriver ?

La money aurait du être débitée et les items auraient du apparaitre dans mon inventaire.

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
