### ISSUE TITLE
[Bug]: XP mineur

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#370]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

En minant de la stone avec une pioche, je ne gagne pas d'xp mineur en étant niveau 0

### Qu'aurait-il dû arriver ?

J'aurais dû gagner 1 XP par stone minée

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
