### ISSUE TITLE
[Bug]: Problème /pay

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#371]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Impossible de payer un autre joueur via la commande /pay, le jeu pense qu'on n'a pas d'argent

### Qu'aurait-il dû arriver ?

Ma money aurait du être envoyée à la personne que j'ai /pay

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
