### ISSUE TITLE
[Bug]: Argent Métiers

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#375]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Normalement quand t-on monte d'un niveau dans un métier nous avons de l'argent, mais cela nous en donne pas à l'heure actuelle.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
