### ISSUE TITLE
[Bug]: Sneak bloqué avec certaines touches

### ISSUE THREAD

**Issue by Waazix** [Paladium-Developpement/Paladium-Issue#376]
### Pseudo InGame

Waazix19

### Que s'est-il passé ?

Si on utilise la touche "SHIFT", "CTRL" ou "RIGHT SHIFT" (et peut-être d'autres) pour le sneak, on peut l'activer mais pas le désactiver.

### Qu'aurait-il dû arriver ?

On devrait pouvoir maintenir la touche pour rester accroupi, et la lâcher pour se relever.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
