### ISSUE TITLE
[FeedBack]: Commande /derank [ Pseudo ]

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#380]
### Pseudo InGame

Siropdebanane59

### Nom de la feature

/Derank [Pseudo]

### Retour sur la Feature

Faire une commande qui permet de reset tout les perm d'un mec, pour lui enlever :
- le vanish 
- le gamemode
- et les perm 
- pour lui remettre en default [ Grade Default Joueur ]

**Comment by aureliancnx** [comment]
Bonjour,

Cette feature a été prise en compte. Cependant, je ferme pour laisser la place aux issues
