### ISSUE TITLE
[Bug]: Mauvais gains lors d'un passage de niveau

### ISSUE THREAD

**Issue by Syb3rtron** [Paladium-Developpement/Paladium-Issue#381]
### Pseudo InGame

Sybertron_

### Que s'est-il passé ?

Lorsque nous passons un niveau dans un métier, nous recevons toujours 1000$ au lieu du vrai gain normalement attribué.

### Qu'aurait-il dû arriver ?

Chaque passage de niveau devrait nous donner un gain de plus en plus gros et non toujours 1000$.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
