### ISSUE TITLE
[Bug]: Image Chargement luncher 

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#383]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

https://prnt.sc/JeiE52EqoQ08

Mettre cette image de chargement au luncher

![Render 11](https://user-images.githubusercontent.com/87950807/172053003-b85d6213-a85e-4e3d-9c7c-225c3137abb3.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
