### ISSUE TITLE
[Bug]: Crash lobby

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#384]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Il est possible de crash quand on va au lobby (kick du serveur ou via le /lobby)

### Qu'aurait-il dû arriver ?

Le jeu n'aurait pas du se fermer

### LOG

[crash-2022-06-05_18.45.24-client.txt](https://github.com/Paladium-Developpement/Paladium-Issue/files/8840364/crash-2022-06-05_18.45.24-client.txt)

**Comment by aureliancnx** [comment]
Bonjour,

Cette erreur a été signalée dans une autre issue. Je ferme donc celle-ci
