### ISSUE TITLE
[Bug]: Vanish

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#39]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Le vanish n'est plus syncro entre les serveurs et se désactive de temps à autres sans action particulière

Même chose pour le 2eme Vanish

### Qu'aurait-il dû arriver ?

Normalement il doit être syncro de partout

Même chose pour le 2eme Vanish

**Comment by aureliancnx** [comment]
Je prends

**Comment by aureliancnx** [comment]
Corrigé
