### ISSUE TITLE
[Bug]: Invitation impossible mauvaise pseudo (changement de pseudo)

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#390]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Le pseudo actuel du joueur n’est pas reconnu par le mod faction. Le joueur a du utilisé le pseudo avec la flèche rouge pour inviter le joueur dans sa faction
![Untitled (1)](https://user-images.githubusercontent.com/92928910/172068942-d3268893-fe54-414d-8d43-06b91b77fbf6.png)
![Untitled (2)](https://user-images.githubusercontent.com/92928910/172068943-02f02ab1-2fe5-44d2-aee4-321ca9cdeaaf.png)
![Untitled](https://user-images.githubusercontent.com/92928910/172068944-a5974eb2-a688-4702-9d58-c27dcc7eba51.png)

### Qu'aurait-il dû arriver ?

Le dernier pseudo être pris en compte et pas les anciens

**Comment by aureliancnx** [comment]
Corrigé
