### ISSUE TITLE
[Bug]: Pvp impossible dans certains claims

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#391]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Les chunks étaient claim par la faction Warzone. (Ils ont été unclaim mais on a eu le même problème pendant la beta et avec des factions joueurs aussi)
![Untitled (3)](https://user-images.githubusercontent.com/92928910/172068992-8d77a8dd-795e-442e-aec0-db036b873737.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
