### ISSUE TITLE
[Bug]: Faction Warzone pas power infini

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#392]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il n’y a pas de power infini pour la faction warzone
![Untitled (4)](https://user-images.githubusercontent.com/92928910/172069030-921d4bd1-baf3-4f57-ae0d-c6700665a2c4.png)

### Qu'aurait-il dû arriver ?

Comme ca
![Untitled (5)](https://user-images.githubusercontent.com/92928910/172069032-45042d5d-728b-489c-86c3-3c16154ebb0e.png)

**Comment by aureliancnx** [comment]
Corrigé mais la sauvegarde des flags est à revoir de mon côté pour éviter ce problème à nouveau
