### ISSUE TITLE
[Bug][Faction]: Pb faction synchro serveur

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#395]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

J’ai créé ma faction sur un serveur faction.
![Untitled (8)](https://user-images.githubusercontent.com/92928910/172069148-48b895e5-0426-46bb-b77d-a9b24ddeb982.png)
Le soucis, c’est que sur un autre serveur, je n’avais plus de faction et j’ai pu rejoindre une faction. Je me retrouve dans deux factions.
![Untitled (9)](https://user-images.githubusercontent.com/92928910/172069156-e089a834-65e8-4df3-aaf9-124b1e109315.png)

**Comment by Akysooo** [comment]
Quand tu es sur un serveur alors que tu es pas reconnu, tu dois te faire kick de la faction dans laquelle tu es supposé être pour pouvoir y être réinvité

**Comment by Akysooo** [comment]
J'étais sur le Soleratl, j'ai rejoint la overlord. 
Ensuite je suis allé sur le Naera où j'ai rejoint la Warzone (car j'avais le bug).
Ensuite je suis allé sur Imbali où j'avais rejoint la az0x (j'avais encore le bug). 
En retournant sur Soleratl, je me suis retrouvé de nouveau dans la wilderness (+ dans les3 factions en via le /f f)
https://prnt.sc/1Xh6zCvK-G2k
https://prnt.sc/0FOXLFRyhtGI
https://prnt.sc/sxUoTY-QLlJt
Et j'avais ca aussi dans mon tchat, je ne sais pas si c'est un pb de packet faction 
++
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 62 22 c2 a7 65 55 6e 65 20 65 72 72 65 75 72 |.b"..eUne erreur|
|00000010| 20 65 73 74 20 73 75 72 76 65 6e 75 65 20 6c 6f | est survenue lo|
|00000020| 72 73 20 64 65 20 76 6f 74 72 65 20 c2 a7 63 73 |rs de votre ..cs|
|00000030| 79 6e 63 68 72 6f 6e 69 73 61 74 69 6f 6e 20 c2 |ynchronisation .|
|00000040| a7 38 28 56 6f 74 72 65 20 64 65 6d 61 6e 64 65 |.8(Votre demande|
|00000050| 20 c3 a0 20 c3 a9 74 c3 a9 20 72 65 66 75 73 c3 | .. ..t.. refus.|
|00000060| a9 65 29 22                                     |.e)"            |
+--------+-------------------------------------------------+----------------+
[14:48:42] [Client thread/INFO]: [CHAT] §7<§aLunaria§7> §7§l[§7Joueur§7§l]§7 Dragnox: §f§fehhh
[14:48:44] [Client thread/INFO]: [CHAT] Exception Connecting:FastDecoderException : Error decoding packet class KeepAlive with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 62 22 c2 a7 65 55 6e 65 20 65 72 72 65 75 72 |.b"..eUne erreur|
|00000010| 20 65 73 74 20 73 75 72 76 65 6e 75 65 20 6c 6f | est survenue lo|
|00000020| 72 73 20 64 65 20 76 6f 74 72 65 20 c2 a7 63 73 |rs de votre ..cs|
|00000030| 79 6e 63 68 72 6f 6e 69 73 61 74 69 6f 6e 20 c2 |ynchronisation .|
|00000040| a7 38 28 56 6f 74 72 65 20 64 65 6d 61 6e 64 65 |.8(Votre demande|
|00000050| 20 c3 a0 20 c3 a9 74 c3 a9 20 72 65 66 75 73 c3 | .. ..t.. refus.|
|00000060| a9 65 29 22                                     |.e)"            |
+--------+-------------------------------------------------+----------------+
[14:48:45] [Client thread/INFO]: [CHAT] Exception Connecting:FastDecoderException : Error decoding packet class KeepAlive with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 62 22 c2 a7 65 55 6e 65 20 65 72 72 65 75 72 |.b"..eUne erreur|
|00000010| 20 65 73 74 20 73 75 72 76 65 6e 75 65 20 6c 6f | est survenue lo|
|00000020| 72 73 20 64 65 20 76 6f 74 72 65 20 c2 a7 63 73 |rs de votre ..cs|
|00000030| 79 6e 63 68 72 6f 6e 69 73 61 74 69 6f 6e 20 c2 |ynchronisation .|
|00000040| a7 38 28 56 6f 74 72 65 20 64 65 6d 61 6e 64 65 |.8(Votre demande|
|00000050| 20 c3 a0 20 c3 a9 74 c3 a9 20 72 65 66 75 73 c3 | .. ..t.. refus.|
|00000060| a9 65 29 22                                     |.e)"            |
+--------+-------------------------------------------------+----------------+
[14:48:46] [Client thread/INFO]: [CHAT] Exception Connecting:FastDecoderException : Error decoding packet class KeepAlive with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 62 22 c2 a7 65 55 6e 65 20 65 72 72 65 75 72 |.b"..eUne erreur|
|00000010| 20 65 73 74 20 73 75 72 76 65 6e 75 65 20 6c 6f | est survenue lo|
|00000020| 72 73 20 64 65 20 76 6f 74 72 65 20 c2 a7 63 73 |rs de votre ..cs|
|00000030| 79 6e 63 68 72 6f 6e 69 73 61 74 69 6f 6e 20 c2 |ynchronisation .|
|00000040| a7 38 28 56 6f 74 72 65 20 64 65 6d 61 6e 64 65 |.8(Votre demande|
|00000050| 20 c3 a0 20 c3 a9 74 c3 a9 20 72 65 66 75 73 c3 | .. ..t.. refus.|
|00000060| a9 65 29 22                                     |.e)"            |
`+--------+-------------------------------------------------+----------------+

**Comment by aureliancnx** [comment]
> J'étais sur le Soleratl, j'ai rejoint la overlord. Ensuite je suis allé sur le Naera où j'ai rejoint la Warzone (car j'avais le bug). Ensuite je suis allé sur Imbali où j'avais rejoint la az0x (j'avais encore le bug). En retournant sur Soleratl, je me suis retrouvé de nouveau dans la wilderness (+ dans les3 factions en via le /f f) https://prnt.sc/1Xh6zCvK-G2k https://prnt.sc/0FOXLFRyhtGI https://prnt.sc/sxUoTY-QLlJt

As-tu rejoins avec /f join en /f admin ou as-tu été invité ?

**Comment by Akysooo** [comment]
Avec le f admin. Mais cela ne change pas grand chose, j'aurai pu faire /f create et recréer des factions. Je n'étais pas pris en compte pas le mod faction

**Comment by Akysooo** [comment]
Personnellement je n'ai plus de problème de désynchronisation faction

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
