### ISSUE TITLE
[Bug][Faction]: Mauvais temps d’actualisation saison classement

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#396]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Les saisons classement doivent durer 28j
![Untitled (10)](https://user-images.githubusercontent.com/92928910/172069226-8bf10d85-0647-4f5a-8448-13dc50634134.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
