### ISSUE TITLE
[Bug]: Bug tptoggle

### ISSUE THREAD

**Issue by PierreLeLonie01** [Paladium-Developpement/Paladium-Issue#397]
### Pseudo InGame

PierreLeLonie

### Que s'est-il passé ?

Les joueurs avec le grade Paladin ne peuvent pas faire de commandes tpa / tpahere. Ils sont obligés de faire /tptoggle. N'ayant pas la perm en tant que Paladin, ils ne peuvent donc pas se tp. 

### Qu'aurait-il dû arriver ?

Soucis de perm ?

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
