### ISSUE TITLE
[Bug]: Joueur considéré comme inexistant

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#399]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

En essayant d'inviter un joueur dans ma faction, le jeu considère qu'il n'existe pas
![2022-06-06_09 42 20](https://user-images.githubusercontent.com/62394506/172117915-852c48fe-2df8-476d-938b-8a282ae33d1e.png)

### Qu'aurait-il dû arriver ?

Le joueur aurait dû être invité dans ma faction

**Comment by Akysooo** [comment]
Même issue que ca je pense #390

**Comment by KraemerJoe** [comment]
https://github.com/Paladium-Developpement/Paladium-Issue/issues/390#issuecomment-1147445910
