### ISSUE TITLE
[Bug]: Lags avec la Dollars Stone

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#404]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Le bug #273 est de retour sur la V8. Lors de l'utilisation de la dollars stone, le serveur lag
Clip remontrant le bug : https://clips.twitch.tv/EmpathicProductiveGerbilTooSpicy-iA7NhMv8g4Ry7XVR

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
