### ISSUE TITLE
[Bug][Faction]: Faction en double

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#406]
### Pseudo InGame

FuzeLeVrai

### Que s'est-il passé ?

J'ai cherché OverLord dans l'annuaire et 2 fois la même faction se sont affiché

![image](https://user-images.githubusercontent.com/7911589/172168589-8bbb0779-fc47-40c2-9e13-1914eb3ea3cc.png)

**Comment by Fuzay** [comment]
Je pense que c'est un bug visuel parceque quand j'ai cliqué sur le premier OverLord je suis arrivé sur Azox. Je pense qu'il a load en élément 1 la OverLoard et qu'il a rechargé par dessus la liste complète des factions (la Overlord est en 2eme position)

**Comment by aureliancnx** [comment]
Je n'ai pas réussi à reproduire le bug de mon côté. Est-ce qu'il est encore d'actualité ?

**Comment by aureliancnx** [comment]
N'ayant pas eu de nouvelles depuis + d'une semaine sur ce ticket, je le ferme. Si le cas se reproduit, l'issue sera réouverte
