### ISSUE TITLE
[Bug]: Dupli avec /home

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#407]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Un joueur duplique son stuff en se téléportant à son home. Je suis allé check il n'y avait rien de particulier, je ne comprends pas d'où ça peut venir. 

Record: https://www.youtube.com/watch?v=Vx4kXPZzudc

**Comment by dadodasyra** [comment]
Lien mort
