### ISSUE TITLE
[Bug]: Faction Instant kick 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#408]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Lorsqu'on se connecte sur un faction les joueurs se font instante kick

**Comment by iWoZ0** [comment]
Idem pour les minages

**Comment by VallouDev** [comment]
Ce bug ce produit à cause de la moula stone. Posé dans le 9e slot de l'inventaire. Qui fait kick pour "internal server error" le joueur de manière instant après avoir rejoint le serveur
