### ISSUE TITLE
[Bug]: Mauvais point de classement de base

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#411]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/172206922-3d212b2b-c3f0-4cfe-bedb-49ec4ec8c25b.png)
![image](https://user-images.githubusercontent.com/92928910/172206984-e12d86ff-a905-475c-ae06-d2b8e53ed74d.png)

**Comment by aureliancnx** [comment]
Corrigé
