### ISSUE TITLE
[FeedBack]: Modification ban list nom de faction

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#412]
### Pseudo InGame

Akyso

### Nom de la feature

Ban list nom de faction

### Retour sur la Feature

Modifier la liste et mettre ca 

fuzeIII
fuseIII
fuzelll
fuselll
fuzell
fusell
fuzellll
fusellll
fuze3
fuse3
fuzeII
fuseII
fuzeIIII
fuseIIII
fuze
fuse
LeVraiFuze
LeVraiFuse
Fuzay
lorn
lorn87
goldo
goldorak85
terrainwax
akyso
Roselynee
Neozias
Alanah
Siropdebanane59
Vahko
Apsig69
BeTa_Deimos
Zeldown
Justine
Soristos
Thibot
VexonTV
Mooded
Pala
Paladium

**Comment by aureliancnx** [comment]
Modification effectué, effectif au prochain redémarrage
