### ISSUE TITLE
[Bug]: /condense partiellement fonctionnel

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#416]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

A l'utilisations du /condense, seul le fer est condensé.
Avant utilisations :
![image](https://user-images.githubusercontent.com/43002022/172252681-8031ed72-4318-479b-87bb-7db4e98e7518.png)
Après multiples utilisations comme à la dernière version :
![image](https://user-images.githubusercontent.com/43002022/172252744-052b3213-ea24-4575-8fbe-cf863fda91f4.png)

### Qu'aurait-il dû arriver ?

Tous les minerais aurait dû être condensé.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
