### ISSUE TITLE
[Bug]: Fill d'attente

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#418]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le joueur StarF est bloqué dans la file d'attente pour soleratl alors qu'il y a seulement 50 joueurs de co dessus. 

Screen: https://cdn.discordapp.com/attachments/983485251324096596/983485330239942696/unknown.png

**Comment by KraemerJoe** [comment]
Normalement fix hier
