### ISSUE TITLE
[Bug][Faction]: Invitation gui inexistante 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#420]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/172364924-9f287888-94c3-4408-8479-5d4b016dc26e.png)
(Screen moi dans la faction qui invite mon dc)

![image](https://user-images.githubusercontent.com/92928910/172364969-5272d8d1-70c5-410b-ae7a-1090a1f0473c.png)
tchat de mon dc

![image](https://user-images.githubusercontent.com/92928910/172365018-41adc07f-4c5d-4cfb-8a5e-243be284bc6c.png)
Gui d'invitation de mon dc qui est vide

![image](https://user-images.githubusercontent.com/92928910/172365090-5c443189-4686-4a87-be88-ee8ade276d83.png)
Mais j'ai bien pu rejoindre avec la commande en jeu

**Comment by aureliancnx** [comment]
Je m’assigne

Est-ce que les deux comptes étaient connectés sur le même serveur au moment de la demande ?

**Comment by Akysooo** [comment]
Oui à littéralement  10 bloc l'un de l'autre

**Comment by aureliancnx** [comment]
Corrigé
