### ISSUE TITLE
[Bug]: Texture Glazed terracota 

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#422]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

La texture du block de light blue glazed terracota [ID=178] a la meme texture que la blue glazed terracota 
Il faut donc que la light blue est une autre texture, bien appliquer la new texture à l'id 178 (une texture de light blue glazed terracota)

Mods: Back to the future (88)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
