### ISSUE TITLE
[Bug]: /condense

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#425]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

En faisant le /condense, les minerais vanilla ont été transformés en blocs, mais pas les minerais moddés

### Qu'aurait-il dû arriver ?

Les minerais moddés auraient du être transformés en blocs

**Comment by Greenwich31** [comment]
https://youtu.be/z2KKsR1nnc0

**Comment by aureliancnx** [comment]
Bonjour

Cette issue semble être dupliquée de celle-ci : https://github.com/Paladium-Developpement/Paladium-Issue/issues/416
