### ISSUE TITLE
[Bug][Faction]: Actualisation du classement trop fréquent (<24h)

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#426]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Le classement s'actualise plusieurs fois par jour

07/06 à 11:15
![image](https://user-images.githubusercontent.com/92928910/172490657-d93f920d-a143-4773-b486-e2f4129f94de.png)

07/06 à 22:46
![image](https://user-images.githubusercontent.com/92928910/172490699-a0b797ea-137b-4674-b486-71530b45777a.png)

L'actualisation doit être tous les 24h à minuit comme le chrono en hover

**Comment by aureliancnx** [comment]
Le serveur a-t-il reboot entre temps ?

**Comment by Akysooo** [comment]
Nos serveurs n'étant pas stable très surement

**Comment by KraemerJoe** [comment]
Changement du système.
