### ISSUE TITLE
[Bug][Faction]: Classement changement de place  sans point ou trend marche pas

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#427]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Des factions ont l'icone de descente mais ils ont tous zero point. Pourquoi ils changent de position ??
![image](https://user-images.githubusercontent.com/92928910/172490854-19866e33-ab94-4e9c-bc7b-ec6bbfd9d262.png)

**Comment by aureliancnx** [comment]
Car l’ordre est défini sur le nombre de points ET sur le nom dans le cas où ils sont à égalité.

Si deux Factions ont 0 point (appelons les A et C), si la faction nommée B est créée et que le classement est mis à jour, alors si B a 0 point de gloire, B sera entre A et C. C sera une place derrière par rapport au dernier classement

**Comment by Akysooo** [comment]
Le classement étant voulu compétitif le système de classement par ordre alphabétique n'est malheureusement pas adapté. Faudrait passer en cas d'égalité sur un système ordre d'arrivé à ces points (le premier arrivé est en haut et le dernier en bas)

**Comment by aureliancnx** [comment]
La variable de date d’arrivée au nombre de gloires X définissant une position N n’est pas présente dans le système actuel d’elo. Cela va être refait pour y inclure ce edge case

**Comment by KraemerJoe** [comment]
Changement du système.
