### ISSUE TITLE
[Bug]: Home remover dans les AP

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#43]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Le home finder fait apparaitre les fantômes dans les AP, mais on ne peux pas les taper

### Qu'aurait-il dû arriver ?

On devrait pouvoir tuer les fantomes pour enlever les homes

### Serveur

Mineria

**Comment by Zeldown** [comment]
Duplicate issue of #41 closed

**Comment by Zeldown** [comment]
Après test sur une AP mineria nord en compagnie de Zazho, cela fonctionne correctement de notre côté.
