### ISSUE TITLE
[Bug][Faction]: Nombre de point de gloire donné par la quête hebdomadaire

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#430]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/172491561-70e5394f-5836-42b5-ab81-2fd9d2d9013b.png)
![image](https://user-images.githubusercontent.com/92928910/172491655-a4c0da4b-3b63-4e73-b23b-3c8f71966fb8.png)

La overlord ont validé deux fois leur quête hebdomadaire. Ils ont 181 surtout qu'ils ont perdu dans l'issue #429 

Il devrait avoir gagné 75 par quête donc 150 en tout ce qui n'est pas le cas.

**Comment by Akysooo** [comment]
Update, via un webhook fait par Zeldown, on a pu constater ca pour la faction Blackold qui a reçu plus de 75 au final. Actuellement elle a gagné 124 via les quêtes en sachant qu'il y a la perdu de l'issue #429  qui sera d'environ pour la nuit dernière de ~25, ce qui nous ferait arriver à 150 de gain.  (Aussi on a rajouté le serveur sur le webhook pour avoir plus d'info dessus dans le futur)

![image](https://user-images.githubusercontent.com/92928910/172956006-7470bfd9-3250-45ee-b4be-b35b35bc35ac.png)
![image](https://user-images.githubusercontent.com/92928910/172956023-28b4b976-89c2-4fc9-adfa-cdf0790f54e2.png)
![image](https://user-images.githubusercontent.com/92928910/172956043-bf3d1acb-87b8-4b6d-9912-0afcf5971df6.png)

**Comment by aureliancnx** [comment]
Corrigé
