### ISSUE TITLE
[Bug]: extractor incassable

### ISSUE THREAD

**Issue by Eclair93** [Paladium-Developpement/Paladium-Issue#433]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Les Extracteurs du métier d'alchimiste sont incassable.
En effet, quand ils sont a 0 durabilité. On peux toujours les utiliser sans qu'ils ne se cassent jamais et donc farm avec les mêmes extracteurs en illimité

### Qu'aurait-il dû arriver ?

Ils auraient dû se casser a 0 de durabilité

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
