### ISSUE TITLE
[Bug]: Fiole avec sève null

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#434]
### Pseudo InGame

Lykeos

### Que s'est-il passé ?

Des fioles peuvent avoir une sève comme été nul mais en ce remplissant quand même.

[https://youtu.be/Cv6pE_Fku54](url)

### Qu'aurait-il dû arriver ?

Elles aurait dû avoir une sève

**Comment by Jabsyyy** [comment]
Lorsqu'un extracteur est a zéro il fonctionne toujours, c'est à dire 0/144 on peut l'utiliser à l'infini ! 
Urgent pour à patch pour l'équilibre des métiers.
