### ISSUE TITLE
[Bug][Faction]: Pas d'auto tabulation sur les pseudos

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#435]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il n'y a pas d'auto tabulation sur les pseudos sur cette commande. Cependant c'est le cas sur la plupart (voir toutes) des commandes factions
![image](https://user-images.githubusercontent.com/92928910/172605787-ba73ce93-bfcd-4ce5-a162-4569db3d23a1.png)

**Comment by aureliancnx** [comment]
La fonctionnalité a été ajoutée !
