### ISSUE TITLE
[Bug]: Disparition cobblebreaker

### ISSUE THREAD

**Issue by Waazix** [Paladium-Developpement/Paladium-Issue#437]
### Pseudo InGame

Waazix19

### Que s'est-il passé ?

Si on shift clic de la cobble dans un cobblebreaker, on garde une cobblestone "buggée". Si on place cette cobble buggée dans un autre cobblebreaker, le cobblebreaker disparait.

Vidéo du bug: https://www.youtube.com/watch?v=8tO-vC3ehp4

### Qu'aurait-il dû arriver ?

Aucune cobble ne devrait être gardée après un shift clic (et le cobblebreaker ne devrait donc pas disparaitre)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
