### ISSUE TITLE
[Bug][Faction]: Problème message d'erreur (/f invite) pas de faction

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#438]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Quand on a pas de faction et qu'on veut inviter un joueur il n'y a pas de message disant qu'on a pas de faction mais ca 
![image](https://user-images.githubusercontent.com/92928910/172626937-28b8cd90-bc18-4b4f-991d-107e40c9494d.png)
https://paladium-work.slack.com/archives/C02KVUAED0S/p1654694084800799 (message console NullPointerException)

**Comment by aureliancnx** [comment]
As-tu effectué la commande quand tu avais le /f admin d'actif ?

**Comment by aureliancnx** [comment]
Corrigé
