### ISSUE TITLE
[Bug]: /feed /craft et autres désactivés en combat

### ISSUE THREAD

**Issue by Camouchat** [Paladium-Developpement/Paladium-Issue#44]
### Pseudo InGame

Camouchaat

### Que s'est-il passé ?

Le /feed  /craft sont désactivés en combat 

### Qu'aurait-il dû arriver ?

Il était activé et n'est plus actif suite à la dernière maintenance

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
