### ISSUE TITLE
[Bug][Faction]: Le /f admin ne donne pas les perms dans une faction

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#440]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Le /f admin ne permet pas d'avoir tous les droits dans une faction (promote, leader, gestion etc)

### Qu'aurait-il dû arriver ?

Nous devrions avoir toutes les perms avec le f admin

**Comment by aureliancnx** [comment]
Déjà signalé ici https://github.com/Paladium-Developpement/Paladium-Issue/issues/321
