### ISSUE TITLE
[Bug][Faction]: Bouton manquant blason dans le gui création de faction

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#442]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

On ne peut pas modifier le blason à la création de la faction (cliquer dessus pour l'editer)
![image](https://user-images.githubusercontent.com/92928910/172651154-91dda7d0-99ba-4ffb-8513-d27d929548f0.png)

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
