### ISSUE TITLE
[Bug][PaintWars]: Sorti de map

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#443]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

Nous pouvons sortir de la map au coordonnées 175 68 317
![Inkedunknown_LI](https://user-images.githubusercontent.com/43002022/172679778-595acd91-a009-427a-9c9e-d037d7c7b8ea.jpg)

https://youtu.be/S_mD3R5VkFY

### Qu'aurait-il dû arriver ?

Il y aurait dû avoir des blocks invisibles ou autre pour bloquer la sortie du joueur

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
