### ISSUE TITLE
[Bug]: Notification XP après limite

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#446]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

Après avoir passé la deuxième limite d'xp (250k donc après les 50%)
![image](https://user-images.githubusercontent.com/43002022/172712220-fa1dc8d4-5f81-447f-b676-e101cf294af8.png)
La notification d'xp apparait toujours avec 0 xp gagné, mais je trouve que si on ne gagne pas d'xp, il faudrait tout simplement pas afficher la notification
![image](https://user-images.githubusercontent.com/43002022/172712388-440045f9-58cc-42dd-ac63-2f85bfa99a60.png)

### Qu'aurait-il dû arriver ?

La notification n'aurait pas dû être afficher

**Comment by aureliancnx** [comment]
Corrigé
