### ISSUE TITLE
[Bug][Faction]: level up métiers et xp faction

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#452]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

J'ai passé un niveau de métier (hunter 1) mais ma faction n'a pas gagné d'xp
PS: Les serveurs n'étant pas à jour sur le git, je précise que ça s'est passé sur Luccento

### Qu'aurait-il dû arriver ?

Ma faction aurait du gagner 1000 xp

### Serveur

Mineria

### Date et heure de la production du bug

09/06/2022 ~16h50

**Comment by aureliancnx** [comment]
Bonjour

Ce bug est-il encore d'actualité lorsque vous passez un niveau ?

**Comment by Telco43** [comment]
Bonjour,

Ce bug n'est plus présent lorsque je passe un niveau de métier en faction. Cependant, je tiens à préciser que, entre temps, cela m'est arrivé en minage, et que je n'ai pas eu le temps de retester depuis.

**Comment by aureliancnx** [comment]
Problème corrigé avec l'update xp
