### ISSUE TITLE
[Bug][Faction]: Elo à 0 alors qu'il est à 505

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#455]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/172935853-61e796dc-090c-4b29-9e97-6e7aa3b83ddc.png)
La Acarnas a 505 (ce sont les points de base d'un début de saison) cependant dans la base de donné il y a marqué 0 donc comme les factions ne peuvent pas descendre en dessous de 0, il y a un problème. 

![image](https://user-images.githubusercontent.com/92928910/172936524-bbfb4e1f-01bf-4855-97cf-7d438da352fa.png)

### Serveur

Minage

### Date et heure de la production du bug

/

**Comment by aureliancnx** [comment]
Corrigé
