### ISSUE TITLE
[Bug][Faction]: Elo non ajouté à une faction

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#458]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Je pense que c'est le même problème que pour les issues #429 et #430 . Mais je préfère en refaire un au cas ou c'est le même problème.
Avec ma faction j'ai testé de compléter la quête hebdomadaire (#456 ). 3 membres de ma faction étaient chacun sur un serveur différent. 
C'est moi qui est validé sur le serveur muzdan. Mais on a rien reçu.

![image](https://user-images.githubusercontent.com/92928910/172956284-dc77b048-c606-4cce-9235-62446f4d3ee5.png)
![image](https://user-images.githubusercontent.com/92928910/172956865-97a6d562-ea8c-48a2-a7a2-4d3eeacac00e.png)
(Les 25 points de gloires que j'ai en plus sont du à l'issue #457 )

### Serveur

Muzdan

### Date et heure de la production du bug

23h54 09/06/2022

**Comment by Akysooo** [comment]
La a0zx n'a pas recu de nouveau son xp pour cette quête ci

**Comment by aureliancnx** [comment]
Corrigé pour l'elo. L'XP est en refonte.
