### ISSUE TITLE
[Bug]: Rollback customnpc

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#460]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Physali faisait une quête sur Imbali et après avoir être allée dans un minage pour revenir sur Imbali, les 2/3 dernières quêtes qu'elle avait faites se sont reset (Aucune log dans "donnés joueur" dans le menu customnpc que ce soit quête ou dialogue).

Rec: https://www.youtube.com/watch?time_continue=133&v=4oWgeCebp2w&feature=emb_logo
Screen "donnés joueur" vide: https://prnt.sc/eRWJ3TaMBrZn
Le 09/06/2022

**Comment by aureliancnx** [comment]
Bonjour,

Le bug a-t-il pu être reproduit depuis ?

Cordialement,

**Comment by Grandpou** [comment]
Non, je n'ai pas eu de report concernant ce problème suite au rec et je n'ai pas essayé de le reproduire.
