### ISSUE TITLE
[Bug]: Bug de duplication : métier mineur

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#461]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

mp Camouchat pour détails et vidéo

### Serveur

Global

### Date et heure de la production du bug

10/06 18:47

**Comment by aureliancnx** [comment]
Bonjour,

Ceci ne semble pas être un bug du plugin Faction.
