### ISSUE TITLE
[Bug][Faction]: Bouton kick caché popup info membre

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#464]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/173135727-9351c85e-9a68-44e0-88aa-7f4133ea6f04.png)
Le bouton kick est caché par le bouton retour

### Qu'aurait-il dû arriver ?

![image](https://user-images.githubusercontent.com/92928910/173136601-39b54597-2991-4232-8e6f-80cbebcddf18.png)
Faudrait le mettre ici ( carré orange)

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
