### ISSUE TITLE
[Bug][Faction]: Changement catégorie de grade sur grade de base 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#466]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/173137500-b8137903-5281-4099-aa34-6bec2c8bcb21.png)
Lorsque l'on edit un grade de base (ici membre), ca catégorie de grade change aussi (ne le fait pas avec un grade créé)

(Créé en carrote puis edit en carrotes)
![image](https://user-images.githubusercontent.com/92928910/173137677-a9fbf6aa-bd51-4c9c-b2d1-6a12dd751a47.png)

### Serveur

Muzdan

### Date et heure de la production du bug

21:34 10/06

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour pour les futures factions créées
