### ISSUE TITLE
[Bug][Faction]: Grade inconnu après avoir renommé un grade 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#467]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il n'est pas possible d'edit deux fois un grade. Quand le grade est créé (ou de base), on peut le modifier. Ensuite on ne peut pas le remodifier car le grade n'existe pas.

![image](https://user-images.githubusercontent.com/92928910/173138154-c82fa0ed-aa37-445c-8ee0-950f42352976.png)
Grade créé en Carotte puis renommé en Carottes  

Lorsque l'on veut le renommer une 2ème fois. (Marche aussi avec les grades de bases). J'ai attendu 5min sur le serveur au cas ou c'était un soucis de cache
![image](https://user-images.githubusercontent.com/92928910/173138253-22fec375-868e-4eab-8f1a-b1a457d5cdb5.png)

### Serveur

Muzdan

### Date et heure de la production du bug

21:34 10/06

**Comment by Akysooo** [comment]
![image](https://user-images.githubusercontent.com/92928910/173138802-a3671567-53d1-47ab-9b8b-a97928c2052e.png)

**Comment by Akysooo** [comment]
Cependant dans le /f f mais gui, c'est le grade non renommé qui est marqué
![image](https://user-images.githubusercontent.com/92928910/173140260-35447555-2a47-492d-9fb1-af891ba906e9.png)

**Comment by aureliancnx** [comment]
Fix
