### ISSUE TITLE
[Bug][Faction]: Erreur /f rank v/view

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#468]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/173138516-46771074-bccb-4175-81d1-a9a0baad2a87.png)

### Serveur

Muzdan

### Date et heure de la production du bug

21:41 10/06

**Comment by aureliancnx** [comment]
Quand tu passes ta souris sur le message, tu devrais voir apparaître une erreur dans le hover, peux-tu me l'envoyer ?

**Comment by aureliancnx** [comment]
Corrigé au prochain redémarrage
