### ISSUE TITLE
[Bug][Faction]: Serpent Invisible 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#471]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Plusieurs joueurs meurent dans la nature à cause de serpent invisible 

### Serveur

Global

### Date et heure de la production du bug

10h

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
