### ISSUE TITLE
[Bug][Launcher]: Problèmes sur le slider de choix de mémoire RAM

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#474]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Le slider de choix de mémoire RAM allouée au jeu sur le launcher contient différents problèmes : 

- Le maximum peut être mis en dessous du minimum
![image](https://user-images.githubusercontent.com/5176500/173188241-4fd79ee3-ad2f-4498-8022-77aa82492232.png)
- Lorsque les paramètres sont fermés et rouverts en ayant le maximum au dessous du minimum, un bug d'affichage se produit : La sélection du minimum se décale à gauche du slider
- La valeur du choix de RAM est signée
![image](https://user-images.githubusercontent.com/5176500/173188291-12a09605-379b-4085-b6db-2ca3aa4c0c64.png)

**Comment by KraemerJoe** [comment]
Merci du report, ce problème avait été corrigé.
