### ISSUE TITLE
[Bug]: Achat cobble 0,00000000000003 admin shop

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#476]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lorsque l'on vend beaucoup de cobble, cela ne le vend pas à 0,1 mais 0,1000000[...]1
Ce qui fait que ca affiche ,000000000[...]3
![image](https://user-images.githubusercontent.com/92928910/173196198-3d7f615b-9ebf-4e2a-b94e-268b69d4af5c.png)

**Comment by aureliancnx** [comment]
Corrigé
