### ISSUE TITLE
[Bug]: Affichage ah

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#478]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le joueur EverydayGecko41 ne voit rien dans son ah depuis hier soir, il dit qu'il n'a touché à aucun paramètre de tri etc
L'argent du joueur de s'affiche pas non plus.
Cela ce produit sur tous les serveurs d'après ces dires.

Screen: https://image.noelshack.com/fichiers/2022/23/6/1654983443-capture-d-ecran-2022-06-11-233659.png

**Comment by KraemerJoe** [comment]
Normalement corrigé avec les mises à jour des thread pools
