### ISSUE TITLE
[Bug][Faction]: /f sethome en dehors des claims

### ISSUE THREAD

**Issue by VallouDev** [Paladium-Developpement/Paladium-Issue#483]
### Pseudo InGame

Switch___

### Que s'est-il passé ?

Le joueur peut /f sethome en dehors de ses claims.

Rec : https://www.youtube.com/watch?v=upr8m2KpVMo

### Qu'aurait-il dû arriver ?

Il aurait eu un message d'erreur 

### Serveur

Global

### Date et heure de la production du bug

12/06/2022 17h30

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
