### ISSUE TITLE
[Bug]: baltop

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#488]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le baltop ne fonctionne pas. Cela nous dit que le classement va se créer mais rien ne se passe même si on attend et retape la commande plus tard. 

Screen: https://prnt.sc/jnJouBNM_jke

**Comment by KraemerJoe** [comment]
Duplicata: https://github.com/Paladium-Developpement/Paladium-Issue/issues/510
