### ISSUE TITLE
[Bug][Faction]: GUI Quête n'update pad l'inventaire

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#489]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

Le container de l'inventaire dans le GUI pour déposer les items de quête ne s'update pas (par exemple si on récupère un item en étant dans le GUI). Il faut le fermer et le rouvrir pour que ça s'actualise (du coup on peut pas utiliser la technique d'avoir les items à nos pieds pour déposer les items dans le truc de quête)

### Serveur

Soleratl

### Date et heure de la production du bug

14/06 12:28

**Comment by KraemerJoe** [comment]
Corrigé via update Apollon
