### ISSUE TITLE
[Bug][Faction]: GUI Permissions

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#491]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/43002022/173612857-16df7b94-3bf8-4eae-b390-a42bf1fffc3d.png)
Il manque un système de scroll dans l'interface des permissions sur la partie Faction en Paix

### Qu'aurait-il dû arriver ?

L'affichage aurait dû avoir un scroll menu

### Serveur

Keltis

### Date et heure de la production du bug

17:12 14/06/2022

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
