### ISSUE TITLE
[Bug][Faction]: Claim infini?

### ISSUE THREAD

**Issue by VallouDev** [Paladium-Developpement/Paladium-Issue#492]
### Pseudo InGame

ViqZo

### Que s'est-il passé ?

Lorsque sa faction à unclaim un territoire, le claim reste sur le /fmap, mais pas sur la faction et reste effectif, il peut donc claim à l'infini
![2022-06-15_16 48 54](https://user-images.githubusercontent.com/98038431/173858185-96e2912a-7f9a-4cf6-96ad-785042b62340.png)

### Qu'aurait-il dû arriver ?

Les claims auraient du être enlévés

### Serveur

Keltis

### Date et heure de la production du bug

16h45 15/06/2022

**Comment by aureliancnx** [comment]
Lorsque tu unclaim, que dit la commande /f access v
?

**Comment by aureliancnx** [comment]
N'ayant pas eu d'informations supplémentaires et des correctifs étant passés pour les claims, je clos ce ticket pour le moment.

Des tests plus approfondis seront réalisés pour régler les derniers détails avec les claims avant la réouverture.
