### ISSUE TITLE
[Bug]: Market : Clear lors de l'expiration d'un item

### ISSUE THREAD

**Issue by VallouDev** [Paladium-Developpement/Paladium-Issue#493]
### Pseudo InGame

Vallou_

### Que s'est-il passé ?

Lorsqu'un item est expiré, celui-ci clear et disparait à tout jamais, il n'est jamais reçu.

### Qu'aurait-il dû arriver ?

Je devrai recevoir mon item car la date limite est dépassée

**Comment by KraemerJoe** [comment]
./market recup ?

**Comment by KraemerJoe** [comment]
Testé in game,fonctionnel
