### ISSUE TITLE
[Bug]: Dollars Stone Clear Money

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#495]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Quand on utilise la Dollars Stone nous avons un clear de money. Plusieurs joueurs sont venu ts et chaque fois ils utilisaient la Dollars Stone et ils étaient clear money.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
