### ISSUE TITLE
[Bug][Métiers]: XP Farmer blé

### ISSUE THREAD

**Issue by Waazix** [Paladium-Developpement/Paladium-Issue#496]
### Pseudo InGame

Waazix19

### Que s'est-il passé ?

Certains joueurs ne gagnent aucun XP farmer à certains endroits mais à d'autres oui.
Par exemple, un joueur en gagne sur deux étages de sa farm mais pas les autres.

### Qu'aurait-il dû arriver ?

Ils auraient dû gagner l'XP correspondant à leur niveau.

**Comment by Zeldown** [comment]
Hello, aurais-tu un rec stp ? 😄 

Merci 🚀

**Comment by Waazix** [comment]
J'en ai pas mais si un joueur report à nouveau le bug je le le ferai.

**Comment by Lorn87** [comment]
fix
