### ISSUE TITLE
[Bug][Faction]: /f levels affichage "faux"

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#499]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/174272064-dbd2a380-274d-4688-ac5a-45c1c418857e.png)
Il faudrait passer comme dans le gui avec un retour à zero à chaque level et réduire le max à juste ce qu'il faut pour passer au niveau suivant

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by KraemerJoe** [comment]
Fix avec la refonte
