### ISSUE TITLE
[Bug][Faction]: Xp max gui faux

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#500]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/174272319-febb179d-1e48-416c-9a24-6e715cd9e7a5.png)
L'xp max affiché est clui cumulé depuis le niveau 10 alors qu'il faudrait marqué juste l'xp nécessaire pour passer au niveau suivant. (ici 704 926)

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by KraemerJoe** [comment]
Fix avec la refonte.

**Comment by Akysooo** [comment]
![image](https://user-images.githubusercontent.com/92928910/175041090-2c6cbaf5-615b-44c8-8969-2d3a0f0c9487.png)
Pas fix il faut normalement 983 062 xp pour passer au lvl 16

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
