### ISSUE TITLE
[Bug]: Bug Plate après transformation

### ISSUE THREAD

**Issue by PetitBiscuit74** [Paladium-Developpement/Paladium-Issue#501]
### Pseudo InGame

Saiichiro974

### Que s'est-il passé ?

Une fois la plate crafter avec des enchantements elle devient irrécupérable au sol et ou dans un GUI type coffre, hopper ..... , même par une personne op 
Nous n'avons malheureusement pas pu record sur le moment 
Serveur Muzdan

### Qu'aurait-il dû arriver ?

La plate aurait du être récupérer

**Comment by Jabsyyy** [comment]
Voici un rec reçu d'un joueur qui a eu plusieurs fois le soucis 

https://youtu.be/AZjemINp58I?t=232 

sanshessone
