### ISSUE TITLE
[Bug]: Flag spell

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#504]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le flag "spell" n'existe pas sur Manashino (peut-être d'autres serveurs).

**Comment by Akysooo** [comment]
![image](https://user-images.githubusercontent.com/92928910/174787842-3c6c10b5-2711-427d-8038-4121c5f35299.png)

**Comment by Akysooo** [comment]
Il existe sur manashino
