### ISSUE TITLE
[Bug]: Usebug tp couche 256

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#508]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Lorsqu'un joueur se trouve à la couche maximale et saute du bloc, il se fait tp en dessous de la ou il se trouve, traversant une couche d'obsidienne.
Le joueur me reportant cela est embeté puisque cela permettrait de rentrer dans sa base claim très facilement pour les enemy

Nom du joueur : theo13
Serveur base : Muzdan
Coordonnées : -27816 / 250 / -24760

rec du soucis : 
https://www.youtube.com/watch?v=jmQ1RKMSEIU

Pov d'un autre joueur ne possédant pas de home en dessous mais se fait tout de même tp à la même position : 
https://www.youtube.com/watch?v=zox7bJ8u9Yo

**Comment by Zeldown** [comment]
❌ C'est une sécurité de l'ANC, cependant ca ne permet pas à un joueur de rentrer dans sa base.
