### ISSUE TITLE
[Bug]: MAJ nouveaux serveurs faction dans bug report

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#509]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Mettre à jour la liste des nouveaux serveurs factions quand on fait un report de bug sur le GitHub, il s'agit encore des anciens sur ces tickets

**Comment by aureliancnx** [comment]
Corrigé merci du signalement
