### ISSUE TITLE
[Bug]:Harpagophytum Clear 

### ISSUE THREAD

**Issue by MrKittenxs** [Paladium-Developpement/Paladium-Issue#511]
### Pseudo InGame

Mr_Kittenxs

### Que s'est-il passé ?

Lors du get de fleur dans le chaudron , l'Harpago ce clear 

### Serveur

Muzdan

### Date et heure de la production du bug

19/06 vers minuit

**Comment by aureliancnx** [comment]
Bonjour,

Ce n'est pas un bug du plugin Faction.

**Comment by MrKittenxs** [comment]
Bonjour , D'accord Désolé
