### ISSUE TITLE
[Bug][Faction]: Kick Coffre Zone Claim

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#513]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Pour tous les joueurs ayant une zone claims, Ils ne peuvent plus utiliser leurs coffres. Chaque fois qu'ils souhaitent ouvrir un coffre ils sont Kick directement du serveur faction.

### Serveur

Global

### Date et heure de la production du bug

09h

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
