### ISSUE TITLE
[Bug][Market]: Abus avec les '!' et espaces

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#514]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/174777959-9c46f576-3e39-46f3-8be0-c771723bad57.png)
![image](https://user-images.githubusercontent.com/92928910/174778031-dd3f2332-ca51-4ede-8271-08c7095dfc99.png)

Les joueurs s'amusent à faire ca pour être premier en ordre alphabétique.

### Qu'aurait-il dû arriver ?

Il faudrait bloquer la possibilité de vendre un item commençant par un espace et qui contient un ! 
Interdire aussi de mettre en vente un item qui a plus de (nombre de caractère de l'item/4) d'espace

**Comment by KraemerJoe** [comment]
Corrigé
