### ISSUE TITLE
[Bug][Faction]: Gui quête hebdo texte décalage & xp

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#515]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/174779928-66302d61-e5c5-418d-9c0e-5f63eecc567f.png)
Le texte position n'est pas centré dans le carré et les pts doivent être de l'xp

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
