### ISSUE TITLE
[Bug][Faction]: Certaines factions sont à 0 elo et ne sont pas classées

### ISSUE THREAD

**Issue by Zeldown** [Paladium-Developpement/Paladium-Issue#517]
### Pseudo InGame

Zeldown

### Que s'est-il passé ?

Certaines factions sont à 0 d'elo et position 0

![image](https://user-images.githubusercontent.com/42982613/174910759-d1708341-52db-4cee-a263-0cc17cd7d2d1.png)

### Serveur

Global

### Date et heure de la production du bug

22/06/2022 01:03

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour
