### ISSUE TITLE
[Bug][Faction]: Classement bug gain/perte place 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#518]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il n'y a pas marqué le nombre de place que les factions ont gagné ou perdu 
![image](https://user-images.githubusercontent.com/92928910/174912572-1eda1f33-f56c-424c-b269-cefbae98fd5d.png)
![image](https://user-images.githubusercontent.com/92928910/174912580-cea40ff1-2052-47bc-9599-1f7afc060394.png)

### Serveur

Global

### Date et heure de la production du bug

22/06/2022 01h24

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour
