### ISSUE TITLE
[Bug][Faction]: Classement faction non affiché

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#519]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/174912690-e11b467f-075f-4821-af8d-4c9749143ba2.png)
![image](https://user-images.githubusercontent.com/92928910/174912701-b0ff5fb7-1130-4562-ba27-d454aadde72e.png)
![image](https://user-images.githubusercontent.com/92928910/174912832-d560788e-910d-47b9-ac65-3807f4e65091.png)

Aucun joueur de la faction LaMeute est co donc ils ne sont pas dans le classement alors qu'ils sont normalement 2ème

### Serveur

Soleratl

### Date et heure de la production du bug

22/06/2022 01h25

**Comment by aureliancnx** [comment]
Corrigé à la future mise à jour
