### ISSUE TITLE
[Bug]: Disparition minerai du crusher si extrait via hopper

### ISSUE THREAD

**Issue by ReyFoxPala** [Paladium-Developpement/Paladium-Issue#52]
Lorsque l'on extrait les minerais d'un crusher via un hopper, les minerais passent de 15 a seulement 1 

vidéo :  https://youtu.be/ODRpG6aeMl0

**Comment by aureliancnx** [comment]
Bonjour,

Le bug est-il toujours d'actualité ?

Cordialement,

**Comment by Zeldown** [comment]
:x: La vidéo n'étant plus valide et étant dans l'incapacité de reproduire le bug, je ferme le ticket.
