### ISSUE TITLE
[Bug][Faction]: Elo faction non actualisé directement

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#520]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/174913140-51fad5bd-1b53-46de-ab30-1882b753599f.png)
![image](https://user-images.githubusercontent.com/92928910/174913162-2f37ad58-0488-4709-95cd-a7f435e2b359.png)

Le 455 sur le 2ème screen devrait être le même que l'elo en temps réel du screen 1

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour
