### ISSUE TITLE
[Bug][Faction]: /f invite joueur ayant changé de pseudo

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#522]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Un joueur a changé de pseudo hier soir et ne peut plus être invité dans une faction. Cela met l'erreur: Le joueur "xxx" n'existe pas.
Pseudo du joueur: BlazyBlazou
Ancien pseudo: Vasthisar

### Serveur

Naera

### Date et heure de la production du bug

Tentative faite sur le Naera à 17h05 le 22/06/2022

**Comment by aureliancnx** [comment]
Corrigé
