### ISSUE TITLE
[Bug][Faction]: Claim de faction

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#525]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Une joueur est venu me report qu'il ne peux pas claim de chunck dans ca faction ca lui met le message "vous ne pouvez claim des chunck non lié" jusque la aucun soucis sauf que le seul chunck claim de ca faction il ne sais pas où il est, la commande unclaim all ne fonctionne pas, et peux importe le serveur où il va il ne peux pas claim alors qu'il n'à que 1 chuck de claim donc normalement 1 seul serveur avec un claim, et peux importe le serveur où on ce situe le message d'erreur est le même.

J'ai testé en op et je n'arrive moi même pas à claim et à unclaim all

### Qu'aurait-il dû arriver ?

Claim sur un serveur sans claim, unclaim all qui unclaim tout les chunck claim

### Serveur

Global

### Date et heure de la production du bug

23/06/2022 14h14

**Comment by Zazho** [comment]
@aureliancnx

**Comment by Zazho** [comment]
Alors j'ai un autre report exactement identique, 
la faction JustDream souhaite claim sur le serveur muzdan un claim en 5058/3/7286, ca dit "impossible claim non lié", avec le claimview je remarque 6 claim, je m'y tp, rien sur muzdan, ils sont tous sur untaa, je peux claim sur muzdan les chunck collé au claim d'untaa, mais je ne peux claim les chucnk qui ne sont pas lié, c'est 2 serveur différent mais les claim sont pris en compte, pseudo des joueurs: elKingnathan et Hadrien67

**Comment by aureliancnx** [comment]
Les claims non liés sont corrigés.
