### ISSUE TITLE
[Bug][Faction]: Vente ap manque historique argent

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#526]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

J'ai revendu mon ap en mode rapide, il faudrait mettre une log dans l'historique de l'ap
Ici +350 000$ par Vente AP sans icone (pour l'instant). Il faudrait aussi que ca marche pour la vente libre (entre joueurs)

![image](https://user-images.githubusercontent.com/92928910/175328674-92812fe1-bc15-426c-a713-29899f0844b3.png)

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
