### ISSUE TITLE
[Bug][Faction]: Ajout d'hover sur l'historique de banque

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#527]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il faudrait en hover marquer, le type de transaction 
![image](https://user-images.githubusercontent.com/92928910/175329755-cb99171d-483a-4ca8-9a5e-06ce53999ac9.png)
Par exemple flèche rouge = achat avant poste
Flèche bleu = ajout d'argent

Type de transaction :
- Retrait
- Ajout
- Achat avant poste
- Achat base claim controller
- Achat Parcelle
- Achat hôtel de ville
- Achat banque de village
- Achat marché
- Achat office du tourisme
- Location maison de faction
- Attaque de village

Pour toutes les transactions non faites par un joueur (par ex vente d'un ap) ne rien mettre

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by Zeldown** [comment]
@KraemerJoe Je m'occupe de rajouter la partie visuelle, tu pourras t'y lier dans GuiFactionBank.java

**Comment by KraemerJoe** [comment]
Réalisé par @Zeldown et adapté via l'API.
