### ISSUE TITLE
[Bug][Faction]: Faction acheteuse ap non claim

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#529]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

L'ap n'est pas claim par la faction qui achète
https://youtu.be/sUm8mAjOQDA

### Serveur

Global

### Date et heure de la production du bug

23/06 ~17h20

**Comment by aureliancnx** [comment]
Corrigé !
