### ISSUE TITLE
[Bug][Faction]: Non actualisation du panneau après achat ap

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#530]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Après avoir acheter un ap, le panneau ne se met pas à jour automatiquement (il faut mettre en vente puis enlever pour qu'il le fasse)
https://youtu.be/sUm8mAjOQDA

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by aureliancnx** [comment]
Corrigé !
