### ISSUE TITLE
[Bug][Faction]: Actualisation panneau après tentative d'achat sans lvl

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#531]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lorsqu'un ap est mis en vente par un autre joueur et qu'on veut l'acheter sans avoir le lvl de faction, le panneau se met à jour
https://youtu.be/26LKbt7j4wY

### Serveur

Global

### Date et heure de la production du bug

/

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour !
