### ISSUE TITLE
[Bug][Market]: Problème de mise en avant

### ISSUE THREAD

**Issue by Eclair93** [Paladium-Developpement/Paladium-Issue#532]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Sur le market, quand on y met quelque chose. Nous avons la possibilité de les mettre en avant avec une somme qui est calculée sur la somme totale de la vente de base.

Si on met en avant pour 1 Million en plus par exemple 10 stacks de bottle Farmer. Il suffit qu'a la fin quand il en reste une. On l'enlève du Market et ça nous rend la totalité de la somme mise pour le mettre en avant sachant qu'on en a profiter pendant toute la vente.

Ce qui fait que les mises en avant sont gratuite et que beaucoup de joueurs profitent de cela

**Comment by KraemerJoe** [comment]
https://github.com/Paladium-Developpement/Palamod/pull/810
