### ISSUE TITLE
[Bug]: Wither 

### ISSUE THREAD

**Issue by Eclair93** [Paladium-Developpement/Paladium-Issue#533]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Le Wither qui est censé casser sur 4 blocs de haut casse actuellement même en dessous de lui. 
Ce qui fait que les bases bedrock et environ toutes les bases sont pillables très facilement

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
