### ISSUE TITLE
[Bug][Faction]: Pose base claim controller

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#535]
### Pseudo InGame

Greensandwich_

### Que s'est-il passé ?

Lorsqu'on pose un base claim controller dans une zone "valide" on a l'erreur : "baseclaimcontroller.place.error.onearound" 
J'ai bien vérifier qu'il n'y en a pas dans les alentours

https://youtu.be/UEswav7QV48

### Serveur

Untaa

### Date et heure de la production du bug

14h20 24/06/2022

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
