### ISSUE TITLE
[Bug]: Craft compte double pour le palapass

### ISSUE THREAD

**Issue by Waazix** [Paladium-Developpement/Paladium-Issue#5351]
### Pseudo InGame

Waazix19

### Que s'est-il passé ?

Quand on a la quête "Musicien en herbe" (crafter 5 jukebox), si on craft les jukebox un par un sans shift click, la quête progresse normalement. Mais si on shift+click pour récupérer les jukebox, alors ils comptent double donc on peut valider la quête en craftant seulement 3 jukebox (voir rec)
Le bug est surement possible avec d'autres quêtes.

### Rec

https://youtu.be/NQgNeJuy4tc

### Qu'aurait-il dû arriver ?

Les crafts devraient compter une seule fois.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
