### ISSUE TITLE
[Bug]: Lucky block

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#5352]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

On ne devrait pas pouvoir relancer son lucky pass (ALT + F4)

### Rec

https://youtu.be/ij22ye775YY

### Qu'aurait-il dû arriver ?

opn ne devrait avoir qu'un seul lancé de lucky pass

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
