### ISSUE TITLE
[Bug]: Event de LB en paladium dans les LB de juin

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5353]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

L'evenement Consolation peut drop dans les LB de Juin alors que c'est un event de LB en Paladium

### Rec

https://www.youtube.com/watch?v=lhlFTzpjwBk

### Qu'aurait-il dû arriver ?

il ne devrait pas drop. Est-ce qu'il ne remplacerait pas un evenement de juin ? (si oui, merci de me dire lequel)

### Serveur

None

**Comment by roselyneelavraie** [comment]
On retrouve aussi l'event Consolation dans les LB de novembre 
https://www.youtube.com/watch?v=uw1sRAMLOME&ab_channel=Soonexe

**Comment by Zeldown** [comment]
❌ L'event consolation n'est pas un event propre à un luckyblock, il survient après bcp d'event négatif pour "consoler".

**Comment by roselyneelavraie** [comment]
Ah ok merci je ne savais pas
