### ISSUE TITLE
[Bug]: POG Autosmelt - pas d'xp de métier

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5356]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Lorsqu'on utilise une POG améliorée AUTO SMELT, les minerais fondus ne rapportent pas d'xp alors qu'ils devraient, logiquement.

### Rec

https://youtu.be/_1_4I8TH4Lg

### Qu'aurait-il dû arriver ?

On devrait recevoir l'xp

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
