### ISSUE TITLE
[Bug]: Banque de faction - item et argent clear

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5358]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Il arrive que l'argent ou les items contenus dans la banque de faction/le coffre de faction soient clear lorsqu'ils sont retirés par les joueurs. 

Exemple pour le coffre : 
https://www.youtube.com/watch?v=lG-KCHZF7Vc

Exemple pour l'argent : 
https://www.youtube.com/watch?v=zbyA2Qjdw4s

### Rec

voir au dessus

### Qu'aurait-il dû arriver ?

ça ne devrait pas clear

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé.

Cordialement,
