### ISSUE TITLE
[Bug]: Bug ah 

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#5359]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

Quand on ouvre le ah il n'y a que 5 à 8 items d'afficher 

### Rec

https://youtu.be/TGT8WE4WWGM

### Qu'aurait-il dû arriver ?

On devrait avoir beaucoup plus d'items d'affichés

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
