### ISSUE TITLE
[Bug]: [Bug][Faction]: QDF - Les items disparaissent

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5363]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Lorsqu'on veut donner des items pour la quête de faction, ils ne sont pas pris en compte pour une grande majorité. 

Ici deux vidéos : 

540 000 packed ice placées et seulement 15 000 environ prises en compte
https://www.youtube.com/watch?v=7m3r1c2fv5Q

2 000 packed ice placées et seulement 512 prises en compte
https://www.youtube.com/watch?v=X19B-f4eooY

A noter aussi qu'une fois les items déposés, le chargement du GUI de QDF est très long et que si c'est une trop grosse quantité déposée, ça peut créer des bugs/lags sur le serveur.

### Rec

voir ci dessus

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
