### ISSUE TITLE
[Bug][Faction]: BUG QDF : depos en masse impossible 

### ISSUE THREAD

**Issue by Missbamby** [Paladium-Developpement/Paladium-Issue#5364]
### Pseudo InGame

Miss_bamby

### Que s'est-il passé ?

Dès que l'ont dépose la qdf dans l'interface une grosse partit n'est pas comptabiliser, et est clear de notre inventaire. 

### Rec

https://www.youtube.com/watch?v=WAwqr8dW6lk

### Qu'aurait-il dû arriver ?

Tout les item aurais du etre comptabiliser dans l'interface 

### Serveur

Global

### Date et heure de la production du bug

05/11/2024 vers 10h30/11h

### Bug du plugin Faction

- [x] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
