### ISSUE TITLE
[Bug]: Market - Mise en avant faite presque en même temps

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5365]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Il y a eu un problème, mais je ne sais pas si c'est un cas isolé ou si ça peut arriver de nouveau, dans le doute, je le mets ici. 

Trois joueurs ont mis en avant pour le même montant un objet à vendre. Le problème, c'est que deux d'entre eux ont bien payé la mise en avant, mais n'ont pas vu leur item mis en avant. Ils ont chacun fait la manipulation dans un intervalle de temps court. Je ne sais pas s'ils avaient le market ouvert en même temps.

Je n'ai pas mis les logs, mais j'ai les liens si besoin.

SayzKen0 - 19h06
Leboniencli1 - 19h08
xeercion - 19h11

Le rec ci-joint est celui de xeercion.

### Rec

https://www.youtube.com/shorts/-z06swxSgVU

### Serveur

None

**Comment by AugmaTV** [comment]
Bug très probablement du a des problèmes avec l'infra ce soir la
