### ISSUE TITLE
[Bug]: Autocrafter - craft de l'obsidienne anti aggro + dynamite

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5367]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Lorsque le craft de l'anti aggro est lancé dans l'autocrafter, cela ne donne qu'une obsidienne alors qu'il faudrait en récupérer 8.

https://github.com/user-attachments/assets/c629a05b-b096-468b-9526-4e988889f5ef

De plus, le craft de la dynamite ne se fait pas.

### Rec

ci dessus

### Qu'aurait-il dû arriver ?

il faut en récupérer 8

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
