### ISSUE TITLE
[Bug]: Dancarok - Au passage au niveau 100, il retombe à un niveau plus bas

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5368]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Lorsque le dancarok passe au niveau 100, il repasse presque aussitôt à un niveau inférieur.

Je ne sais pas si les tedarok et ravirok sont concernés par le bug, mais peut-être que c'est le cas.

Rec : 
0:01 : le dancarok est au niveau 99, très proche du niveau 100
3:08 : le dancarok repasse niveau 54

### Rec

https://www.youtube.com/watch?v=55xE9G6mYjU

### Qu'aurait-il dû arriver ?

Le Dancarok devrait resté niveau 100. 

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
