### ISSUE TITLE
[Bug]: Bouleau des rivières - la pousse saute et disparaît sous l'angelic

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5369]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Comme le bug de la dernière fois, la pousse saute au contact de l'eau, ce qui ne devrait pas arriver. Pire, avec la modification récente, la pousse de bouleau des rivières ne drop pas et est perdue alors que le joueur devrait pouvoir la récupérer. Cela empêche donc totalement le craft de la colle.

https://github.com/user-attachments/assets/0668793e-47e0-4bdb-916b-057b0cd9f978

### Rec

ci dessus

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
