### ISSUE TITLE
[Bug]: boutique IG

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#5370]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

Quand j'ouvre la boutique IG je crash pour revenir directement au lobby

### Rec

https://youtu.be/s8xXhUVC4Wo

### Qu'aurait-il dû arriver ?

Je devrait voir les grade disponible et autre achat IG

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
