### ISSUE TITLE
[Bug]: /condense en Minage

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#5372]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on utilise le /condense en minage , les id ne sont pas les bons. L'améthyste donne des plantes et on peut /condense des baits. (Ça se produit uniquement avec les minerais moddées, les minerais vanilla sont good)

### Rec

https://youtu.be/8wyU_xVp4J4

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
