### ISSUE TITLE
[Bug]: Palapass - Quêtes mensuelles

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5374]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Certaines quêtes ne se mettent pas à jour correctement et ne se valident pas (entre l'enregistrement et le traitement, il y a eu 24/48h et ça n'a pas changé)

### Rec

https://www.youtube.com/watch?v=0QVU-lKGdGw

### Qu'aurait-il dû arriver ?

Les quêtes devraient se mettre à jour et être validées

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Le problème est-il toujours d'actualité avec les quêtes Palapass de ce mois-ci ?
