### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by L0wBly** [Paladium-Developpement/Paladium-Issue#5377]
### Pseudo InGame

L0wBly

### Que s'est-il passé ?

Bug de dupli avec tous les items qui sont dans le rec. Je ne sais pas comment il fonctionne 

### Rec

https://youtu.be/2OtYrtxpOko

### Qu'aurait-il dû arriver ?

L'auto crafter ne devrait plus pouvoir crafter quand il n'y a plus de ressources

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
