### ISSUE TITLE
[Bug]: Boss - notification 

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5384]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

La notification de fin annonce toujours tobalt, peu importe le boss qui a spawn. Cette fois, par exemple, c'était Arachna. 
![image](https://github.com/user-attachments/assets/13eaf587-e53e-4d06-a1f5-81a33efc6625)

### Rec

gpo

### Qu'aurait-il dû arriver ?

Il faudrait afficher le bon nom

### Serveur

None

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
