### ISSUE TITLE
[Bug]: Calendrier de l'avent non-fonctionnel pour certains joueurs

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5385]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Le calendrier ne fonctionne pas pour tout le monde et le message suivant s'affiche :

![image](https://github.com/user-attachments/assets/e53c5a07-6dfa-44b0-9af5-5e6452eef866)

### Rec

gpo

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
