### ISSUE TITLE
[Bug]: QDF - Problème de quota

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5387]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Ici, on voit que la BTP a "fini" la quête, pourtant, elle n'a pas rempli le quota et n'a reçu aucune récompense. Le TOP est pourtant bien indiqué, mais c'est le même problème partout. Ils ne peuvent plus mettre d'item non plus. Le quota semble se bloquer à partir de 350 000 objets.

Backtoprime
![image](https://github.com/user-attachments/assets/b516491c-483a-4cdc-86d8-d4d134a138aa)

Wilderhess
![image](https://github.com/user-attachments/assets/81aa3205-975d-4749-afa9-17429818dcbe)

Blackprime
![image](https://github.com/user-attachments/assets/6c9d1e40-d157-4e6f-9275-48a5839a824f)

### Rec

gpo

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
