### ISSUE TITLE
[Bug]: Points de gloire - Problème de calcul des malus d'alliance/truce

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5388]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Normalement, le fait d'être en alliance ou truce avec une faction cause la perte de 3 points par jour par alliance/truce. Actuellement, il y a un problème puisque LaRevolt, qui n'a que 7 alliances/truces perd **729** points d'elo par jour au lieu de **21**. 

Le calcul n'est pas régulier puisque la BlackOld, elle, n'a que 4 alliances/truces, perd **81** points par jour au lieu de **12**. 

### Rec

gpo

### Qu'aurait-il dû arriver ?

Les factions devraient perdre le bon nombre de points de gloire, dont le calcul est **"(nombre d'alliés / truces) x 3 / jour"**.

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Ce n'est pas un bug. Le calcul est correct selon ce qui avait été prévu à la base par le Game design : 3^(allies+truces), et non pas (allies/truces)*x/day. 

Cette demande avait été formulée suite à un trop gros nombre d'alliances et de truces.
