### ISSUE TITLE
[Bug]: MDF - Problème au niveau du renouvellement automatique de la location

### ISSUE THREAD

**Issue by roselyneelavraie** [Paladium-Developpement/Paladium-Issue#5391]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Le renouvellement automatique fonctionne, mais il a prélevé deux fois la faction "Consilium" et pour le montant de 220 000 dollars (440 000$ en tout) au lieu de 154 000 $ (avec la réduction Trixium + c'est une maison de faction sur Kilmordra, où les prix sont plus bas).

### Rec

gpo

### Qu'aurait-il dû arriver ?

Normalement, le prélèvement devrait être unique et ici, de 154 000 $ 

### Serveur

None

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Le renouvellement en double a été corrigé. Cependant, pour la réduction Trixium+, étant donné que l'auto renew n'est pas le fait du joueur mais de la faction, il n'y a pas de calcul sur les avantages grades lors du renouvellement. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
