### ISSUE TITLE
[Bug]: Lucky pass irrécupérable

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#5392]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Les gens ayant le trixium plus avec le lucky pass, ne peuvent pas le récupérer, le message étant: Utilisable dans: en cours.
J'ai le même soucis sur mon compte joueur.
Voir screen ci dessous:

### Rec

https://cdn.discordapp.com/attachments/1138836974556422226/1317883859551129620/image.png?ex=67604e7d&is=675efcfd&hm=abc435b13729be543f46ce1e66c90884d3f9282dbbbfc224cf6290312001aacd&

### Qu'aurait-il dû arriver ?

Le lucky pass devrait pouvoir être récupérable normalement.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
