### ISSUE TITLE
[Bug]:  problème golem/Guardian keeper 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#541]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

j'ai eu plusieur joueur qui mon report un bug
quand il tue leur golem avec le Guardian Hammer, il ne retrouve pas la Guardian stone dans le Guardian keeper 

j'ai deja eu 2-3 joueur mais aucun n'avais un rec video 

### Qu'aurait-il dû arriver ?

la Guardian stone aurai du ce trouver dans le guardian keeper

**Comment by aureliancnx** [comment]
Bonjour,

Ce bug semble être un duplicate de celui-ci : https://github.com/Paladium-Developpement/Paladium-Issue/issues/536
