### ISSUE TITLE
[Bug]: utilisation des sort dans les spawn 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#543]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

j'ai vus qu'on pouvais utiliser les sort dans le spawn, comme le sort répulsion 
des joueur se sont amuser a le faire proche de la warzone (le joueur n'avais pas de rec) 

j'ai essayer au milieu du spawn et le sort marche 

### Qu'aurait-il dû arriver ?

on ne devrais aps pouvoir les utiliser au spawn 

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
