### ISSUE TITLE
[Bug]: Chaudron

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#544]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le chaudron récupère les items créé par lui même. 

Record: https://www.youtube.com/watch?v=eXO3zuU1dTQ
Time code: 3:15
Serveur: Neolith
Heure: 16h18

### Serveur

Neolith

**Comment by Zeldown** [comment]
:x: Ceci n'est pas un bug.
