### ISSUE TITLE
[Bug]: Slowmode

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#545]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le slowmode ne marche pas. Les joueurs ont bien un message expliquant que le slowmode est activé mais ils peuvent encore écrire dans le tchat.

Screen: https://cdn.discordapp.com/attachments/990616313867157575/990616345764847646/Capture_decran_156.png

### Serveur

Neolith

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
