### ISSUE TITLE
1er spawn faction, hors rg  

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#546]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

joueur qui s'est connecté pour la première fois sur un serveur faction.
Il a spawn au-dessus du spawn et c'est fait kill par un autre joueur car la rg n'est pas active à cet endroit.

### Qu'aurait-il dû arriver ?

Il aurait du spawn au 00.

### Serveur

Naera

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
