### ISSUE TITLE
[Bug]: Block add anti noclip

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#560]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

Ajouté les block du mod [ back to the future (88) ] à l'anti noclip, c'est infernal de ce glitch dans les block dans les spawn

**Comment by Siropdebanane59** [comment]
Add aussi la dérogation pour le banbou, l'on reglitch dedans

**Comment by Lorn87** [comment]
fix
