### ISSUE TITLE
[Bug]: rollback lorsque l'on traverse un ghostblock

### ISSUE THREAD

**Issue by ZeeN0w** [Paladium-Developpement/Paladium-Issue#562]
### Pseudo InGame

ZeeN0w

### Que s'est-il passé ?

Un joueur est venue reporté un bug à propos des ghosts block, quand il a posé un ghost block et quand il va dedans celà lui fait rollback et il ne pouvait pas le traverser.

### Qu'aurait-il dû arriver ?

Il aurait dû traverser le ghost block sans aucun problème.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
