### ISSUE TITLE
[Bug]: trade kick item

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#566]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

Lors d'un echange en minage ou en faction, 
pendant l'echange si les deux partie on deja mis leurs item, mais que l'un deux ce fait kick, le joueur non kick recupere l'item qu'il ç mis mais le joueur kick lui ne recupere pas son item à sa reconnection, du coup perte d'item pour le joueur kick

### Serveur

Global

**Comment by Zeldown** [comment]
❌ Le système de trade est désactivé et sera entièrement refait
