### ISSUE TITLE
[Bug]: block invisible cassables [ back to the future (88) ] wither

### ISSUE THREAD

**Issue by Siropdebanane59** [Paladium-Developpement/Paladium-Issue#568]
### Pseudo InGame

Siropdebanane59

### Que s'est-il passé ?

Les block invisible du mod [ Back to the future (88) ] sont cassable au wither, ce qui peut etre derangeant ^^ 

### Serveur

Global

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
