### ISSUE TITLE
[Bug]: Upgrade Boutique IG

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#569]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Impossible d'acheter une upgrade de grade avec des pbs depuis la boutique en jeu.

https://www.youtube.com/watch?v=y85yTr5af9k

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
