### ISSUE TITLE
[Bug]: Limite de Map Neolith

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#570]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Limite de map modifier en 19k x 15K

https://www.youtube.com/watch?v=XFqVYTru80Y

### Serveur

Neolith

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
