### ISSUE TITLE
[Bug]: restriction couleur chat IG

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#572]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Il n'y a plus aucune restriction de couleur en jeu (utilisation des &)

### Qu'aurait-il dû arriver ?

Il devrait y avoir une restriction (voir luckperms)

### Serveur

Global

**Comment by aureliancnx** [comment]
Corrigé!
