### ISSUE TITLE
[Bug]: Flag tp

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#573]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le flag tp ne marche pas (il ne téléporte pas aux bonnes coordonnées)

Rec: https://youtu.be/JEQJ1UDp7ig

### Serveur

Imbali

**Comment by Grandpou** [comment]
L'ordre des coordonnées semble avoir bien été corrigé, par contre quand on entre dans la rg rien ne se passe (alors que le flag est actif + la rg a la bonne priorité)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
