### ISSUE TITLE
[Bug]: staffhistory

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#577]
### Pseudo InGame

Apsig69 

### Que s'est-il passé ?

Sur certaines personnes le staffhistory ne retourne aucun résultat et n'affiche rien dans le chat

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Peux-tu me fournir par message privé un pseudo sur lequel le bug se produit ?

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
