### ISSUE TITLE
[Bug]: Achat ah

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#578]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Bug normalement résolu. Quand un joueur achète au ah, il peut ne pas recevoir l'item mais être quand même crédité.

Rec datant du 11/07/2022 à 23h30: https://www.youtube.com/watch?v=YOyuii9bZbY
Serveur: Soleratl

### Serveur

Soleratl

**Comment by Grandpou** [comment]
https://www.youtube.com/watch?v=LSAszwoZSk8

Autre preuve

**Comment by KraemerJoe** [comment]
Devrait être fix dans la MAJ cresus via les remboursement d'expiration.
