### ISSUE TITLE
[Bug]: metier farmer pas d'xp 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#579]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

j'ai un joueur qui ma expliquer un soucis avec le gain d'xp du métier Farmer 
quand il casse une plante une premier fois même si elle a pousser il ne gagne pas dxp mais si il la replante et la recasse quand elle est pousser la il gagne de l'xp 
donc il doit la casser de deux fois au lieu de une fois  il a tester que avec les chervils 

je sais pas si j'ai bien était claire 

### Qu'aurait-il dû arriver ?

il aurai du gagner de lxp des la premier casse

**Comment by KraemerJoe** [comment]
Hello, testé avec toutes les plantes pas eut de soucis, si le bug se représente merci de nous le refaire parvenir
