### ISSUE TITLE
[Bug][Faction]: Affichage faction niveau 1 alors que niveau 12 (graphique)

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#584]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

Ma faction est marquée comme étant niveau 1 alors qu'elle est niveau 12

### Serveur

Soleratl

### Date et heure de la production du bug

13/07 11:27

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour
