### ISSUE TITLE
[Bug]: Market revient à la "homepage" après un achat

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#585]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

Quand j'achète un truc au market, le market se "reset" et je perd ma rechrche. C'est pas pratique si par exemple je veux acheter plusieurs fois le même item

### Serveur

Global

### Date et heure de la production du bug

13/07 12:21

**Comment by KraemerJoe** [comment]
Corrigé.
