### ISSUE TITLE
[Bug]: Market Same ne garde pas la quantité

### ISSUE THREAD

**Issue by Fuzay** [Paladium-Developpement/Paladium-Issue#586]
### Pseudo InGame

LeVraiFuze

### Que s'est-il passé ?

Le /market same ne garde pas la quantité précédente mise.

### Qu'aurait-il dû arriver ?

Mettre la même quantité que la dernière vente. Si y'a pas assez d'item dispo mettre la quantité max

### Serveur

Global

### Date et heure de la production du bug

13/07 14:04

**Comment by KraemerJoe** [comment]
Corrigé.
