### ISSUE TITLE
[Bug][Faction]: Panneaux des AP

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#587]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on est propriétaire de l'AP on peux casser le panneau qui est devant l'ap. (le panneaux dois être incassable par n'importe qui, même opérateur)
AP nord 2ème et 3ème vers la droite

### Qu'aurait-il dû arriver ?

Personne aurait du réussir à casser le panneau

### Serveur

Soleratl

### Date et heure de la production du bug

13/07/2022 14h00

**Comment by aureliancnx** [comment]
Corrigé à la prochaine mise à jour
