### ISSUE TITLE
[Bug]: bambou ne poussent pas 

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#589]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Le bambou ne pousse dans aucun chunk. 
Que ce soit sur des grass_block ou sand.

Ils ne se transforment pas en poussent de bambou lorsqu'on les pose.

j'ai attendu plus de 30min et aucun bambou sur plus de 2 stacks n'a poussé.

petit extrait vidéo à l'appui ou j'y ai juste planté quelques bambous pour montrer qu'il ne s'update pas en pousse de bambou.

https://youtu.be/1rDx5J9eSCQ

### Qu'aurait-il dû arriver ?

le bambou aurait du poussé et s'update en pousse.

### Serveur

Untaa

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
