### ISSUE TITLE
[Bug]: KOTH Bug Vanilla 

### ISSUE THREAD

**Issue by NaXiiiPaladium** [Paladium-Developpement/Paladium-Issue#590]
### Pseudo InGame

NaXiii

### Que s'est-il passé ?

Il existe un bug en vanilla que certains utilisent lors des KOTH, qui permet de rester bloquer dans un des angles en posant coté client des blocks pour se coincer

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
