### ISSUE TITLE
[Bug][Faction]: Permission /f home

### ISSUE THREAD

**Issue by Elwing123** [Paladium-Developpement/Paladium-Issue#592]
### Pseudo InGame

El_wing

### Que s'est-il passé ?

Le /f home est accessible sans la permissions.
Que ce soit coché ou décocher dans le menu faction on y a quand même accès.

### Qu'aurait-il dû arriver ?

Cela ne devrait pas fonctionné, le /f home sans la permission est censé être désactivé.

### Serveur

Global

### Date et heure de la production du bug

20h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by KraemerJoe** [comment]
Corrigé
