### ISSUE TITLE
[Bug][Faction]: coffre incassable dans un claim ennemy

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#593]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

tentative de casser un coffre dans un coffre ennemy à la dyna mais ne fonctionne pas.

https://www.youtube.com/watch?v=QdDlHewUcow

### Qu'aurait-il dû arriver ?

le coffre aurait du broke

### Serveur

Untaa

### Date et heure de la production du bug

15/07/22 à 00h00

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by KraemerJoe** [comment]
Bonjour
Bug testé et impossible de le reproduire, bug toujours présent ?

**Comment by Danflaa** [comment]
Rebonjour, aucune idée, je n’ai plus retenté. C’était un joueur qui m’avait tp.
bat.
Danfla

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :mercredi 20 juillet 2022 15:55
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Paladium-Developpement/Paladium-Issue] [Bug][Faction]: coffre incassable dans un claim ennemy (Issue #593)


Bonjour
Bug testé et impossible de le reproduire, bug toujours présent ?
