### ISSUE TITLE
[Bug]: Pickaxe of the gods (auto smelt)

### ISSUE THREAD

**Issue by PetitBiscuit74** [Paladium-Developpement/Paladium-Issue#595]
### Pseudo InGame

PetitBiscuit_74

### Que s'est-il passé ?

Suite à l'ajour de l'upgrade auto smelt sur la POG, les minerais casser avec la pioche reste en minerais et ne sont donc pas smelt

### Qu'aurait-il dû arriver ?

Les minerais auraient-du fondre 

### Serveur

Global

### LOG

Lien vidéo youtube > https://www.youtube.com/watch?v=-5tpm3Rgal4

**Comment by KraemerJoe** [comment]
Corrigé.
