### ISSUE TITLE
[Bug]: Bug dimension mineur

### ISSUE THREAD

**Issue by Kuraaah** [Paladium-Developpement/Paladium-Issue#603]
### Pseudo InGame

Kuraaah

### Que s'est-il passé ?

Un joueur m'a report le fais qu'on ne perd pas les points normalement dans la dimension mineur lorsque qu'on casse les minerais avec un hammer speed 3 ou une PoG Big hole, https://www.youtube.com/watch?v=O51OtGEdZHo
Voici le lien de sa vidéo

### Qu'aurait-il dû arriver ?

les points de la dimension devraient se perdre normalement

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
