### ISSUE TITLE
[Bug]: Le coordinate jammer ne fonctionne pas avec Helios

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#604]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

le coordinate jammer ne change pas les coordonnées sur le helios mais il fonctione pour les coordonnées F3.

### Qu'aurait-il dû arriver ?

le coordinate jammer aurait du changer les co sur le plugin helios.

### Serveur

Imbali

### Date et heure de la production du bug

17/07/2022 à 00h00

### Bug du plugin Faction

- [x] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
As-tu lu correctement la case à cocher? Il ne s’agit pas d’un bug du plugin/mod Factions mais d’un vis-à-vis d’Helios.

**Comment by Danflaa** [comment]
Désolé, je pensais que ça faisait parti du plugin faction donc j’ai coché la case.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 17 juillet 2022 00:45
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Paladium-Developpement/Paladium-Issue] [Bug][Faction]: Le coordinate jammer ne fonctionne pas avec Helios (Issue #604)


As-tu lu correctement la case à cocher? Il ne s’agit pas d’un bug du plugin/mod Factions mais d’un vis-à-vis d’Helios.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
