### ISSUE TITLE
[Bug]:  Double XP FarmLand

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#605]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Le Double XP Métiers est toujours actif en FarmLand.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
