### ISSUE TITLE
[Bug]: dimension mineur

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#607]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

quand on choisis un minage on peut spawn directement dans la dimension mineur même sans être lvl 20 et on est plusieurs sur ce minage . sa met arriver mais on pouvais pas récupère tout les minerai 
et un joueur ma dit qu'il a énormément de minerai 

### Qu'aurait-il dû arriver ?

ne pas atterrir dans la dimension minage 

### LOG

![image](https://user-images.githubusercontent.com/105238057/179397306-56bf2da3-694e-46e8-8411-a32906b13a3a.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
