### ISSUE TITLE
[Bug]: Dimension mineur 

### ISSUE THREAD

**Issue by Ikenakkk** [Paladium-Developpement/Paladium-Issue#608]
### Pseudo InGame

Ikenak

### Que s'est-il passé ?

De nombreux joueurs ayant crash au moment de rejoindre la dimension mineur ne peuvent plus se co depuis cet instant.
A chaque tentative de connexion depuis ce moment le jeu time out en boucle avant même de pouvoir arriver sur le serveur.
Lien vers une vidéo d'un joueur qui essaye de se connecter après le bug : https://youtu.be/2BVw65OCOJU

### Qu'aurait-il dû arriver ?

Je suppose que soit le jeu fait rentrer le joueur dans la dimension si celle-ci est open ou juste le redirige vers un lobby si celle-ci est fermé.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
