### ISSUE TITLE
[Bug][Faction]: Récompense koth

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#609]
### Pseudo InGame

GreenwichI

### Que s'est-il passé ?

La Az0x a gagné le koth mais n'a pas reçu la récompense d'argent (les 250k $)

### Qu'aurait-il dû arriver ?

La banque de faction aurait normalement du être crédité de 250k 

### Serveur

Soleratl

### Date et heure de la production du bug

Samedi dernier 21h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
