### ISSUE TITLE
[Bug]: Kill Dyna Farmland

### ISSUE THREAD

**Issue by SirLink23** [Paladium-Developpement/Paladium-Issue#610]
### Pseudo InGame

/

### Que s'est-il passé ?

Un joueur m'a report sur TS qu'il est possible de prendre des dégâts d'explosion (en particulier avec des dynas) dans la farmland.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
