### ISSUE TITLE
[Bug][Faction]: Mdf location

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#612]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

La location de mdf ne marche pas.
Record: https://youtu.be/IY-tIgXJHdg
Le 18/07/2022 sur Imbali à 17h25

### Serveur

Imbali

### Date et heure de la production du bug

Le 18/07/2022 sur Imbali à 17h25

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
