### ISSUE TITLE
[Bug][Faction]: Panneau mdf

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#613]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Il est possible de casser le panneau de location de mdf. 
Record: https://youtu.be/22gpWEmg70c

### Qu'aurait-il dû arriver ?

On ne devrait pas pouvoir le casser même en créa

### Serveur

Imbali

### Date et heure de la production du bug

Le 18/07/2022 sur Imbali à 17h25

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
