### ISSUE TITLE
[Bug][Faction]: Prix ap

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#614]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

La réduction pour les gradés n'est pas proposée lors de l'achat d'un ap.
Peu importe le grade du joueur, l'ap est vendu à 700k.

### Serveur

Global

### Date et heure de la production du bug

18/07/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
