### ISSUE TITLE
[Bug][GuardianGolem]: NotifApi Golem

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#616]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

impossible d'inviter le bot sur un serveur discord voici l'erreur :

https://prnt.sc/N9R4U_cONvYS

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
