### ISSUE TITLE
[Bug][Faction]: Problème classement quête hebdos

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#617]
### Pseudo InGame

GreenwichI

### Que s'est-il passé ?

La BlackOld a réalisé sa quête en 3 ème mais n'apparait pas dans le classement : 
https://cdn.discordapp.com/attachments/693925225695543326/998922004721848381/unknown.png

De plus ils n'ont pas reçu le boost de récompense sur l'argent et l'xp.

### Serveur

Soleratl

### Date et heure de la production du bug

19/07/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
