### ISSUE TITLE
[Bug]:  Endium Dyna Désactivé

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#619]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Endium Dyna Désactivé sur six serveur faction Luccento / Untaa / Imbali / Naera / Neolith / Keltis

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
