### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#620]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

impossible de poser le Base claim controller.

### Qu'aurait-il dû arriver ?

on devrait normalement pouvoir le poser.

**Comment by KraemerJoe** [comment]
Bonjour
Quelle est l'erreur lors de la tentative de poser le BCC ?

**Comment by Danflaa** [comment]
Nous avons acheté le bcc et lors de la tentative de pose du bloc, le bloc revenait immédiatement dans les mains avec comme message (je n’ai pas pu prendre de screen car ce n’est pas moi le chef de fac). Mais ça disait : impossible de poser le bcc car il y en a déjà un sur paladium (quelque chose comme ça)
Je vais tenter d’obtenir un screen.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :mercredi 20 juillet 2022 13:23
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Paladium-Developpement/Paladium-Issue] [Bug]: (Issue #620)


Bonjour
Quelle est l'erreur lors de la tentative de poser le BCC ?
