### ISSUE TITLE
[Bug]: Bug spawn withered pistons

### ISSUE THREAD

**Issue by Kuraaah** [Paladium-Developpement/Paladium-Issue#622]
### Pseudo InGame

Kuraaah

### Que s'est-il passé ?

Alors, quand on souhaite faire des withered pistons (faire spawn un wither tout en l'ayant entouré de pistons posés pour qu'il explose lors de son spawn et casse les pistons pour les transformer en withered pistons), il se trouve que ceux-ci remontent à la surface sans qu'on le sache et donc on peut penser qu'ils n'ont pas spawn et que ça n'a pas marché, mais non en effet ils ont bien été transformé mais remontent juste à la surface (détail inconnu pour la quasi totalité des joueurs).

Un rec de test a été effectué par moi et Zazho, le voici : https://youtu.be/HvmLSHSby1M

### Qu'aurait-il dû arriver ?

Les withered pistons devraient spawn normalement à l'endroit où on a fait spawn le wither et non pas remonter à la surface.

### Serveur

Muzdan

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
