### ISSUE TITLE
[FeedBack]: Helios crosshair

### ISSUE THREAD

**Issue by VexonTV1** [Paladium-Developpement/Paladium-Issue#623]
### Pseudo InGame

VexonTV

### Nom de la feature

Helios crosshair

### Retour sur la Feature

![image](https://user-images.githubusercontent.com/103930978/180087225-6e15650d-511d-4fe4-bd15-687838745753.png)

Ce serait une bonne idée de rajouter la possibilité d'activer / désactiver le fait de voir le crosshair en F5

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
