### ISSUE TITLE
[Bug]: /noclip bugé

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#625]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on utilise le /noclip on ne vois pas à travers le mur, avec ou sans item dans la mains.
https://prnt.sc/-k8729N9cyRo

### Qu'aurait-il dû arriver ?

Voir à travers les blocks

**Comment by aureliancnx** [comment]
Ce bug est dû aux configurations de xray
