### ISSUE TITLE
[Bug]: Bug récup xp farmer

### ISSUE THREAD

**Issue by Kuraaah** [Paladium-Developpement/Paladium-Issue#626]
### Pseudo InGame

Kuraaah

### Que s'est-il passé ?

Un joueur m'a report le fait qu'il ne récupérait pas l'xp farmer quand il cassait ses eggplants, je lui ai demandé un rec pour vous faciliter la compréhension du bug, mais en gros il récupère de l'xp 1 fois sur 5 en cassant à la main et avec sa pioche hyper xp il ne récupère aucune xp.
Voici le rec : https://www.youtube.com/watch?v=cpLGPLIV8qY

### Qu'aurait-il dû arriver ?

l'xp devrait être gagnée normalement

### Serveur

Muzdan

**Comment by Lorn87** [comment]
fix
