### ISSUE TITLE
[Bug][Faction]: /f Access

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#628]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Le /f access p <pseudo> no dans un claim ne fonctionne pas, le membre de la faction peut toujours poser ainsi que le casser des blocs

### Serveur

Global

### Date et heure de la production du bug

14h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Après avoir exécuté la commande pour supprimer un joueur, est-ce que le joueur est toujours affiché dans la commande  _/f access v_ ?

Cordialement
