### ISSUE TITLE
[Bug]: crash ah 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#629]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

quand on est sur la page de vente et qu'on ne met aucun item mais qu'on appuis sur vendre sa nous fait crash 

### Qu'aurait-il dû arriver ?

sa devrais pas nous faire crash

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
