### ISSUE TITLE
[Bug]: Bug claims faction

### ISSUE THREAD

**Issue by Kuraaah** [Paladium-Developpement/Paladium-Issue#630]
### Pseudo InGame

Kuraaah

### Que s'est-il passé ?

Si on unclaim all sur un serveur (quand on trouve pas l'emplacement de ses chunks) alors qu'on a une base sur un autre serveur, celle-ci deviendra bug au niveau des claims fais, je m'explique : 

La base en question reste claim et on voit bien sur le /f map que c'est claim, nous ne pouvons pas poser de blocs etc, et les gens qui ont les perms eux peuvent poser normalement ou interagir normalement. MAIS, sur le /f f [nomfaction] on ne retrouve 0 claims dans l'endroit du détails power/claims.
Donc en résumé, la base est bien unclaim au niveau du /f f, mais sur place, elle est pas unclaim et en plus les joueurs ne peuvent ni unclaim, ni claim par dessus. 
Si besoin de plus demandez moi sans soucis

### Qu'aurait-il dû arriver ?

tout devrait être unclaim avec /f unclaimall 

### Serveur

Untaa

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
