### ISSUE TITLE
[Bug]: zone pvp 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#631]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

dans la zone pvp les commande sont désactivé notamment le /spawn 
mais il a un moyen de contourner sa il fait /warp spawn  et sa fonctionne tres bien 

### Qu'aurait-il dû arriver ?

normalement le /warp spawn ne devrais pas fonctionner

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
