### ISSUE TITLE
[Bug]: crash  sort inertiu

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#632]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

quant un joueur utilise le sort inertium avec un item modée qui peut avoir une contenance (cobblebreaquer, palaforge) et qui utilise le sort il ce fait crash et crash les joueur autour 

### Qu'aurait-il dû arriver ?

personne ne devrait crashé 

### LOG

https://youtu.be/vO59zlAwkY8

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
