### ISSUE TITLE
[Bug]: Home remover non fonctionnel

### ISSUE THREAD

**Issue by Slyverito** [Paladium-Developpement/Paladium-Issue#633]
### Pseudo InGame

Slyverito45

### Que s'est-il passé ?

Lors de l'utilisation du **Home Remover**, on voit les fantômes de tous les joueurs ayant posé un home dans le rayon adéquat. Avec l'utilisation de la **Housing Stone**, le fantôme se transforme en "PNJ" qu'il faut tuer pour retirer le home de la personne.
Mais lors de la mort de celui-ci. **Le home ne se retire pas**.

(_Testé par Alanah pour confirmation du problème_) 

### Qu'aurait-il dû arriver ?

Lors de la mort du "PNJ", le home du joueur aurait du être retiré.

**Comment by KraemerJoe** [comment]
Sera réglé avec la refonte, merci
