### ISSUE TITLE
[Bug]: Bug Golem

### ISSUE THREAD

**Issue by ZeeN0w** [Paladium-Developpement/Paladium-Issue#634]
### Pseudo InGame

ZeeN0w

### Que s'est-il passé ?

Un joueur est venue me report que son Golem le tape lorsqu'il avait la whitelist golem, il n'avait pas mis la compétence "Golem Fou", il avais tout mis sur la catégorie "Guerrier" sauf "Golem Fou". Il était le propriétaire du Golem !

### Qu'aurait-il dû arriver ?

Normalement le Golem ne devrait pas tapé son propriétaire.

**Comment by Zeldown** [comment]
Bonsoir @ZeeN0w, serait-il possible de demander à un opérateur de reproduire le soucis et de fournir un rec, merci ! ❤️

**Comment by aureliancnx** [comment]
Bonjour,

N'ayant pas eu de nouvelles sur ce bug ni de rec/reproduction du problème, je em permets de fermer cette issue.
Si le problème persiste, je vous invite à réouvrir une issue avec les informations nécessaires et une démonstration afin d'améliorer l'efficacité de traitement des tickets.
