### ISSUE TITLE
[Bug][Faction]: Probleme claim AP

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#635]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Une personne a acheter un AP sur Naera hier soir, il avais le claim et pouvais casser poser des block...
Aujourd'hui il y retourne il n'a plus le claim et ne peut donc plus rien faire dedans cependant sur le panneau y a bien le nom de sa faction. Il est chef de sa faction.

### Qu'aurait-il dû arriver ?

Il aurai du pouvoir poser casser des block et garder son claim

### Serveur

Naera

### Date et heure de la production du bug

23/07/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Sans plus d'informations sur le signalement du bug (pseudo du joueur, nom de sa faction), je ne peux pas résoudre le problème.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
