### ISSUE TITLE
[Bug]: Disparition de lingots après fonte dans la palaforge

### ISSUE THREAD

**Issue by Caitline86** [Paladium-Developpement/Paladium-Issue#64]
### Pseudo InGame

Caitline1986

### Que s'est-il passé ?

Bonjour,

En fait, après la fonte, les lingots reçus ne s'ajoutent pas toujours dans l'inventaire, ils disparaissent. Un joueur de ma fac m'en a parlé et je fais donc ce report.

Voici un rec pour la preuve: https://youtu.be/vbakq6dqIb8

### Qu'aurait-il dû arriver ?

Récupérer les lingots.

**Comment by aureliancnx** [comment]
Bonjour,

Le bug est-il toujours d'actualité ?

Cordialement,

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
