### ISSUE TITLE
[Bug][Faction]: Chat Faction 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#642]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Quand on utilise la commande /f c f en faction
Quand on utilise la commande pour reparler en chat publique celle-ci fonctionne 
Mais si on vient à déco reco le chat faction / changement du serveur faction, cela se remet automatiquement étant donné que la commande /f c p est bloqué en minage les gens ne peuvent pas écrire dans le chat publique

### Serveur

Global

### Date et heure de la production du bug

16h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
