### ISSUE TITLE
[Bug]: achat d'un slot de mise en vente au AH payé x2 (rec)

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#644]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

j'ai acheté un slot de mise en vente au AH contre 100pb's mais ça me l'a décompté 2x lorsque j'ai voulu confirmé l'achat car j'ai cliqué 2x pensant que ça n'avait pas fonctionné la première fois.

Rec : https://youtu.be/6Uw_3-PDoDU

Bonne journée et bonne chance dans votre travail ;) 

### Qu'aurait-il dû arriver ?

ça n'aurait pas du me débiter x2

### Serveur

Muzdan

**Comment by Lorn87** [comment]
fix
