### ISSUE TITLE
[Bug]: Bug de dupli Gogo

### ISSUE THREAD

**Issue by AlanahPaladium** [Paladium-Developpement/Paladium-Issue#649]
### Pseudo InGame

Alanah

### Que s'est-il passé ?

Hola

On me report qu'un ancien bug de dupli de gogo est toujours possible : https://www.youtube.com/watch?v=VwYBxyJnrAo

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
