### ISSUE TITLE
[Bug]: Stregnht stick fait trop de dégat

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#65]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Le strenght stick une fois activé fait beaucoup plus de dégat que prévu on peut 3 shot un joueur en full p4, ce qui n'étais pas le cas avant, ce n'es pas uniquement en warzone mais partout sur la map.
J'ai accompagné ca d'une vidéo qui le montre.
https://www.youtube.com/watch?v=1Wa_VQ0I2Oo

### Serveur

Mineria

**Comment by Zeldown** [comment]
Je ne vois aucun soucis dans le rec actuel.

Il faut 4 coups pour tuer avec force III & 3 coups critiques.

Il n'y a pas de soucis dans ces chiffres là.
