### ISSUE TITLE
[Bug]: Bug nom de grade et quantité de home avec le grade légende

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#651]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Pseudo du joueur: Herve04
Il n'a que 10 homes et non 15 avec le grade légende, quand il parle dans le lobby ca lui note ceci: https://prnt.sc/yK0mLasJTu0O
Dans un faction: https://prnt.sc/726sJt2UIvtn
Quand il veux faire des homes en plus: https://prnt.sc/2GqDnMhCtTkW
lp user: https://prnt.sc/EIaorNqDT6pv

Date 28/07/2022 10h48

### Qu'aurait-il dû arriver ?

J'ai aucune info sur le grade légende mais je pense que 15 homes est normal comme le grade endium, mais il y a un soucis avec le lobby

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
