### ISSUE TITLE
[Bug]: mobstacker 

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#653]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

on ne peut pas stacker + de 2 mobs dans le mobstacker.

### Qu'aurait-il dû arriver ?

on devrait pouvoir en stacker beaucoup +

**Comment by iWoZ0** [comment]
Je rajoute aussi lorsqu'on tue un mob le reste du mobstack meurt
