### ISSUE TITLE
[Bug][Faction]: Chat faction

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#654]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Le Chat Faction / Alliés / Truces ne fonctionne plus

### Serveur

Global

### Date et heure de la production du bug

15h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Corrigé
