### ISSUE TITLE
[Bug][Faction]: Baltop faction

### ISSUE THREAD

**Issue by Kuraaah** [Paladium-Developpement/Paladium-Issue#656]
### Pseudo InGame

Kuraaah

### Que s'est-il passé ?

Le /f baltop est complètement cassé et on ne voit aucune money etc...

### Qu'aurait-il dû arriver ?

Il devrait fonctionner normalement 

### Serveur

Global

### Date et heure de la production du bug

28/07/22 à 20h43 

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Nous allons passer la commande /f baltop en maintenance. Un message sera visible lors de la prochaine mise à jour, le temps de remettre en place la commande.

Merci du signalement.
