### ISSUE TITLE
[Bug]: Tp vers un joueur bug, même les commande gm

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#657]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Impossible de me tp au joueur _Califoutre, avec les commande /tpa ou même /tp, lui peux ce tp par contre.

Rec: https://www.youtube.com/watch?v=xZczQAwTcVs

29/07/2022 14h00

### Serveur

Rakavi

**Comment by Zeldown** [comment]
_Calcifoutre*

**Comment by Lorn87** [comment]
fix
