### ISSUE TITLE
[Bug][Faction]: Unclaim all ne marche pas

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#659]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Report de la faction Insomnium

Ils ont fait un unclaim all, tout les claim sont rester mais enlever sur le /f f

https://prnt.sc/hKJCsEkkg-sB
https://prnt.sc/kI0N3dKKvRd7

Date 29/07/2022 16h00

### Serveur

Keltis

### Date et heure de la production du bug

29/07/2022 16h00

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Zazho** [comment]
Manashino je me suis trompé

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
