### ISSUE TITLE
[Bug]: Création des potion de force 2

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#660]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il est possible de créer des potion de force 2, de les mettre par le biai d'un hopper dans un dispenser, et de ce les splash sur sois même, cela donne 1 minute de force 2

### Qu'aurait-il dû arriver ?

Impossible à craft

### Serveur

Manashino

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
