### ISSUE TITLE
[Bug][Faction]: Base Claim Controler

### ISSUE THREAD

**Issue by Eclair93k** [Paladium-Developpement/Paladium-Issue#662]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Notre Base Claim Contrôler (BlackOld) est posé depuis maintenant 2 jours et n'a rapporter aucun aucun point de classement à la faction.

### Serveur

Keltis

### Date et heure de la production du bug

Ça fait 2 jours

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
