### ISSUE TITLE
[Bug][Faction]: Mise en combat d'alliés 

### ISSUE THREAD

**Issue by Eclair93k** [Paladium-Developpement/Paladium-Issue#663]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Les Dynamites, Flèches, EnderPearl et quelques sorts mettent en combat des membres de la même Faction.

### Serveur

Global

### Date et heure de la production du bug

Depuis le début de la saison 

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
