### ISSUE TITLE
[Bug]: Cauldron

### ISSUE THREAD

**Issue by Eclair93k** [Paladium-Developpement/Paladium-Issue#664]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Quand on lance de la glowstone dans un cauldron elle se fait 1 par 1 au lieu du stack ce qui rend la production vraiment lente

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
