### ISSUE TITLE
[Bug]: Anvil Cassable dans les Claim adverses

### ISSUE THREAD

**Issue by Eclair93k** [Paladium-Developpement/Paladium-Issue#665]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Les Anvil sont cassables dans les claim adverses en fusionnant des objets pour lui faire perdre de la durabilité.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
