### ISSUE TITLE
[Bug]: Bug bottes frost walker

### ISSUE THREAD

**Issue by Kuraaah** [Paladium-Developpement/Paladium-Issue#670]
### Pseudo InGame

Kuraaah

### Que s'est-il passé ?

Les bottes frost walker ne marchent pas du tout, voici un rec : https://www.youtube.com/watch?v=RO32_UFqtps

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
