### ISSUE TITLE
[Bug]: Mise en avant Market

### ISSUE THREAD

**Issue by Eclair93k** [Paladium-Developpement/Paladium-Issue#672]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Quand on met un Item dans son Market et qu'on le met en avant pour par exemple 1 Million de $. On attend que quelques trucs partent au bout d'une heure. Le bouton pour mettre en avant est redisponible. Une fois que le bouton est redispo. On remet l'item en avant pour par exemple 1$ et on retire les items de notre /Ah.

Ce qui nous rendra les 1 Million de mise en avant de base et nous prendra les 1$

**Comment by KraemerJoe** [comment]
Corrigé merci.
