### ISSUE TITLE
[Bug]: endium flower disparait dans le chaudron

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#673]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Clear de l'endium dans le chaudron.
Je sais que cela est normal et qu'on peut jeter une endium flower dans le chaudron pour récupérer un pollen mais contrairement aux autres fleurs moddées, l'endium flower disparait instantanément sans possibilité de récup. 
les autres fleurs moddées restent un petit temps dans le chaudron, permettant ainsi de les récupérer.
https://youtu.be/M_oKTl3iigs

**Comment by Zeldown** [comment]
:x: Ceci n'est pas un bug et ne sera donc pas corrigé.
