### ISSUE TITLE
[Bug]: Le flag spell n'existe plus

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#675]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/182429015-9560aa77-1b6e-4771-8372-7fead7e37618.png)

### Qu'aurait-il dû arriver ?

Exister

### Serveur

Soleratl

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
