### ISSUE TITLE
[Bug]: Drawer dans les EC

### ISSUE THREAD

**Issue by MrKittenxs** [Paladium-Developpement/Paladium-Issue#676]
### Pseudo InGame

Mr_Kittenxs

### Que s'est-il passé ?

On peux de nouveau remettre les drawers dans les EC

### Qu'aurait-il dû arriver ?

au debut un message expliquer qu'on n'avez pas le droit

**Comment by aureliancnx** [comment]
Le problème a déjà été signalé ici : https://github.com/Paladium-Developpement/Paladium-Issue/issues/309
