### ISSUE TITLE
[Bug]: Bug gain XP spawner T4 squelette

### ISSUE THREAD

**Issue by PetitBiscuit74** [Paladium-Developpement/Paladium-Issue#677]
### Pseudo InGame

PetitBiscuit_74 

### Que s'est-il passé ?

Le joueur après avoir tué de multiples squelettes ne gagne pas d'expérience

### Qu'aurait-il dû arriver ?

Le joueur aurait dû gagner l'expérience des mobs

### Serveur

Global

### LOG

Je vous fournis une preuve vidéo
https://www.youtube.com/watch?v=uesNCPUY9Q8

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
