### ISSUE TITLE
[Bug][Faction]: Renommage de grade en 2 temps

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#680]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lorsque l'on renomme un grade il faut 2 clique pour l'onglet se ferme. Le premier fait réellement la modification (sans notif mais avec un message dans le tchat) mais le gui ne se ferme pas. Si on fait retour, ça n'actualise pas le gui et il faut quitter et revenir pour voir le grade renommé.
Sinon il faut recliquer, là une notif apparait avec une erreur en mode ca existe déjà puis le gui se ferme
![modifgrade2temps](https://user-images.githubusercontent.com/92928910/182826903-b1e50ef3-e2de-4c1f-ab64-05efeca5532d.gif)

### Serveur

Soleratl

### Date et heure de la production du bug

04 08 2022 12h33

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
