### ISSUE TITLE
[Bug][Faction]: Rg mdf ne se créait pas

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#681]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

La rg ne se créait pas et du coup on peut pas louer la mdf car le joueur ne peut pas être add à la rg. (L'argent est bien débité par contre) 
![image](https://user-images.githubusercontent.com/92928910/182831645-b29a2b72-2329-4842-90f7-9889047afa86.png)
![image](https://user-images.githubusercontent.com/92928910/182831800-0065e997-2e9d-4fa0-8ccc-5e65110a1943.png)

### Serveur

Soleratl

### Date et heure de la production du bug

04 08 2022 13h01

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
