### ISSUE TITLE
[Bug]: Problème d'agro du wither

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#682]
### Pseudo InGame

Taxbac

### Que s'est-il passé ?

Le wither perd l'agro quand on change de claim

**Comment by Greenwich31** [comment]
https://youtu.be/mq6AdE1vdLA vidéo montrant bien le problème

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
