### ISSUE TITLE
[Bug]: bug récompense lvl 10 alchi

### ISSUE THREAD

**Issue by Kuraaah** [Paladium-Developpement/Paladium-Issue#683]
### Pseudo InGame

Kuraaah

### Que s'est-il passé ?

Un joueur m'a rapporté le fait qu'il ai reçu 10 shiny jacaranda wood comme récompense pour son level 10 alchimiste, sauf que normalement c'est du Shiny Judeceeris Wood qu'on devrait recevoir à ce level alchi.

### Serveur

Global

**Comment by Zeldown** [comment]
Ceci n'est pas un bug :x:
