### ISSUE TITLE
[Bug][Faction]: Piston possible dans les claims

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#684]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Il est possible de pousser des blocks dans les claims avec un piston

Vidéo de démonstration : https://youtu.be/plPPDpD-n8k

### Qu'aurait-il dû arriver ?

Le piston ne devrait pas pousser le block dans les chunks où les joueurs ne sont pas access. 

### Serveur

Global

### Date et heure de la production du bug

23:00

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Zeluck-tv** [comment]
Bug qui a été noté comme corrigé sur le patch-note du 17/07/22
https://paladium-pvp.fr/articles/patchnote-v8-0-1-2-17-07-2022

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
