### ISSUE TITLE
[Bug]: Piston Infini

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#685]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Il est possible de faire des pistons infini dans les claims d'une faction ennemie 

Donc cela est possible aussi de faire juste un brigde normal dans une base claim adverse 
Petit exemple en vidéo : https://www.youtube.com/watch?v=plPPDpD-n8k

### Serveur

Global

**Comment by aureliancnx** [comment]
https://github.com/Paladium-Developpement/Paladium-Issue/issues/684
