### ISSUE TITLE
[Bug][Faction]: Bug dans l'annuaire

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#687]
### Pseudo InGame

GreenwichI

### Que s'est-il passé ?

https://youtu.be/G8DN-ck8Aeo

### Serveur

Manashino

### Date et heure de la production du bug

05/08/2022 16h20

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
