### ISSUE TITLE
[Bug][Apollon]: Bug de description

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#688]
### Pseudo InGame

GreenwichI

### Que s'est-il passé ?

La description des factions ne s'affiche pas entièrement lors de l'inspection :
https://youtu.be/VBN8tByZvcs

### Serveur

Manashino

### Date et heure de la production du bug

05/08/2022 16h24

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
