### ISSUE TITLE
[Bug][Faction]: Crash permission faction allié

### ISSUE THREAD

**Issue by Greenwich31** [Paladium-Developpement/Paladium-Issue#689]
### Pseudo InGame

GreenwichI

### Que s'est-il passé ?

Lorsque l'on ouvre les permission des faction allié on crash avec un fatal error

### Serveur

Manashino

### Date et heure de la production du bug

05/08/2022 16h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
not dev
https://github.com/Paladium-Developpement/Paladium-Issue/issues/237
