### ISSUE TITLE
[Bug]: Dimension mineur

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#690]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Une personne a ouvert son portail vers la dimension mineur. Une fois rentré dedans ca l'a bien mis dans le lobby de cette dernière, ca lui dit que la dimension est en train de ce créer et ceux sans jamais le mettre dans sa dimension. SI il fait /dimension en jeu ca lui met la barre comme ci il y était mais en étant dans un serveur faction normal.

### Qu'aurait-il dû arriver ?

Il aurai du aller dans la dimension

### Serveur

Global

### LOG

https://youtu.be/Yi1_IXenqnY (dimension en cours de création / redirection inexistante)
https://youtu.be/jPNnyaGQtlk (Barre dimension mineur dans un faction)

Nouveau rec

https://www.youtube.com/watch?v=_gfr9p7fdJE

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
