### ISSUE TITLE
[Bug]: DrawBridge | Plusieurs totems dans les chunks

### ISSUE THREAD

**Issue by PetitBiscuit74** [Paladium-Developpement/Paladium-Issue#693]
### Pseudo InGame

PetitBiscuit_74

### Que s'est-il passé ?

Suite à la pose du drawbridge avec l'inventaire rempli de totem, les totems se mettent tous à la suite dans le chunk et multiplie leur effet d'accélération de pousse au sein de ce même chunk

### Qu'aurait-il dû arriver ?

Les totems ne devrait pas être poser par le drawbribge, et il dois y en avoir 1 seul par chunk maximum 

### Serveur

Global

### LOG

Je ne suis malheureusement pas en capacité de record le bug

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
