### ISSUE TITLE
[Bug][Faction]: Bug claim ap

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#694]
### Pseudo InGame

SheyZzn

### Que s'est-il passé ?

Nous pouvons casser/poser des bloc dans les ap sur untaa (tester sur d'autre aussi donc possiblement globale a tous les serv ou que certain) sans les avoir acheter il y a un soucis avec la rg c'est que sur les ligne d'ap.

### Serveur

Global

### Date et heure de la production du bug

09/08/2022 19:40

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

### LOG

https://www.youtube.com/watch?v=37z-M2SuAds

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
