### ISSUE TITLE
[Bug][Jobs]: XP métier

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#695]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Impossible d'xp au dessus du lvl 20 sauf avec des bottle

### Qu'aurait-il dû arriver ?

Pourvoir xp de la même manière que du lvl 19 au lvl 20 ( vus avec lorn)

### Serveur

Global

**Comment by Lorn87** [comment]
fix
