### ISSUE TITLE
[Bug]: Portail endium rempli ne donne pas de récompense

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#696]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Une fois le portail alchimiste lvl 20 posé et activé, je l'ai rempli de sève et de pollen jusqu'à la jauge maximale de la clef.
A son reset, je n'ai reçu aucune récompense
J'ai tenté à 5 reprises de remplir la clef, à chaque fois elle revient à 0 sans me donner de récompense

### Qu'aurait-il dû arriver ?

J'aurais du récupérer des orangeblue ou avec un peu de chance un nugget en endium

### Serveur

Neolith

**Comment by Grandpou** [comment]
Je rajoute une vidéo: https://youtu.be/2r8alhCi28U

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
