### ISSUE TITLE
[Bug]: Hardened cassable avec Big hole

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#698]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Un joueur a pu casser de la hardened obsidian en utilisant big hole sur un bloc adjacent à la hardened, ce qui a eu pour effet de la casser aussi.

### Qu'aurait-il dû arriver ?

La hardened n'aurait pas du se casser.

**Comment by Lorn87** [comment]
fix
