### ISSUE TITLE
[Bug]: Impossible d'utiliser une cisaille sur un mouton éponge 

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#699]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Après que le mouton soit imbibé d'eau et qu'il soit en éponge, il est impossible de le tondre.

### Qu'aurait-il dû arriver ?

On doit récupérer une éponge sur le mouton

**Comment by aureliancnx** [comment]
Bonjour

Cette issue semble être un duplicate de celle ci : https://github.com/Paladium-Developpement/Paladium-Issue/issues/729
