### ISSUE TITLE
[Bug]: Bug avec sealed xp bottler

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#70]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Un joueur a fait un rec, il n'arrivais pas a remplir de fiole d'xp en tuant des golem
https://www.youtube.com/watch?v=UP-AvP7biGk

### Qu'aurait-il dû arriver ?

Remplir la fiole d'xp pour le métier de hunter

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
Malgré différents tests il m'est impossible de reproduire le bug
