### ISSUE TITLE
[Bug]: Bambou ne poussent pas

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#700]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Le bamboo ne pousse pas. il ne s'update pas en pousse de bambou et est considéré comme un simple "bloc".

### Qu'aurait-il dû arriver ?

Le bambou devrait pousser.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport

**Comment by Danflaa** [comment]
Salut, ce sera actif dans un prochain patch ou c’est déjà d’actualité ?

merci, bonne journée à toi


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :lundi 15 août 2022 14:04
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Paladium-Developpement/Paladium-Issue] [Bug]: Bambou ne poussent pas (Issue #700)


✔️ Le bug à été corrigé !

🚀 Merci pour le rapport
