### ISSUE TITLE
[Bug][Faction]:  Zone Pvp

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#701]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Il est Possible de claim la Zone Pvp ainsi que le spawn avec le /f claim auto

### Serveur

Global

### Date et heure de la production du bug

15h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
