### ISSUE TITLE
[Bug]: Bug dupli xp sealed

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#702]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Le bug de dupli xp en farmant des lightning potion en minage est toujours actif (malgré le close des anciennes issues qui le reportaient)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
