### ISSUE TITLE
[Bug]: snow golem 

### ISSUE THREAD

**Issue by GhostYruama** [Paladium-Developpement/Paladium-Issue#709]
### Pseudo InGame

GhostYruama

### Que s'est-il passé ?

Le snow golem a spawn en étant invisible et est mort a peine 2 sec après .

### Qu'aurait-il dû arriver ?

le snow golem  Aurais du spawn en étant visible et n'aurais pas du mourir 

### LOG

https://www.youtube.com/watch?v=hC4ihnIL0k4 
vidéo montrant le bug

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
