### ISSUE TITLE
[Bug]: La mise en vente d'article dans le /market ne fonctionne pas toujours

### ISSUE THREAD

**Issue by Camouchat** [Paladium-Developpement/Paladium-Issue#71]
### Pseudo InGame

Camouchaat

### Que s'est-il passé ?

Lorsque l'on souhaite mettre en vente un article au /ah rien ne se passe quand on appuie sur le bouton ''Vendre'' 
En changeant de serveur, cela peut fonctionner à nouveau. 
Pour l'instant serveurs où j'ai localisé ce bug (c'est peut être le cas sur tous, mais cela m'est arrivé uniquement là bas) : 
- Océania
- Forestia 
- Mineria 

### Qu'aurait-il dû arriver ?

L'item devrait se mettre en vente normalement en cliquant sur le bouton ''Vendre''

**Comment by aureliancnx** [comment]
Bonjour,

Est-ce qu'il y a des erreurs dans les logs du jeu quand tu essayes de vendre un item et que cela ne fonctionne pas ?

**Comment by Camouchat** [comment]
Coucou, aucun bug lorsque cela ne fonctionne pas s'affiche in game. J'essaierai de te récupérer les logs si cela recommence.

**Comment by Camouchat** [comment]
Coucou cela vient de se produire à nouveau j'ai pensé à te prendre des logs ! 
les voici :) https://pastebin.com/FjZQEVeB

**Comment by aureliancnx** [comment]
Bonjour,

Cela arrive-t-il notamment quand tu es connecté sur un serveur depuis peu de temps ?
Concernant les logs, il n'y a pas d'information pouvant m'indiquer un problème de ton côté, il faut donc creuser à ce sujet

**Comment by Camouchat** [comment]
Non pas spécialement peu de temps, j'ai aussi été interpellé par pas mal de joueurs à ce sujet in game et pareil il y a des tickets sur le palasupport qui remontent à ce sujet
