### ISSUE TITLE
[Bug]: Name Tag Endium

### ISSUE THREAD

**Issue by ZeeN0w** [Paladium-Developpement/Paladium-Issue#711]
### Pseudo InGame

ZeeN0w

### Que s'est-il passé ?

Quand on utilise le Name Tag en endium sur un mob, le mob dispawn pendant le clear lag !

### Qu'aurait-il dû arriver ?

Il aurait dû arriver que le mob ne dispawn pas au clear lag.

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
