### ISSUE TITLE
[Bug]: Seau de lave dans le palafurnace

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#712]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Lorsque l'on met un seau de lave dans un palafurnace le seau est aussi consomé

### Qu'aurait-il dû arriver ?

Il n'y a que la lave qui aurait du être prise, le seau aurait du être laissé

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
