### ISSUE TITLE
[Bug]: Commande /minage

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#713]
### Pseudo InGame

Physali

### Que s'est-il passé ?

La commande /minage peut nous déconnecter avec ce message
![Screenshot_33](https://user-images.githubusercontent.com/92942134/184538681-af503ca4-47ec-4f7a-bacf-3d39203100d8.png)
 

### Serveur

Lobby

**Comment by aureliancnx** [comment]
Bonjour,

La commande /minage fonctionne bien. En effet, c'est lors du changement d'un serveur que cette erreur peut apparaître, notamment lorsque l'on clique plusieurs fois. Elle n'est pas spécifique à cette commande

Cordialement,
