### ISSUE TITLE
[Bug]: Touche pour ouvrir l'interface faction en minage

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#714]
### Pseudo InGame

Physali

### Que s'est-il passé ?

La touche pour ouvrir l'interface des factions fait crash quand on l'active sur un serveur minage

### Qu'aurait-il dû arriver ?

Il devrait y avoir un message d'erreur disant que la commande n'est pas accessible en minage comme pour les autres commandes du plugin faction 
![image](https://user-images.githubusercontent.com/92942134/184538951-02eb95b7-eca7-462c-9efd-901612b6c85c.png)

### Serveur

Minage

**Comment by aureliancnx** [comment]
Bonjour,

Peux-tu m'envoyer les logs de ton jeu ?

Cordialement,

**Comment by Phyzali** [comment]
Il s'agit plus d'un fatal error 
![image](https://user-images.githubusercontent.com/92942134/184548691-cf356a44-86a2-404c-9c84-85a2f8fe4557.png)
Mais voici les logs après un test 
https://pastebin.com/AxQ8SHgk

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
