### ISSUE TITLE
[Bug]: home remover/home finder

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#715]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

j'ai eu le report d'un joueur 
quand il utilise sont home finder il voit qu'il a bien 9home mais on ne voit aucun pseudo ou fantôme 
même le ciens on ne le voit pas 

### Qu'aurait-il dû arriver ?

on aurai du voir les fantomes des joueur 

### LOG

https://www.youtube.com/watch?v=u-kdB6YKmQ8

**Comment by RedFlys72** [comment]
https://www.youtube.com/watch?v=hLa0Lae88wE

j'ai un autre rec du soucis mais cette fois il a aussie le fait quil ne peut pas tuer le fantom
e et il reste a l'endroit

**Comment by Jabsyyy** [comment]
Bug toujours présent sur le serveur le 28/08/2022
Voici un rec fait à ce jour : https://youtu.be/TNRLzLcqorQ

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
