### ISSUE TITLE
[Bug]: Commande f map en minage

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#716]
### Pseudo InGame

Physali

### Que s'est-il passé ?

La commande /f map reste activée dans un minage, il est impossible de la désactiver sans avoir à retourner sur un serveur faction

### Qu'aurait-il dû arriver ?

Le /f map auto ne devrait pas s'afficher en minage

### Serveur

Minage

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
