### ISSUE TITLE
[Bug]: Commande après utilisation du crusher

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#717]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Après avoir utilisé le crusher certaines commandes sont inaccessibles comme le /home /sethome /feed ..

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
