### ISSUE TITLE
[Bug]: Minerais avec le crusher

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#718]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Quand les minerais apparaissent dans le crusher, si on veut les récupérer ils disparaissent, et ne réapparaissent pas suite à un /lobby

**Comment by Zeldown** [comment]
Hello @Phyzali aurais-tu un rec ? Je n'ai aucun soucis de mon côté

**Comment by aureliancnx** [comment]
L'issue n'ayant pas eu de réponse, je me permets de la fermer.
