### ISSUE TITLE
[Bug]: Stack Snow Golem

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#719]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Lors qu'on enleve la tete d'un snow et qu'il ce stack avec les autres (ceux avec la tete ce stack sur celui qui ne l'a pas) on ne récupère pas l'xp hunter cependant ils ne meurt pas deux sec après (ce soucis est uniquement pour ceux avec la tête)

### Qu'aurait-il dû arriver ?

Nous aurions dû récupéré de l'xp hunter

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
