### ISSUE TITLE
[Bug]: Fly Event LB "Là-Haut"

### ISSUE THREAD

**Issue by SirLink23** [Paladium-Developpement/Paladium-Issue#72]
### Pseudo InGame

the100crr

### Que s'est-il passé ?

Lorsque le joueur a eu l'event "Là-Haut" dans les LB il a gardé le fly
https://www.youtube.com/watch?v=LW5iNQuQuIo

### Qu'aurait-il dû arriver ?

Il aurait du perdre le fly

**Comment by aureliancnx** [comment]
Corrigé
