### ISSUE TITLE
Sort Mentalis non fonctionnel

### ISSUE THREAD

**Issue by Jabsyyy** [Paladium-Developpement/Paladium-Issue#723]
Lorsque l'on utilise le sort mentalis, il se déclanche bien mais on ne sait pas prendre la vue depuis le fantôme. 

Voici une vidéo : https://youtu.be/w7uOaJXN5Ko
Voici le report : 
![image](https://user-images.githubusercontent.com/92877608/185098822-bd21ce4c-e55c-4ad5-98f9-6d731b2c2542.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
