### ISSUE TITLE
[Bug]: Le magnet ne fonctionne plus

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#724]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Le magnet n'attire plus les objets vers le joueur qui le porte.
Quand on clic droit dessus il s'active bien (effet surbrillance) et le message dans le tchat comme quoi il est activé est bien noté mais il n'attire pas les objets
https://youtu.be/n84P6VDXngQ

### Qu'aurait-il dû arriver ?

Le magnet devrait attirer les objets vers le joueur

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
