### ISSUE TITLE
[Bug]: Enchantement récupération non fonctionnel

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#728]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

L'enchantement récupération ne donne pas l'effet escompté (il ne se passe rien quand on tue un mob avec une épée enchantée)

### Qu'aurait-il dû arriver ?

On devrait récupérer le loot du mob quand on le tue avec une épée enchantée récupération

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
