### ISSUE TITLE
[Bug]: Il est possible de poser des glueball dans le spawn

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#730]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Il est possible de poser des glueball dans le spawn, et notamment d'obstruer le point de spawn de tous les joueurs qui réalisent la commande /spawn (en posant la glueball pile sur le point de spawn central)

**Comment by Phyzali** [comment]
l'accès est bloqué, il faut cliquer sur le message pour se téléporter
https://www.youtube.com/watch?v=a-eMz4bs2Xk

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
