### ISSUE TITLE
[Bug]: Gros Bug Têtes de Wither

### ISSUE THREAD

**Issue by Eclair93** [Paladium-Developpement/Paladium-Issue#732]
### Pseudo InGame

Eclair93 

### Que s'est-il passé ?

Quand on pose un T4 Squelette dans le Nether en Minage

Les Loot des Squelettes changent et ils donnent des têtes de Wither. Ce qui fait que des gens se font des dizaines de millions grâce à ce bug

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
