### ISSUE TITLE
[Bug]: BCC reste affiché dans /f f une fois cassé par explosion

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#733]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Si des joueurs pillent un BCC de manière ''non prévue" par exemple via explosion d'une endium dyna, le BCC se casse.
Il reste affiché dans le /f f de la faction avec ses anciennes coordonnées. 
De même si la faction souhaite en racheter un elle le peut, mais elle ne peut pas le reposer cela indique : le base claim controller est déjà posé

Rec affichaghe suite à l'explosion : https://youtu.be/3CrdfKYjbQ0 
Rec suite à l'explosion, impossible de poser un nouveau: https://youtu.be/YblGwatgygs 

### Qu'aurait-il dû arriver ?

Il faudrait soit : désactiver les explosions comme moyen de casser le bcc
soit : supprimer le fait qu'il soit encore présent dans les informations de la fac si il est cassé par explosions

### Serveur

Naera

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
