### ISSUE TITLE
[Bug]: Bypass de la mise en avant au market

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#734]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Des joueurs arrivent à bypass la mise en avant sur le market (je ne sais pas comment ils font)
Mais par exemple : il y a le joueur Titancolossal qui pour mettre 64 blocs de Pala doit faire une mise en avant de 1M de money ce qui me semble peu probable. 
un joueur est aussi venu ts pour se plaindre de ça.

### Qu'aurait-il dû arriver ?

Il ne devrait pas savoir bypass la mise en avant du AH

**Comment by KraemerJoe** [comment]
Corrigé merci.
