### ISSUE TITLE
[Bug]: Stack de mobs one shoot par une épée avec Récupération dessus

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#735]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Lorsqu'on tape avec une épée récupération sur un stack de membre (t4), celui est one shoot et on ne récupère évidemment pas l'xp pour le métier hunter.

Vidéo --> https://youtu.be/N34U1MglMRs

### Qu'aurait-il dû arriver ?

Le stack ne devrait pas se faire one shoot.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
