### ISSUE TITLE
[Bug]: Travel Leggings

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#736]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Je n'ai pas l'effet speed III qui est censé être donné par le travel leggings

### Qu'aurait-il dû arriver ?

Je devrais avoir l'effet speed III

### Serveur

Keltis

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
