### ISSUE TITLE
[Bug]: Vanish

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#738]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

On ne peux plus retirer le vanish et le vanish admin

Si on essaye de retirer le vanish il nous dit qu'on est en vanish admin
Si on essaye de retirer le vanish admin, il nous dit qu'on est en vanish simple

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
