### ISSUE TITLE
[Bug][Faction]: f map auto 

### ISSUE THREAD

**Issue by Slyverito** [Paladium-Developpement/Paladium-Issue#739]
### Pseudo InGame

Slyverito45

### Que s'est-il passé ?

Lors de l'activation du /f map auto, les claims ne sont plus affichés dans le chat automatiquement.

### Qu'aurait-il dû arriver ?

Lors du changement de chunk, un "nouveau" f map aurait du apparaître dans le chat.

### Serveur

Soleratl

### Date et heure de la production du bug

20-08-22 15h40

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
