### ISSUE TITLE
[Bug]: Autocrafter (ne stoppe pas si full)

### ISSUE THREAD

**Issue by Caitline86** [Paladium-Developpement/Paladium-Issue#74]
### Pseudo InGame

Caitline1986

### Que s'est-il passé ?

Bonjour,

La machine continue de crafter les items malgré que la zone de récupération soit pleine.

D'autre part, il est impossible de shift clic pour déposer le matériel ou pour récupérer les éléments craftés.

Voici un rec: https://youtu.be/0MZnVGj_Drk

### Qu'aurait-il dû arriver ?

L'appareil devrait stopper les crafts car il peut arriver de ne pas toujours regarder la machine et ça consomme inutilement des ressources.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
Impossible de reproduire le bug

Cependant je fix le fait que le prix pour le craft des spikes en subrecipe ne consomme que 1 épée

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
