### ISSUE TITLE
[Bug]: Kick click droit

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#740]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Lorsqu'on fait un click droit avec la main vide sur un joueur en faction ou en minage on est kick au lobby avec comme erreur "Server error"

### Qu'aurait-il dû arriver ?

On devrait pas être kick

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
