### ISSUE TITLE
[Bug]: L'utilisation du cauldron clear son coeur

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#741]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Lorsqu'on utilise un chaudron( par exemple pour transformer du bois moddé en shiny), la transformation du bois avec une lightning fait clear le coeur du chaudron

### Qu'aurait-il dû arriver ?

Le coeur devrait rester en place

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
