### ISSUE TITLE
[Bug][Faction]: Ap claim par ma faction mais inutilisable

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#746]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Notre AP a été surclaim illégalement par la Az0x quand il y a eu les bugs AP.
Il y a quelques jours, Lorn s'est chargé de nous rendre notre AP, le claim est à nous mais on ne peut tjs pas build dedans.
L'Ap se trouve en -56/470 sortie N sur Solé.

### Qu'aurait-il dû arriver ?

On devrait pouvoir build dans notre ap

### Serveur

Soleratl

### Date et heure de la production du bug

depuis quelques semaines déjà

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. Nous allons investiguer la cause dès que possible.

Cordialement

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.
⚠️ Cependant, je ne ferme pas l'issue car je dois vous rendre l'AP une fois que le fix sera passé :) 

Cordialement,

**Comment by aureliancnx** [comment]
Bonjour,

Le problème est corrigé. Nous vous remercions du signalement. ✅ 
En cas de nouveau problème, n'hésitez pas à ouvrir un ticket

Cordialement,

**Comment by Danflaa** [comment]
Bonjour,

Pas de souci, merci à toi, à vous 😊
Bonne journée !

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :jeudi 25 août 2022 13:30
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Paladium-Developpement/Paladium-Issue] [Bug][Faction]: Ap claim par ma faction mais inutilisable (Issue #746)


Bonjour,

Merci pour le signalement de ce bug. ✔️

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.
⚠️ Cependant, je ne ferme pas l'issue car je dois vous rendre l'AP une fois que le fix sera passé :)

Cordialement,
