### ISSUE TITLE
[Bug][Faction]: /lobby qui fait crash dans un chunk (corrompu?)

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#747]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Des joueurs de la faction frozen viennent de claim une zone en 4X4 sur Luccento.
Depuis ce claim, dès qu'on souhaite réaliser la commande /lobby, notre jeu crash et se ferme (uniquement dans la zone claim); cela se produit uniquement pour la commande /lobby (par exemple /spawn fonctionne)

Me mp pour les coo exactes ;
Sinon /home valerian2112 ''hautbc''

### Qu'aurait-il dû arriver ?

La commande devrait fonctionner normalement dans leur claim

### Serveur

Luccento

### Date et heure de la production du bug

22/08 20h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Est-il possible d'avoir les logs client ?

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
