### ISSUE TITLE
[Bug]: Aucune possibilité de débind la combinaison Ctrl+c côté client

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#748]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

La combinaison Ctrl+c est bind côté client sur l'ancienne wheel des émotes de Fuze
Il n'est plus possible de debind cette combinaison de touche côté client alors que cette roue ne sert plus à rien
Report par un joueur qui utilise cette combinaison pour le pvp et ne peut pas la désactiver

### Qu'aurait-il dû arriver ?

Avoir la possibilité de debind cette touche ou simplement de supprimer l'ancienne wheel du jeu

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
