### ISSUE TITLE
[Bug]: Crash Sort ( Boss / Warzone ) 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#749]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Le sort Mentalis fait crash tous les joueurs aux alentours une fois l'âme du sort tué 

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
