### ISSUE TITLE
[Bug]: Affichage Market

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#750]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

J'ai mis en vente des items, mais ceux ci n'apparaissent pas dans la liste des items mise en vente (voir screen 1). Cependant, ils apparaissent bien quand on les recherche (voir screen 2)
![2022-08-23_22 18 00](https://user-images.githubusercontent.com/62394506/186258131-7d98c52f-d2e0-46f3-8c37-8836bb026e1f.png)
![2022-08-23_22 17 23](https://user-images.githubusercontent.com/62394506/186258204-d2c39fdf-56e4-4654-8766-d4a426972efe.png)

### Qu'aurait-il dû arriver ?

L'item devrait apparaître dans la liste des items mis en vente

### Serveur

Luccento

**Comment by KraemerJoe** [comment]
Merci, vu avec le joueur directement, bug d'affichage
