### ISSUE TITLE
[Bug]: Bug de dupli item (plate 4607) avec typesettingtable

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#751]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Quand on met plusieurs plate dans la typesettingtable et qu'on spam le clic droit sans item au préalable dans la main, les plates se duplliquent à l'infini.

### Qu'aurait-il dû arriver ?

pas de duppli 

### Serveur

Naera

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
