### ISSUE TITLE
[Bug]: Crusher

### ISSUE THREAD

**Issue by Grandpou** [Paladium-Developpement/Paladium-Issue#753]
### Pseudo InGame

Grandpou

### Que s'est-il passé ?

Le crusher ne fonctionne pas, il ne donne pas l'endium nugget même si la barre de progression est à 100%
Testé le 22 ou 23 Aout sur Neolith

### Serveur

Neolith

**Comment by Zeldown** [comment]
:x: Le crusher ne donne un endium que à 75% d'avoir un endium même avec 100%
