### ISSUE TITLE
[Bug]: Commande Opérateur 

### ISSUE THREAD

**Issue by PierreLeLonie01** [Paladium-Developpement/Paladium-Issue#754]
### Pseudo InGame

PierreLeLonie

### Que s'est-il passé ?

Lorsque l'on tape la commande /money set PSEUDo sur un joueur il est impossible de faire passer la commande lorsque le joueur est déconnecté. Pareil lorsqu'on le veut voir la money d'un joueur connecté.

### Qu'aurait-il dû arriver ?

Affichage de la monnaie du joueur et le changement de la monnaie du joueur. 

### Serveur

Neolith

**Comment by KraemerJoe** [comment]
Si tu peux vérifier stp car à priori ca fonctionne si le joueur existe et s'est déjà connecté depuis la migration, que ce soit pour voir sa monnaie ou pour la set

**Comment by aureliancnx** [comment]
@PierreLeLonie01

**Comment by PierreLeLonie01** [comment]
C'est good, ça a fonctionné, merci
