### ISSUE TITLE
[Bug]: Le LB FastLearner ne donne pas de récompense une fois le dailyxp passé

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#755]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Lorsqu'un joueur dépasse sa limite d'xp quotidienne et ouvre le LuckyBlock ''FastLearner'', il reçoit bien dans le tchat le message comme quoi il a gagné un level dans X métier, cependant il ne reçoit pas vraiment l'xp dans ses métiers. 

### Qu'aurait-il dû arriver ?

Le fait d'atteindre le daily xp ne devrait pas influencer sur les récompenses de LuckyBlock

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
