### ISSUE TITLE
[Bug][Faction]: Bug Ap (Fac Enosya) nord soléralt (Aurelian)

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#756]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Les joueurs peuvent build dans notre ap (même bug Aurelian, je t ai mp discord avec le screen)
Ils nous ont tous les blocs.

### Serveur

Soleratl

### Date et heure de la production du bug

28/08 à +/- 13h45

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
