### ISSUE TITLE
[Bug]: Problemes avec les amulettes / Voyance et Combat

### ISSUE THREAD

**Issue by PetitBiscuit74** [Paladium-Developpement/Paladium-Issue#758]
### Pseudo InGame

PetitBiscuit_74

### Que s'est-il passé ?

La vie et le pseudo du joueur ne devraient pas être visible aux autres personnes 

### Qu'aurait-il dû arriver ?

Le pseudo et la vie du joueur devraient rester cacher aux yeux des autres

### LOG

https://www.youtube.com/watch?v=jlu-FRGtZ2U

**Comment by Zeldown** [comment]
:x Ces amulettes sont volontairement désactivée, elles seront retirées du jeu à l'avenir.
