### ISSUE TITLE
[Bug]: Use bug home (sethome/delhome) 

### ISSUE THREAD

**Issue by Jabsyyy** [Paladium-Developpement/Paladium-Issue#759]
### Pseudo InGame

Jabsyyy

### Que s'est-il passé ?

Un vieux bug a été remonté ajd, des joueurs ont réussi à descendre dans une bc en utilisant le usebug home.
C'est à dire qu'il met un home dans les protections, il se déco, il revient, il sneak et il redescend en remettant un home, et avec ce bug tu peux descendre dans une bc facilement. 

Voici un rec mais peu descriptif : https://youtu.be/gQtBYDHh1dI

### Qu'aurait-il dû arriver ?

En revenant à un home on ne devrait pas descendre et pouvoir use bug si facilement pour pilier.

Désolé c'est un use bug assez technique, compliqué à reproduire et également à expliquer. 

### Serveur

Luccento

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
