### ISSUE TITLE
[Bug]: Palapass - mélange des quêtes

### ISSUE THREAD

**Issue by calixtass** [Paladium-Developpement/Paladium-Issue#763]
### Pseudo InGame

calixtas

### Que s'est-il passé ?

Les évènements quêtes journalières et quêtes de saison se mélangent selon les connexions / réussites

![Screenshot_1548](https://user-images.githubusercontent.com/112474861/187456348-d5d3bfa2-4ed9-4597-9811-ec424835cfbf.png)
![Screenshot_1549](https://user-images.githubusercontent.com/112474861/187456388-44cd79e5-c082-4532-a105-d2904506d097.png)

Désolée je n'ai pas réussi à comprendre quelles étaient les bonnes quêtes et reproduire les mélanges pour savoir comment résoudre le pb - les messages dans le chat semblent répondre à une classification pour autant qui n'est pas non plus celle de l'affichage - exemple ici alors que la quête était affichée en journalière :

![Screenshot_1550](https://user-images.githubusercontent.com/112474861/187456841-575b3383-fd65-4324-bc74-4cdc893d7f85.png)

### Qu'aurait-il dû arriver ?

Classification stable des événements journaliers et saisonniers et messages dans le chat correspondants.

**Comment by KraemerJoe** [comment]
Hello merci pour le report, il semble que tu sois sur l'ancienne MAJ ( on le reconnait à cause des flêches manquantes à droite et à gauche de la barre)
Est-ce que tu peux me confirmer que tu ne rencontres plus ce soucis ? Merci.
