### ISSUE TITLE
[Bug]: Palapass - fautes d'orthographe / syntaxe

### ISSUE THREAD

**Issue by calixtass** [Paladium-Developpement/Paladium-Issue#764]
### Pseudo InGame

calixtass

### Que s'est-il passé ?

Je n'ai pas tout relevé mais faire relire l'ensemble des éléments du GUI / quêtes du Palapass 

Exemples de fautes :-//
![Screenshot_1539](https://user-images.githubusercontent.com/112474861/187457783-18953563-d6ec-4908-9112-a1337066d1ca.png)
![Screenshot_1540](https://user-images.githubusercontent.com/112474861/187457810-15a5253a-98d0-4443-8274-1ebf0fb94c20.png)
![Screenshot_1541](https://user-images.githubusercontent.com/112474861/187457832-724bdb5a-a214-43a7-a7d9-769e6c7aa06a.png)

### Qu'aurait-il dû arriver ?

-

**Comment by KraemerJoe** [comment]
Merci pour le report, la créa s'occupera de faire corriger la configuration avant la release, je close.
