### ISSUE TITLE
[Bug]: Kick Farmland lorsqu'on kill un mob

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#765]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

On est kick du serve au moment de kill un mob

### Qu'aurait-il dû arriver ?

on ne devrait pas etre kick

### Serveur

Farmland

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
