### ISSUE TITLE
[Bug]: pop-up combat

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#77]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

La pop-up en bas à droite de l'écran "vous êtes désormais en combat" apparait a la fin du timer

La pop-up en bas à droite de l'écran "vous n'êtes désormais plus en combat" apparait au début du timer

### Qu'aurait-il dû arriver ?

l'inverse

### Serveur

Minage

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
