### ISSUE TITLE
[Bug][Faction]: Création faction reset texte lors edit blason

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#771]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lors de la création d'une faction, si on marque un nom puis qu'on clique sur le blason, que l'on le modifie puis que l'on valide la modification, on revient au menu de création mais le nom de faction est clear 

### Serveur

Soleratl

### Date et heure de la production du bug

01 09 22   16:03

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
