### ISSUE TITLE
[Bug][Faction]: Gui ap prix de vente sans être en vente

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#772]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/187933695-072ee71d-3a02-4327-bb32-0815702af633.png)
L'ap m'appartient, quand j'ouvre le gui avec mon compte (ou un autre hors de ma fac), j'ai un prix qui s'affiche alors qu'il n'est pas en vente.
![image](https://user-images.githubusercontent.com/92928910/187933866-fcbfe0c2-a1c5-4bb5-af40-85199a2ba1d7.png)

### Serveur

Soleratl

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
