### ISSUE TITLE
[Bug][Faction]: Banque de faction, nom d'action achat ap

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#774]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/187935741-3daf19ab-c292-4f91-bf6d-d7190b1fedff.png)

### Qu'aurait-il dû arriver ?

Il faudrait mettre ap_buy (ou même achat ap)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
