### ISSUE TITLE
[Bug][Faction]: Banque ordre d'affichage

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#775]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

L'action la plus récente devrait s'afficher tout en haut et non tout en bas
![image](https://user-images.githubusercontent.com/92928910/187936130-79402ff1-627d-4a3a-a225-cffe90062646.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
