### ISSUE TITLE
[Bug][Faction]: Ap vente entre particulier

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#776]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Le vendeur ne reçoit pas l'argent suite à l'achat de son ap
![ap bug](https://user-images.githubusercontent.com/92928910/187940850-25b1346e-6df5-4014-812e-5820332aecc2.gif)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
