### ISSUE TITLE
[Bug][Faction]: Réduction ap achat entre particulier

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#777]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

La réduction ne devrait pas s'appliquer pour les achats d'ap entre particulier 
![ap buy reduction](https://user-images.githubusercontent.com/92928910/187944162-f9cde8b3-5417-4998-b0bd-f917aeee05c6.gif)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
