### ISSUE TITLE
[Bug]: Pala pass quête unclaim finder

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#778]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

La quête du pala pass qui demande de craft l'unclaim finder vert dans la palamachine est impossible car il ce craft dans une table de craft, la quête est donc impossible à remplir.

### Serveur

Global

**Comment by KraemerJoe** [comment]
Corrigé merci
