### ISSUE TITLE
[Bug]: PalaPass Récompense de quête

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#779]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lors des récompense du Palapass, un joueur à reçu 64 billet au lieu de 64 pala ingot, aucune preuve sauf que j'ai récup les billets, c'est normalement impossible d'en avoir.

### Serveur

Farmland

**Comment by KraemerJoe** [comment]
Corrigé merci
