### ISSUE TITLE
[Bug]: Lb findium bug Boule de Cristal

### ISSUE THREAD

**Issue by Celtix27** [Paladium-Developpement/Paladium-Issue#783]
### Pseudo InGame

Celtix27

### Que s'est-il passé ?

Un joueur a ouvert un lb en findium et obtenu le lot Boule de cristal et n'a rien recu. Malheureusement le joueur n'a pas de rec.
pseudo du joueur : SlowiZz 
Regarder si nous pouvons le rembourser

### Qu'aurait-il dû arriver ?
Obtenir un loot, mais aucune idée c'est quoi
_No response_

**Comment by KraemerJoe** [comment]
Salut, la voyante donne un effet de lucky block aléatoire, il a du recevoir quelque chose sans s'en rendre compte, je viens de tester, cela fonctionne bien.
