### ISSUE TITLE
[Bug][Faction]: Gui invitation en cours

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#784]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il manque le blason de la faction et il faudrait aligner le nom de la faction (gui invitation en cours quand on a pas de faction)
![image](https://user-images.githubusercontent.com/92928910/188102333-9bf87740-7568-4979-b2e9-bccbce9a1359.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
