### ISSUE TITLE
[Bug]: PALAPASS Quête minerais paladium + minerais amethyst

### ISSUE THREAD

**Issue by Volpe0008** [Paladium-Developpement/Paladium-Issue#785]
### Pseudo InGame

Volpe08

### Que s'est-il passé ?

Il est impossible de faire la quête où il faut casser 64 minerais de pala idem pour la quête d'améthyst cela ne les prend pas en compte

### Qu'aurait-il dû arriver ?

Cela aurai dû être pris en compte dans la quête

### Serveur

Minage

**Comment by KraemerJoe** [comment]
Fonctionnel merci
