### ISSUE TITLE
[Bug][Faction]: Manque traduction après vente direct ap

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#787]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/188113865-20d60443-8a48-429e-a6bd-68360a52778f.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
