### ISSUE TITLE
[Bug]: Palapass obsi (La taupe)

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#789]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Quand on mine de l'obsidienne la quête n'avance pas 
https://www.youtube.com/watch?v=j_kGzWuwPPM

**Comment by KraemerJoe** [comment]
Est-ce que le bug est toujours d'actualité ? ( sur un serveur ayant redémarré )

**Comment by KraemerJoe** [comment]
![Uploading image.png…]()

**Comment by KraemerJoe** [comment]
![image](https://user-images.githubusercontent.com/40207750/188242202-fe6a2320-7b65-463b-bf1d-3581048b9f4b.png)
