### ISSUE TITLE
[Bug]: Le jeu crashe si unclaim helmet bleu aux AP

### ISSUE THREAD

**Issue by Caitline86** [Paladium-Developpement/Paladium-Issue#79]
### Pseudo InGame

Caitline1986

### Que s'est-il passé ?

Bonsoir,

A plusieurs reprises, le crash du jeu s'est répété. Au début, il semblait que c'était suite aux tables de craft mais après une demande à Aurelian, il s'est avéré que ce n'était pas possible.

Seulement cela s'est reproduit et c'est tellement il y a de pourcentages à charger d'un coup sur l'unclaim finder bleu présent sur le casque.

Pas de rec dispo. Cela produit également des difficultés à se reconnecter au jeu même après plusieurs fermetures du launcher.

### Qu'aurait-il dû arriver ?

Aucun crash suite à la tp.

**Comment by aureliancnx** [comment]
Est-ce que tu peux me fournir les logs du jeu ?
