### ISSUE TITLE
[Bug]: Récompense Palapass "5 cauldron block"

### ISSUE THREAD

**Issue by Ikenakkk** [Paladium-Developpement/Paladium-Issue#790]
### Pseudo InGame

Ikenak

### Que s'est-il passé ?

Lorsqu'un joueur récupère les "5 cauldron blocs" soit la récompense des 2000 points du palapass, il reçoit en réalité 5 cauldron cores

Voici le rec d'un joueur qui illustre le problème : https://www.youtube.com/watch?v=96kC0iQzjtY&t=26s&ab_channel=Luna3181
( à 0;25 )

### Qu'aurait-il dû arriver ?

Le joueur aurait du reçevoir 5 cauldron blocs

### Serveur

Global

**Comment by KraemerJoe** [comment]
Problème corrigé avec le changement des ID, si le problème survient encore merci de réopen 
merci
