### ISSUE TITLE
[Bug]: Palapass enchanté une pioche en paladium

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#792]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

L'évent enchanté une pioche en pala, avec une table d'enchant lvl 30 ne marche pas

**Comment by KraemerJoe** [comment]
Est-ce que le bug est toujours d'actualité ? ( sur un serveur ayant redémarré )

**Comment by KraemerJoe** [comment]
![image](https://user-images.githubusercontent.com/40207750/188242159-7ff17fa0-52ba-4d3e-b976-35ea5c04af65.png)
