### ISSUE TITLE
[Bug]: Epée améliorée PalaPass

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#797]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Dans la description de la quête c'est écrit enchanter une pioche en paladium alors qu'il faut enchanter une épée en paladium 
![image](https://user-images.githubusercontent.com/104795165/188264749-5f49350f-48a2-4547-a5c2-a5e61402dff3.png)

**Comment by KraemerJoe** [comment]
Merci, corrigé dans le fichier de config.
