### ISSUE TITLE
[Bug]:Quêtes de minage de blocs dans le Palapass

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#798]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Il est possible de compléter les quêtes de minage du Palapass (minerais, obsidienne...) en posant le bloc en question et en le minant après.
Vidéo du problème [ici](https://youtu.be/4n4ELERZzyE).

### Serveur

Global

**Comment by KraemerJoe** [comment]
Merci, corrigé pour la prochaine MAJ
