### ISSUE TITLE
[Bug]: Impossible d'xp avec la cobble 

### ISSUE THREAD

**Issue by Ikenakkk** [Paladium-Developpement/Paladium-Issue#802]
### Pseudo InGame

Ikenak

### Que s'est-il passé ?

Lorsqu'un joueur casse de la cobblestone il ne gagne pas d'xp de mineur.

Voici deux recs de deux joueurs différents ayant rencontré le bug :
- https://www.youtube.com/watch?v=5or8FVMvwUM&ab_channel=TomLegrand
- https://www.youtube.com/watch?v=NbUeEiSxGDo&ab_channel=thomasefe

A noter que le joueur gagne quand même de l'xp avec le fer donc c'est bien la cobble qui pose problème 

### Qu'aurait-il dû arriver ?

Le joueur aurait du recevoir de l'xp pour son métier de mineur.

### Serveur

Global

**Comment by KraemerJoe** [comment]
Merci, sera corrigé à la prochaine MAJ
