### ISSUE TITLE
[Bug]: Graine Infini Urgent 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#809]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Voir le bug avec la vidéo
https://www.youtube.com/watch?v=Jkf8iPemlPc

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
