### ISSUE TITLE
[Bug][Faction]: Inspection de faction icone position classement incorrecte 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#812]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

L'icone représentant la position de la faction est incorrecte. La faction est première et n'a pas le blason 1er. Dans tous les cas, même si la faction n'était pas dans les 3er, il y aurait un pb car il devrait être avec le casque en argent.
![image](https://user-images.githubusercontent.com/92928910/188320114-bf26a3eb-beea-4643-9230-24256311dd8b.png)
![image](https://user-images.githubusercontent.com/92928910/188320118-135045d1-4a40-4627-84c1-9d094ae4ac3c.png)
![image](https://user-images.githubusercontent.com/92928910/188320451-0d5d1396-8fe3-41ee-b0bc-d484ad40a2b9.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
