### ISSUE TITLE
[Bug]: Bug moutons spongieux farmland + faction

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#814]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

Lorsqu'on veut créer un mouton spongieux en farmland, il disparait. (farmland)
Lorsuq'on veut récupérer l'éponge mouillée à l'aide de cisailles, c'est impossible. (serveur faction)

### Qu'aurait-il dû arriver ?

on devrait pouvoir récupérer la laine

**Comment by aureliancnx** [comment]
Bonjour

Cette issue semble être un duplicate de celle ci : https://github.com/Paladium-Developpement/Paladium-Issue/issues/729
