### ISSUE TITLE
[Bug][Faction]: BCC impossible à poser

### ISSUE THREAD

**Issue by PetitBiscuit74** [Paladium-Developpement/Paladium-Issue#815]
### Pseudo InGame

PetitBiscuit_74

### Que s'est-il passé ?

Le joueur à essayer de poser un BCC dans son claim, après plusieurs essaie il lui est impossible de le poser (même de leader de faction) avec le message suivant afficher > "Veuillez attendre 14 jours entre la pose d'un autre base claim controller"

Informations complémentaires

> Le bcc possède des blocs libres autour de lui
> La faction est plus que level 10
> Dernier Bcc de faction poser début juillet 
> Vidéo explicative : https://www.youtube.com/watch?v=0_t4SQ76uts

### Qu'aurait-il dû arriver ?

Le joueur aurait du pouvoir poser de BCC 

### Serveur

Manashino

### Date et heure de la production du bug

Heure 9:00 le 06/09/2022 

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by KraemerJoe** [comment]
@aureliancnx @Zeldown il faudrait récupérer dans l'API la dernière update des BCC de la Overlord du coup pour voir, moi je ne peux pas

**Comment by aureliancnx** [comment]
Bonjour @PetitBiscuit74 

Le problème est-il toujours d'actualité ?

**Comment by aureliancnx** [comment]
N'ayant pas eu de réponse ni de signalement similaire pour le moment, je ferme ce ticket.
