### ISSUE TITLE
[Bug]: Palapass, Mineur débutant, blocs comptés x4

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#817]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

En minant des minerais d'améthyste pour la quête **Mineur débutant** du Palapass, les blocs minés étaient comptés **4 fois dans la quête du Palapass**, ce qui fait que j'ai du miner **32 minerais d'améthyste** pour la quête (au lieu de 128).
Edit: Je viens d'avoir le même bug avec l'obsidienne
Vidéo du bug [ici](https://youtu.be/dOR8Lv9uGTM)

### Serveur

Minage

**Comment by Celtix27** [comment]
J'ajoute également que c'est possible avec l'obsidienne et que l'enchantement fortune est activé sur le minage de l''obsidienne. Donc en résumé, si je mine 1 d'obsi, parfois le palapass le compte pour 1/2/3 block miner et non 1.

**Comment by KraemerJoe** [comment]
@terrainwax @Zeldown @aureliancnx problème lié au Palamod plusieurs events dont: breakblock, craft, smelt appellent 4x les events, non causé par le Palapass mais aucune piste sur la cause

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
