### ISSUE TITLE
[Bug][Faction]: Gui mdf texte et image mal incorporé 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#819]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/188854157-894719bd-a408-4380-bf56-154ebbd0f4c5.png)
Décalé l'heure d'expiration qui est trop à droite

![image](https://user-images.githubusercontent.com/92928910/188854260-2e15a08e-df53-4562-b9a2-42ba9337bd27.png)
Réduire la taille des têtes de joueurs et center le nom de faction

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
texte centré, il reste le scale de la tête

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
