### ISSUE TITLE
[Bug][Faction]: Mdf pas de rg

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#820]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il n'y a pas de région créé pour les maisons de factions

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Peux tu mettre un titre sur tes issues

**Comment by aureliancnx** [comment]
Peux tu mettre un titre sur tes issues

**Comment by Akysooo** [comment]
Yep pardon

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
