### ISSUE TITLE
[Bug]: Timeout si kick lors de la connexion

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#821]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Lorsqu'un joueur se connecte à Paladium et se fait kick lors de la connexion à un lobby (ex : kick car le jeu n'est pas à jour), il reçoit une erreur Timed Out au lieu du motif du kick en question.

### Serveur

Lobby

### LOG

https://paste.rocks/?3d6ab40f8fa1dac6#9epms4CU6txHVDiN1emsZxsiVkf13WmZxtzFcztCRVb

**Comment by aureliancnx** [comment]
Bonjour,

Cela peut arriver et est dû plutôt à la connexion netty avec MC qu'autre chose. Les kicks pour ban etc sont cependant bien pris en compte. Il leur suffit de juste relancer le jeu si le jeu n'est pas à jour
