### ISSUE TITLE
[Bug]: Attaque à partir du spawn (arc)

### ISSUE THREAD

**Issue by xh0ney** [Paladium-Developpement/Paladium-Issue#828]
### Pseudo InGame

xh0ney__ // Phenix259 (personne qui a signalé le bug)

### Que s'est-il passé ?

Possibilité d'attaquer les joueurs en warzone à partir du spawn avec un arc.

### Serveur

Imbali

### Date et heure de la production du bug

13/09/22 vers 21h30

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
