### ISSUE TITLE
[Bug]: Craft Stick of God qui compte pour un autre joueur.

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#830]
### Pseudo InGame

Alpha334

### Que s'est-il passé ?

Le joueur craft un Stick of God pour sa qupete du palapass. Celui-ci ne compte pas pour sa quête, mais compte pour la quête de son ami.

### Qu'aurait-il dû arriver ?

Le joueur craft un Stick of God pour sa qupete du palapass. Sa quête s'incrémente de 1.

### LOG

Record de démonstration :
https://www.youtube.com/watch?v=7uI6H8KGHtU

**Comment by KraemerJoe** [comment]
Hello, ce n'est pas un bug, c'est la dernière personne a clique droit sur la machine avant le craft qui aura la comptabilisation.
