### ISSUE TITLE
Le jetpack est utilisable en warzone

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#831]
### Pseudo InGame

M4GiiKKzZz

### Que s'est-il passé ?

Un joueur inconnu utilisé le jetpackk en warzone, alors qu'il n'est théoriquement pas possible de l'utiliser.

### Qu'aurait-il dû arriver ?

Le jetpack n'aurait pas du fonctionner

**Comment by aureliancnx** [comment]
Bonjour,

Ce bug a-t-il pu être reproduit d'une façon ou d'une autre ?

Cordialement,

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
