### ISSUE TITLE
[Bug][Faction]: ap message panneau vente warzone

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#832]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Un ap quand il est en vente "admin", en gros qu'il est détenu par la faction warzone a le même message qu'un vente entre joueur ![image](https://user-images.githubusercontent.com/92928910/190224029-05a515a5-b576-48db-a4f6-7cdfbdd728a1.png)alors qu'il devrait avoir le message personnalisé suivant

![image](https://user-images.githubusercontent.com/92928910/190224013-ba00babd-ff9e-457f-8576-01acf00b3f91.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
