### ISSUE TITLE
[Bug][Faction]: Ap problème affichage possédé panneau

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#833]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Le nom de la faction propriétaire n'est pas affiché sur le panneau + l'affichage doit être en mode nn à vendre
![image](https://user-images.githubusercontent.com/92928910/190226288-17eb69b1-9e11-4b59-afa0-f07338c10773.png)
![image](https://user-images.githubusercontent.com/92928910/190226306-ba9c688c-cf83-4e13-a829-167013571af5.png)
![image](https://user-images.githubusercontent.com/92928910/190226510-0b3dd5b4-828c-402c-9e79-a0e125668531.png)

### Serveur

Naera

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Est-il possible de me fournir la procédure de reproduction du bug ? Le bug a-t-il juste été trouvé en regardant le panneau ou il a été retesté ? ...

Cordialement

**Comment by Akysooo** [comment]
Il vient d'être setup

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
