### ISSUE TITLE
[Bug][Faction]: Ap impossible de le créer

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#834]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Ca me met qu'il existe déjà mais je peut pas l'enlever car il n'existe pas. (Cela m'arrive sur une partie du serveur)
![image](https://user-images.githubusercontent.com/92928910/190230950-8a232fc0-0675-4589-b0c7-2c218c19e5ec.png)

### Serveur

Untaa

### Date et heure de la production du bug

20h12 14/09

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Et en faisant un unclaim admin ?

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
