### ISSUE TITLE
[Bug]: Possibilité de se freeze dans les airs

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#835]
### Pseudo InGame

M4GiiKzZz

### Que s'est-il passé ?

Il est possible de se Freeze dans les airs (avec un handglider) durant un certain temps, notamment en warzone pour laisser le temps défiler. Le freeze interviendrait côté client, mais serait aussi effectif côté server. 

Note : Il est possible que le freeze soit possible aussi bien en l'air que sur terre en fonction de ou ce trouve le joueur. Mais cette technique est actuellement utilisé pour échaper au pvp en se bloquant dans le ciel.

### Qu'aurait-il dû arriver ?

Le joueur avec le handglider devrait continuer de descendre au lieu de rester fixe à voler.

### LOG

Lien de l'exemple vidéo :
https://www.youtube.com/watch?v=vkYa87jFbGw

**Comment by aureliancnx** [comment]
Bonjour,

Il s’agit d’un problème inhérent à Minecraft de base dont nous ne pouvons pas faire grand chose pour le moment vu le fonctionnement de celui-ci.

**Comment by Zeldown** [comment]
❌ Ce bug était provoqué par LWJGL ne peut être corrigé, je ferme donc l'issue.
