### ISSUE TITLE
[Bug]:  Home finder

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#838]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Le home finder ne fonctionne toujours pas.
Les joueurs peuvent voir les entités mais ils ne peuvent pas les mettre en combat
Ce qu'il le rend toujours inutilisable

**Comment by RedFlys72** [comment]
bug toujours en vigueur

**Comment by KraemerJoe** [comment]
Refonte en cours.
