### ISSUE TITLE
[Bug]: Eponge

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#840]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les éponge n'absorbe pas l'eau, que ce soit dans un claim ou hors claim

### Qu'aurait-il dû arriver ?

Absorber les sources d'eau

### Serveur

Imbali

**Comment by Zeldown** [comment]
❌ L'éponge fonctionne très bien.
