### ISSUE TITLE
[Bug]: Arc et xp hunter

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#841]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lors de l'utilisation d'un arc, la mort du mobs ne donne pas d'exp hunter, cependant lors de l'utilisation d'un épée, l'exp est bien donné

### Qu'aurait-il dû arriver ?

Donné de l'exp peu importe la méthode de mort

### Serveur

Imbali

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
