### ISSUE TITLE
[Bug]: Farm à graine , sans bone meal

### ISSUE THREAD

**Issue by SKOR3N** [Paladium-Developpement/Paladium-Issue#842]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Un joueur vien de me report un bug, concernant les claims factions. Le joueur se trouvant dans un claim ennemi ne peut pas casser les hautes herbes, mais obtiens les graines moddées. Il peut farmer les graines sans bonne meal et plus rapidement qu'une ferme à graine normale.

### Qu'aurait-il dû arriver ?

Les hautes herbes ne devraient pas drop les graines, lorsqu'ils sont brisés dans un claim ennemi.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
