### ISSUE TITLE
[Bug]: armurier flemmard 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#844]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

j'ai eu un joueur qui a eu un soucis avec cette quêtes il a essayer de réparer des armure, et tout avec plusieurs ring ou avec plusieurs manière mais sa ne valide pas la quêtes et sa ne la charge pas du tout il a même essayer de réparer plus de 500 

### Qu'aurait-il dû arriver ?

sa aurai du validé la quetes 

### LOG

https://discord.com/channels/@me/1021127184712224849/1021127368833761391

**Comment by KraemerJoe** [comment]
Duplicata je close
https://github.com/Paladium-Developpement/Paladium-Issue/issues/855
