### ISSUE TITLE
[Bug]: Crash client lorsque nous pechons  sur Neolith

### ISSUE THREAD

**Issue by Celtix27** [Paladium-Developpement/Paladium-Issue#845]
### Pseudo InGame

Celtix27

### Que s'est-il passé ?

Lorsque nous faisons un click droit avec la souris avec une canne a pêche en main, nous crachons client.

### LOG

[latest.log](https://github.com/Paladium-Developpement/Paladium-Issue/files/9595010/latest.log)

**Comment by KraemerJoe** [comment]
Est-ce que le soucis est toujours présent ?
Personnellement je ne l'ai pas
