### ISSUE TITLE
[Bug][Helios]: Couleurs onglets chat

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#846]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

En redémarrant le jeu, si on a changé les couleurs des onglets du chat, celles-ci se réinitialisent.

### Qu'aurait-il dû arriver ?

Les couleurs devraient rester les mêmes qu'en fermant le jeu.

### Serveur

Global

**Comment by aureliancnx** [comment]
Bonjour,

Le problème est-il d'actualité ?

**Comment by Telco43** [comment]
Bonjour, le problème est en effet toujours d'actualité

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
