### ISSUE TITLE
[Bug]: Clear du Haut-Parleur

### ISSUE THREAD

**Issue by PetitBiscuit74** [Paladium-Developpement/Paladium-Issue#847]
### Pseudo InGame

PetitBiscuit_74

### Que s'est-il passé ?

A chaque fois qu'un joueur prend ou dépose un haut-parleur dans un coffre ou un enderchest l'objet clear totalement de sont inventaire ou celui du coffre.

Voici un record pour expliquer le souci > https://www.youtube.com/watch?v=VbNBPpJicRo

### Qu'aurait-il dû arriver ?

Le haut parleur ne devrait pas être clear quand il passe d'un inventaire à l'autre

### Serveur

Luccento

**Comment by KraemerJoe** [comment]
Salut, est-ce que ce bug est toujours d'actualité ?

**Comment by KraemerJoe** [comment]
Fermé étant donné le fonctionnement et le non retour, merci
