### ISSUE TITLE
[Bug]: Palapass item a crafter compter plusieurs fois

### ISSUE THREAD

**Issue by Phyzali** [Paladium-Developpement/Paladium-Issue#848]
### Pseudo InGame

Physali

### Que s'est-il passé ?

Lors des quêtes ou il faut crafter des items comme jukebox, laine rouge .. si on les récupères un par un en gardant les items  en main, ils sont comptabiliser en plus 
Ici sur le rec j'ai craft 3 jukebox au lieu de 5
https://www.youtube.com/watch?v=KSxug7Dynj8

### Qu'aurait-il dû arriver ?

Les items que l'on tien ne devraient pas être pris en compte dans la quête

**Comment by KraemerJoe** [comment]
Bug lié au Palamod, introuvable jusqu'à présent.

**Comment by KraemerJoe** [comment]
Même raison que https://github.com/Paladium-Developpement/Paladium-Issue/issues/817
