### ISSUE TITLE
[Bug]: palier 50 % LuckyStats

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#85]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Arriver au palier 50% du luckystats, on obtiens 21 super beacon

### Qu'aurait-il dû arriver ?

On devrait en obtenir un seul

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
