### ISSUE TITLE
[Bug]: NPE dans la GUI du menu échap

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#851]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Le jeu crashe lorsque le menu Echap est ouvert. Un NPE est indiqué dans les logs.

### LOG

https://paste.rocks/?fb4578be4a6a85bf#C61FKhTrBQhmSUknPg6xVzHdtdeo48LZrhE5qkk4zemZ

**Comment by KraemerJoe** [comment]
Bonjour,
Possibilité d'avoir plus de précision ?
Personnellement mon menu échap ne cause aucun soucis.

**Comment by AlxTNF** [comment]
Bonjour.

Le problème a été depuis résolu. Je ferme l'issue.
