### ISSUE TITLE
[Bug]: NPE dans la Natural Box

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#852]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Lors de l'ouverture de la Natural Box, le jeu des joueurs crashe. Un NPE s'affiche dans les logs du jeu

### LOG

https://paste.rocks/?aa2cc43572dc50de#DvuQqwD3CWKdTFuGMZ531g2tGmGR2ib7CECDZf8nCho9

**Comment by Zeldown** [comment]
:x: Le paste a expiré, ne voyant aucune autre issue similaire, je ferme celle-ci.
