### ISSUE TITLE
le /shop fait crash le jeu en minage.

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#853]
### Pseudo InGame

legamer72270

### Que s'est-il passé ?

Quand on tente d'ouvrir le /shop en minage, le serveur nous kick, entrainant parfois le crash du jeu.

### Qu'aurait-il dû arriver ?

Le /shop aurait du pouvoir s'ouvrir et être utilisé normalement, sans kick, ni crash.

### Serveur

Minage

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
