### ISSUE TITLE
[Bug][Faction]: La commande /f elo dump FACTION ne fonctionne plus

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#858]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

La commande /f elo dump FACTION ne fonctionne plus, elle n'affiche pas l'elo gagnée

### Qu'aurait-il dû arriver ?

Elle devrait afficher le nombre d'elo gagné

### Serveur

Global

### Date et heure de la production du bug

20h le 23 septembre

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Après vérification, il semblerait que ce soit notre hébergeur de dump textuels qui n'accepte plus nos requêtes. Une autre solution sera envisagé prochainement.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
