### ISSUE TITLE
[Bug][Faction]: Problème AP Imbali

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#859]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Deux soucis remontés pour un AP acheté sur Imbali aujourd'hui par la ShadowsRaven : 
- Un gradé endium a acheté un AP mais il a payé le prix fort (700k) (vérifié dans la banque de fac)
- L'AP est bien a eux mais ils sont dans l'impossibilité de construire / poser des blocs / détruire

### Qu'aurait-il dû arriver ?

Le prix aurait du être de 490k
Une fois l'AP acheté les joueurs de la faction devraient pouvoir l'aménager

### Serveur

Imbali

### Date et heure de la production du bug

23/09 à 01h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Camoouchat** [comment]
Coo de l'AP en question : 90 70 -450

**Comment by aureliancnx** [comment]
Les AP sur cette zone sont désactivés pour le moment avec une region. Ce n'est pas un bug

**Comment by Camoouchat** [comment]
Hello, à ce sujet, j'ai un joueur qui me demande si il peut acheter un AP tout de même sur Imbali pour ''réserver'' la place ou si tout va être unclaim all quand tu vas reset le plugin?

**Comment by aureliancnx** [comment]
Je ne conseille pas de faire d'achat d'AP dans cette zone en attendant la réactivation de la possibilité de construire à nouveau, par mesure de sécurité.
