### ISSUE TITLE
[Bug]: kick pour fly avec le jetpack

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#862]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

quand on utilise un jet pack plusieurs fois pour aller plus haut, sa nous fait kick du serveur  pour fly 

### Qu'aurait-il dû arriver ?

sa ne devrais pas nous faire kick pour fly 

### LOG

https://www.youtube.com/watch?v=6jq9ZZxBJfM

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
