### ISSUE TITLE
[Bug]: dimension mineur 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#863]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

plusieur joueur et moi meme on a un soucis on a bien créer la dimension mineur 
sa nous met au lobby en attendant quelle ce prépare et au moment de la création sa nous kick et on peut pas la rejoindre 

### Qu'aurait-il dû arriver ?

on aurai du la rejoindre 

### LOG

https://media.discordapp.net/attachments/618206596715249685/1023259840690262036/unknown.png

**Comment by VexonTV1** [comment]
Petite précision : lorsque le joueur se connecte à la DIMMineur, celle-ci redémarre 
Exemple actuel : Revali19 / DimMiner-c03e4cd7-98ab-4067-a870-0e90b06039f0

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
