### ISSUE TITLE
[Bug]: Drawers dans les LuckyDrawers

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#864]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Les joueurs ont la possibilité de mettre des drawers dans les LuckyDrawers, ce qui fait qu'on ne peut pas voir leur contenu et donc des "Luckys Blocks" comme avant l'arrivé de ces derniers.

### Qu'aurait-il dû arriver ?

Il ne devrait pas y avoir de drawers dans les LuckyDrawers

### Serveur

Global

**Comment by KraemerJoe** [comment]
Possibilité d'ajouter un Drawer dans un LuckyDrawer corrigé.
merci
