### ISSUE TITLE
[Bug]: Drawers dans Lucky drawer (bug complet du ah ajout au report de Kortz) 

### ISSUE THREAD

**Issue by Danflaa** [Paladium-Developpement/Paladium-Issue#865]
### Pseudo InGame

Danfla

### Que s'est-il passé ?

J'ai mis des Drawers dans le lucky drawers (ne sachant pas que c'etait interdit car je n'ai pas eu le temps de suivre l'actualité de pala cette semaine à cause du boulot).
Depuis, impossible d'accéder à l'onglet 'SELL" dans le AH + kick si je clic + de 2 fois sur SELL.
De plus, impossible de rec mon écran via geforce depuis ce bug. 
Si jamais je peux envoyer des screens sur discord si vous voulez.

### Serveur

Muzdan

**Comment by KraemerJoe** [comment]
Est-ce que tu as des erreurs dans tes logs ?
![image](https://user-images.githubusercontent.com/40207750/192156105-e029e632-b60a-430d-9aa0-686ccf2c5af1.png)

Personnellement je n'ai pas de soucis

**Comment by Danflaa** [comment]
Je ne crois pas, je n’ai pas de dossier crash.
Je ne peux tjs pas accéder à la partie « SELL » du ah et je suis kick du serveur lorsque je spam un peu comme si j’abusais d’une commande.
Après, je t’avoue que je ne suis pas des plus à l’aise avec les logs.
Si jamais tu veux que je passe ts dis le moi ou discord si jamais pour Stream mon écran car je ne peux plus utiliser nvidia.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :dimanche 25 septembre 2022 19:09
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Paladium-Developpement/Paladium-Issue] [Bug]: Drawers dans Lucky drawer (bug complet du ah ajout au report de Kortz) (Issue #865)


Est-ce que tu as des erreurs dans tes logs ?
[image]<https://user-images.githubusercontent.com/40207750/192156105-e029e632-b60a-430d-9aa0-686ccf2c5af1.png>

Personnellement je n'ai pas de soucis

**Comment by KraemerJoe** [comment]
Lances Paladium, fais toi crash et tout en ayant le jeu allumé, transfert moi le latest.txt du dossier logs stp

**Comment by Danflaa** [comment]
https://we.tl/t-eat7xV7TBh

Lien wetransfer car le fichier trop volumineux

**Comment by KraemerJoe** [comment]
Possibilité d'ajouter un Drawer dans un LuckyDrawer corrigé.
merci
