### ISSUE TITLE
[Bug]: Wireless lever

### ISSUE THREAD

**Issue by ZyF0x** [Paladium-Developpement/Paladium-Issue#867]
### Pseudo InGame

ZyF0x

### Que s'est-il passé ?

Le wireless lever ne s'active pas

### Serveur

Global

**Comment by Zeldown** [comment]
:x: Merci de mettre suffisamment d'informations lors de l'ouverture d'une issue.

Après plusieurs tentatives, mon wireless lever à fonctionné à chaque fois.
