### ISSUE TITLE
[Bug][Faction]: Panneaux AP

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#869]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

https://github.com/Paladium-Developpement/Paladium-Issue/issues/587#issue-1303349368

Issus non corrigé, j'arrive encore à casser les panneaux

### Qu'aurait-il dû arriver ?

Panneaux incassable

### Serveur

Neolith

### Date et heure de la production du bug

25/09/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Est-ce que tu es en Admin Mode ?
