### ISSUE TITLE
[Bug]: Space Food LuckyBlock

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#870]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Par moments le Space Food ne fonctionné pas il ne fait pas décoller les joueurs et ne casse pas entièrement.

Exemple de moment ou l'espace food ne fonctionne pas : https://youtu.be/wR9NayibsYA

### Qu'aurait-il dû arriver ?

Tout les blocs au dessus du joueurs aurait du être casser et le joueur aurait du avoir un décompte dans le chat avant de s'envoler dans le ciel.

### Serveur

Global

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
