### ISSUE TITLE
[Bug]: Annonce MailBox (longs textes)

### ISSUE THREAD

**Issue by Vahkette** [Paladium-Developpement/Paladium-Issue#872]
### Pseudo InGame

Vahko

### Que s'est-il passé ?

Reminder pour Zeldown

### Qu'aurait-il dû arriver ?

Que ce soit bien dev du premier coup :v

### Serveur

Global

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
