### ISSUE TITLE
[Bug]: Tab n'affichant pas le bon préfix pour le grade légende 

### ISSUE THREAD

**Issue by Samxvdhn** [Paladium-Developpement/Paladium-Issue#873]
### Pseudo InGame

Samxvdhn

### Que s'est-il passé ?

Bonjour, le grade légende ne s'applique pas correctement. En effet au lobby je suis affiché comme Endium
![image](https://user-images.githubusercontent.com/43002022/192518843-6543edbf-b300-406c-b2a0-38b87f1d1ab0.png)
Et en faction comme Légende
![image](https://user-images.githubusercontent.com/43002022/192518891-33a288e2-2081-4629-91d9-d22f1e741e7c.png)
De plus, le prefix dans le tab n'est pas à la hauteur de ma grandeur, je ne souhaite pas être assimilé aux Endium :joy: 
![image](https://user-images.githubusercontent.com/43002022/192519055-f4545d1a-9e79-4eb3-971e-a2604670c9db.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
