### ISSUE TITLE
[Bug]: Impossible de vendre les sog au AH

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#875]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il n'est pas possible de vendre les stick of god au ah
https://prnt.sc/JYUaxO3cGkc8

**Comment by Zazho** [comment]
Idem pour les Harpagophytum

**Comment by Zazho** [comment]
Idem pour les POG

**Comment by KraemerJoe** [comment]
Corrigé merci
