### ISSUE TITLE
[Bug]: La quête des Extrapolated Bucket du palapass n'est pas fonctionnelle

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#877]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

La quête Extrapolated Bucket n'est pas fonctionnelle : Les crafts ne sont pas comptabilisés 

Vidéo montrant le bug : https://www.youtube.com/watch?v=lOD3mFMRgJg

**Comment by Zazho** [comment]
La quete extrapolated ne fonctionne tout simplement pas

**Comment by AlxTNF** [comment]
Issue modifiée suite aux tests de @Zazho

**Comment by KraemerJoe** [comment]
Corrigé merci
