### ISSUE TITLE
[Bug]: Les quêtes journalières ne se reset pas a 2h00 AM

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#878]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Les quêtes journalières du Palapass ne se reset a 2 heures du matin.

### Qu'aurait-il dû arriver ?

Les quêtes journalières auraient dû ce reset et donnez 3 nouvelles quêtes.

**Comment by KraemerJoe** [comment]
Corrigé merci
