### ISSUE TITLE
[Bug]: Palapass minage de paladium ore non comptabilisé.

### ISSUE THREAD

**Issue by Sylestre** [Paladium-Developpement/Paladium-Issue#879]
### Pseudo InGame

Syylestre

### Que s'est-il passé ?

Un joueur mine du minerai de paladium récupère le minerai (minerai naturel c'est à dire non déjà poser par le joueur) mais ne récupère pas son point sur le palapass.

https://www.youtube.com/watch?v=0hPGcve24w8 rec de cceci.

### Qu'aurait-il dû arriver ?

Le minerai miner aurait dû être comptabiliser dans le palapass du joueur.

### Serveur

Minage

### Date et heure de la production du bug

30/09/22 report vers 19h20

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Zazho** [comment]
Oui aurelian je sais qu'il a pas mis au bon endroit, c'étais ca première fois

**Comment by KraemerJoe** [comment]
Testé et fonctionnel
