### ISSUE TITLE
[Bug]: NPC

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#88]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Régulièrement, les NPC partent en vacance en disparaissant, ou se la joue Splinter Cell en entrant à moitié dans les blocs sur lesquels ils se trouvent

ça n'arrivait pas du tout avant

**Comment by aureliancnx** [comment]
Les NPC sont ils correctement configurés ?
