### ISSUE TITLE
[Bug]: Amulette Helios

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#880]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Quand le module "Nametag" est activé sur Helios il est possible de voir certaines informations qui devrait être cachée par les amulettes sur le plastron

Rec : https://youtu.be/IZxmP39Ea3I

### Qu'aurait-il dû arriver ?

Même avec le modules nametag étant donné les amulettes sur le plastron on ne devrait pas voir la vie, la faction et le pseudo

### Serveur

Global

**Comment by Zeldown** [comment]
:x: Ceci n'est pas un bug

Les amulettes impactant l'affichage du nametag ne devraient plus être en jeu
