### ISSUE TITLE
[Bug][Cosmetiques]: Plusieurs cosmétiques identiques

### ISSUE THREAD

**Issue by Telco43** [Paladium-Developpement/Paladium-Issue#881]
### Pseudo InGame

Telco_

### Que s'est-il passé ?

Certaines cosmétiques pour les grades du mois d'octobre sont présentes dans l'inventaire de cosmétiques en plusieurs exemplaires identiques.
[Vidéo du problème](https://youtu.be/057l5bii_BA)

### Qu'aurait-il dû arriver ?

On ne devrait recevoir ces cosmétiques qu'une seule fois.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
