### ISSUE TITLE
Auto smelt sur la POG ne fonctionne pas seul.

### ISSUE THREAD

**Issue by VeckPex** [Paladium-Developpement/Paladium-Issue#882]
### Pseudo InGame

Roselynee

### Que s'est-il passé ?

Quand on mine à la PoG, auto smelt seul ne fonctionne pas, alors qu'associé à Big Hole il fonctionne tout le temps.

### Qu'aurait-il dû arriver ?

Qu'il soit seul ou avec Big Hole, auto smelt devrait fonctionner et ainsi permettre de cuire directement les minerais

### Serveur

Global

**Comment by KraemerJoe** [comment]
Corrigé.
