### ISSUE TITLE
[Bug][Faction]: Quête hebdo

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#883]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/193612578-e21dbc75-692a-4a73-84fa-2ee2e56f674d.png)
Les 3 premiers s'affichent mal

### Serveur

Soleratl

### Date et heure de la production du bug

heure du l'issue

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by KraemerJoe** [comment]
Merci, normalement corrigé, si le bug survient les semaines suivantes merci de recréer une issue
