### ISSUE TITLE
[Bug]: Market manque catégorie 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#884]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/193628408-108a75b4-b14f-45e9-ac3f-c21b9f693fbc.png)
Il manque la catégorie stuff et luckydrawer

**Comment by KraemerJoe** [comment]
Corrigé merci
