### ISSUE TITLE
[Bug]: Sources Angelic Water lors de la récupération du chaudron

### ISSUE THREAD

**Issue by Camouchat** [Paladium-Developpement/Paladium-Issue#89]
### Pseudo InGame

Camouchaat

### Que s'est-il passé ?

Lorsque l'on casse le chaudron pour le récupérer, il est possible de récupérer 9 sources d'Angelic Water après en avoir seulement drop 1 seule pour la création du chaudron

### Qu'aurait-il dû arriver ?

Nous aurions du en récupérer qu'une seule voire 0

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
