### ISSUE TITLE
[Bug]: Market onglet pvp et equipement 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#891]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Les icones pvp et equipement ne sont pas alignés dans leur case 
![image](https://user-images.githubusercontent.com/92928910/193871430-fee32333-c203-4092-9431-ab2912b19fe4.png)

**Comment by KraemerJoe** [comment]
Corrigé merci
