### ISSUE TITLE
[Bug]: Echange GodVillager

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#892]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les god villager ne propose pas les échanges bloc de paladium --> endium nuggets
https://www.youtube.com/watch?v=VaFLNLnSN0A
test avec un oeufs de god villager aussi

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
