### ISSUE TITLE
[Bug][Faction]: AP Non Fonctionnels

### ISSUE THREAD

**Issue by Eclair93** [Paladium-Developpement/Paladium-Issue#898]
### Pseudo InGame

Eclair93

### Que s'est-il passé ?

Malgré le patch note d'aujourd'hui qui dit que les AP sont de nouveau fonctionnels.
On a toujours pas de permissions dedans (même avec le grade Leader IG)

### Serveur

Global

### Date et heure de la production du bug

11/10 

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. 

Cordialement,
