### ISSUE TITLE
[Bug][Faction]: Réduction gradés non présente pour l'achat d'un AP

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#901]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

La réduction pour les gradés n'est pas appliquée lors de l'achat d'un AP.

### Serveur

Imbali

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
