### ISSUE TITLE
[Bug][Faction]:  Gain de money lors de la victoire du KOTH

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#902]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lors de la victoire du KOTH le gain de money n'est pas fait automatiquement, la overlord à gagner le KOTH d'hier on leur à donné à la main

### Qu'aurait-il dû arriver ?

Gain auto

### Serveur

Soleratl

### Date et heure de la production du bug

12/10/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
