### ISSUE TITLE
[Bug]: Lucky drawer, rien ne drop

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#904]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Rec d'un joueur, et pas le premier, il a casser des lucky drawer avec que des bighole dedans mais rien n'a drop
rec:https://www.youtube.com/watch?v=J0VVoEaRZOs

**Comment by Lorn87** [comment]
fix
