### ISSUE TITLE
[Bug]: Quete Palapass, extrapolated

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#907]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lors du craft des extras, tout ce qui est craft n'est pas comptabilisé, dans ce rec on vois bien le joueur craft les 45, cependant il n'y en a que 23 de compter
rec: https://www.youtube.com/watch?v=uo2yMjGfq8U

### Serveur

Rakavi

**Comment by KraemerJoe** [comment]
Toujours lié au Palamod et events appelé 4x, + la sécurité qui créer ca
