### ISSUE TITLE
[Bug]: LuckyDrawer impossible à récup dans le ah + crash 

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#908]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Plusieurs joueurs ont mis en vente des items dans des LuckyDrawers, une fois la commande /marketrecup réalisée, ils n'ont récupéré qu'une partie des LD, et certains restent affichés en vente dans le ah. Il est impossible de les acheter ou d'intéragir avec eux. 
De plus : lorsque les joueurs en questions tentent d'ouvrir leur pannel LuckyDrawer dans le ah, ils crashent instant

Report de deux joueurs : 
SosoLPB
Mamath716

En dessous vous retrouverez leur crash report 

### Serveur

Global

### LOG

https://pastebin.com/6guHkwSY
Sosolpb

https://pastebin.com/xjvaab3b
Mamath716

**Comment by KraemerJoe** [comment]
Merci problème corrigé pour le cas connu
