### ISSUE TITLE
[Bug]: pas d'xp avec la mineral flower 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#909]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

j'ai un joueur qui est venue me reporte un bug 
il a voulus jeter des minéral Flower dans le chaudron mais sa ne lui a pas donner d'xp 

### Qu'aurait-il dû arriver ?

sa aurai du lui donner de lxp dans son cas 2xp

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
