### ISSUE TITLE
[Bug]: Crash des joueurs au alentour

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#91]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Avec le bloc que donne le sort inertium, si on réutilise inertium avec on fait crash les joueurs et sois même au alentour.
https://www.youtube.com/watch?v=NekllTpN8Xo

### Qu'aurait-il dû arriver ?

Ne pas crash

**Comment by terrainwax** [comment]
Je m'en occupe
