### ISSUE TITLE
[Bug]: Retour du bug unsafe TP

### ISSUE THREAD

**Issue by Apsig69** [Paladium-Developpement/Paladium-Issue#911]
### Pseudo InGame

Apsig69

### Que s'est-il passé ?

Le bug unsafe TP est de retour, log de son utilisation retrouvé sur divers pillages

Log dispo sur demande car coordonnées de base présentes dans le pastbin

Investigation en cours pour le process exacte utilisé

**Comment by Lorn87** [comment]
fix
