### ISSUE TITLE
[Bug]: Les temples de l'Océan sont actifs en dimension mineur

### ISSUE THREAD

**Issue by Camoouchat** [Paladium-Developpement/Paladium-Issue#912]
### Pseudo InGame

Camouchat

### Que s'est-il passé ?

Les temples de l'Océan sont actifs en dimension mineur

### Qu'aurait-il dû arriver ?

Ils sont désactivés en faction et en minage, peut être un oubli?

**Comment by Lorn87** [comment]
Pas grave
