### ISSUE TITLE
[Bug]: Bonbon impossible à déballer

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#914]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Il n'est pas possible de déballer les bonbons, les bonbons ouvert avant la maj sont redevenu des bonbon normaux avec un autre ID, https://prnt.sc/us2PrDPtyNOp, il est impossible de les "manger" pour avoir les pts ou même de les ouvrir, il est aussi impossible de faire la différence entre les deux étant donné que c'étais à la base 2 bonbon différents.

**Comment by Lorn87** [comment]
fix
