### ISSUE TITLE
[Bug]: Trophée black

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#915]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les trophées gagné via le palapass black sont nommé "personne"
https://prnt.sc/KXH8wqgsAncJ

### Qu'aurait-il dû arriver ?

Nommé au nom du joueur qui à fait le palapass

### Serveur

Imbali

**Comment by Lorn87** [comment]
fix
