### ISSUE TITLE
[Bug]: Impossible de recharger un pistolet à eau

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#918]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Le craft pour recharger le pistolet à eau marche uniquement quand le pistolet à sa durabilité à au complet , lorsqu'on tire une seule fois , le craft ne devient plus possible

### Qu'aurait-il dû arriver ?

Le craft aurait du être possible peu importe la durabilité

**Comment by Lorn87** [comment]
fix
