### ISSUE TITLE
[Bug][Faction]: Mdf message des rg couleurs marchent pas 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#920]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/196965953-a3e86cbd-9bff-4e45-8127-8f8c4e47cefd.png)
La couleur dans les flags automatiques des mdf ne marche pas

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Fix
