### ISSUE TITLE
[Bug][Faction]: Mdf Pas d'access au claim de la zone

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#921]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Les personnes ayant accès à la mdf ne sont pas access au claim 
![image](https://user-images.githubusercontent.com/92928910/196966421-02facb29-c58a-46ff-a1cc-255efd32870f.png)
![image](https://user-images.githubusercontent.com/92928910/196966452-4f6fcdee-d460-4844-92ce-5417f129b764.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Akysooo** [comment]
(Ca ne marche pas peut importe le claim, pour le problème d'au dessus, j'ouvre une issue #923 )

**Comment by aureliancnx** [comment]
Corrigé pour le build
