### ISSUE TITLE
[Bug][Faction]: Mdf tête gui trop grosse + nom pas aligné

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#922]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/196966625-7dfe6803-5c40-496d-a527-d4b66cf6455a.png)
Les têtes sont trop grosses. les textes sont mal alignés

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Corrigé pour les textes

Pour la tête par contre ca dépend du scale du jeu, j'ai essayé de "réparer", c'est un peu mieux mais elle s'extend pas si on élargit l'écran

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
