### ISSUE TITLE
[Bug][Faction]: /f access dans Warzone (faction perma)

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#923]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/196970353-729b8dc1-60fc-4db2-9f1c-27873b191ac1.png)
Il n'est pas possible en f admin d'access une faction ou un joueur dans un claim d'une faction comme la Warzone ou la wilderness

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Fixé pour la WarZone en Admin Mode.

Pour la Wilderness, ce sera un wontfix, car la Wilderness ne fonctionne pas sur le principe de "j'ai claim tout et on peut me surclaim" mais en mode "cet endroit n'est pas claim ? ça affiche que c'est la wilderness" pour une question d'opti.

**Comment by Akysooo** [comment]
La wilderness était donné qu'a titre d'exemple. On a pas besoin d'access quelqu'un dedans normalement
