### ISSUE TITLE
[Bug][Faction]: Mdf non retrait joueur rg

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#924]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Si on enlève un joueur de la mdf, il n'est pas retiré de la rg. 
https://youtu.be/_XskM7EoCNk 

### Serveur

Soleratl

### Date et heure de la production du bug

16h13 20/10

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Fix.
