### ISSUE TITLE
[Bug][Faction]: Mdf gui - problème affichage bouton

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#925]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Le bouton est très moche comme cela, 
![image](https://user-images.githubusercontent.com/92928910/196975965-d7ae3a5a-90e6-40d4-9002-3d16022fd588.png)

### Qu'aurait-il dû arriver ?

![image](https://user-images.githubusercontent.com/92928910/196976012-4e6d6952-e905-4ccb-ae5b-2829d5331bd6.png)
Il devrait être comme ça.

(Slot si jamais pour la modif)
![slots](https://user-images.githubusercontent.com/92928910/196977451-82ade909-474a-46c0-9e88-14fdd59cbfe8.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
