### ISSUE TITLE
[Bug][Faction]: Mdf rg position y

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#929]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lors de la création d'une mdf, la rg ne prend pas en compte le point y. On se retrouve donc avec des rg qui vont de 0 à 255
![image](https://user-images.githubusercontent.com/92928910/197337327-45a9f804-7425-4823-a0d6-435f40c2e0ef.png)
![image](https://user-images.githubusercontent.com/92928910/197337335-5dbe9775-46e6-457b-8477-beea9c7bf875.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
