### ISSUE TITLE
[Bug]: "Clear" de homes

### ISSUE THREAD

**Issue by TT54** [Paladium-Developpement/Paladium-Issue#93]
### Pseudo InGame

TT54

### Que s'est-il passé ?

J'avais plusieurs homes sur Forestia, et lorsque je me suis reconnecté tout à l'heure, ils avaient tous disparus du /home. Je me suis donc retp à une des coordonnées où je savais que j'avais un home, et lors d'un /scanhomes il apparait toujours. J'y ai donc reposé un home si jamais vous avez besoin de voir cela, il s'agit de mon home quete sur Forestia.

### Qu'aurait-il dû arriver ?

Les homes n'auraient pas dû disparaitres.

### Serveur

Forestia

**Comment by TT54** [comment]
Étonnamment mes homes sont revenus aujourd'hui, par contre j'en ai un en double du coup (le home quete) ce qui peut être embêtant pour un joueur.
![image](https://user-images.githubusercontent.com/36418247/146426436-4e106154-af2a-48f5-9aeb-392753c4d9de.png)

**Comment by aureliancnx** [comment]
Malheureusement ce bug n'est pas un bug qui semble être reproduisible selon des actions biens spécifiques. Peut être que le plugin n'arrivait pas à faire la liaison avec la base de données des homes, ce qui t'affichait aucun home.
