### ISSUE TITLE
[Bug]: Ouverture du chat quand on rentre dans un lit

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#931]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on décide de rentrer dans un lit, le chat s'ouvre il nous est impossible de le refermer il s'ouvre en boucle donc impossible de quitter le lit

### Serveur

Imbali

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
