### ISSUE TITLE
[Bug][Spells]: Timer de sort

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#932]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Lors de l'utilisation d'un sort, un cooldown est normalement affiché, ce n'est actuellement plus le cas.
Je viens tout juste de l'utiliser, et cela ne change pas si j'attend https://prnt.sc/uAOPdR7X0_xi

### Serveur

Imbali

**Comment by aureliancnx** [comment]
Bonjour,

Cela ne fonctionne pas en activant le module correspondant dans Hélios ?
