### ISSUE TITLE
[Bug]: Builder wand 

### ISSUE THREAD

**Issue by Reguitec** [Paladium-Developpement/Paladium-Issue#936]
### Pseudo InGame

Reguitec 

### Que s'est-il passé ?

Quand je pose des blocs en dessous de moi avec la builder wand, dans le nether, ça m'a tp au Spawn.

### Qu'aurait-il dû arriver ?

Normalement, on ne doit pas être téléporté au Spawn. 

### Serveur

Minage

### LOG

https://youtu.be/qLhIMXm8Fqs

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
