### ISSUE TITLE
[Bug]: Graines à l'infinie sans bone meal[Bug]: 

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#937]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Dans des claims ennemies, le fait de casser des graines les replantes automatiquement tout en recoltant les graines, ce qui en fait une farm infinie.

### Qu'aurait-il dû arriver ?

Aucunes graines n'est censé être drop.

### Serveur

Global

**Comment by Akysooo** [comment]
Une issue existe déjà #842
