### ISSUE TITLE
[Bug]: lightning potion dupli

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#939]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

avec les quête quotidienne, quand on arrive au Lightning potion il en a 4 qui sont stacker quand on les met dans un coffre en fer, et qu'on casse le coffre en fer. elle sont dupliquer 

je n'est pas pus tester et le joueur n'avais pas de rec 

### Qu'aurait-il dû arriver ?

il aurai pas du être dupliquer

**Comment by Lorn87** [comment]
impossible a reproduire donne bien le nombre
