### ISSUE TITLE
[Bug]: LB noir récompense palier manquante

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#940]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/197398993-e20320c9-644f-43d6-b67d-b5c0c2d1f173.png)
Il manque les cosmétiques

**Comment by Lorn87** [comment]
Le coté rendu cosmétiques n'est pas dev pour ca demande une refonte
