### ISSUE TITLE
[Bug]: Trade Journalier Limite Reset

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#941]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on change de serveur , sur l'interface on aura toujours le nombre de trade restant , mais lorsque nous faisons a nouveau le trade , ce nombre se reset et revient a 0.

https://www.youtube.com/watch?v=1VTN9Vyw7w4&ab_channel=Sebastien

### Qu'aurait-il dû arriver ?

Notre limite de trade ne devrait pas ce reset.

**Comment by SK0R3N** [comment]
Update : Il sagit d'un bug visuel.

**Comment by Zeldown** [comment]
❌ Etant seulement visuel et l'event arrivant à sa fin je ferme l'issue.
