### ISSUE TITLE
[Bug][Faction]: Elo départ classement

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#943]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

La faction Anarchy a commencé la saison avec 485 d'elo alors qu'elle est niveau 28. Elle doit la perte d'elo à la pvp area. 

### Qu'aurait-il dû arriver ?

Elle aurait du être à "645 - 20" donc 625 d'elo.

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by Akysooo** [comment]
Voir la fuz3fac pour je pense le même pb (pour trouver le lien). Mais ça touche bcp de faction visiblement, peut être recevoir une perte met à 505 et non 505 + lvl*5 ??

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.
Les prochaines saisons ne devraient pas avoir ce problème.

Cordialement,
