### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#948]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Report d'un joueur qui peut déclencher le combat avec les fantômes mais ne peut pas les taper. 

### Qu'aurait-il dû arriver ?

Un combat devrait avoir lieu entre les fantômes et le joueur afin de supprimer les homes.

### Serveur

Global

**Comment by KraemerJoe** [comment]
Ce problème sera résolu avec la refonte.
