### ISSUE TITLE
[Bug] Flag sort

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#949]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Le flag de désactivation des sorts ne marche plus après le redémarrage des serveur, a chaque koth on dois le remettre (issus sur le demande d'Akyso)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
