### ISSUE TITLE
[Bug][Faction]: Permission allié/truce par défaut non fait

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#950]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Il manque les permissions "par défaut" pour les factions alliés et en truce
![image](https://user-images.githubusercontent.com/92928910/198118817-71d82f4f-26f4-4aae-898d-b65d3a139c24.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
https://github.com/Paladium-Developpement/Paladium-Issue/issues/951
