### ISSUE TITLE
[Bug][Faction]: Bouton modification permission faction allié / truce non accessible 

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#951]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

https://youtu.be/T0KoKaTB_Bw

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
