### ISSUE TITLE
[Bug]: Bug de fly avec le balai

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#953]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Quand on équipe/déséquipe le balai rapidement on peux fly plusieurs seconde sans consommé le balai, il est donc possible de le faire indéfiniment, test sur mon compte et cela fonctionne bien, rec du joueur https://www.youtube.com/watch?v=bovmBKGuCKs

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
