### ISSUE TITLE
[Bug]: Dimension mineur et potion mineur fou

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#954]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Report d'un joueur, pas testé, "si on mine en dimension miner avec une potion de mineur fou, les points perdus a cause des minerais ne sont pas retirés des 1000"

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
