### ISSUE TITLE
[Bug][Faction]: Message village de fac

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#955]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Lorsqu'un joueur sort d'un village de faction celui-ci ce fait rollback et un message d'erreur s'affiche dans le chat.

Rec : https://youtu.be/A_Zvy5esR9Q

### Serveur

Global

### Date et heure de la production du bug

27/10/2022 | 21h

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
This is not a bug.

En effet, tu ne peux pas sortir d'un village de Faction sans faire la commande /spawn
Le message d'erreur n'est pas traduit, ce sera en revanche corrigé
