### ISSUE TITLE
[Bug][PaintWars]: Partie injoignable 

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#956]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Lorsque on essaye de rejoindre le paintwars même après avoir attendu la fin de la file d'attente aucune partie n'est trouvée et personne ne peut rejoindre.

Screen : https://prnt.sc/QpUW3IjlXJBT

### Qu'aurait-il dû arriver ?

Ont devraient pouvoir jouer en paintwars a moins que celui-ci soit close mais il faudrait mettre un message d'erreur clair dans ce cas-ci.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
