### ISSUE TITLE
[Bug]: Connaitre à l'avance un évent de lucky block

### ISSUE THREAD

**Issue by TT54** [Paladium-Developpement/Paladium-Issue#96]
### Pseudo InGame

TT54

### Que s'est-il passé ?

Lorsqu'un joueur ouvre un lucky block et qu'un autre joueur, dans une autre faction, claim le chunk, alors l'évent du luckyblock n'a pas lieu, et le joueur connait à l'avance l'event de ce lucky block. Si l'event est bien, alors le second joueur unclaim la zone, et le premier peut ouvrir le lucky block et aura son évent. Sinon, il casse le lucky block, obtient un item lucky block qui ne se stack pas avec les autres et qui, s'il est posé, donnera la même récompense, et pour pouvoir avoir un nouvel évent avec ce lucky block, il suffit de le poser à l'aide d'un builder wand sur un autre lucky block, ce qui remettra à zéro l'évent du lucky block.
Voici une vidéo qui le montre : https://www.youtube.com/watch?v=zlx6pGdN7fk

### Qu'aurait-il dû arriver ?

L'évent du lucky block ne devrait pas être prévisible et aurait dû être modifié lorsque l'on ouvre de nouveau le lucky block qui s'est annulé à cause du joueur qui a claim.

**Comment by aureliancnx** [comment]
Corrigé
