### ISSUE TITLE
[Bug]: Particule en or 

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#961]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Les compacting drawer ne donne pas de particule d'or mais des nuggets en or c'est le seul minerais à le faire
https://prnt.sc/PZQ-u0eYYaX9

**Comment by KraemerJoe** [comment]
9x particule de Paladium = 1 lingot
9x lingot = 1 bloc

9x NUGGETS de Gold = 1 lingot
9x lingot = 1 bloc

Processus équivalent avec l'item gold nuggets déjà existant dans Minecraft de base et représentant les particules.

Je ne pense pas qu'il y ait de soucis

**Comment by Zazho** [comment]
Le soucis c'est que avant la v8 les particule en or donné par les cobblebreaker donnais des lingot dans le compacting drawer, maintenant ce n'est plus possible car ce sont des nuggets, 2 item différent, il y a eu une modification la dessus

**Comment by Zazho** [comment]
Tout les cobble breaker donne des particule, sauf que dans tout les compacting seul l'or ne prend pas les particule, alors qu'avant la v8 c'étais le cas
