### ISSUE TITLE
[Bug]:  Palapass "Au Bouleau" (Quete)

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#965]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Bonsoir,
Pour la quête du palapass "au boulot" il suffit de reposer le bloc à chaque fois pour la terminer

**Comment by KraemerJoe** [comment]
Hello
Bug toujours lié au divers appels du Palamod, déjà report merci
