### ISSUE TITLE
[Bug]: Impossible de récupérer les récompenses 100% LuckyStats LB de Noël

### ISSUE THREAD

**Issue by Camouchat** [Paladium-Developpement/Paladium-Issue#97]
### Pseudo InGame

Camouchaat

### Que s'est-il passé ?

Le joueur a atteint le 100% du LuckyStats des LuckyBlocs de Noël mais impossible de récupérer ses récompenses : 
https://www.youtube.com/watch?v=UNHK1tC5oSU rec
Pseudo IG : Lndisponible 

### Qu'aurait-il dû arriver ?

Il aurait du récupérer les récompenses

**Comment by aureliancnx** [comment]
Corrigé
