### ISSUE TITLE
[Bug][Faction]: Flag powerloss

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#970]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

Le flag powerloss pour les faction si on le met en no on perds quand même la power, faction "quête"

### Qu'aurait-il dû arriver ?

Ne pas perdre de power quand on meurt dans une zone claim par cette faction

### Serveur

Imbali

### Date et heure de la production du bug

01/11/2022

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour

Le flag power loss évite la perte de power pour la faction, pas pour les gens dans les claims de cette faction

**Comment by aureliancnx** [comment]
Bien un bug en fait.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,

**Comment by aureliancnx** [comment]
Le correctif ne semble pas fonctionner. Je réouvre l’Issue
