### ISSUE TITLE
Le joueur se fait kick et crash à chaque connexion de lobby 

### ISSUE THREAD

**Issue by Ramoniste** [Paladium-Developpement/Paladium-Issue#971]
### Pseudo InGame

Ramoniste

### Que s'est-il passé ?

Un joueur (Le senpai), se fait kick de chaque lobby et ne peut donc pas se connecter à un serveur faction. 
Il à déjà essayer de supprimer son fichier .paladium je joins son dossier crash report

### Qu'aurait-il dû arriver ?

Il devrai pouvoir se connecter sur le serveur faction

### LOG

https://paste.rocks/?054512d14d24351c#6VDXAHxGER3cTjFi3PN5KZjQFRp7Dam5iAPRm2Rq4BP5

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
