### ISSUE TITLE
[Bug][Faction]: Annuaire bug chargement faction scroll

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#972]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

https://www.youtube.com/watch?v=lpgeB0SaMmQ
Quand on charge de nouvelles factions dans l'annuaire, la barre de scroll remonte 

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
