### ISSUE TITLE
[Bug][Faction]: Inspection scroll derrière le gui

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#973]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

![image](https://user-images.githubusercontent.com/92928910/199280949-9224c5a5-4cc1-4f9d-b7bc-6c2f96a7700f.png)

### Serveur

Global

### Date et heure de la production du bug

/

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
