### ISSUE TITLE
[Bug]: POG qui utilise le Palamixed a n'importe quel niveau.

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#974]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Une joueuse est venu nous voir sur ts pour nous avertir d'un bug concernant la POG. En effet , la POG utilise du Palamixed coal , même quand elle n'a aucune amélioration dessus (Ce qui consomme inutilement le Palamixed Coal) .

https://www.youtube.com/watch?v=KqjAovGt_qU&ab_channel=chloe 

### Qu'aurait-il dû arriver ?

La POG doit consommer du Palamixed Coal , seulement quand il y a une amélioration.

**Comment by iWoZ0** [comment]
https://prnt.sc/cPBsvseTo5iE

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
