### ISSUE TITLE
[Bug]: Pickaxe Of the God qui consomme du palamixed coal

### ISSUE THREAD

**Issue by steboomRedact** [Paladium-Developpement/Paladium-Issue#977]
### Pseudo InGame

steboom

### Que s'est-il passé ?

Je voulais creuser de la pierre du nether avec ma Pickaxe of The god level  16, donc sans amélioration spéciale. J'avais du palamixed coal dans mon inventaire. Lorsque j'ai donc voulu casser la pierre du nether, un palamixed coal fût consommé, la température de la POG augmenta et elle commença à casser 2 blocs par 2 blocs. Donc, ce qui est normalement pas possible. 

Lien du rec : https://youtu.be/2JGtrJBYkyI

### Qu'aurait-il dû arriver ?

La POG n'aurait pas dû consommer un palamixed coal et n'aurait pas dû commencer à casser plusieurs blocs.

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
