### ISSUE TITLE
[Bug]:  Cosmétique du Mois

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#978]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Hello, On a un souci sur le cosmétique du mois. ( j'ai acheté celui du mois dernier et je pense que cela vient de la ) j'ai moov un joueur est pareil pour lui il a le même souci

![image](https://user-images.githubusercontent.com/104795165/199769201-51028e1b-f485-4933-90f7-d68bfbf8e09e.png)

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
