### ISSUE TITLE
[Bug]: Bug d'affichage chest

### ISSUE THREAD

**Issue by Shadixxs** [Paladium-Developpement/Paladium-Issue#979]
### Pseudo InGame

Shadixs

### Que s'est-il passé ?

En fonction d'ou on regarde, les coffres disparaissent et réapparaissent 
Video : https://youtu.be/c0CDm6Vvw5I 

### Qu'aurait-il dû arriver ?

Les coffres devraient apparaitre tout le temps

### Serveur

Global

**Comment by Zeldown** [comment]
❌ Ceci est un bug vanilla de rendu provoqué par les caveblocks, il ne sera donc pas corrigé.

Merci du rapport tout de même 🚀
