### ISSUE TITLE
[Bug]: Chute de FPS et Freez intempestifs

### ISSUE THREAD

**Issue by Camouchat** [Paladium-Developpement/Paladium-Issue#98]
### Pseudo InGame

Camouchaat

### Que s'est-il passé ?

Depuis la dernière mise à jour (V7.6), la majorité des joueurs (y compris moi) ont des très grosses baisses de FPS en jeu (drop aux alentours de 0 pendant qq secondes). 
Après plusieurs vérifications ''côté client'' avec Xynos notamment sur l'allocation mémoire et autres termes techniques il semblerait que tout soit ok pour que le jeu fonctionne normalement. 
Cette MAJ entraine donc des freeze (très fréquents, toutes les minutes). 
Le fait de relancer le jeu ne règle pas le problème. 

### Qu'aurait-il dû arriver ?

Il ne devrait pas y avoir de chutes de FPS et freeze aussi fréquents

**Comment by aureliancnx** [comment]
en cours

**Comment by aureliancnx** [comment]
le problème devrait être corrigé
