### ISSUE TITLE
[Bug]: Possibilité de monter plus haut que level 80 Sort

### ISSUE THREAD

**Issue by SK0R3N** [Paladium-Developpement/Paladium-Issue#981]
### Pseudo InGame

SK0R3N

### Que s'est-il passé ?

Lorsqu'on gagne un level au-dessus du Level 20, nous continuous de gagner des levels/points de sorts. Ce qui fait que nous pouvons être au-dessus du level 80

Screen : https://prnt.sc/VxJ-Em6dnkn7

### Qu'aurait-il dû arriver ?

Nous ne devrions gagner aucun point/levels suite à un passage d'un level supérieur au level 20 dans un métier.

**Comment by Zeldown** [comment]
❌ Ceci n'est pas un bug
