### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by K0rTzz** [Paladium-Developpement/Paladium-Issue#982]
### Pseudo InGame

K0rTz

### Que s'est-il passé ?

Le joueur en ouvrant sa dimension mineur est bien téléporté dedans mais au moment de la redirection de la dimension, un message d'erreur apparait.

### Qu'aurait-il dû arriver ?

Le joueur aurait dû être téléporté dans sa dimension.  

### Serveur

Global

**Comment by Zeldown** [comment]
⁉️ Quel fût le message d'erreur ?
