### ISSUE TITLE
[Bug]: Market mise en vente ! 

### ISSUE THREAD

**Issue by iWoZ0** [Paladium-Developpement/Paladium-Issue#983]
### Pseudo InGame

iWoZ_

### Que s'est-il passé ?

Bonjour, 
Si nous mettons en vente des luckydrawers au market, nous ne pouvons plus accéder au slot pour mettre en vente au market 
je parle du bouton ci-dessous : 

![image](https://user-images.githubusercontent.com/104795165/200122192-68b0df52-4d53-4224-9906-89dac50cd60e.png)

Voici l'erreur
![image](https://user-images.githubusercontent.com/104795165/200122153-e03b1c83-8282-4ea9-bdae-eb0b24fd6617.png)

### Serveur

Global

**Comment by iWoZ0** [comment]
Je rajoute aussi possible de faire crash le jeu si on appuie sur la flèche retour 
![image](https://user-images.githubusercontent.com/104795165/200122354-f0eb227b-f50b-4652-8170-224ffef9cd0d.png)

**Comment by KraemerJoe** [comment]
Salut problème pas général, logs ?

**Comment by iWoZ0** [comment]
Salut euh bah j'ai plus aucun soucis 
Il fallait qu'une personne m'achète un item pour que le souci sois résolu

**Comment by KraemerJoe** [comment]
Ok ca marche
