### ISSUE TITLE
[Bug][Faction]: Flagpowerloss

### ISSUE THREAD

**Issue by Zazho** [Paladium-Developpement/Paladium-Issue#984]
### Pseudo InGame

Zazho

### Que s'est-il passé ?

https://github.com/Paladium-Developpement/Paladium-Issue/issues/970

noté comme corrigé dans la PN, test avec mon double compte mais ne marche pas

### Serveur

Imbali

### Date et heure de la production du bug

08/11/2022 16h53

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
On va réouvrir l’issue au lieu d’en faire une deuxième
