### ISSUE TITLE
[Bug]: Pas de drop du bambou lorsqu'il est cassé à la main

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#985]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Le bambou ne droppe pas s'il est cassé à la main, seules les pousses du dessus cassent.

Ex : En cassant un plant de 4 bambous à la base, seules 3 sont récupérées
https://www.youtube.com/watch?v=ExTl26UM6Ro

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
