### ISSUE TITLE
[Bug][Faction]: mdf player action bloquée

### ISSUE THREAD

**Issue by Akysooo** [Paladium-Developpement/Paladium-Issue#987]
### Pseudo InGame

Akyso

### Que s'est-il passé ?

Lorsqu'un joueur est ajouté à une maison de faction, la partie rg marche bien cependant la partie (access enfin le truc que tu as fait) ne marche pas . Quand tu poses un bloc ou tu veux le casser, il y a pas de message d'erreur mais le bloc ne se pose pas /casse pas 

### Serveur

Soleratl

### Date et heure de la production du bug

15:18 10/11

### Bug du plugin Faction

- [X] Le bug que je signale concerne **uniquement** un bug du plugin Factions

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,

**Comment by Akysooo** [comment]
Le bug est toujours d'actualité

**Comment by Akysooo** [comment]
J'ai acheté une mdf avec un compte joueur, je peux rentrer dedans sans problème mais quand je psoe un bloc ou casse un bloc, ce dernier respawn ou ne reste pas. Aucun message d'erreur.

**Comment by aureliancnx** [comment]
Bonjour,

Merci pour le signalement de ce bug. ✔️ 

Il a été corrigé. Le correctif sera appliqué lors de la prochaine mise à jour de Paladium.

Cordialement,
