### ISSUE TITLE
[Bug]: récompense du luckystat recus avant le palier 

### ISSUE THREAD

**Issue by RedFlys72** [Paladium-Developpement/Paladium-Issue#991]
### Pseudo InGame

RedFly

### Que s'est-il passé ?

je suis actuellement a 24% du luckystats et j'ai eu le palier des 25%

### Qu'aurait-il dû arriver ?

normalement j'aurai pas du avoir les récompense 

### LOG

https://imgur.com/a/dP9P9mh
https://imgur.com/a/RMyHC72

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
