### ISSUE TITLE
[Bug]: Crash du jeu avec la Mineral Flower

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#995]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

Lorsqu'un joueur utilise de la bone meal pour récupérer les minerais d'une mineral flower, le jeu crashe.

### LOG

https://paste.rocks/?b790a58eaef29023#9Ds5rwyvRFTQKaDovgwqUrbzccoAKpXvnjVj5moU57yQ

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
