### ISSUE TITLE
[Bug]: Disparition de crafts dans l'Autocrafter

### ISSUE THREAD

**Issue by AlxTNF** [Paladium-Developpement/Paladium-Issue#996]
### Pseudo InGame

NyoSan

### Que s'est-il passé ?

L'autocrafter ne donne pas le résultat de tous les crafts qu'il fait.
Vidéo montrant le problème : https://www.youtube.com/watch?v=GMKQVezqsm8

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !
