### ISSUE TITLE
[Bug]: Bow Machine Interdit au market

### ISSUE THREAD

**Issue by Zeluck-tv** [Paladium-Developpement/Paladium-Issue#997]
### Pseudo InGame

Zeluck_tv

### Que s'est-il passé ?

Le bow machine n'est pas vendable au market pour nom interdit

Screenshot : https://prnt.sc/iCD8TiU2R84M

### Qu'aurait-il dû arriver ?

Les joueurs devraient pouvoir le vendre au market.

**Comment by Zeldown** [comment]
Je prend en charge la correction de ce bug 🚀 Merci !

**Comment by Zeldown** [comment]
✔️ Le bug à été corrigé ! 

🚀 Merci pour le rapport
